### ISSUE TITLE
Sample Submission

### ISSUE THREAD

**Issue by jshawl** [ga-wdi-exercises/to_oz#1]
```
jesse@ga:~/wdi/exercises/to_oz $ mkdir House
jesse@ga:~/wdi/exercises/to_oz $ cd House
jesse@ga:~/wdi/exercises/to_oz/House $ touch Dorothy Toto
jesse@ga:~/wdi/exercises/to_oz/House $ ls
total 0
drwxr-xr-x  4 jesse  staff  136 Jan 29 16:26 ./
drwxr-xr-x  3 jesse  staff  102 Jan 29 16:26 ../
-rw-r--r--  1 jesse  staff    0 Jan 29 16:26 Dorothy
-rw-r--r--  1 jesse  staff    0 Jan 29 16:26 Toto
```

**Comment by RobertAKARobin** [comment]
-10000 points.

**Comment by afm2105** [comment]
Last login: Mon Mar 14 16:44:04 on ttys000
~ 
$ pwd
/Users/antonyscmputer
~ 
$ ls
Applications    Downloads   Music       fundamentals    world
Desktop     Library     Pictures    funny_things
Documents   Movies      Public      wdi
~ 
$ mkdir house
~ 
$ ls
Applications    Downloads   Music       fundamentals    wdi
Desktop     Library     Pictures    funny_things    world
Documents   Movies      Public      house
~ 
$ cd house
~/house 
$ touch dorothy.txt toto.txt
~/house 
$ ls
dorothy.txt toto.txt
~/house 
$ mkdir oz
~/house 
$ ls
dorothy.txt oz      toto.txt
~/house 
$ cd oz
~/house/oz 
$ touch good_witch_of_the_north.txt wicked_witch_of_the_east.txt good_withc_of_the_south.txt wicked_witch_of_the_west.txt
~/house/oz 
$ ls
good_witch_of_the_north.txt wicked_witch_of_the_east.txt
good_withc_of_the_south.txt wicked_witch_of_the_west.txt
~/house/oz 
$ rm wicked_witch_of_the_east.txt
~/house/oz 
$ ls
good_witch_of_the_north.txt wicked_witch_of_the_west.txt
good_withc_of_the_south.txt
~/house/oz 
$ cd ..
~/house 
$ pwd
/Users/antonyscmputer/house
~/house 
$ mv dorothy house/oz
mv: rename dorothy to house/oz: No such file or directory
~/house 
$ mv dorothy.txt house/oz
mv: rename dorothy.txt to house/oz: No such file or directory
~/house 
$ pwd
/Users/antonyscmputer/house
~/house 
$ mv dorothy.txt /Users/antonyscmputer/house/oz
~/house 
$ cd oz
~/house/oz 
$ ls
dorothy.txt         good_withc_of_the_south.txt
good_witch_of_the_north.txt wicked_witch_of_the_west.txt
~/house/oz 
$ touch scarecrow.txt tin_man.txt cowardly_lion.txt
~/house/oz 
$ mkdir emerald city
~/house/oz 
$ ls
city                good_withc_of_the_south.txt
cowardly_lion.txt       scarecrow.txt
dorothy.txt         tin_man.txt
emerald             wicked_witch_of_the_west.txt
good_witch_of_the_north.txt
~/house/oz 
$ pwd
/Users/antonyscmputer/house/oz
~/house/oz 
$ mv scarecrow.txt tin_man.txt cowardly_lion.txt /Users/antonyscmputer/house/oz/emerald_city
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/house/oz 
$ cd emerald city
~/house/oz/emerald 
$ ls
~/house/oz/emerald 
$ ls
~/house/oz/emerald 
$ cd ..
~/house/oz 
$ ls
city                good_withc_of_the_south.txt
cowardly_lion.txt       scarecrow.txt
dorothy.txt         tin_man.txt
emerald             wicked_witch_of_the_west.txt
good_witch_of_the_north.txt
~/house/oz 
$ mv /house/oz/emerald /house/oz/emerald_city
mv: rename /house/oz/emerald to /house/oz/emerald_city: No such file or directory
~/house/oz 
$ cd ~
~ 
$ pwd
/Users/antonyscmputer
~ 
$ ls
Applications    Downloads   Music       fundamentals    wdi
Desktop     Library     Pictures    funny_things    world
Documents   Movies      Public      house
~ 
$ cd house
~/house 
$ pwd
/Users/antonyscmputer/house
~/house 
$ cd emerald
-bash: cd: emerald: No such file or directory
~/house 
$ ls
oz      toto.txt
~/house 
$ cd oz
~/house/oz 
$ ls
city                good_withc_of_the_south.txt
cowardly_lion.txt       scarecrow.txt
dorothy.txt         tin_man.txt
emerald             wicked_witch_of_the_west.txt
good_witch_of_the_north.txt
~/house/oz 
$ pwd
/Users/antonyscmputer/house/oz
~/house/oz 
$ cd emerald
~/house/oz/emerald 
$ pwd
/Users/antonyscmputer/house/oz/emerald
~/house/oz/emerald 
$ mv /Users/antonyscmputer/house/oz/emerald /Users/antonyscmputer/house/oz/emerald_city
~/house/oz/emerald 
$ ls
~/house/oz/emerald 
$ cd ..
~/house/oz 
$ ls
city                good_withc_of_the_south.txt
cowardly_lion.txt       scarecrow.txt
dorothy.txt         tin_man.txt
emerald_city            wicked_witch_of_the_west.txt
good_witch_of_the_north.txt
~/house/oz 
$ pwd
/Users/antonyscmputer/house/oz
~/house/oz 
$ cd emerald_city
~/house/oz/emerald_city 
$ cd ..
~/house/oz 
$ ls
city                good_withc_of_the_south.txt
cowardly_lion.txt       scarecrow.txt
dorothy.txt         tin_man.txt
emerald_city            wicked_witch_of_the_west.txt
good_witch_of_the_north.txt
~/house/oz 
$ mv scarecrow.txt tin_man.txt cowardly_lion.txt ~/house/oz/emerald_city 
~/house/oz 
$ cd emerald_city
~/house/oz/emerald_city 
$ ls
cowardly_lion.txt   scarecrow.txt       tin_man.txt
~/house/oz/emerald_city 
$ cd ..
~/house/oz 
$ touch flying_monkeys.txt
~/house/oz 
$ ls
city                good_witch_of_the_north.txt
dorothy.txt         good_withc_of_the_south.txt
emerald_city            wicked_witch_of_the_west.txt
flying_monkeys.txt
~/house/oz 
$ rm wicked_witch_of_the_west.txt
~/house/oz 
$ ls
city                flying_monkeys.txt
dorothy.txt         good_witch_of_the_north.txt
emerald_city            good_withc_of_the_south.txt
~/house/oz 
$ cd emerald_city
~/house/oz/emerald_city 
$ echo "a diploma" >>scarecrow.txt
~/house/oz/emerald_city 
$ ls
cowardly_lion.txt   scarecrow.txt       tin_man.txt
~/house/oz/emerald_city 
$ open scarecrow.txt
~/house/oz/emerald_city 
$ pwd
/Users/antonyscmputer/house/oz/emerald_city
~/house/oz/emerald_city 
$ echo "a heart shaped watch" >>tin_man.txt
~/house/oz/emerald_city 
$ open tin_man.txt
~/house/oz/emerald_city 
$ echo "a medal for bravery" >>cowardly_lon.txt
~/house/oz/emerald_city 
$ open cowardly_lion.txt
~/house/oz/emerald_city 
$ echo "a medal for bravery" >>cowardly_lon.txti
~/house/oz/emerald_city 
$ open cowardly_lion.txt
~/house/oz/emerald_city 
$ echo "a medal for bravery" >>cowardly_lion.txti
~/house/oz/emerald_city 
$ open cowardly_lion.txt
~/house/oz/emerald_city 
$ ls
cowardly_lion.txt   cowardly_lon.txt    scarecrow.txt
cowardly_lion.txti  cowardly_lon.txti   tin_man.txt
~/house/oz/emerald_city 
$ open cowardly_lon.txt
~/house/oz/emerald_city 
$ rm cowardly_lon.txt
~/house/oz/emerald_city 
$ ls
cowardly_lion.txt   cowardly_lon.txti   tin_man.txt
cowardly_lion.txti  scarecrow.txt
~/house/oz/emerald_city 
$ echo "a medal for bravery" >>cowardly_lion.txt
~/house/oz/emerald_city 
$ open cowardly_lion.txt
~/house/oz/emerald_city
