### ISSUE TITLE
Sanjaya's Day 1 HW

### ISSUE THREAD

**Issue by ssatyal** [ga-wdi-exercises/to_oz#10]
Last login: Mon Feb  8 16:09:44 on ttys000
~ 
$ pwd
/Users/satyal89
~ 
$ cd /wdi
-bash: cd: /wdi: No such file or directory
~ 
$ cd wdi
~/wdi 
$ pwd
/Users/satyal89/wdi
~/wdi 
$ mkdir House
~/wdi 
$ cd House
~/wdi/House 
$ touch Dorothy.txt Toto.txt
~/wdi/House 
$ mkdir Oz
~/wdi/House 
$ cd Oz
~/wdi/House/Oz 
$ touch Good\ Witch\ of\ the\ North.txt Wicked\ Witch\ of\ the\ East.txt Good\ Witch\ of\ the\ South.txt Wicked\ Witch\ of\ the\ West.txt
~/wdi/House/Oz 
$ rm Wicked\ Witch\ of\ the\ East.txt
~/wdi/House/Oz 
$ mv Dorothy.txt /Oz
mv: rename Dorothy.txt to /Oz: No such file or directory
~/wdi/House/Oz 
$ mv Dorothy.txt ~/Oz/
mv: rename Dorothy.txt to /Users/satyal89/Oz/: No such file or directory
~/wdi/House/Oz 
$ pwd
/Users/satyal89/wdi/House/Oz
~/wdi/House/Oz 
$ mv Dorothy.txt ~/wdi/House/Oz/
mv: rename Dorothy.txt to /Users/satyal89/wdi/House/Oz/Dorothy.txt: No such file or directory
~/wdi/House/Oz 
$ cd .
~/wdi/House/Oz 
$ cd .
~/wdi/House/Oz 
$ cd ..
~/wdi/House 
$ mv Dorothy.txt ~/wdi/House/Oz/
~/wdi/House 
$ touch Scarecrow.txt Tin\ Man.txt Cowardly\ Lion.txt
~/wdi/House 
$ mkdir Emerald\ City
~/wdi/House 
$ mv Scarecrow.txt Tin\ Man.txt Cowardly\ Lion.txt ~/wdi/House/Emerald\ City
~/wdi/House 
$ touch Flying\ Monkeys.txt
~/wdi/House 
$ rm /Oz/Wicked\ Witch\ of\ the\ West.txt
rm: /Oz/Wicked Witch of the West.txt: No such file or directory
~/wdi/House 
$ rm ~/wdi/House/Oz/Wicked\ Witch\ of\ the\ West.txt
~/wdi/House 
$ echo "a diploma" >> Oz/Scarecrow.txt
~/wdi/House 
$ echo "a heart shaped watch" >> Oz/Tin\ Man.txt
~/wdi/House 
$ echo "a medal" >> Oz/Cowardly\ Lion.txt
~/wdi/House 
$

**Comment by RobertAKARobin** [comment]
Writing backslashes is annoying, so you can also write `echo "a medal" >> Oz/"Cowardly Lion.txt"`
