### ISSUE TITLE
Ben Brizzi HW1

### ISSUE THREAD

**Issue by brizzi10** [ga-wdi-exercises/to_oz#101]
Comfort: 5
Completeness: 5
Comments: After each command in the terminal, I receive a message "-bash: __git_ps1: command not found", which I am assuming is the result of an error during the install-fest. I believe this is preventing the terminal from showing the current path to the working directory to the left of the $.

```
$ mkdir house
$ cd house
$ touch Dorothy
$ touch Toto
$ cd ..
$ mkdir Oz
$ cd Oz
$ touch "Good Witch of the North"
$ touch "Wicked Witch of the East"
$ touch "Good Witch of the South"
$ touch "Wicked Witch of the West"
$ rm "Wicked Witch of the East"
$ mv ../House/Dorothy .
$ touch "Scarecrow"
$ touch "Tin Man"
$ touch "Cowardly Lion"
$ cd ..
$ mkdir "Emerald City"
$ mv "Cowardly Lion" "Dorothy" "Scarecrow" "Tin Man" ../"Emerald City"/
$ touch "Flying Monkeys"
$ rm "Wicked Witch of the West"
$ cd ..
$ cd "Emerald City"
$ echo "a diploma" >> ./Scarecrow
$ echo "a heart shaped watch" >> ./"Tin Man"
$ echo "a medal" >> ./"Cowardly Lion"
```

**Comment by andrewsunglaekim** [comment]
get with me during office hours tonight or at some point, and we'll get rid of that git ps1 error but gj!
👍
