### ISSUE TITLE
Jac Ahn's HW: to_oz

### ISSUE THREAD

**Issue by jacahn** [ga-wdi-exercises/to_oz#102]
Comfort: 3.5

Completeness: 3.5

Comments: The devil is in the details! I realize how closely I have to read instructions because, I made directories for Dorothy and Toto, but the instructions asked for files. At first I felt pretty comfy with the exercise, but then I kept making mistakes and realized that I needed to be way more careful.

Jacs-MacBook-Pro:to_oz jacahn$ mkdir House
Jacs-MacBook-Pro:to_oz jacahn$ cd House
Jacs-MacBook-Pro:House jacahn$ mkdir Dorothy
Jacs-MacBook-Pro:House jacahn$ mkdir Toto
Jacs-MacBook-Pro:House jacahn$ cd ..
Jacs-MacBook-Pro:to_oz jacahn$ mkdir Oz
Jacs-MacBook-Pro:Oz jacahn$ mkdir GoodWitchoftheNorth WickedWitchoftheEast WickedWitchoftheWest GoodWitchoftheSouth
Jacs-MacBook-Pro:Oz jacahn$ ls
GoodWitchoftheNorth WickedWitchoftheEast
GoodWitchoftheSouth WickedWitchoftheWest
Jacs-MacBook-Pro:Oz jacahn$ rm -r WickedWitchoftheEast
Jacs-MacBook-Pro:Oz jacahn$ ls
GoodWitchoftheNorth GoodWitchoftheSouth WickedWitchoftheWest

Jacs-MacBook-Pro:Oz jacahn$ cd ..
Jacs-MacBook-Pro:to_oz jacahn$ cd House
Jacs-MacBook-Pro:House jacahn$ mv Dorothy ../Oz
Jacs-MacBook-Pro:House jacahn$ ls
Toto
Jacs-MacBook-Pro:House jacahn$ cd ..
Jacs-MacBook-Pro:to_oz jacahn$ cd Oz
Jacs-MacBook-Pro:Oz jacahn$ ls
Dorothy         GoodWitchoftheSouth
GoodWitchoftheNorth WickedWitchoftheWest
Jacs-MacBook-Pro:Oz jacahn$ 

Jacs-MacBook-Pro:Oz jacahn$ touch Scarecrow.f TinMan.f CowardlyLion.f
Jacs-MacBook-Pro:Oz jacahn$ ls
CowardlyLion.f      GoodWitchoftheSouth WickedWitchoftheWest
Dorothy         Scarecrow.f
GoodWitchoftheNorth TinMan.f

Jacs-MacBook-Pro:Oz jacahn$ mv Scarecrow.f TinMan.f CowardlyLion.f EmeraldCity
Jacs-MacBook-Pro:Oz jacahn$ ls
Dorothy         GoodWitchoftheNorth WickedWitchoftheWest
EmeraldCity     GoodWitchoftheSouth
Jacs-MacBook-Pro:Oz jacahn$ cd EmeraldCity
Jacs-MacBook-Pro:EmeraldCity jacahn$ ls
CowardlyLion.f  Scarecrow.f TinMan.f
Jacs-MacBook-Pro:EmeraldCity jacahn$ cd ..
Jacs-MacBook-Pro:Oz jacahn$ touch FlyingMonkeys.f
Jacs-MacBook-Pro:Oz jacahn$ rm -r WickedWitchoftheWest
Jacs-MacBook-Pro:Oz jacahn$ cd EmeraldCity
Jacs-MacBook-Pro:EmeraldCity jacahn$ ls
CowardlyLion.f  Scarecrow.f TinMan.f
Jacs-MacBook-Pro:EmeraldCity jacahn$ echo "a diploma" >> EmeraldCity/Scarecrow
-bash: EmeraldCity/Scarecrow: No such file or directory
Jacs-MacBook-Pro:EmeraldCity jacahn$ echo "a diploma" >> EmeraldCity/Scarecrow.f
-bash: EmeraldCity/Scarecrow.f: No such file or directory
Jacs-MacBook-Pro:EmeraldCity jacahn$

**Comment by andrewsunglaekim** [comment]
👍
