### ISSUE TITLE
Daniela Noir HW

### ISSUE THREAD

**Issue by danielanoir** [ga-wdi-exercises/to_oz#103]
Comfort Score: 5
Completeness: 5

Comments: Learned a lot about "mv" command. I don't really understand what "echo" did. I'm worried the gang didn't get gifts and may feel unappreciated :(.

'''
dani@T550:~$ mkdir House
dani@T550:~$ pwd
/home/dani
dani@T550:~$ cd House
dani@T550:~/House$ touch Dorothy
dani@T550:~/House$ touch Toto
dani@T550:~/House$ ls
Dorothy Toto
dani@T550:~/House$ cd ~
dani@T550:~$ pwd
/home/dani
dani@T550:~$ mkdir Oz
dani@T550:~$ touch Good Witch of the North
dani@T550:~$ touch Wickd Witch of the East
dani@T550:~$ touch Good Witch of the South
dani@T550:~$ touch Wicked Witch of the West
dani@T550:~$ ls
Daniela East Good Music Pictures the Wicked
Desktop examples.desktop hello world.txt North Public Videos Witch
Documents file1 House of South West
Downloads fundamentals index.html Oz Templates Wickd
dani@T550:~$ ls
Daniela Documents examples.desktop House Music Pictures Templates
Desktop Downloads fundamentals index.html Oz Public Videos
dani@T550:~$ cd Oz
dani@T550:~/Oz$ ls
dani@T550:~/Oz$ ls
dani@T550:~/Oz$ pwd
/home/dani/Oz
dani@T550:~/Oz$ cd Oz
bash: cd: Oz: No such file or directory
dani@T550:~/Oz$ pwd
/home/dani/Oz
dani@T550:~/Oz$ pwd
/home/dani/Oz
dani@T550:~/Oz$ pwd
/home/dani/Oz
dani@T550:~/Oz$ pwd
/home/dani/Oz
dani@T550:~/Oz$ ls
dani@T550:~/Oz$ cd ~
dani@T550:~$ pwd
/home/dani
dani@T550:~$ cd Oz
bash: cd: Oz: No such file or directory
dani@T550:~$ mkdir Oz
dani@T550:~$ pwd
/home/dani
dani@T550:~$ cd Oz
dani@T550:~/Oz$ ls
dani@T550:~/Oz$ touch "Good Witch of the North"
dani@T550:~/Oz$ ls
Good Witch of the North
dani@T550:~/Oz$ touch "Wicked Witch of the East" "Good Witch of the South"
dani@T550:~/Oz$ ls
Good Witch of the North Good Witch of the South Wicked Witch of the East
dani@T550:~/Oz$ touch "Wicked Witch of the West"
dani@T550:~/Oz$ ls
Good Witch of the North Wicked Witch of the East
Good Witch of the South Wicked Witch of the West
dani@T550:~/Oz$ rm "Wicked Witch of the East"
dani@T550:~/Oz$ ls
Good Witch of the North Good Witch of the South Wicked Witch of the West
dani@T550:~/Oz$ mv Dorothy Oz/
mv: cannot stat 'Dorothy': No such file or directory
dani@T550:~/Oz$ cd~
No command 'cd~' found, did you mean:
Command 'cde' from package 'cde' (universe)
Command 'cdp' from package 'irpas' (multiverse)
Command 'cdv' from package 'codeville' (universe)
Command 'cdb' from package 'tinycdb' (main)
Command 'cdw' from package 'cdw' (universe)
Command 'cd5' from package 'cd5' (universe)
Command 'cdo' from package 'cdo' (universe)
Command 'cdi' from package 'cdo' (universe)
cd~: command not found
dani@T550:~/Oz$ cd ~
dani@T550:~$ pwd
/home/dani
dani@T550:~$ ls
Daniela Documents examples.desktop House Music Pictures Templates
Desktop Downloads fundamentals index.html Oz Public Videos
dani@T550:~$ cd House
dani@T550:~/House$ ls
Dorothy Toto
dani@T550:~/House$ mv Dorothy Oz/
mv: cannot move 'Dorothy' to 'Oz/': Not a directory
dani@T550:~/House$ pwd
/home/dani/House
dani@T550:~/House$ cd ~
dani@T550:~$ pwd
/home/dani
dani@T550:~$ mv Dorothy Oz/
mv: cannot stat 'Dorothy': No such file or directory
dani@T550:~$ cd House
dani@T550:~/House$ mv Dorothy Oz/
mv: cannot move 'Dorothy' to 'Oz/': Not a directory
dani@T550:~/House$ cd ..
dani@T550:~$ pwd
/home/dani
dani@T550:~$ cd Oz
dani@T550:~/Oz$ mv Dorothy Oz/
mv: cannot stat 'Dorothy': No such file or directory
dani@T550:~/Oz$ mv Home/House/Dorothy Home/Oz/
mv: cannot stat 'Home/House/Dorothy': No such file or directory
dani@T550:~/Oz$ cd~
No command 'cd~' found, did you mean:
Command 'cd5' from package 'cd5' (universe)
Command 'cdo' from package 'cdo' (universe)
Command 'cdb' from package 'tinycdb' (main)
Command 'cdw' from package 'cdw' (universe)
Command 'cdv' from package 'codeville' (universe)
Command 'cdi' from package 'cdo' (universe)
Command 'cdp' from package 'irpas' (multiverse)
Command 'cde' from package 'cde' (universe)
cd~: command not found
dani@T550:~/Oz$ cd ~
dani@T550:~$ pwd
/home/dani
dani@T550:~$ ls
Daniela Documents examples.desktop House Music Pictures Templates
Desktop Downloads fundamentals index.html Oz Public Videos
dani@T550:~$ cd House
dani@T550:~/House$ ls
Dorothy Toto
dani@T550:~/House$ cd ~
dani@T550:~$ pwd
/home/dani
dani@T550:~$ mv /home/House/Dorothy /home/Oz/
mv: cannot stat '/home/House/Dorothy': No such file or directory
dani@T550:~$ cd ~
dani@T550:~$ pwd
/home/dani
dani@T550:~$ ls
Daniela Documents examples.desktop House Music Pictures Templates
Desktop Downloads fundamentals index.html Oz Public Videos
dani@T550:~$ mv /House/Dorothy /Oz/
mv: cannot stat '/House/Dorothy': No such file or directory
dani@T550:~$ mv Dorothy Oz/
mv: cannot stat 'Dorothy': No such file or directory
dani@T550:~$ cd house
bash: cd: house: No such file or directory
dani@T550:~$ cd House
dani@T550:~/House$ lst
No command 'lst' found, but there are 17 similar ones
lst: command not found
dani@T550:~/House$ pwd
/home/dani/House
dani@T550:~/House$ ls
Dorothy Toto
dani@T550:~/House$ cd ..
dani@T550:~$ ls
Daniela Documents examples.desktop House Music Pictures Templates
Desktop Downloads fundamentals index.html Oz Public Videos
dani@T550:~$ mv ~/House/Dorothy Oz/
dani@T550:~$ cd Oz
dani@T550:~/Oz$ ls
Dorothy Good Witch of the South
Good Witch of the North Wicked Witch of the West
dani@T550:~/Oz$ cd ~
dani@T550:~$ pwd
/home/dani
dani@T550:~$ touch "Scarecrow"
dani@T550:~$ ls
Daniela Downloads House Oz Scarecrow
Desktop examples.desktop index.html Pictures Templates
Documents fundamentals Music Public Videos
dani@T550:~$ touch "Tin Man" "Cowardly Lion"
dani@T550:~$ ls
Cowardly Lion Documents fundamentals Music Public Tin Man
Daniela Downloads House Oz Scarecrow Videos
Desktop examples.desktop index.html Pictures Templates
dani@T550:~$ mkdir "Emerald City"
dani@T550:~$ ls
Cowardly Lion Documents examples.desktop index.html Pictures Templates
Daniela Downloads fundamentals Music Public Tin Man
Desktop Emerald City House Oz Scarecrow Videos
dani@T550:~$ mv ~/Cowardly Lion ~/Emerald City
mv: target 'City' is not a directory
dani@T550:~$ mv ~/Cowardly Lion ~/Emerald City/
mv: target 'City/' is not a directory
dani@T550:~$ mv ~/"Cowardly Lion" ~/"Emerald City"/
dani@T550:~$ pwd
/home/dani
dani@T550:~$ cd Emerald City
bash: cd: Emerald: No such file or directory
dani@T550:~$ cd "Emerald City"
dani@T550:~/Emerald City$ ls
Cowardly Lion
dani@T550:~/Emerald City$ mv ~/"Tin man" ~/"Scarecrow" ~/"Emerald City"/
mv: cannot stat '/home/dani/Tin man': No such file or directory
dani@T550:~/Emerald City$ mv ~/"Tin Man" ~/"Scarecrow" ~/"Emerald City"/
mv: cannot stat '/home/dani/Scarecrow': No such file or directory
dani@T550:~/Emerald City$ ls
Cowardly Lion Scarecrow Tin Man
dani@T550:~/Emerald City$ cd ..
dani@T550:~$ pwd
/home/dani
dani@T550:~$ ls
Daniela Downloads fundamentals Music Public
Desktop Emerald City House Oz Templates
Documents examples.desktop index.html Pictures Videos
dani@T550:~$ cd Oz
dani@T550:~/Oz$ touch "Flying Monkeys"
dani@T550:~/Oz$ ls
Dorothy Good Witch of the North Wicked Witch of the West
Flying Monkeys Good Witch of the South
dani@T550:~/Oz$ rm "Wicked Witch of the West"
dani@T550:~/Oz$ ls
Dorothy Flying Monkeys Good Witch of the North Good Witch of the South
dani@T550:~/Oz$ echo "a diploma" >> Oz/Scarecrow
bash: Oz/Scarecrow: No such file or directory
dani@T550:~/Oz$ echo "a heart shaped watch" >> Oz/"Tin Man"
bash: Oz/Tin Man: No such file or directory
dani@T550:~/Oz$ echo "a heard shaped watch" >> Oz/Tin Man
bash: Oz/Tin: No such file or directory
dani@T550:~/Oz$ ls
Dorothy Flying Monkeys Good Witch of the North Good Witch of the South
dani@T550:~/Oz$ cd ..
dani@T550:~$ pwd
/home/dani
dani@T550:~$ cd "Emerald City"
dani@T550:~/Emerald City$ ls
Cowardly Lion Scarecrow Tin Man
dani@T550:~/Emerald City$ cd Scarecrow
bash: cd: Scarecrow: Not a directory
dani@T550:~/Emerald City$ ~cd
No command '~cd' found, did you mean:
Command 'bcd' from package 'bsdgames' (universe)
Command 'hcd' from package 'hfsutils' (main)
Command 'mcd' from package 'mtools' (main)
~cd: command not found
dani@T550:~/Emerald City$ cd ~
dani@T550:~$ echo "a heart shaped watch" >> ~/Oz/"Tin Man"
dani@T550:~$ echo "a medal" >> ~/Oz/"Lion"
dani@T550:~$ ^C
dani@T550:~$
'''

**Comment by superbuggy** [comment]
Looks like you're getting the hang of the CLI, but you probably want to make sure you _aren't_ doing HW in your root directory (`cd ~`). Instead, we recommend that you make an `exercises` directory _inside_ of a `wdi` directory. Please reach out to us if you have questions, the earlier the better. We aren't about weeding out students and like to help! Good work though!
