### ISSUE TITLE
D.Giranew HW#1

### ISSUE THREAD

**Issue by D-giranew** [ga-wdi-exercises/to_oz#106]
...
giranew@giranew-HP-Pavilion-17-Notebook-PC:~$ ~/wdi/exercises
bash: /home/giranew/wdi/exercises: Is a directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~$ mkdir House
mkdir: cannot create directory ‘House’: File exists
giranew@giranew-HP-Pavilion-17-Notebook-PC:~$ cd House/
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House$ touch Dorothy Toto
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House$ ls
Dorothy  Toto
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House$ mkdir Oz
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House$ cd Oz
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ touch Good Witch of the North Wicked Witch of the EastGood Witch of the South Wicked Witch of the West
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ ls
EastGood  Good  North  of  South  the  West  Wicked  Witch
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ rmdir Oz
rmdir: failed to remove 'Oz': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ ls
EastGood  Good  North  of  South  the  West  Wicked  Witch
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South  Wicked_Witch_of_the_West
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ ls
EastGood                 North  West                      Witch
Good                     of     Wicked
Good_Witch_of_the_North  South  Wicked_Witch_of_the_East
Good_Witch_of_the_South  the    Wicked_Witch_of_the_West
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ rm "Wicked Witch of the East"rm: cannot remove 'Wicked Witch of the East': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ ^C
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ rm "Wicked Witch of the East"rm: cannot remove 'Wicked Witch of the East': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ rm Wicked_Witch_of_the_West
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ ls
EastGood  Good_Witch_of_the_North  North  South  West    Wicked_Witch_of_the_East
Good      Good_Witch_of_the_South  of     the    Wicked  Witch
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Dorothy Oz/
mv: cannot move '/home/giranew/House/Dorothy' to 'Oz/': Not a directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Dorothy Oz
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ touch Scarecrow
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ touch Tin Man
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ touch Cowardly Lion
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mkdir Emerald City
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Scarecrow Emerald City
mv: cannot stat '/home/giranew/House/Scarecrow': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Tin Man Emerald City
mv: cannot stat '/home/giranew/House/Tin': No such file or directory
mv: cannot stat 'Emerald': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Cowardly Lion Emerald City
mv: cannot stat '/home/giranew/House/Cowardly': No such file or directory
mv: cannot stat 'Emerald': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Oz/Scarecrow Emerald City
mv: cannot stat 'Emerald': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Oz/Tin Man Emerald City
mv: cannot stat 'Man': No such file or directory
mv: cannot stat 'Emerald': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Oz/Cowardly Lion Emerald City
mv: cannot stat 'Lion': No such file or directory
mv: cannot stat 'Emerald': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ 
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Oz Scarecrow Emerald City
mv: cannot move '/home/giranew/House/Oz' to a subdirectory of itself, 'City/Oz'
mv: cannot stat 'Scarecrow': No such file or directory
mv: cannot stat 'Emerald': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Oz Tin Man Emerald City
mv: cannot move '/home/giranew/House/Oz' to a subdirectory of itself, 'City/Oz'
mv: cannot stat 'Tin': No such file or directory
mv: cannot stat 'Man': No such file or directory
mv: cannot stat 'Emerald': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Oz Cowardly Lion Emerald City
mv: cannot move '/home/giranew/House/Oz' to a subdirectory of itself, 'City/Oz'
mv: cannot stat 'Cowardly': No such file or directory
mv: cannot stat 'Lion': No such file or directory
mv: cannot stat 'Emerald': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Oz Scarecrow Emerald City
mv: cannot move '/home/giranew/House/Oz' to a subdirectory of itself, 'City/Oz'
mv: cannot stat 'Scarecrow': No such file or directory
mv: cannot stat 'Emerald': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Oz Tin_Man Emerald City
mv: cannot move '/home/giranew/House/Oz' to a subdirectory of itself, 'City/Oz'
mv: cannot stat 'Tin_Man': No such file or directory
mv: cannot stat 'Emerald': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv ~/House/Oz Cowardly_Lion Emerald City
mv: cannot move '/home/giranew/House/Oz' to a subdirectory of itself, 'City/Oz'
mv: cannot stat 'Cowardly_Lion': No such file or directory
mv: cannot stat 'Emerald': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$  mv ~/"Cowardly Lion" ~/"Emerald City"/
mv: cannot stat '/home/giranew/Cowardly Lion': No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ ls
City                     North  West
EastGood                 of     Wicked
Good                     Oz     Wicked_Witch_of_the_East
Good_Witch_of_the_North  South  Witch
Good_Witch_of_the_South  the
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ cd ~/House
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House$ ls
Oz  Toto
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House$ ~/House/Ozbash: /home/giranew/House/Oz: Is a directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House$ cd ~/House Oz
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House$ cd Oz
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ ls
City                     North  West
EastGood                 of     Wicked
Good                     Oz     Wicked_Witch_of_the_East
Good_Witch_of_the_North  South  Witch
Good_Witch_of_the_South  the
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ cd Emerald City
bash: cd: Emerald: No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ touch Scarecrow
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ ls
City                     North      the
EastGood                 of         West
Good                     Oz         Wicked
Good_Witch_of_the_North  Scarecrow  Wicked_Witch_of_the_East
Good_Witch_of_the_South  South      Witch
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ touch Tin_Man
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ ls
City                     of         West
EastGood                 Oz         Wicked
Good                     Scarecrow  Wicked_Witch_of_the_East
Good_Witch_of_the_North  South      Witch
Good_Witch_of_the_South  the
North                    Tin_Man
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ touch Cowardly_Lion
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ ls
City                     North      Tin_Man
Cowardly_Lion            of         West
EastGood                 Oz         Wicked
Good                     Scarecrow  Wicked_Witch_of_the_East
Good_Witch_of_the_North  South      Witch
Good_Witch_of_the_South  the
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mkdir Emerald_City
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ ls
City                     Oz
Cowardly_Lion            Scarecrow
EastGood                 South
Emerald_City             the
Good                     Tin_Man
Good_Witch_of_the_North  West
Good_Witch_of_the_South  Wicked
North                    Wicked_Witch_of_the_East
of                       Witch
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ cd House
bash: cd: House: No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ cd~/House
bash: cd~/House: No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv Scarecrow Emerald_City
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv Tin_Man Emerald_City
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ mv Cowardly_Lion Emerald_City
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ touch Flying_Monkeys
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ rm Wicked_Witch_of_the_East
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ touch Wicked Witch of the West
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ rm Wicked Witch of the West
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ echo "a diploma" >> Oz/Scarecrow
bash: Oz/Scarecrow: Not a directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ echo "a heart shaped watch" >> Oz/Scarecrow
bash: Oz/Scarecrow: Not a directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ echo "a medal" >> Oz/Scarecrow
bash: Oz/Scarecrow: Not a directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ echo "a diploma" >> Emerald_City/Scarecrow
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ echo "a heart shaped watch" >> Emerald_City/Tin_Man
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ echo "a medal" >> Emerald_City/Cowardly_Lion
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/House/Oz$ 
...

Comfort:2
Completeness: 4

**Comment by nayana487** [comment]
Did you have any questions on this? Feel free to reach out for help.
