### ISSUE TITLE
Pamela Olneys HW Week 1:Day 1

### ISSUE THREAD

**Issue by pamelaolney** [ga-wdi-exercises/to_oz#108]
Comfort: 4
Completeness: 4

This homework was okay.  I just don't understand how to move files from one directory to another.

For example. Move "Dorothy" from "House" to "Oz"

`$mv Dorothy.txt Oz/`

Homework is below.

```
$mkdir house
$cd house
$touch Dorothy.txt Toto.txt
$cd ..
$mkdir Oz
$touch "Good Witch of the North".txt
$touch "Wicked Witch of the East".txt
$touch "Good Witch of the South".txt
$touch "Wicked Witch of the West".txt
$rm "Wicked Witch of the East".txt

Unfortunately I still dont understanding move text files from one dir to another one that is outside of the folder.

$touch Scarecrow.txt "Tin Man".txt "Cowardly Lion".txt
$mkdir Emerald city
$mv Scarecrow.txt "Tin Man".txt "Cowardly Lion".txt  "Emerald city"/
$cd ..
$cd Oz
$touch "Flying Monkeys".txt
$rm "Wicked Witch of the West"
Give Scarecrow a diploma
Give Tin Man a heart shaped watch
Give Lion a medal
$ echo "a diploma" >> Oz/Scarecrow
$ echo "a heart shaped watch" >> Oz/"Tin Man"
$ echo "a medal" >> Oz/Lion
```

**Comment by superbuggy** [comment]
👍 for pointing out what you need help with. Note that `mkdir Emerald city` will make 2 directories, `Emerald` and `city`. You obviously used ""s with the other files, so I know you get the concept of needing quotes if you have spaces in the file name. Note that sometimes you need to use a backward slash `\` if you reference a directory whose name contains a space, and are not using quotes. That's a mouthful so here's a pic:
![image](https://cloud.githubusercontent.com/assets/17716232/16458224/567de3e0-3dec-11e6-9072-daf523867d79.png)
