### ISSUE TITLE
Gio Homework #1

### ISSUE THREAD

**Issue by GioSilva** [ga-wdi-exercises/to_oz#109]
'''
$ mkdir house
-bash: __git_ps1: command not found
  Tue Jun 28 06:58:33 ~
$ ls
Applications        Downloads       Pictures
Creative Cloud Files    Library         Public
Desktop         Movies          house
Documents       Music           wdi
-bash: __git_ps1: command not found
  Tue Jun 28 06:59:03 ~
$ touch --help
touch: illegal option -- -
usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...
-bash: __git_ps1: command not found
  Tue Jun 28 07:02:14 ~
$ touch house/Dorothy.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:05:05 ~
$ touch house/Toto.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:05:17 ~
$ ls house
Dorothy.txt Toto.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:05:25 ~
$ mkdir Oz
-bash: __git_ps1: command not found
  Tue Jun 28 07:06:00 ~
$ touch house/Good_Witch_of_the_North
-bash: __git_ps1: command not found
  Tue Jun 28 07:06:33 ~
$ ls house
Dorothy.txt     Good_Witch_of_the_North Toto.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:06:41 ~
$ mv Good_Witch_of_the_North /Oz
mv: rename Good_Witch_of_the_North to /Oz: No such file or directory
-bash: __git_ps1: command not found
  Tue Jun 28 07:09:09 ~
$ ls Oz
-bash: __git_ps1: command not found
  Tue Jun 28 07:09:14 ~
$ ls Oz
-bash: __git_ps1: command not found
  Tue Jun 28 07:09:25 ~
$ ls house
Dorothy.txt     Good_Witch_of_the_North Toto.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:09:34 ~
$ mv Good_Witch_of_the_North Oz/
mv: rename Good_Witch_of_the_North to Oz/Good_Witch_of_the_North: No such file or directory
-bash: __git_ps1: command not found
  Tue Jun 28 07:10:23 ~
$ ls Oz
-bash: __git_ps1: command not found
  Tue Jun 28 07:10:29 ~
$ mv house/Good_Witch_of_the_North Oz/Good_Witch_of_the_North
-bash: __git_ps1: command not found
  Tue Jun 28 07:11:38 ~
$ ls Oz
Good_Witch_of_the_North
-bash: __git_ps1: command not found
  Tue Jun 28 07:11:42 ~
$ mv Oz/Good_Witch_of_the_North Oz/Good_Witch_of_the_North.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:12:17 ~
$ ls Oz
Good_Witch_of_the_North.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:12:20 ~
$ touch Oz/Wicked Witch of the North
-bash: __git_ps1: command not found
  Tue Jun 28 07:13:25 ~
$ ls Oz
Good_Witch_of_the_North.txt Wicked
-bash: __git_ps1: command not found
  Tue Jun 28 07:13:30 ~
$ rm Oz/Wicked
-bash: __git_ps1: command not found
  Tue Jun 28 07:13:46 ~
$ ls Oz
Good_Witch_of_the_North.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:13:49 ~
$ touch Oz/Wicked_Witch_of_the_East.txt Oz/Good_Witch_of_the_South.txt Oz/Wicked_Witch_of_the_West.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:15:44 ~
$ ls Oz
Good_Witch_of_the_North.txt Wicked_Witch_of_the_East.txt
Good_Witch_of_the_South.txt Wicked_Witch_of_the_West.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:15:46 ~
$ rm Oz/Wicked_Witch_of_the_East.txt 
-bash: __git_ps1: command not found
  Tue Jun 28 07:16:49 ~
$ move house/Dorothy.txt Oz/
-bash: move: command not found
-bash: __git_ps1: command not found
  Tue Jun 28 07:17:16 ~
$ ls Oz
Good_Witch_of_the_North.txt Good_Witch_of_the_South.txt Wicked_Witch_of_the_West.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:17:23 ~
$ mv house/Dorothy.txt Oz/Dorothy.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:17:46 ~
$ ls Oz
Dorothy.txt         Good_Witch_of_the_South.txt
Good_Witch_of_the_North.txt Wicked_Witch_of_the_West.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:17:49 ~
$ ls house
Toto.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:17:53 ~
$ touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt 
-bash: __git_ps1: command not found
  Tue Jun 28 07:19:07 ~
$ mkdir Emerald City
-bash: __git_ps1: command not found
  Tue Jun 28 07:20:05 ~
$ ls
Applications        Documents       Music           Scarecrow.txt       the
City            Downloads       North           Tin_Man.txt     wdi
Cowardly_Lion.txt   Emerald         Oz          Witch
Creative Cloud Files    Library         Pictures        house
Desktop         Movies          Public          of
-bash: __git_ps1: command not found
  Tue Jun 28 07:20:08 ~
$ rm /Emerald
rm: /Emerald: No such file or directory
-bash: __git_ps1: command not found
  Tue Jun 28 07:20:22 ~
$ ls
Applications        Documents       Music           Scarecrow.txt       the
City            Downloads       North           Tin_Man.txt     wdi
Cowardly_Lion.txt   Emerald         Oz          Witch
Creative Cloud Files    Library         Pictures        house
Desktop         Movies          Public          of
-bash: __git_ps1: command not found
  Tue Jun 28 07:20:24 ~
$ mkdir Emerald-City
-bash: __git_ps1: command not found
  Tue Jun 28 07:20:43 ~
$ ls 
Applications        Documents       Movies          Public          of
City            Downloads       Music           Scarecrow.txt       the
Cowardly_Lion.txt   Emerald         North           Tin_Man.txt     wdi
Creative Cloud Files    Emerald-City        Oz          Witch
Desktop         Library         Pictures        house
-bash: __git_ps1: command not found
  Tue Jun 28 07:20:45 ~
$ mv Scarecrow.txt Emerald-City
-bash: __git_ps1: command not found
  Tue Jun 28 07:21:37 ~
$ ls
Applications        Documents       Movies          Public          the
City            Downloads       Music           Tin_Man.txt     wdi
Cowardly_Lion.txt   Emerald         North           Witch
Creative Cloud Files    Emerald-City        Oz          house
Desktop         Library         Pictures        of
-bash: __git_ps1: command not found
  Tue Jun 28 07:21:40 ~
$ ls Emerald-City
Scarecrow.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:21:50 ~
$ mv Tin_Man.txt, Cowardly_Lion.txt Emerald-City
mv: rename Tin_Man.txt, to Emerald-City/Tin_Man.txt,: No such file or directory
-bash: __git_ps1: command not found
  Tue Jun 28 07:22:23 ~
$ mv Tin_Man.txt Emerald-City/Tin_Man.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:23:06 ~
$ ls
Applications        Documents       Library         Oz          house
City            Downloads       Movies          Pictures        of
Creative Cloud Files    Emerald         Music           Public          the
Desktop         Emerald-City        North           Witch           wdi
-bash: __git_ps1: command not found
  Tue Jun 28 07:23:30 ~
$ ls Emerald-city
Cowardly_Lion.txt   Scarecrow.txt       Tin_Man.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:24:19 ~
$ touch Oz/Flying-Monkeys
-bash: __git_ps1: command not found
  Tue Jun 28 07:25:19 ~
$ ls Oz
Dorothy.txt         Good_Witch_of_the_North.txt Wicked_Witch_of_the_West.txt
Flying-Monkeys          Good_Witch_of_the_South.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:25:22 ~
$ echo "a diploma" >> Emerald-City/Scarecrow.txt 
-bash: __git_ps1: command not found
  Tue Jun 28 07:26:54 ~
$ echo "a heart shaped watch" >> Emerald-City/Tin_Man.txt 
-bash: __git_ps1: command not found
  Tue Jun 28 07:28:37 ~
$ echo "a medal" >> Emerald-City/Cowardly_Lion.txt 
-bash: __git_ps1: command not found
  Tue Jun 28 07:29:11 ~
$ ls Emerald-City
Cowardly_Lion.txt   Scarecrow.txt       Tin_Man.txt
-bash: __git_ps1: command not found
  Tue Jun 28 07:29:25 ~
$ rm of
-bash: __git_ps1: command not found
  Tue Jun 28 07:29:47 ~
$ rm the
-bash: __git_ps1: command not found
  Tue Jun 28 07:29:52 ~
$ rm North
-bash: __git_ps1: command not found
  Tue Jun 28 07:29:57 ~
$ ls
Applications        Documents       Library         Pictures        wdi
City            Downloads       Movies          Public
Creative Cloud Files    Emerald         Music           Witch
Desktop         Emerald-City        Oz          house
-bash: __git_ps1: command not found
  Tue Jun 28 07:29:58 ~
$

**Comment by nayana487** [comment]
👍 

Hey, come find one of us during office hours so we can figure out that bash error.
