### ISSUE TITLE
Melissa Homework 1

### ISSUE THREAD

**Issue by holytoastr** [ga-wdi-exercises/to_oz#11]
To Oz? To Oz!
$ mkdir House
$ cd House/
$ touch Dorothy Toto
$ cd ..
$ mkdir Oz
$ cd Oz/
$ touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West

Ding! Dong! The Witch is Dead
$ rm -i Wicked_Witch_of_the_East
remove Wicked_Witch_of_the_East? y
$ cd ../House/
$ mv Dorothy ../Oz/

Follow the Yellow Brick Road
$ cd ../Oz
$ touch Scarecrow Tin_Man Cowardly_Lion
$ mkdir Emerald_City
$ mv Cowardly_Lion Tin_Man Scarecrow Emerald_City/

You Must Kill the Witch
$ touch Flying_Monkeys
$ rm -i Wicked_Witch_of_the_West
remove Wicked_Witch_of_the_West? y
$ echo "a diploma" >> Emerald_City/Scarecrow
$ echo "a heart shaped watch" >> Emerald_City/Tin_Man
$ echo "a medal" >> Emerald_City/Cowardly_Lion

$ mkdir Homework1
$ mv House/ Oz/ Homework1/
$ ls -R Homework1/
House   Oz

Homework1//House:
Toto

Homework1//Oz:
Dorothy         Flying_Monkeys      Good_Witch_of_the_South
Emerald_City        Good_Witch_of_the_North

Homework1//Oz/Emerald_City:
Cowardly_Lion   Scarecrow   Tin_Man

**Comment by RobertAKARobin** [comment]
Noice.
