### ISSUE TITLE
CLI HW (Michael L)

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/to_oz#110]
Last login: Tue Sep  6 15:28:58 on ttys005
 MichaelZLai Tue Sep 06 15:29:08 ~ (master #)
$ pwd
/Users/MichaelZLai
 MichaelZLai Tue Sep 06 16:49:02 ~ (master #)
$ cd wdi
 MichaelZLai Tue Sep 06 16:49:13 ~/wdi (master #)
$ pwd
/Users/MichaelZLai/wdi
 MichaelZLai Tue Sep 06 16:49:15 ~/wdi (master #)
$ ls
Rakefile        installfest.yml projects
exercises       lessons     sandbox
 MichaelZLai Tue Sep 06 16:49:17 ~/wdi (master #)
$ cd exercises
 MichaelZLai Tue Sep 06 16:55:03 ~/wdi/exercises (master #)
$ ls
 MichaelZLai Tue Sep 06 16:55:04 ~/wdi/exercises (master #)
$ pwd
/Users/MichaelZLai/wdi/exercises
 MichaelZLai Tue Sep 06 16:55:06 ~/wdi/exercises (master #)
$ mkdir House
 MichaelZLai Tue Sep 06 16:55:16 ~/wdi/exercises (master #)
$ ls
House
 MichaelZLai Tue Sep 06 16:55:17 ~/wdi/exercises (master #)
$ touch Dorothy Toto
 MichaelZLai Tue Sep 06 16:55:32 ~/wdi/exercises (master #)
$ ls
Dorothy House   Toto
 MichaelZLai Tue Sep 06 16:55:33 ~/wdi/exercises (master #)
$ mv Dorothy House
 MichaelZLai Tue Sep 06 16:57:00 ~/wdi/exercises (master #)
$ ls
House   Toto
 MichaelZLai Tue Sep 06 16:57:01 ~/wdi/exercises (master #)
$ mv Toto House
 MichaelZLai Tue Sep 06 16:57:08 ~/wdi/exercises (master #)
$ ls
House
 MichaelZLai Tue Sep 06 16:57:09 ~/wdi/exercises (master #)
$ mkdir Oz
 MichaelZLai Tue Sep 06 16:57:16 ~/wdi/exercises (master #)
$ touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West Oz
 MichaelZLai Tue Sep 06 16:58:58 ~/wdi/exercises (master #)
$ ls
Good_Witch_of_the_North     Oz
Good_Witch_of_the_South     Wicked_Witch_of_the_East
House               Wicked_Witch_of_the_West
 MichaelZLai Tue Sep 06 16:58:59 ~/wdi/exercises (master #)
$ mv Good_Witch_of_the_North Good_Witch_of_the_South Wicked_Witch_of_the_East Wicked_Witch_of_the_West Oz
 MichaelZLai Tue Sep 06 17:01:11 ~/wdi/exercises (master #)
$ ls
House   Oz
 MichaelZLai Tue Sep 06 17:01:13 ~/wdi/exercises (master #)
$ cd Oz
 MichaelZLai Tue Sep 06 17:02:27 ~/wdi/exercises/Oz (master #)
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_East
Good_Witch_of_the_South     Wicked_Witch_of_the_West
 MichaelZLai Tue Sep 06 17:02:28 ~/wdi/exercises/Oz (master #)
$ rm Wicked_Witch_of_the_East
 MichaelZLai Tue Sep 06 17:02:39 ~/wdi/exercises/Oz (master #)
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
 MichaelZLai Tue Sep 06 17:02:39 ~/wdi/exercises/Oz (master #)
$ cd ..
 MichaelZLai Tue Sep 06 17:02:48 ~/wdi/exercises (master #)
$ ls
House   Oz
 MichaelZLai Tue Sep 06 17:02:49 ~/wdi/exercises (master #)
$ cd House
 MichaelZLai Tue Sep 06 17:02:55 ~/wdi/exercises/House (master #)
$ ls
Dorothy Toto
 MichaelZLai Tue Sep 06 17:02:57 ~/wdi/exercises/House (master #)
$ mv Dorthy ../Oz
mv: rename Dorthy to ../Oz/Dorthy: No such file or directory
 MichaelZLai Tue Sep 06 17:03:17 ~/wdi/exercises/House (master #)
$ ls
Dorothy Toto
 MichaelZLai Tue Sep 06 17:03:26 ~/wdi/exercises/House (master #)
$ mv Dorothy ../Oz
 MichaelZLai Tue Sep 06 17:03:43 ~/wdi/exercises/House (master #)
$ ls
Toto
 MichaelZLai Tue Sep 06 17:03:44 ~/wdi/exercises/House (master #)
$ cd ..
 MichaelZLai Tue Sep 06 17:03:48 ~/wdi/exercises (master #)
$ ls
House   Oz
 MichaelZLai Tue Sep 06 17:03:50 ~/wdi/exercises (master #)
$ cd Oz
 MichaelZLai Tue Sep 06 17:04:00 ~/wdi/exercises/Oz (master #)
$ ls
Dorothy             Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
 MichaelZLai Tue Sep 06 17:04:02 ~/wdi/exercises/Oz (master #)
$ cd ..
 MichaelZLai Tue Sep 06 17:04:21 ~/wdi/exercises (master #)
$ ls
House   Oz
 MichaelZLai Tue Sep 06 17:04:22 ~/wdi/exercises (master #)
$ pwd
/Users/MichaelZLai/wdi/exercises
 MichaelZLai Tue Sep 06 17:04:47 ~/wdi/exercises (master #)
$ ls
House   Oz
 MichaelZLai Tue Sep 06 17:04:57 ~/wdi/exercises (master #)
$ touch Scarecrow Tin_Man Cowardly_Lion
 MichaelZLai Tue Sep 06 17:05:52 ~/wdi/exercises (master #)
$ ls
Cowardly_Lion   House       Oz          Scarecrow       Tin_Man
 MichaelZLai Tue Sep 06 17:05:53 ~/wdi/exercises (master #)
$ mkdir Emerald_City
 MichaelZLai Tue Sep 06 17:06:01 ~/wdi/exercises (master #)
$ ls
Cowardly_Lion   House       Scarecrow
Emerald_City    Oz          Tin_Man
 MichaelZLai Tue Sep 06 17:06:02 ~/wdi/exercises (master #)
$ mv Cowardly_Lion Scarecrow Tin_Man Emerald_City
 MichaelZLai Tue Sep 06 17:06:27 ~/wdi/exercises (master #)
$ ls
Emerald_City    House       Oz
 MichaelZLai Tue Sep 06 17:06:27 ~/wdi/exercises (master #)
$ cd Emerald_City
 MichaelZLai Tue Sep 06 17:06:34 ~/wdi/exercises/Emerald_City (master #)
$ ls
Cowardly_Lion   Scarecrow       Tin_Man
 MichaelZLai Tue Sep 06 17:06:35 ~/wdi/exercises/Emerald_City (master #)
$ cd ..
 MichaelZLai Tue Sep 06 17:06:51 ~/wdi/exercises (master #)
$ ls
Emerald_City    House       Oz
 MichaelZLai Tue Sep 06 17:06:52 ~/wdi/exercises (master #)
$ cd Oz
 MichaelZLai Tue Sep 06 17:06:55 ~/wdi/exercises/Oz (master #)
$ ls
Dorothy             Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
 MichaelZLai Tue Sep 06 17:06:56 ~/wdi/exercises/Oz (master #)
$ touch Flying_Monkeys
 MichaelZLai Tue Sep 06 17:07:05 ~/wdi/exercises/Oz (master #)
$ ls
Dorothy             Good_Witch_of_the_South
Flying_Monkeys          Wicked_Witch_of_the_West
Good_Witch_of_the_North
 MichaelZLai Tue Sep 06 17:07:06 ~/wdi/exercises/Oz (master #)
$ rm Wicked_Witch_of_the_West
 MichaelZLai Tue Sep 06 17:09:36 ~/wdi/exercises/Oz (master #)
$ ls
Dorothy         Good_Witch_of_the_North
Flying_Monkeys      Good_Witch_of_the_South
 MichaelZLai Tue Sep 06 17:09:36 ~/wdi/exercises/Oz (master #)
$ cd ..
 MichaelZLai Tue Sep 06 17:10:04 ~/wdi/exercises (master #)
$ ls
Emerald_City    House       Oz
 MichaelZLai Tue Sep 06 17:10:05 ~/wdi/exercises (master #)
$ cd Emerald_City
 MichaelZLai Tue Sep 06 17:10:11 ~/wdi/exercises/Emerald_City (master #)
$ ls
Cowardly_Lion   Scarecrow       Tin_Man
 MichaelZLai Tue Sep 06 17:10:12 ~/wdi/exercises/Emerald_City (master #)
$ echo "diploma" >> Scarecrow
 MichaelZLai Tue Sep 06 17:14:39 ~/wdi/exercises/Emerald_City (master #)
$ ls
Cowardly_Lion   Scarecrow       Tin_Man
 MichaelZLai Tue Sep 06 17:14:40 ~/wdi/exercises/Emerald_City (master #)
$ echo "heart shaped watch" >> Tin_Man
 MichaelZLai Tue Sep 06 17:15:08 ~/wdi/exercises/Emerald_City (master #)
$ echo "medal" >> Cowardly_Lion
 MichaelZLai Tue Sep 06 17:15:27 ~/wdi/exercises/Emerald_City (master #)
$ open Cowardly_Lion
 MichaelZLai Tue Sep 06 17:18:01 ~/wdi/exercises/Emerald_City (master #)
$ open Tin_Man
 MichaelZLai Tue Sep 06 17:18:12 ~/wdi/exercises/Emerald_City (master #)
$ open Scarecrow
 MichaelZLai Tue Sep 06 17:18:24 ~/wdi/exercises/Emerald_City (master #)
$

**Comment by nolds9** [comment]
👍
