### ISSUE TITLE
CLI HW (Poh Chuan Kuan)

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/to_oz#112]
Last login: Tue Sep  6 16:37:42 on ttys000
 pohckuan  Tue Sep 06 16:57:03 ~
$ cd~
-bash: cd~: command not found
 pohckuan  Tue Sep 06 16:58:49 ~
$ cd ~
 pohckuan  Tue Sep 06 16:58:51 ~
$ cd wdi
 pohckuan  Tue Sep 06 16:59:08 ~/wdi
$ mkdir House
 pohckuan  Tue Sep 06 16:59:12 ~/wdi
$ cd House
 pohckuan  Tue Sep 06 16:59:20 ~/wdi/House
$ touch Dorothy.txt 
 pohckuan  Tue Sep 06 16:59:36 ~/wdi/House
$ touch Toto.txt
 pohckuan  Tue Sep 06 16:59:42 ~/wdi/House
$ cd wdi
-bash: cd: wdi: No such file or directory
 pohckuan  Tue Sep 06 16:59:56 ~/wdi/House
$ ../
-bash: ../: is a directory
 pohckuan  Tue Sep 06 17:00:05 ~/wdi/House
$ cd ~/wdi
 pohckuan  Tue Sep 06 17:00:12 ~/wdi
$ mkdir Oz 
 pohckuan  Tue Sep 06 17:00:21 ~/wdi
$ touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
 pohckuan  Tue Sep 06 17:02:39 ~/wdi
$ mv Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West Oz/
 pohckuan  Tue Sep 06 17:06:11 ~/wdi
$ cd Oz
 pohckuan  Tue Sep 06 17:08:40 ~/wdi/Oz
$ rm Wicked_Witch_of_the_East
 pohckuan  Tue Sep 06 17:08:57 ~/wdi/Oz
$ mv Dorothy.txt ../Oz
mv: rename Dorothy.txt to ../Oz/Dorothy.txt: No such file or directory
 pohckuan  Tue Sep 06 17:11:52 ~/wdi/Oz
$ mv Dorothy.txt Oz/
mv: rename Dorothy.txt to Oz/: No such file or directory
 pohckuan  Tue Sep 06 17:12:08 ~/wdi/Oz
$ mv Dorothy Oz/
mv: rename Dorothy to Oz/: No such file or directory
 pohckuan  Tue Sep 06 17:12:23 ~/wdi/Oz
$ cd wdi
-bash: cd: wdi: No such file or directory
 pohckuan  Tue Sep 06 17:13:18 ~/wdi/Oz
$ pwd
/Users/pohckuan/wdi/Oz
 pohckuan  Tue Sep 06 17:13:21 ~/wdi/Oz
$ cd ~wdi
-bash: cd: ~wdi: No such file or directory
 pohckuan  Tue Sep 06 17:13:30 ~/wdi/Oz
$ cd ~
 pohckuan  Tue Sep 06 17:13:33 ~
$ cd wdi/House
 pohckuan  Tue Sep 06 17:13:44 ~/wdi/House
$ mv Dorothy.txt Oz/
mv: rename Dorothy.txt to Oz/: No such file or directory
 pohckuan  Tue Sep 06 17:13:55 ~/wdi/House
$ cp Dorothy.txt Oz/
cp: directory Oz does not exist
 pohckuan  Tue Sep 06 17:18:26 ~/wdi/House
$ mv Dorothy.txt Oz/Dorothy.txt
mv: rename Dorothy.txt to Oz/Dorothy.txt: No such file or directory
 pohckuan  Tue Sep 06 17:19:54 ~/wdi/House
$ mv Dorothy.txt ../Oz
 pohckuan  Tue Sep 06 17:21:33 ~/wdi/House
$ cd ~/wdi
 pohckuan  Tue Sep 06 17:21:52 ~/wdi
$ touch Scarecrow Tin_Man Cowardly_Lion 
 pohckuan  Tue Sep 06 17:22:21 ~/wdi
$ mkdir Emerald City 
 pohckuan  Tue Sep 06 17:22:34 ~/wdi
$ mv Scarecrow Tin_Man Cowardly_Lion Emerald City/
 pohckuan  Tue Sep 06 17:23:40 ~/wdi
$ cd ~Emerald City
-bash: cd: ~Emerald: No such file or directory
 pohckuan  Tue Sep 06 17:26:02 ~/wdi
$ cd wdi
-bash: cd: wdi: No such file or directory
 pohckuan  Tue Sep 06 17:26:05 ~/wdi
$ cd ~/wdi
 pohckuan  Tue Sep 06 17:26:09 ~/wdi
$ ls
City        Oz      exercises   lessons     sandbox
House       Rakefile    installfest.yml projects
 pohckuan  Tue Sep 06 17:26:11 ~/wdi
$ touch Scarecrow Tin_Man Cowardly_Lion
 pohckuan  Tue Sep 06 17:26:43 ~/wdi
$ ls
City        Oz      Tin_Man     lessons
Cowardly_Lion   Rakefile    exercises   projects
House       Scarecrow   installfest.yml sandbox
 pohckuan  Tue Sep 06 17:26:45 ~/wdi
$ mkdir Emerald_City
 pohckuan  Tue Sep 06 17:26:55 ~/wdi
$ mv Scarecrow Tin_Man Cowardly_Lion Emerald_City/
 pohckuan  Tue Sep 06 17:27:26 ~/wdi
$ touch Flying_Monkeys
 pohckuan  Tue Sep 06 17:30:53 ~/wdi
$ mv Flying_Monkeys Oz/
 pohckuan  Tue Sep 06 17:31:00 ~/wdi
$ cd Oz
 pohckuan  Tue Sep 06 17:31:17 ~/wdi/Oz
$ rm Wicked_Witch_of_the_West
 pohckuan  Tue Sep 06 17:31:31 ~/wdi/Oz
$ echo "diploma" >> Scarecrow
 pohckuan  Tue Sep 06 17:34:15 ~/wdi/Oz
$ echo "heart_shaped_watch" >> Tin_Man
 pohckuan  Tue Sep 06 17:35:19 ~/wdi/Oz
$ echo "medal" >> Cowardly_Lion
 pohckuan  Tue Sep 06 17:35:30 ~/wdi/Oz
$ cd ~wdi/Emerald_City
-bash: cd: ~wdi/Emerald_City: No such file or directory
 pohckuan  Tue Sep 06 17:36:50 ~/wdi/Oz
$ cd ~/Emerald_City
-bash: cd: /Users/pohckuan/Emerald_City: No such file or directory
 pohckuan  Tue Sep 06 17:37:03 ~/wdi/Oz
$ cd ~/wdi/Emerald_City
 pohckuan  Tue Sep 06 17:37:22 ~/wdi/Emerald_City
$ echo "diploma" >> Scarecrow
 pohckuan  Tue Sep 06 17:37:34 ~/wdi/Emerald_City
$ echo "heart_shaped_watch" >> Tin_Man
 pohckuan  Tue Sep 06 17:37:41 ~/wdi/Emerald_City
$ echo "medal" >> Cowardly_Lion
 pohckuan  Tue Sep 06 17:37:50 ~/wdi/Emerald_City
$

**Comment by nolds9** [comment]
👍
