### ISSUE TITLE
CLI HW (Latoya Watson)

### ISSUE THREAD

**Issue by LWatsonlm** [ga-wdi-exercises/to_oz#113]
Latoyas-MacBook-Air:wdi latoyawatson$ cd exercises
Latoyas-MacBook-Air:exercises latoyawatson$ mkdir House
Latoyas-MacBook-Air:House latoyawatson$ touch Dorothy.txt
Latoyas-MacBook-Air:House latoyawatson$ touch Toto.txt
Latoyas-MacBook-Air:House latoyawatson$ mkdir Oz
Latoyas-MacBook-Air:House latoyawatson$ cd Oz
Latoyas-MacBook-Air:Oz latoyawatson$ touch Good_Witch_of_The_North.txt
Latoyas-MacBook-Air:Oz latoyawatson$ touch Wicked_Witch_of_The_East.txt
Latoyas-MacBook-Air:Oz latoyawatson$ touch Good_Witch_of_The_South.txt
Latoyas-MacBook-Air:Oz latoyawatson$ touch Wicked_Witch_of_The_West.txt
Latoyas-MacBook-Air:Oz latoyawatson$ ls -al
Latoyas-MacBook-Air:Oz latoyawatson$ rm Wicked_Witch_of_The_East.txt
Latoyas-MacBook-Air:Oz latoyawatson$ cd ..
Latoyas-MacBook-Air:House latoyawatson$ ls
Dorothy.txt     Oz          Toto.txt
Latoyas-MacBook-Air:House latoyawatson$ mv Dorothy.txt Oz/
Latoyas-MacBook-Air:House latoyawatson$ touch Scarecrow.txt
Latoyas-MacBook-Air:House latoyawatson$ touch Tin_Man.txt
Latoyas-MacBook-Air:House latoyawatson$ touch Cowardly_Lion.txt
Latoyas-MacBook-Air:House latoyawatson$ mkdir Emerald_City
Latoyas-MacBook-Air:House latoyawatson$ mv -iv -- Tin_Man.txt Scarecrow.txt Cowardly_Lion.txt ... Emerald_City/
Latoyas-MacBook-Air:House latoyawatson$ cd Emerald_City/
Latoyas-MacBook-Air:Emerald_City latoyawatson$ ls
Cowardly_Lion.txt       Scarecrow.txt       Tin_Man.txt
Latoyas-MacBook-Air:House latoyawatson$ ls
Emerald_City    Oz          Toto.txt
Latoyas-MacBook-Air:House latoyawatson$ cd Oz
Latoyas-MacBook-Air:Oz latoyawatson$ touch Flying_Monkeys.txt
Latoyas-MacBook-Air:Oz latoyawatson$ rm Wicked_Witch_of_The_West.txt
atoyas-MacBook-Air:Emerald_City latoyawatson$ echo "diploma" >> Scarecrow.txt
Latoyas-MacBook-Air:Emerald_City latoyawatson$ echo "A heart shaped watch" >> Tin_Man.txt
Latoyas-MacBook-Air:Emerald_City latoyawatson$ echo "medal" >> Cowardly_Lion.txt
Latoyas-MacBook-Air:Emerald_City latoyawatson$ open Scarecrow.txt
Latoyas-MacBook-Air:Emerald_City latoyawatson$ open Cowardly_Lion.txt
Latoyas-MacBook-Air:Emerald_City latoyawatson$ open Tin_Man.txt

**Comment by jshawl** [comment]
👍
