### ISSUE TITLE
CLI HW (Mike Rubin)

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/to_oz#115]
Comfort: 3  I had to re-do some things as my buffer in my terminal did not have then entire work I originally did.  I went back deleted the files and redid the exercise copying over each portion one at a time as I completed each section.

Completion: 5

[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  pwd
/Users/MICHAELS_MAC/wdi/homework/tooz
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  mkdir "House"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  touch "House/Dorthy"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  touch "House/Toto"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  Mkdir "Oz"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  tree
.
├── House
│   ├── Dorthy
│   └── Toto
├── Oz
├── readme.md
├── solution.txt
└── spec
    └── oz_spec.js

touch "Oz/Good Witch of the North"
touch "Oz/Wicked Witch of the East"
touch "Oz/Good Witch of the South"
touch "Oz/Wicked Witch of the West"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  touch "Oz/Good Witch of the North"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  touch "Oz/Wicked Witch of the East"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  touch "Oz/Good Witch of the South"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  touch "Oz/Wicked Witch of the West"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  tree
.
├── House
│   ├── Dorthy
│   └── Toto
├── Oz
│   ├── Good\ Witch\ of\ the\ North
│   ├── Good\ Witch\ of\ the\ South
│   ├── Wicked\ Witch\ of\ the\ East
│   └── Wicked\ Witch\ of\ the\ West
├── readme.md
├── solution.txt
└── spec
    └── oz_spec.js

3 directories, 9 files
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$

MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  rm "Oz/Wicked Witch of the East"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  tree
.
├── House
│   ├── Dorthy
│   └── Toto
├── Oz
│   ├── Good\ Witch\ of\ the\ North
│   ├── Good\ Witch\ of\ the\ South
│   └── Wicked\ Witch\ of\ the\ West
├── readme.md
├── solution.txt
└── spec
    └── oz_spec.js

3 directories, 8 files
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  mv house/Dorthy oz
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  tree
.
├── House
│   └── Toto
├── Oz
│   ├── Dorthy
│   ├── Good\ Witch\ of\ the\ North
│   ├── Good\ Witch\ of\ the\ South
│   └── Wicked\ Witch\ of\ the\ West
├── readme.md
├── solution.txt
└── spec
    └── oz_spec.js

3 directories, 8 files
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$
touch "Scarecrow"
touch "Tin Man"
touch "Cowardly Lion"

ICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  tree
.
├── House
│   └── Toto
├── Oz
│   ├── Cowardly\ Lion
│   ├── Dorthy
│   ├── Good\ Witch\ of\ the\ North
│   ├── Good\ Witch\ of\ the\ South
│   ├── Scarecrow
│   ├── Tin\ Man
│   └── Wicked\ Witch\ of\ the\ West
├── readme.md
├── solution.txt
└── spec
    └── oz_spec.js

3 directories, 11 files
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  cd oz
[MICHAELS_MAC@Michaels-MacBook-Pro-2 oz]$  mkdir "Emerald City"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 oz]$  mv "Cowardly Lion" "Emerald City"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 oz]$  mv "Scarecrow" "Emerald City"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 oz]$  mv "Tin Man" "Emerald City"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 oz]$  cd ..
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  tree
.
├── House
│   └── Toto
├── Oz
│   ├── Dorthy
│   ├── Emerald\ City
│   │   ├── Cowardly\ Lion
│   │   ├── Scarecrow
│   │   └── Tin\ Man
│   ├── Good\ Witch\ of\ the\ North
│   ├── Good\ Witch\ of\ the\ South
│   └── Wicked\ Witch\ of\ the\ West
├── readme.md
├── solution.txt
└── spec
    └── oz_spec.js

4 directories, 11 files
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  mkdir "Flying Monkeys"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  rm "Wicked Witch of the West"
rm: Wicked Witch of the West: No such file or directory
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  ls
Flying Monkeys  House       Oz          readme.md       solution.txt    spec
[MICHAELS_MAC@Michaels-MacBook-Pro-2 tooz]$  cd oz
[MICHAELS_MAC@Michaels-MacBook-Pro-2 oz]$  rm "Wicked Witch of the West"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 oz]$  tree
.
├── Dorthy
├── Emerald\ City
│   ├── Cowardly\ Lion
│   ├── Scarecrow
│   └── Tin\ Man
├── Good\ Witch\ of\ the\ North
└── Good\ Witch\ of\ the\ South

1 directory, 6 files
[MICHAELS_MAC@Michaels-MacBook-Pro-2 oz]$  cd "Emerald City"/
[MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  ls
Cowardly Lion   Scarecrow       Tin Man
[MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  echo "heart shaped watch" > "Scarcrow"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  rm "Scarcrow"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  echo "heart shaped watch" > "Scarecrow"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  cat Scarecrow
heart shaped watch
[MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  rm "Scarecrow"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  touch Scarecrow
[MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  echo "deploma" > Scarecrow
[MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  cat Scarecrow
deploma
[MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  echo "heart shaped watch" > "Tin Man"
[MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  cat "Tin Man

> "
> cat: Tin Man
> : No such file or directory
> [MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  cat "Tin Man"
> heart shaped watch
> [MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  echo "medal" > Lian
> [MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  cat Lion
> cat: Lion: No such file or directory
> [MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  cat Lion
> cat: Lion: No such file or directory
> [MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  ls
> Cowardly Lion   Lian        Scarecrow       Tin Man
> [MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  rm Lian
> [MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  echo "medal" > Lion
> [MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$  cat lion
> medal
> [MICHAELS_MAC@Michaels-MacBook-Pro-2 Emerald City]$

**Comment by jshawl** [comment]
👍
