### ISSUE TITLE
LI HW (Kevin Mahoney)

### ISSUE THREAD

**Issue by kjmahoney** [ga-wdi-exercises/to_oz#117]
mkDir House
cd House
touch Dorothy.txt Toto.txt
cd ../
mkDir Oz
cd Oz
touch "Wicked Witch of the West.txt" "Wicked Witch of the East.txt" "Good Witch of the North.txt" "Good Witch of the South.txt"

rm -r "Wicked Witch of the East.txt"
cd ../
mv House/Dorothy.txt Oz/

cd Oz
touch Scarecrow.txt "Tin Man.txt" "Cowardly Lion.txt"
mkdir "Emerald City"
mv "Cowardly Lion.txt" "Emerald City/"
mv "Scarecrow.txt" "Emerald City/"
mv "Tin Man.txt" "Emerald City/"
mv Dorothy.txt "Emerald City/"

touch "flying monkeys.txt"
rm -r "Wicked Witch of the West.txt"
cd "Emerald City"/
echo "diploma" > Scarecrow.txt
echo "heart shaped watch" > "Tin Man.txt"
echo "medal" > "Cowardly Lion.txt"

[Go to Oz Steps.txt](https://github.com/ga-wdi-exercises/to_oz/files/457914/Go.to.Oz.Steps.txt)

**Comment by nolds9** [comment]
👍
