### ISSUE TITLE
CLI HW (Mariana Lungu)

### ISSUE THREAD

**Issue by marlungu** [ga-wdi-exercises/to_oz#118]
ml wdi $ ls
Rakefile        exercises       installfest.yml lessons     projects        sandbox
ml wdi $ cd lessons/
ml lessons $ ls
ml lessons $ mkdir House
ml lessons $ ls
House
ml lessons $ cd House/
ml House $ ls
ml House $ touch  "Dorothy"
ml House $ ls
Dorothy
ml House $ cd Dorothy
-bash: cd: Dorothy: Not a directory
ml House $ touch "Toto"
ml House $ ls
Dorothy Toto
ml House $ cd ..
ml lessons $ mkdir Oz
ml lessons $ ls
House   Oz
ml lessons $ cd Oz/
ml Oz $ touch "Good Witch of the North"
ml Oz $ touch "Wicked Witch of the East"
ml Oz $ touch "Good Witch of the South"
ml Oz $ touch "Wicked Witch of the West"
ml Oz $ ls
Good Witch of the North     Good Witch of the South     Wicked Witch of the East        Wicked Witch of the West
ml Oz $ rm  "Wicked Witch of the East"
ml Oz $ ls
Good Witch of the North     Good Witch of the South     Wicked Witch of the West
ml Oz $ cd ..
ml lessons $ ls
House   Oz
ml lessons $ cd House/
ml House $ ls
Dorothy Toto
ml House $ mv Dorothy /Oz
mv: rename Dorothy to /Oz: Permission denied
ml House $ mv Dorothy ./Oz
ml House $ ls
Oz      Toto
ml House $ cd Oz
-bash: cd: Oz: Not a directory
ml House $ mv Oz./Dorothy
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
ml House $ mv Oz ./Dorothy
ml House $ ls
Dorothy Toto
ml House $ cd ..
ml lessons $ ls
House   Oz
ml lessons $ cd Oz
ml Oz $ ls
Good Witch of the North     Good Witch of the South     Wicked Witch of the West
ml Oz $ cd ..
ml lessons $ cd House/
ml House $ ls
Dorothy Toto
ml House $ mv Dorothy Oz
ml House $ ls
Oz      Toto
ml House $ cd Oz
-bash: cd: Oz: Not a directory
ml House $ mv Oz Dorothy
ml House $ ls
Dorothy Toto
ml House $ mv Dorothy ./Oz/
mv: rename Dorothy to ./Oz/: No such file or directory
ml House $ mv Dorothy Oz/
mv: rename Dorothy to Oz/: No such file or directory
ml House $ cd ..
ml lessons $ ls
House   Oz
ml lessons $ ls Oz
Good Witch of the North     Good Witch of the South     Wicked Witch of the West
ml lessons $ ls House/
Dorothy Toto
ml lessons $ mv House/Dorothy Oz/
ml lessons $ ls
House   Oz
ml lessons $ cd Oz/
ml Oz $ ls
Dorothy             Good Witch of the North     Good Witch of the South     Wicked Witch of the West
ml Oz $ touch "Scarecrow"
ml Oz $ touch "Tin Man"
ml Oz $ touch "Cowardly Lion"
ml Oz $ mkdir Emerald City
ml Oz $ ls
City                Emerald             Scarecrow
Cowardly Lion           Good Witch of the North     Tin Man
Dorothy             Good Witch of the South     Wicked Witch of the West
ml Oz $ cd C
City/          Cowardly Lion
ml Oz $ cd Emerald/
ml Emerald $ cd ..
ml Oz $ rm -R Emerald/
ml Oz $ rm -R C
City/          Cowardly Lion
ml Oz $ rm -R City/
ml Oz $ ls
Cowardly Lion           Good Witch of the North     Scarecrow               Wicked Witch of the West
Dorothy             Good Witch of the South     Tin Man
ml Oz $ mkdir "Emerald City"
ml Oz $ ls
Cowardly Lion           Emerald City            Good Witch of the South     Tin Man
Dorothy             Good Witch of the North     Scarecrow               Wicked Witch of the West
ml Oz $ cd Emerald\ City/
ml Emerald City $ mv  "Scarecrow"
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
ml Emerald City $ cd ..
ml Oz $ mv "Scarecrow" Emerald\ City/
ml Oz $ ls
Cowardly Lion           Emerald City            Good Witch of the South     Wicked Witch of the West
Dorothy             Good Witch of the North     Tin Man
ml Oz $ cd Emerald\ City/
ml Emerald City $ ls
Scarecrow
ml Emerald City $ cd ..
ml Oz $ mv "Tin Man" Emerald\ City/
ml Oz $ mv "Cowardly Lion" Emerald\ City/
ml Oz $ ls
Dorothy             Good Witch of the North     Wicked Witch of the West
Emerald City            Good Witch of the South
ml Oz $ cd Emerald\ City/
ml Emerald City $ ls
Cowardly Lion   Scarecrow       Tin Man
ml Emerald City $ cd ..
ml Oz $ touch  "Flying Monkeys"
ml Oz $ ls
Dorothy             Flying Monkeys          Good Witch of the South
Emerald City            Good Witch of the North     Wicked Witch of the West
ml Oz $ rm  "Wicked Witch of the West"
ml Oz $ ls
Dorothy         Emerald City        Flying Monkeys      Good Witch of the North Good Witch of the South
ml Oz $ cd Emerald\ City/
ml Emerald City $ ls
Cowardly Lion   Scarecrow       Tin Man
ml Emerald City $ echo "diploma" >> Scarecrow
ml Emerald City $ ls
Cowardly Lion   Scarecrow       Tin Man
ml Emerald City $ cd Scarecrow
-bash: cd: Scarecrow: Not a directory
ml Emerald City $ open Scarecrow
ml Emerald City $ echo " heart shaped watch" >> Tin\ Man
ml Emerald City $ ls
Cowardly Lion   Scarecrow       Tin Man
ml Emerald City $ cd Tin\ Man
-bash: cd: Tin Man: Not a directory
ml Emerald City $ open Tin\ Man
ml Emerald City $ echo "metal" >> Cowardly Lion
ml Emerald City $ ls
Cowardly        Cowardly Lion   Scarecrow       Tin Man
ml Emerald City $ open Cowardly
ml Emerald City $ open Cowardly Lion
The file /Users/ml/wdi/lessons/Oz/Emerald City/Lion does not exist.
ml Emerald City $ rm Cowardly Lion
rm: Lion: No such file or directory
ml Emerald City $ rm Cowardly\ Lion
ml Emerald City $ ls
Scarecrow       Tin Man
ml Emerald City $ touch "Cowardly Lion"
ml Emerald City $ ls
Cowardly Lion   Scarecrow       Tin Man
ml Emerald City $ echo "metal" >> Lion
ml Emerald City $ ls
Cowardly Lion   Lion        Scarecrow       Tin Man
ml Emerald City $ open Lion
ml Emerald City $ tree
.
├── Cowardly\ Lion
├── Lion
├── Scarecrow
└── Tin\ Man

0 directories, 4 files
ml Emerald City $ cd ..
ml Oz $ tree
.
├── Dorothy
├── Emerald\ City
│   ├── Cowardly\ Lion
│   ├── Lion
│   ├── Scarecrow
│   └── Tin\ Man
├── Flying\ Monkeys
├── Good\ Witch\ of\ the\ North
└── Good\ Witch\ of\ the\ South

1 directory, 8 files
ml Oz $ cd ..
ml lessons $ tree
.
├── House
│   └── Toto
└── Oz
    ├── Dorothy
    ├── Emerald\ City
    │   ├── Cowardly\ Lion
    │   ├── Lion
    │   ├── Scarecrow
    │   └── Tin\ Man
    ├── Flying\ Monkeys
    ├── Good\ Witch\ of\ the\ North
    └── Good\ Witch\ of\ the\ South

3 directories, 9 files
ml lessons $

**Comment by nolds9** [comment]
👍
