### ISSUE TITLE
CLI HW (Angelo Brown)

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/to_oz#119]
Comfort Score = 5/5
Completeness Score = 5/5

Last login: Tue Sep  6 18:38:56 on ttys000
  Tue Sep 06 19:10:20 ~
$ pwd
/Users/angelobrown
  Tue Sep 06 19:10:38 ~
$ mkdir House
  Tue Sep 06 19:10:45 ~
$ cd House
  Tue Sep 06 19:10:52 ~/House
$ touch Dorothy
  Tue Sep 06 19:11:19 ~/House
$ touch Toto
  Tue Sep 06 19:11:23 ~/House
$ ls
Dorothy Toto
  Tue Sep 06 19:11:25 ~/House
$ cd ..
  Tue Sep 06 19:11:40 ~
$ mkdir Oz
  Tue Sep 06 19:11:52 ~
$ cd Oz
  Tue Sep 06 19:11:55 ~/Oz
$ touch Good_Witch_of_the_North
  Tue Sep 06 19:12:17 ~/Oz
$ touch Wicked_Witch_of_the_East
  Tue Sep 06 19:12:30 ~/Oz
$ touch Good_Witch_of_the_South
  Tue Sep 06 19:12:42 ~/Oz
$ touch Wicked_Witch_of_the_West
  Tue Sep 06 19:12:56 ~/Oz
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_East
Good_Witch_of_the_South     Wicked_Witch_of_the_West
  Tue Sep 06 19:12:58 ~/Oz
$ rm Wicked_Witch_of_the_East
  Tue Sep 06 19:13:26 ~/Oz
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
  Tue Sep 06 19:13:27 ~/Oz
$ cd ..
  Tue Sep 06 19:13:38 ~
$ cd House
  Tue Sep 06 19:13:42 ~/House
$ ls
Dorothy Toto
  Tue Sep 06 19:13:45 ~/House
$ mv Dorothy ~/Oz/
  Tue Sep 06 19:13:58 ~/House
$ cd ..
  Tue Sep 06 19:14:03 ~
$ cd Oz
  Tue Sep 06 19:14:08 ~/Oz
$ ls
Dorothy             Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
  Tue Sep 06 19:14:08 ~/Oz
$ touch Scarecrow
  Tue Sep 06 19:14:32 ~/Oz
$ touch Tin_Man
  Tue Sep 06 19:14:50 ~/Oz
$ touch Cowardly_Lion
  Tue Sep 06 19:14:58 ~/Oz
$ mkdir Emerald_City
  Tue Sep 06 19:15:26 ~/Oz
$ ls
Cowardly_Lion           Good_Witch_of_the_South
Dorothy             Scarecrow
Emerald_City            Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_the_West
  Tue Sep 06 19:15:31 ~/Oz
$ mv Dorothy Scarecrow Cowardly_Lion Tin_Man Emerald_City/
  Tue Sep 06 19:17:57 ~/Oz
$ ls
Emerald_City            Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
  Tue Sep 06 19:17:59 ~/Oz
$ cd Emerald_City
  Tue Sep 06 19:18:09 ~/Oz/Emerald_City
$ ls
Cowardly_Lion   Dorothy     Scarecrow       Tin_Man
  Tue Sep 06 19:18:09 ~/Oz/Emerald_City
$ cd ..
  Tue Sep 06 19:18:26 ~/Oz
$ ls
Emerald_City            Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
  Tue Sep 06 19:18:32 ~/Oz
$ touch Flying_Monkeys
  Tue Sep 06 19:18:41 ~/Oz
$ ls
Emerald_City            Good_Witch_of_the_South
Flying_Monkeys          Wicked_Witch_of_the_West
Good_Witch_of_the_North
  Tue Sep 06 19:18:42 ~/Oz
$ rm Wicked_Witch_of_the_West
  Tue Sep 06 19:19:03 ~/Oz
$ ls
Emerald_City        Good_Witch_of_the_North
Flying_Monkeys      Good_Witch_of_the_South
  Tue Sep 06 19:19:04 ~/Oz
$ cd Emerald_City
  Tue Sep 06 19:32:10 ~/Oz/Emerald_City
$ ls
Cowardly_Lion   Dorothy     Scarecrow       Tin_Man
  Tue Sep 06 19:32:11 ~/Oz/Emerald_City
$ ECHO diploma > Scarecrow
  Tue Sep 06 19:32:54 ~/Oz/Emerald_City
$ ECHO heart shaped watch > Tin_Man
  Tue Sep 06 19:33:24 ~/Oz/Emerald_City
$ ECHO medal > Cowardly_Lion
  Tue Sep 06 19:33:44 ~/Oz/Emerald_City
$ ls
Cowardly_Lion   Dorothy     Scarecrow       Tin_Man
  Tue Sep 06 19:34:29 ~/Oz/Emerald_City
$ open Cowardly_Lion
  Tue Sep 06 19:34:36 ~/Oz/Emerald_City
$ open Scarecrow
  Tue Sep 06 19:34:51 ~/Oz/Emerald_City
$ open Tin_Man
  Tue Sep 06 19:35:01 ~/Oz/Emerald_City
$

**Comment by amaseda** [comment]
:+1:

Please use backticks when referencing code in a Github issue. Makes it a lot more readable!
