### ISSUE TITLE
Patrick's Day 1 HW

### ISSUE THREAD

**Issue by pkmoran** [ga-wdi-exercises/to_oz#12]
$ mkdir To_Oz
~/wdi/exercises 
$ cd To_Oz/
~/wdi/exercises/To_Oz 
$ ls
~/wdi/exercises/To_Oz 
$ mkdir House
~/wdi/exercises/To_Oz 
$ cd House/
~/wdi/exercises/To_Oz/House 
$ cd ..
~/wdi/exercises/To_Oz 
$ cd House
~/wdi/exercises/To_Oz/House 
$ touch Dorothy Toto
~/wdi/exercises/To_Oz/House 
$ ls
Dorothy Toto
~/wdi/exercises/To_Oz/House 
$ cd ..
~/wdi/exercises/To_Oz 
$ mkdir Oz
~/wdi/exercises/To_Oz 
$ cd Oz
~/wdi/exercises/To_Oz/Oz 
$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
~/wdi/exercises/To_Oz/Oz 
$ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South     Wicked Witch of the West
~/wdi/exercises/To_Oz/Oz 
$ rm "Wicked Witch of the East"
~/wdi/exercises/To_Oz/Oz 
$ ls
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
~/wdi/exercises/To_Oz/Oz 
$ mv -v ~/wdi/exercises/To_Oz/House/Dorothy ~/wdi/exercises/To_Oz/Oz/
/Users/patrickmoran/wdi/exercises/To_Oz/House/Dorothy -> /Users/patrickmoran/wdi/exercises/To_Oz/Oz/Dorothy
~/wdi/exercises/To_Oz/Oz 
$ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the West
~/wdi/exercises/To_Oz/Oz 
$ cd..
-bash: cd..: command not found
~/wdi/exercises/To_Oz/Oz 
$ cd ..
~/wdi/exercises/To_Oz 
$ cd House
~/wdi/exercises/To_Oz/House 
$ ls
Toto
~/wdi/exercises/To_Oz/House 
$ cd ../Oz
~/wdi/exercises/To_Oz/Oz 
$ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the West
~/wdi/exercises/To_Oz/Oz 
$ touch "Scarecrow" "Tin Man" "Cowardly Lion"
~/wdi/exercises/To_Oz/Oz 
$ mkdir "Emerald City"
~/wdi/exercises/To_Oz/Oz 
$ mv "Dorothy" "Scarecrow" "Tin Man" "Cowardly Lion" /"Emerald City"/
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/exercises/To_Oz/Oz 
$ mv "Dorothy" "Scarecrow" "Tin Man" "Cowardly Lion" "Emerald City"/
~/wdi/exercises/To_Oz/Oz 
$ ls
Emerald City            Good Witch of the South
Good Witch of the North     Wicked Witch of the West
~/wdi/exercises/To_Oz/Oz 
$ cd Emerald\ City/
~/wdi/exercises/To_Oz/Oz/Emerald City 
$ ls
Cowardly Lion   Dorothy     Scarecrow   Tin Man
~/wdi/exercises/To_Oz/Oz/Emerald City 
$ cd ..
~/wdi/exercises/To_Oz/Oz 
$ touch "Flying Monkeys"
~/wdi/exercises/To_Oz/Oz 
$ rm "Wicked Witch of the West"
~/wdi/exercises/To_Oz/Oz 
$ ls
Emerald City        Good Witch of the North
Flying Monkeys      Good Witch of the South
~/wdi/exercises/To_Oz/Oz 
$ echo "a diploma" >> Oz/"Emerald City"/Scarecrow
-bash: Oz/Emerald City/Scarecrow: No such file or directory
~/wdi/exercises/To_Oz/Oz 
$ echo "a diploma" >> "Emerald City"/Scarecrow
~/wdi/exercises/To_Oz/Oz 
$ ehco "a heart shaped watch" >> "Emerald City"/"Tin Man"
-bash: ehco: command not found
~/wdi/exercises/To_Oz/Oz 
$ echo "a heart shaped watch" >> "Emerald City"/"Tin Man"
~/wdi/exercises/To_Oz/Oz 
$ echo "a medal" >> "Emerald City"/Lion
~/wdi/exercises/To_Oz/Oz 
$

**Comment by RobertAKARobin** [comment]
Nice!
