### ISSUE TITLE
CLI HW (Ian Hollands)

### ISSUE THREAD

**Issue by ihollands** [ga-wdi-exercises/to_oz#120]
Last login: Tue Sep  6 20:13:14 on ttys000
Ians-MacBook-Pro:~ ianhollands$ mkdir House
Ians-MacBook-Pro:~ ianhollands$ ls
Applications        General_Assembly        Public
Creative Cloud Files    House           Rakefile
Desktop         Library         World
Documents           Movies          fundamentals
Downloads           Music           installfest.yml
Dropbox         Pictures            wdi
Ians-MacBook-Pro:~ ianhollands$ rm -r House
Ians-MacBook-Pro:~ ianhollands$ ls
Applications        General_Assembly        Rakefile
Creative Cloud Files    Library         World
Desktop         Movies          fundamentals
Documents           Music           installfest.yml
Downloads           Pictures            wdi
Dropbox         Public
Ians-MacBook-Pro:~ ianhollands$
Ians-MacBook-Pro:~ ianhollands$ ls
Applications        General_Assembly        Rakefile
Creative Cloud Files    Library         World
Desktop         Movies          fundamentals
Documents           Music           installfest.yml
Downloads           Pictures            wdi
Dropbox         Public
Ians-MacBook-Pro:~ ianhollands$ rm -r installfest.yml
Ians-MacBook-Pro:~ ianhollands$ ls
Applications        General_Assembly        Rakefile
Creative Cloud Files    Library         World
Desktop         Movies          fundamentals
Documents           Music           wdi
Downloads           Pictures
Dropbox         Public
Ians-MacBook-Pro:~ ianhollands$ cd Rakefile
-bash: cd: Rakefile: Not a directory
Ians-MacBook-Pro:~ ianhollands$ rm -r Rakefile
Ians-MacBook-Pro:~ ianhollands$
Ians-MacBook-Pro:~ ianhollands$ ls
Applications        Dropbox         Pictures
Creative Cloud Files    General_Assembly        Public
Desktop         Library         World
Documents           Movies          fundamentals
Downloads           Music           wdi
Ians-MacBook-Pro:~ ianhollands$ mv fundamentals/ Fundamentals
Ians-MacBook-Pro:~ ianhollands$ ls
Applications        Dropbox         Music
Creative Cloud Files    Fundamentals        Pictures
Desktop         General_Assembly        Public
Documents           Library         World
Downloads           Movies          wdi
Ians-MacBook-Pro:~ ianhollands$ cd Fundamentals
Ians-MacBook-Pro:Fundamentals ianhollands$ ls
wdi-fundamentals-memorygame
Ians-MacBook-Pro:Fundamentals ianhollands$
Ians-MacBook-Pro:Fundamentals ianhollands$ cd ..
Ians-MacBook-Pro:~ ianhollands$ ls
Applications        Dropbox         Music
Creative Cloud Files    Fundamentals        Pictures
Desktop         General_Assembly        Public
Documents           Library         World
Downloads           Movies          wdi
Ians-MacBook-Pro:~ ianhollands$
Ians-MacBook-Pro:~ ianhollands$ ls
Applications        Dropbox         Music
Creative Cloud Files    Fundamentals        Pictures
Desktop         General_Assembly        Public
Documents           Library         World
Downloads           Movies          wdi
Ians-MacBook-Pro:~ ianhollands$ cd wdi
Ians-MacBook-Pro:wdi ianhollands$ ls
exercises       lessons     projects        sandbox     to_oz
Ians-MacBook-Pro:wdi ianhollands$ cd sandbox
Ians-MacBook-Pro:sandbox ianhollands$ ls
Ians-MacBook-Pro:sandbox ianhollands$ mkdir House
Ians-MacBook-Pro:sandbox ianhollands$ ls
House
Ians-MacBook-Pro:sandbox ianhollands$ touch Dorothy.txt
Ians-MacBook-Pro:sandbox ianhollands$ touch Toto.txt
Ians-MacBook-Pro:sandbox ianhollands$ ls
Dorothy.txt     House       Toto.txt
Ians-MacBook-Pro:sandbox ianhollands$ touch good_witch_of_the_n
Ians-MacBook-Pro:sandbox ianhollands$ touch Good Witch of the North
Ians-MacBook-Pro:sandbox ianhollands$ ls
Dorothy.txt     House       Toto.txt        of
Good        North       Witch       the
Ians-MacBook-Pro:sandbox ianhollands$ cd ..
Ians-MacBook-Pro:wdi ianhollands$ ls
exercises       lessons     projects        sandbox     to_oz
Ians-MacBook-Pro:wdi ianhollands$ cd sandbox
Ians-MacBook-Pro:sandbox ianhollands$ ls
Dorothy.txt     House       Toto.txt        of
Good        North       Witch       the
Ians-MacBook-Pro:sandbox ianhollands$ rm -r Dorothy.txt House Good North Witch Toto.txt of the
Ians-MacBook-Pro:sandbox ianhollands$ ls
Ians-MacBook-Pro:sandbox ianhollands$
Ians-MacBook-Pro:sandbox ianhollands$ mk dir House
-bash: mk: command not found
Ians-MacBook-Pro:sandbox ianhollands$
Ians-MacBook-Pro:sandbox ianhollands$ mkdir House
Ians-MacBook-Pro:sandbox ianhollands$ ls
House
Ians-MacBook-Pro:sandbox ianhollands$ cd House
Ians-MacBook-Pro:House ianhollands$ touch Dorothy
Ians-MacBook-Pro:House ianhollands$ touch Toto
Ians-MacBook-Pro:House ianhollands$ ls
Dorothy Toto
Ians-MacBook-Pro:House ianhollands$ cd ..
Ians-MacBook-Pro:sandbox ianhollands$ ls
House
Ians-MacBook-Pro:sandbox ianhollands$ cd ..
Ians-MacBook-Pro:wdi ianhollands$ ls
exercises       lessons     projects        sandbox     to_oz
Ians-MacBook-Pro:wdi ianhollands$ cd sandbox
Ians-MacBook-Pro:sandbox ianhollands$ ls
House
Ians-MacBook-Pro:sandbox ianhollands$ rm -r House
Ians-MacBook-Pro:sandbox ianhollands$ ls
Ians-MacBook-Pro:sandbox ianhollands$
Ians-MacBook-Pro:sandbox ianhollands$ mkdir House
Ians-MacBook-Pro:sandbox ianhollands$ cd House
Ians-MacBook-Pro:House ianhollands$ touch Dorothy.txt
Ians-MacBook-Pro:House ianhollands$ touch Toto.txt
Ians-MacBook-Pro:House ianhollands$ mkdir Oz
Ians-MacBook-Pro:House ianhollands$ ls
Dorothy.txt     Oz          Toto.txt
Ians-MacBook-Pro:House ianhollands$ mv Oz ..
Ians-MacBook-Pro:House ianhollands$ ls
Dorothy.txt     Toto.txt
Ians-MacBook-Pro:House ianhollands$ cd ..
Ians-MacBook-Pro:sandbox ianhollands$ ls
House   Oz
Ians-MacBook-Pro:sandbox ianhollands$ touch Good_Witch_of_the_North.txt
Ians-MacBook-Pro:sandbox ianhollands$ touch Good_Witch_of_the_South.txt
Ians-MacBook-Pro:sandbox ianhollands$ touch Wicked_Witch_of_the_East.txt
Ians-MacBook-Pro:sandbox ianhollands$ touch Wicked_Witch_of_the_West.txt
Ians-MacBook-Pro:sandbox ianhollands$ ls
Good_Witch_of_the_North.txt     Oz
Good_Witch_of_the_South.txt     Wicked_Witch_of_the_East.txt
House               Wicked_Witch_of_the_West.txt
Ians-MacBook-Pro:sandbox ianhollands$  Wicked_Witch_of_the_West.txt
Ians-MacBook-Pro:sandbox ianhollands$ mv Good_Witch_of_the_North.txt Oz/
Ians-MacBook-Pro:sandbox ianhollands$ ls
Good_Witch_of_the_South.txt     Wicked_Witch_of_the_East.txt
House               Wicked_Witch_of_the_West.txt
Oz
Ians-MacBook-Pro:sandbox ianhollands$ mv Good_Witch_of_the_South.txt Oz/
Ians-MacBook-Pro:sandbox ianhollands$ mv Wicked_Witch_of_the_East.txt Oz/
Ians-MacBook-Pro:sandbox ianhollands$ mv Wicked_Witch_of_the_West.txt Oz/
Ians-MacBook-Pro:sandbox ianhollands$ ls
House   Oz
Ians-MacBook-Pro:sandbox ianhollands$ cd Oz
Ians-MacBook-Pro:Oz ianhollands$ ls
Good_Witch_of_the_North.txt     Wicked_Witch_of_the_East.txt
Good_Witch_of_the_South.txt     Wicked_Witch_of_the_West.txt
Ians-MacBook-Pro:Oz ianhollands$ rm Wicked_Witch_of_the_East.txt
Ians-MacBook-Pro:Oz ianhollands$ ls
Good_Witch_of_the_North.txt     Wicked_Witch_of_the_West.txt
Good_Witch_of_the_South.txt
Ians-MacBook-Pro:Oz ianhollands$ cd ..
Ians-MacBook-Pro:sandbox ianhollands$ ls
House   Oz
Ians-MacBook-Pro:sandbox ianhollands$ cd House
Ians-MacBook-Pro:House ianhollands$ ls
Dorothy.txt     Toto.txt
Ians-MacBook-Pro:House ianhollands$ mv Dorothy.txt ../Oz/
Ians-MacBook-Pro:House ianhollands$ cd ..
Ians-MacBook-Pro:sandbox ianhollands$ ls
House   Oz
Ians-MacBook-Pro:sandbox ianhollands$ cd Oz
Ians-MacBook-Pro:Oz ianhollands$ ls
Dorothy.txt             Good_Witch_of_the_South.txt
Good_Witch_of_the_North.txt     Wicked_Witch_of_the_West.txt
Ians-MacBook-Pro:Oz ianhollands$ touch Scarecrow.txt
Ians-MacBook-Pro:Oz ianhollands$ touch Tin_Man.txt
Ians-MacBook-Pro:Oz ianhollands$ touch Cowardly_Lion.txt
Ians-MacBook-Pro:Oz ianhollands$ mkdir Emerald City
Ians-MacBook-Pro:Oz ianhollands$ ls
City                Good_Witch_of_the_South.txt
Cowardly_Lion.txt           Scarecrow.txt
Dorothy.txt             Tin_Man.txt
Emerald             Wicked_Witch_of_the_West.txt
Good_Witch_of_the_North.txt
Ians-MacBook-Pro:Oz ianhollands$ mv Cowardly_Lion.txt Scarecrow.txt Tin_Man.txt Dorothy.txt Emerald/
Ians-MacBook-Pro:Oz ianhollands$ rm -r City
Ians-MacBook-Pro:Oz ianhollands$ ls
Emerald             Good_Witch_of_the_South.txt
Good_Witch_of_the_North.txt     Wicked_Witch_of_the_West.txt
Ians-MacBook-Pro:Oz ianhollands$ mv Emerald Emerald_City/
Ians-MacBook-Pro:Oz ianhollands$ ls
Emerald_City            Good_Witch_of_the_South.txt
Good_Witch_of_the_North.txt     Wicked_Witch_of_the_West.txt
Ians-MacBook-Pro:Oz ianhollands$ pwd
/Users/ianhollands/wdi/sandbox/Oz
Ians-MacBook-Pro:Oz ianhollands$ touch Flying_Monkeys.txt
Ians-MacBook-Pro:Oz ianhollands$ rm Wicked_Witch_of_the_West.txt
Ians-MacBook-Pro:Oz ianhollands$ ls
Emerald_City            Good_Witch_of_the_North.txt
Flying_Monkeys.txt          Good_Witch_of_the_South.txt
Ians-MacBook-Pro:Oz ianhollands$ cd Emerald_City
Ians-MacBook-Pro:Emerald_City ianhollands$ ls
Cowardly_Lion.txt       Scarecrow.txt
Dorothy.txt         Tin_Man.txt
Ians-MacBook-Pro:Emerald_City ianhollands$ echo -e "diploma" > Scarecrow.txt
Ians-MacBook-Pro:Emerald_City ianhollands$ echo -e "heart-shaped watch" > Tin_Man.txt
Ians-MacBook-Pro:Emerald_City ianhollands$ echo -e "medal" > Cowardly_Lion.txt
Ians-MacBook-Pro:Emerald_City ianhollands$

**Comment by amaseda** [comment]
:+1:

Don't forget to use backtickets when referencing code in an issue. Makes it a lot more readable!
