### ISSUE TITLE
CLI HW (Liza Floyd)

### ISSUE THREAD

**Issue by lizafloyd** [ga-wdi-exercises/to_oz#121]
Last login: Tue Sep  6 21:34:26 on ttys000
  Tue Sep 06 21:35:21 ~
$ ls
Applications        Incompatible Software   Sites
Desktop         Library         World
Documents           Movies          testing
Downloads           Music           wdi
Dropbox         Pictures
FontAgent Pro Fonts     Public
  Tue Sep 06 21:35:25 ~
$ cd wdi
  Tue Sep 06 21:35:29 ~/wdi
$ ls
Rakefile        installfest.yml projects
exercises       lessons     sandbox
  Tue Sep 06 21:35:33 ~/wdi
$ cd exercises
  Tue Sep 06 21:35:41 ~/wdi/exercises
$ mkdir House
  Tue Sep 06 21:35:51 ~/wdi/exercises
$ touch Dorothy.txt
  Tue Sep 06 21:36:35 ~/wdi/exercises
$ touch Toto.txt
  Tue Sep 06 21:36:41 ~/wdi/exercises
$ mkdir Oz
  Tue Sep 06 21:37:26 ~/wdi/exercises
$ cd Oz
  Tue Sep 06 21:37:28 ~/wdi/exercises/Oz
$ pwd
/Users/lizafloyd/wdi/exercises/Oz
  Tue Sep 06 21:37:31 ~/wdi/exercises/Oz
$ touch Good_Witch_of_the_North.txt
  Tue Sep 06 21:37:53 ~/wdi/exercises/Oz
$ touch Wicked_Witch_of_the_East.txt
  Tue Sep 06 21:38:15 ~/wdi/exercises/Oz
$ touch Good_Witch_of_the_South.txt
  Tue Sep 06 21:38:37 ~/wdi/exercises/Oz
$ touch Wicked_Witch_of_the_West.txt
  Tue Sep 06 21:38:55 ~/wdi/exercises/Oz
$ ls
Good_Witch_of_the_North.txt     Wicked_Witch_of_the_East.txt
Good_Witch_of_the_South.txt     Wicked_Witch_of_the_West.txt
  Tue Sep 06 21:38:59 ~/wdi/exercises/Oz
$ rm Wicked-Witch_of_the_East.txt
rm: Wicked-Witch_of_the_East.txt: No such file or directory
  Tue Sep 06 21:39:37 ~/wdi/exercises/Oz
$ rm Wicked_Witch_of_the_East.txt
  Tue Sep 06 21:40:38 ~/wdi/exercises/Oz
$ cd ..
  Tue Sep 06 21:41:48 ~/wdi/exercises
$ ls
Dorothy.txt     House       Oz          Toto.txt
  Tue Sep 06 21:41:56 ~/wdi/exercises
$ mv Dorothy.txt Oz/
  Tue Sep 06 21:42:52 ~/wdi/exercises
$ ls
House       Oz          Toto.txt
  Tue Sep 06 21:43:08 ~/wdi/exercises
$ mk Scarecrow.txt
-bash: mk: command not found
  Tue Sep 06 21:43:29 ~/wdi/exercises
$ touch Scarecrow.txt
  Tue Sep 06 21:43:52 ~/wdi/exercises
$ touch Tin_Man.txt
  Tue Sep 06 21:44:15 ~/wdi/exercises
$ touch Cowardly_Lion.txt
  Tue Sep 06 21:44:40 ~/wdi/exercises
$ mkdir Emerald_City
  Tue Sep 06 21:44:57 ~/wdi/exercises
$ ls
Cowardly_Lion.txt       Oz              Toto.txt
Emerald_City        Scarecrow.txt
House           Tin_Man.txt
  Tue Sep 06 21:45:03 ~/wdi/exercises
$ mv Cowardly_Lion.txt Emerald_City/
  Tue Sep 06 21:45:25 ~/wdi/exercises
$ mv Tin_Man.txt Emerald_City/
  Tue Sep 06 21:45:48 ~/wdi/exercises
$ mv Scarecrow.txt Emerald_City/
  Tue Sep 06 21:46:08 ~/wdi/exercises
$ ls
Emerald_City    House       Oz          Toto.txt
  Tue Sep 06 21:46:11 ~/wdi/exercises
$ cd Oz
  Tue Sep 06 21:46:21 ~/wdi/exercises/Oz
$ touch Flying_Monkeys.txt
  Tue Sep 06 21:46:37 ~/wdi/exercises/Oz
$ cd ..
  Tue Sep 06 21:48:24 ~/wdi/exercises
$ cd Emerald_City
  Tue Sep 06 21:48:33 ~/wdi/exercises/Emerald_City
$ ls
Cowardly_Lion.txt       Scarecrow.txt       Tin_Man.txt
  Tue Sep 06 21:48:36 ~/wdi/exercises/Emerald_City
$ echo "diploma" >> Scarecrow.txt
  Tue Sep 06 21:49:05 ~/wdi/exercises/Emerald_City
$ Scarecrow.txt
-bash: Scarecrow.txt: command not found
  Tue Sep 06 21:49:44 ~/wdi/exercises/Emerald_City
$ open Scarecrow.txt
  Tue Sep 06 21:50:39 ~/wdi/exercises/Emerald_City
$ echo "Heart" >> Tin_Man.txt
  Tue Sep 06 21:51:13 ~/wdi/exercises/Emerald_City
$ echo "medal" >> Cowardly_Lion.txt
  Tue Sep 06 21:51:30 ~/wdi/exercises/Emerald_City
$

**Comment by lizafloyd** [comment]
Comfort_level: 5;
Completeness: 5;

**Comment by amaseda** [comment]
:+1:

Don't forget to use backticks when referencing code in an issue. Makes it a lot more readable!
