### ISSUE TITLE
CLI HW Domonique Griffin

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/to_oz#122]
mkdir House
touch Dorothy.txt touch Toto.txt
mkdir Oz
touch Good_Witch_Of_The_North
touch Wicked_Witch_Of_The_East
touch Good_Witch_Of_the_South
touch Wicked_Witch_Of_The_West
rm -r Wicked_Witch_Of_The_East
mv Dorothy.txt /Oz

touch Scarecrow.txt
touch Tin_Man.txt
touch Cowardly_Lion.txt
mkdir Emerald City

mv Scarecrow.txt /Emerald City
mv Tin_Man.txt /Emerald City
mv Cowardly_Lion.txt /Emerald City

cd ../
cd Oz
touch Flying_Monkey.txt
rm -r Wicked_Witch_Of_The_West

cd ../
cd Emerald City
echo “Diploma” >> Scarecrow.txt
echo “A heart shaped watch” >> Tin_Man.txt
echo “A medal” >> Cowardly_Lion.txt

**Comment by amaseda** [comment]
:+1:
