### ISSUE TITLE
CLI HW (Nick Oki)

### ISSUE THREAD

**Issue by nickoki** [ga-wdi-exercises/to_oz#123]
nro: ~/wdi/exercises $ mkdir House
nro: ~/wdi/exercises $ mkdir Oz
nro: ~/wdi/exercises $ cd Oz
nro: ~/wdi/exercises/Oz $ touch "Good Witch of the North"
nro: ~/wdi/exercises/Oz $ touch "Wicked Witch of the East"
nro: ~/wdi/exercises/Oz $ touch "Good Witch of the South"
nro: ~/wdi/exercises/Oz $ touch "Wicked Witch of the West"
nro: ~/wdi/exercises/Oz $ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South     Wicked Witch of the West
nro: ~/wdi/exercises/Oz $ rm "Wicked Witch of the East"
nro: ~/wdi/exercises/Oz $ ls
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
nro: ~/wdi/exercises/Oz $ cd ..
nro: ~/wdi/exercises $ cd house
nro: ~/wdi/exercises/house $ ls
Dorothy Toto
nro: ~/wdi/exercises/house $ mv Dorothy ../Oz
nro: ~/wdi/exercises/house $ ls
Toto
nro: ~/wdi/exercises/house $ cd ..
nro: ~/wdi/exercises $ cd oz
nro: ~/wdi/exercises/oz $ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the West
nro: ~/wdi/exercises/oz $ touch Scarecrow "Tin Man"
nro: ~/wdi/exercises/oz $ ls
Dorothy             Scarecrow
Good Witch of the North     Tin Man
Good Witch of the South     Wicked Witch of the West
nro: ~/wdi/exercises/oz $ touch "Cowardly Lion"
nro: ~/wdi/exercises/oz $ ls
Cowardly Lion           Scarecrow
Dorothy             Tin Man
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
nro: ~/wdi/exercises/oz $ mkdir "Emerald City"
nro: ~/wdi/exercises/oz $ ls
Cowardly Lion           Good Witch of the South
Dorothy             Scarecrow
Emerald City            Tin Man
Good Witch of the North     Wicked Witch of the West
nro: ~/wdi/exercises/oz $ mv Dorothy "Emerald City"
nro: ~/wdi/exercises/oz $ mv Scarecrow "Emerald City"
nro: ~/wdi/exercises/oz $ mv "Cowardly Lion" "Emerald City"
nro: ~/wdi/exercises/oz $ ls
Emerald City            Tin Man
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
nro: ~/wdi/exercises/oz $ mv "Tin Man" "Emerald City"
nro: ~/wdi/exercises/oz $ ls
Emerald City            Good Witch of the South
Good Witch of the North     Wicked Witch of the West
nro: ~/wdi/exercises/oz $ cd "Emerald City"
nro: ~/wdi/exercises/oz/Emerald City $ ls
Cowardly Lion   Dorothy     Scarecrow   Tin Man
nro: ~/wdi/exercises/oz/Emerald City $ cd ..
nro: ~/wdi/exercises/oz $ touch "Flying Monkeys"
nro: ~/wdi/exercises/oz $ ls
Emerald City            Good Witch of the South
Flying Monkeys          Wicked Witch of the West
Good Witch of the North
nro: ~/wdi/exercises/oz $ rm "Wicked Witch of the West"
nro: ~/wdi/exercises/oz $ ls
Emerald City        Good Witch of the North
Flying Monkeys      Good Witch of the South
nro: ~/wdi/exercises/oz $ cd "Emerald City"
nro: ~/wdi/exercises/oz/Emerald City $ ls
Cowardly Lion   Dorothy     Scarecrow   Tin Man
nro: ~/wdi/exercises/oz/Emerald City $ echo "diploma" > Scarecrow
nro: ~/wdi/exercises/oz/Emerald City $ cat Scarecrow
diploma
nro: ~/wdi/exercises/oz/Emerald City $ echo "heart shaped watch" > "Tin Man"
nro: ~/wdi/exercises/oz/Emerald City $ cat "Tin Man"
heart shaped watch
nro: ~/wdi/exercises/oz/Emerald City $ echo "medal" > "Cowardly Lion"
nro: ~/wdi/exercises/oz/Emerald City $ cat "Cowardly Lion"
medal

**Comment by nolds9** [comment]
👍
