### ISSUE TITLE
CLI HW (Andy Whitley)

### ISSUE THREAD

**Issue by AndyWhitley** [ga-wdi-exercises/to_oz#126]
Last login: Wed Sep  7 08:33:37 on ttys000
 AndrewWhitley ~
$ ls
Applications    Downloads       Music       World       wdi
Desktop     Library     Pictures        fundamentals
Documents       Movies      Public      funny-things
 AndrewWhitley ~
$ cd wdi
 AndrewWhitley ~/wdi
$ ls
exercises       lessons     projects        sandbox
 AndrewWhitley ~/wdi
$ cd sandbox
 AndrewWhitley ~/wdi/sandbox
$ mkdir House
 AndrewWhitley ~/wdi/sandbox
$ cd House
 AndrewWhitley ~/wdi/sandbox/House
$ touch Dorothy.txt Toto.txt
 AndrewWhitley ~/wdi/sandbox/House
$ ls
Dorothy.txt     Toto.txt
 AndrewWhitley ~/wdi/sandbox/House
$ cd ..
 AndrewWhitley ~/wdi/sandbox
$ mkdir Oz
 AndrewWhitley ~/wdi/sandbox
$ cd Oz
 AndrewWhitley ~/wdi/sandbox/Oz
$ touch 'Good Witch of the North'.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Good Witch of the North.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ touch 'Wicked Witch of the East'.txt 'Good Witch of the South'.txt 'Wicked Witch of the West'.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Good Witch of the North.txt     Wicked Witch of the East.txt
Good Witch of the South.txt     Wicked Witch of the West.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ rm 'Wicked Witch of the West'.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Good Witch of the North.txt     Wicked Witch of the East.txt
Good Witch of the South.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ mv Dorothy.txt ~/wdi/sandbox/House ~/wdi/sandbox/Oz
mv: rename Dorothy.txt to /Users/AndrewWhitley/wdi/sandbox/Oz/Dorothy.txt: No such file or directory
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Good Witch of the North.txt     House
Good Witch of the South.txt     Wicked Witch of the East.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ cd House
 AndrewWhitley ~/wdi/sandbox/Oz/House
$ ls
Dorothy.txt     Toto.txt
 AndrewWhitley ~/wdi/sandbox/Oz/House
$ mv House ~/wdi/sandbox
mv: rename House to /Users/AndrewWhitley/wdi/sandbox/House: No such file or directory
 AndrewWhitley ~/wdi/sandbox/Oz/House
$ ls
Dorothy.txt     Toto.txt
 AndrewWhitley ~/wdi/sandbox/Oz/House
$ cd ..
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Good Witch of the North.txt     House
Good Witch of the South.txt     Wicked Witch of the East.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ mv House ~/wdi/sanbox
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Good Witch of the North.txt     Wicked Witch of the East.txt
Good Witch of the South.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ mv ~/wdi/sandbox/House/Dorothy.txt ~/wdi/sandbox/Oz
mv: rename /Users/AndrewWhitley/wdi/sandbox/House/Dorothy.txt to /Users/AndrewWhitley/wdi/sandbox/Oz/Dorothy.txt: No such file or directory
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Good Witch of the North.txt     Wicked Witch of the East.txt
Good Witch of the South.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ cd ../..
 AndrewWhitley ~/wdi
$ ls
exercises       lessons     projects        sanbox      sandbox
 AndrewWhitley ~/wdi
$ cd sandbox
 AndrewWhitley ~/wdi/sandbox
$ ls
Oz
 AndrewWhitley ~/wdi/sandbox
$ cd ..
 AndrewWhitley ~/wdi
$ cd sanbox
 AndrewWhitley ~/wdi/sanbox
$ ls
Dorothy.txt     Toto.txt
 AndrewWhitley ~/wdi/sanbox
$ cd ..
 AndrewWhitley ~/wdi
$ ls
exercises       lessons     projects        sanbox      sandbox
 AndrewWhitley ~/wdi
$ mv sanbox House
 AndrewWhitley ~/wdi
$ ls
House       exercises       lessons     projects        sandbox
 AndrewWhitley ~/wdi
$ cd Hosue
-bash: cd: Hosue: No such file or directory
 AndrewWhitley ~/wdi
$ cd House
 AndrewWhitley ~/wdi/House
$ ls
Dorothy.txt     Toto.txt
 AndrewWhitley ~/wdi/House
$ cd ..
 AndrewWhitley ~/wdi
$ ls
House       exercises       lessons     projects        sandbox
 AndrewWhitley ~/wdi
$ mv House sandbox
 AndrewWhitley ~/wdi
$ ls
exercises       lessons     projects        sandbox
 AndrewWhitley ~/wdi
$ cd sandbox
 AndrewWhitley ~/wdi/sandbox
$ ls
House   Oz
 AndrewWhitley ~/wdi/sandbox
$ cd Oz
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Good Witch of the North.txt     Wicked Witch of the East.txt
Good Witch of the South.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ mv ~/wdi/sandbox/House/Dorothy.txt ~/wdi/sandbox/Oz
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Dorothy.txt             Good Witch of the South.txt
Good Witch of the North.txt     Wicked Witch of the East.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ touch Scarecrow.txt 'Tin Man'.txt 'Cowardly Lion'.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Cowardly Lion.txt           Scarecrow.txt
Dorothy.txt             Tin Man.txt
Good Witch of the North.txt     Wicked Witch of the East.txt
Good Witch of the South.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ mkdir 'Emerald City'
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Cowardly Lion.txt           Good Witch of the South.txt
Dorothy.txt             Scarecrow.txt
Emerald City            Tin Man.txt
Good Witch of the North.txt     Wicked Witch of the East.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ mv 'Cowardly Lion'.txt Scarecrow.txt 'Tin Man'.txt Dorothy.txt 'Emerald City'
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Emerald City            Good Witch of the South.txt
Good Witch of the North.txt     Wicked Witch of the East.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ cd 'Emerald City'
 AndrewWhitley ~/wdi/sandbox/Oz/Emerald City
$ ls
Cowardly Lion.txt       Scarecrow.txt
Dorothy.txt         Tin Man.txt
 AndrewWhitley ~/wdi/sandbox/Oz/Emerald City
$ pwd
/Users/AndrewWhitley/wdi/sandbox/Oz/Emerald City
 AndrewWhitley ~/wdi/sandbox/Oz/Emerald City
$ cd ..
 AndrewWhitley ~/wdi/sandbox/Oz
$ pwd
/Users/AndrewWhitley/wdi/sandbox/Oz
 AndrewWhitley ~/wdi/sandbox/Oz
$ touch 'Flying Monkeys'.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ ls
Emerald City            Good Witch of the South.txt
Flying Monkeys.txt          Wicked Witch of the East.txt
Good Witch of the North.txt
 AndrewWhitley ~/wdi/sandbox/Oz
$ cd 'Emerald City'
 AndrewWhitley ~/wdi/sandbox/Oz/Emerald City
$ ls
Cowardly Lion.txt       Scarecrow.txt
Dorothy.txt         Tin Man.txt
 AndrewWhitley ~/wdi/sandbox/Oz/Emerald City
$ echo

 AndrewWhitley ~/wdi/sandbox/Oz/Emerald City
$ echo "diploma" > Scarecrow.txt
 AndrewWhitley ~/wdi/sandbox/Oz/Emerald City
$ open Scarecrow.txt
 AndrewWhitley ~/wdi/sandbox/Oz/Emerald City
$ echo "heart shaped watch" > 'Tin Man'.txt
 AndrewWhitley ~/wdi/sandbox/Oz/Emerald City
$ echo "medal" > 'Cowardly Lion'.txt
 AndrewWhitley ~/wdi/sandbox/Oz/Emerald City
$ open 'Tin Man'.txt
 AndrewWhitley ~/wdi/sandbox/Oz/Emerald City
$

**Comment by jshawl** [comment]
👍
