### ISSUE TITLE
CLI HW (Mike Flores)

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/to_oz#127]
# Commands

$ mkdir House
$ touch House/Dorothy
$ touch House/Toto
$ mkdir Oz
$ touch Oz/Good-Witch-of-the-North
$ touch Oz/Wicked-Witch-of-the-East
$ touch Oz/Good-Witch-of-the-South
$ touch Oz/Wicked-Witch-of-the-West

$ rm -rf Oz/Good-Witch-of-the-East
$ mv House/Dorothy Oz/

$ touch Scarecrow
$ touch Tin-Man
$ touch Cowardly-Lion
$ mkdir Emerald-City
$ mv the-gang Emerald-City/

$ touch Oz/Flying-Monleys
$ rm -rf Oz/Wicked-Witch-of-the-West
$ echo diploma > Scarecrow
$ echo heart-shaped-watch > Tin-Man
$ echo medal > Lion

**Comment by jshawl** [comment]
👍
