### ISSUE TITLE
CLI HW Ryan Brophy

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/to_oz#128]
Last login: Wed Sep  7 12:59:17 on ttys000
  Wed Sep 07 13:16:17 ~ (master #)
$ mkdir House
mkdir: House: File exists
  Wed Sep 07 13:16:24 ~ (master #)
$ touch Dorothy.txt Toto.txt
  Wed Sep 07 13:16:39 ~ (master #)
$ cd home
-bash: cd: home: No such file or directory
  Wed Sep 07 13:17:08 ~ (master #)
$ rm Oz/
rm: Oz/: No such file or directory
  Wed Sep 07 13:18:03 ~ (master #)
$ rm Oz
rm: Oz: No such file or directory
  Wed Sep 07 13:18:06 ~ (master #)
$ cd House
  Wed Sep 07 13:18:12 ~/House (master #)
$ cd Oz
  Wed Sep 07 13:18:46 ~/House/Oz (master #)
$ touch Good_Witch_of_the_north.txt Wicked_Witch_of_the_East.txt Good_Witch_of_the_South.txt Wicked_Witch_of_the_West.txt
  Wed Sep 07 13:20:25 ~/House/Oz (master #)
$ rm Wicked_Witch_of_the_East.txt
  Wed Sep 07 13:20:54 ~/House/Oz (master #)
$ cd House
  Wed Sep 07 13:21:03 ~/House/Oz/House (master #)
$ mv dorothy.txt Oz/
mv: rename dorothy.txt to Oz/: No such file or directory
  Wed Sep 07 13:21:16 ~/House/Oz/House (master #)
$ touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt
  Wed Sep 07 13:22:14 ~/House/Oz/House (master #)
$ mkdir Emerald_City
  Wed Sep 07 13:22:35 ~/House/Oz/House (master #)
$ mv  Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt Emerald_City/
  Wed Sep 07 13:23:12 ~/House/Oz/House (master #)
$ cd Oz
-bash: cd: Oz: No such file or directory
  Wed Sep 07 13:23:22 ~/House/Oz/House (master #)
$ pwd
/Users/ryanbrophy/House/Oz/House
  Wed Sep 07 13:23:26 ~/House/Oz/House (master #)
$ ..
-bash: ..: command not found
  Wed Sep 07 13:23:41 ~/House/Oz/House (master #)
$ touch Flying_Monkeys Oz/
touch: Oz/: No such file or directory
  Wed Sep 07 13:24:42 ~/House/Oz/House (master #)
$ touch Flying_Monkeys.txt
  Wed Sep 07 13:24:55 ~/House/Oz/House (master #)
$ mv  Flying_Monkeys.txt Oz/
mv: rename Flying_Monkeys.txt to Oz/: No such file or directory
  Wed Sep 07 13:25:31 ~/House/Oz/House (master #)
$ echo "diploma" >> Scarecrow.txt
  Wed Sep 07 13:27:22 ~/House/Oz/House (master #)
$ echo "heart_shaped_watch" Cowardly_Lion.txt
heart_shaped_watch Cowardly_Lion.txt
  Wed Sep 07 13:27:45 ~/House/Oz/House (master #)
$ echo "medal" Cowardly_Lion.txt
medal Cowardly_Lion.txt
  Wed Sep 07 13:28:20 ~/House/Oz/House (master #)
$

**Comment by amaseda** [comment]
:+1: Let me know if you have any questions about the errors you got as you worked on this assignment.
