### ISSUE TITLE
CLI HW (Alexander Spottswood)

### ISSUE THREAD

**Issue by ajspotts** [ga-wdi-exercises/to_oz#129]
Last login: Wed Sep  7 14:19:20 on ttys000
  Wed Sep 07 14:20:45 ~
$ cd ~
  Wed Sep 07 14:21:02 ~
$ cd ~wdi
  Wed Sep 07 14:21:05 ~/~wdi
$ ls
exercises   lessons     projects    sandbox
  Wed Sep 07 14:21:10 ~/~wdi
$ mkdir House
  Wed Sep 07 14:21:19 ~/~wdi
$ cd House
  Wed Sep 07 14:21:53 ~/~wdi/House
$ touch Dorothy.txt Toto.txt
  Wed Sep 07 14:22:13 ~/~wdi/House
$ cd ..
  Wed Sep 07 14:22:38 ~/~wdi
$ mkdir Oz
  Wed Sep 07 14:22:45 ~/~wdi
$ cd Oz
  Wed Sep 07 14:22:51 ~/~wdi/Oz
$ touch Good_Witch_of_the_North.txt Wicked_Witch_of_the_East.txt Good_Witch_of_the_South.txt Wicked_Witch_of_the_West.txt
  Wed Sep 07 14:24:14 ~/~wdi/Oz
$ rm Wicked_Witch_of_the_East.txt
  Wed Sep 07 14:24:42 ~/~wdi/Oz
$ ls
Good_Witch_of_the_North.txt Wicked_Witch_of_the_West.txt
Good_Witch_of_the_South.txt
  Wed Sep 07 14:24:44 ~/~wdi/Oz
$ cd ..
  Wed Sep 07 14:26:44 ~/~wdi
$ cd House
  Wed Sep 07 14:26:47 ~/~wdi/House
$ mv Dorothy.txt ../Oz
  Wed Sep 07 14:27:03 ~/~wdi/House
$ ls
Toto.txt
  Wed Sep 07 14:27:04 ~/~wdi/House
$ cd ..
  Wed Sep 07 14:27:15 ~/~wdi
$ cd House
  Wed Sep 07 14:28:33 ~/~wdi/House
$ touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt
  Wed Sep 07 14:29:05 ~/~wdi/House
$ cd ..
  Wed Sep 07 14:29:11 ~/~wdi
$ mkdir Emerald_City
  Wed Sep 07 14:29:24 ~/~wdi
$ cd House
  Wed Sep 07 14:29:34 ~/~wdi/House
$ mv Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt ../Emerald_City
  Wed Sep 07 14:30:12 ~/~wdi/House
$ cd..
-bash: cd..: command not found
  Wed Sep 07 14:30:21 ~/~wdi/House
$ cd ..
  Wed Sep 07 14:30:26 ~/~wdi
$ cd Emerald_City
  Wed Sep 07 14:30:37 ~/~wdi/Emerald_City
$ ls
Cowardly_Lion.txt   Scarecrow.txt       Tin_Man.txt
  Wed Sep 07 14:30:40 ~/~wdi/Emerald_City
$ cd Oz
-bash: cd: Oz: No such file or directory
  Wed Sep 07 14:30:51 ~/~wdi/Emerald_City
$ cd ..
  Wed Sep 07 14:30:56 ~/~wdi
$ cd Oz
  Wed Sep 07 14:31:02 ~/~wdi/Oz
$ touch Flying_Monkeys.txt
  Wed Sep 07 14:31:25 ~/~wdi/Oz
$ rm Wicked_Witch_of_the_West.txt
  Wed Sep 07 14:32:05 ~/~wdi/Oz
$ ls
Dorothy.txt         Good_Witch_of_the_North.txt
Flying_Monkeys.txt      Good_Witch_of_the_South.txt
  Wed Sep 07 14:32:09 ~/~wdi/Oz
$ echo "Diploma" > Scarecrow.txt
  Wed Sep 07 14:34:46 ~/~wdi/Oz
$ cd ..
  Wed Sep 07 14:35:40 ~/~wdi
$ cd Emerald_City
  Wed Sep 07 14:35:58 ~/~wdi/Emerald_City
$ echo "Diploma" > Scarecrow.txt
  Wed Sep 07 14:36:34 ~/~wdi/Emerald_City
$ echo "Heart Shaped Watch" > Tin_Man.txt
  Wed Sep 07 14:37:17 ~/~wdi/Emerald_City
$ echo "Medal" > Lion.txt

**Comment by jshawl** [comment]
👍
