### ISSUE TITLE
Kim's Day1 HW

### ISSUE THREAD

**Issue by kimcabb** [ga-wdi-exercises/to_oz#13]
geekfresh@LOGOS:~/wdi$ mkdir House
geekfresh@LOGOS:~/wdi$ cd House
geekfresh@LOGOS:~/wdi/House$ touch Dorothy Toto
geekfresh@LOGOS:~/wdi/House$ ls
Dorothy  Toto
geekfresh@LOGOS:~/wdi/House$ cd ..
geekfresh@LOGOS:~/wdi$ mkdir Oz
geekfresh@LOGOS:~/wdi$ cd Oz
geekfresh@LOGOS:~/wdi/Oz$ touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
geekfresh@LOGOS:~/wdi/Oz$ ls
Good_Witch_of_the_North  Wicked_Witch_of_the_East
Good_Witch_of_the_South  Wicked_Witch_of_the_West
geekfresh@LOGOS:~/wdi/Oz$ rm Wicked_Witch_of_the_East
geekfresh@LOGOS:~/wdi/Oz$ ls
Good_Witch_of_the_North  Good_Witch_of_the_South  Wicked_Witch_of_the_West
geekfresh@LOGOS:~/wdi/Oz$ cd ../House
geekfresh@LOGOS:~/wdi/House$ ls
Dorothy  Toto
geekfresh@LOGOS:~/wdi/House$ mv Dorothy ../Oz
geekfresh@LOGOS:~/wdi/House$ ls ../Oz
Dorothy                  Good_Witch_of_the_South
Good_Witch_of_the_North  Wicked_Witch_of_the_West
geekfresh@LOGOS:~/wdi/House$ cd ../Oz
geekfresh@LOGOS:~/wdi/Oz$ touch Scarecrow Tin_Man Cowardly_Lion
geekfresh@LOGOS:~/wdi/Oz$ ls
Cowardly_Lion            Good_Witch_of_the_South  Wicked_Witch_of_the_West
Dorothy                  Scarecrow
Good_Witch_of_the_North  Tin_Man
geekfresh@LOGOS:~/wdi/Oz$ mkdir Emerald_City
geekfresh@LOGOS:~/wdi/Oz$ ls
Cowardly_Lion  Good_Witch_of_the_North  Tin_Man
Dorothy        Good_Witch_of_the_South  Wicked_Witch_of_the_West
Emerald_City   Scarecrow
geekfresh@LOGOS:~/wdi/Oz$ mv Scarecrow Emerald_City
geekfresh@LOGOS:~/wdi/Oz$ ls Emerald_City
Scarecrow
geekfresh@LOGOS:~/wdi/Oz$ mv Dorothy Emerald_City
geekfresh@LOGOS:~/wdi/Oz$ mv Cowardly_Lion Emerald_City
geekfresh@LOGOS:~/wdi/Oz$ mv Tin_Man Emerald_City
geekfresh@LOGOS:~/wdi/Oz$ ls Emerald_City
Cowardly_Lion  Dorothy  Scarecrow  Tin_Man
geekfresh@LOGOS:~/wdi/Oz$ touch Flying_Monkeys
geekfresh@LOGOS:~/wdi/Oz$ ls
Emerald_City    Good_Witch_of_the_North  Wicked_Witch_of_the_West
Flying_Monkeys  Good_Witch_of_the_South
geekfresh@LOGOS:~/wdi/Oz$ rm Wicked_Witch_of_the_West
geekfresh@LOGOS:~/wdi/Oz$ ls
Emerald_City    Good_Witch_of_the_North
Flying_Monkeys  Good_Witch_of_the_South
geekfresh@LOGOS:~/wdi/Oz$ cd Emerald_City
geekfresh@LOGOS:~/wdi/Oz/Emerald_City$ echo "a diploma" >> Scarecrow
geekfresh@LOGOS:~/wdi/Oz/Emerald_City$ echo "a heart shaped watch" >> Tin_Man
geekfresh@LOGOS:~/wdi/Oz/Emerald_City$ echo "a medal" >> Cowardly_Lion
geekfresh@LOGOS:~/wdi/Oz/Emerald_City$ cat Scarecrow
a diploma
geekfresh@LOGOS:~/wdi/Oz/Emerald_City$ cat Tin_Man
a heart shaped watch
geekfresh@LOGOS:~/wdi/Oz/Emerald_City$ cat Cowardly_Lion
a medal
geekfresh@LOGOS:~/wdi/Oz/Emerald_City$

**Comment by RobertAKARobin** [comment]
Nice!
