### ISSUE TITLE
CLI HW (Rae Owens)

### ISSUE THREAD

**Issue by raeowens** [ga-wdi-exercises/to_oz#130]
Last login: Wed Sep  7 11:34:13 on ttys000
  Wed Sep 07 14:11:37 ~
$ pwd
/Users/raeowens
  Wed Sep 07 14:14:56 ~
$ mkdir House
  Wed Sep 07 14:15:04 ~
$ cd House
  Wed Sep 07 14:15:12 ~/House
$ touch Dorothy.txt
  Wed Sep 07 14:16:18 ~/House
$ touch Toto.txt
  Wed Sep 07 14:16:29 ~/House
$ ls
Dorothy.txt     Toto.txt
  Wed Sep 07 14:16:32 ~/House
$ ~
-bash: /Users/raeowens: is a directory
  Wed Sep 07 14:17:14 ~/House
$ cd ~
  Wed Sep 07 14:17:22 ~
$ mkdir Oz
  Wed Sep 07 14:17:32 ~
$ cd Oz
  Wed Sep 07 14:17:36 ~/Oz
$ touch GoodWitchoftheNorth.txt
  Wed Sep 07 14:18:35 ~/Oz
$ touch WickedWitchoftheEast.txt
  Wed Sep 07 14:18:48 ~/Oz
$ touch GoodWitchoftheSouth.txt
  Wed Sep 07 14:19:05 ~/Oz
$ touch WickedWitchoftheWest.txt
  Wed Sep 07 14:19:32 ~/Oz
$ la
-bash: la: command not found
  Wed Sep 07 14:19:38 ~/Oz
$ ls
GoodWitchoftheNorth.txt     WickedWitchoftheEast.txt
GoodWitchoftheSouth.txt     WickedWitchoftheWest.txt
  Wed Sep 07 14:19:41 ~/Oz
$ rm WickedWitchoftheEast.txt
  Wed Sep 07 14:23:15 ~/Oz
$ ls
GoodWitchoftheNorth.txt     GoodWitchoftheSouth.txt     WickedWitchoftheWest.txt
  Wed Sep 07 14:23:17 ~/Oz
$ cd House
-bash: cd: House: No such file or directory
  Wed Sep 07 14:23:35 ~/Oz
$ cd ~
  Wed Sep 07 14:23:47 ~
$ cd House
  Wed Sep 07 14:23:55 ~/House
$ ls
Dorothy.txt     Toto.txt
  Wed Sep 07 14:23:58 ~/House
$ mv Dorothy.txt Oz/
mv: rename Dorothy.txt to Oz/: No such file or directory
  Wed Sep 07 14:24:11 ~/House
$ ls
Dorothy.txt     Toto.txt
  Wed Sep 07 14:24:24 ~/House
$ cd ~
  Wed Sep 07 14:24:38 ~
$ cd Oz
  Wed Sep 07 14:24:41 ~/Oz
$ ls
GoodWitchoftheNorth.txt     GoodWitchoftheSouth.txt     WickedWitchoftheWest.txt
  Wed Sep 07 14:24:43 ~/Oz
$ cd ~
  Wed Sep 07 14:25:39 ~
$ cd House
  Wed Sep 07 14:25:42 ~/House
$ ls
Dorothy.txt     Toto.txt
  Wed Sep 07 14:25:43 ~/House
$ mv Dorothy.txt ../Oz
  Wed Sep 07 14:26:05 ~/House
$ ls
Toto.txt
  Wed Sep 07 14:26:08 ~/House
$ cd ~
  Wed Sep 07 14:26:14 ~
$ cd Oz
  Wed Sep 07 14:26:18 ~/Oz
$ ls
Dorothy.txt             GoodWitchoftheSouth.txt
GoodWitchoftheNorth.txt     WickedWitchoftheWest.txt
  Wed Sep 07 14:26:19 ~/Oz
$ touch Scarecrow.txt
  Wed Sep 07 14:31:27 ~/Oz
$ touch TinMan.txt
  Wed Sep 07 14:31:35 ~/Oz
$ touch CowardlyLion.txt
  Wed Sep 07 14:31:50 ~/Oz
$ cd ~
  Wed Sep 07 14:31:54 ~
$ mkdir EmeraldCity
  Wed Sep 07 14:32:25 ~
$ mv Scarecrow ../EmeraldCity
mv: rename Scarecrow to ../EmeraldCity: No such file or directory
  Wed Sep 07 17:10:35 ~
$ cd EmeraldCity
  Wed Sep 07 17:10:48 ~/EmeraldCity
$ ls
  Wed Sep 07 17:10:50 ~/EmeraldCity
$ cd ~
  Wed Sep 07 17:11:00 ~
$ cd Oz
  Wed Sep 07 17:11:11 ~/Oz
$ ls
CowardlyLion.txt            Scarecrow.txt
Dorothy.txt             TinMan.txt
GoodWitchoftheNorth.txt     WickedWitchoftheWest.txt
GoodWitchoftheSouth.txt
  Wed Sep 07 17:11:12 ~/Oz
$ cd ~
  Wed Sep 07 17:11:39 ~
$ mv Scarecrow.txt ../EmeraldCity
mv: rename Scarecrow.txt to ../EmeraldCity: No such file or directory
  Wed Sep 07 17:11:59 ~
$ cd Oz
  Wed Sep 07 17:12:07 ~/Oz
$ mv Scarecrow.txt ../EmeraldCity
  Wed Sep 07 17:12:36 ~/Oz
$ cd ~
  Wed Sep 07 17:12:49 ~
$ cd EmeraldCity
  Wed Sep 07 17:13:02 ~/EmeraldCity
$ ls
Scarecrow.txt
  Wed Sep 07 17:13:04 ~/EmeraldCity
$ ..
-bash: ..: command not found
  Wed Sep 07 17:13:15 ~/EmeraldCity
$ cd ..
  Wed Sep 07 17:13:19 ~
$ cd Oz
  Wed Sep 07 17:13:38 ~/Oz
$ mv TinMan.txt ../EmeraldCity
  Wed Sep 07 17:14:00 ~/Oz
$ mv CowardlyLion.txt ../EmeraldCity
  Wed Sep 07 17:14:16 ~/Oz
$ cd ..
  Wed Sep 07 17:14:24 ~
$ cd EmeraldCity
  Wed Sep 07 17:14:45 ~/EmeraldCity
$ ls
CowardlyLion.txt        Scarecrow.txt       TinMan.txt
  Wed Sep 07 17:14:47 ~/EmeraldCity
$ cd ..
  Wed Sep 07 17:14:54 ~
$ cd Oz
  Wed Sep 07 17:15:05 ~/Oz
$ touch FlyingMonkeys.txt
  Wed Sep 07 17:15:39 ~/Oz
$ ls
Dorothy.txt             GoodWitchoftheSouth.txt
FlyingMonkeys.txt           WickedWitchoftheWest.txt
GoodWitchoftheNorth.txt
  Wed Sep 07 17:15:42 ~/Oz
$ rm WickedWitchoftheWest.txt
  Wed Sep 07 17:16:03 ~/Oz
$ ls
Dorothy.txt         GoodWitchoftheNorth.txt
FlyingMonkeys.txt       GoodWitchoftheSouth.txt
  Wed Sep 07 17:16:05 ~/Oz
$ echo "Diploma" > Scarecrow.txt
  Wed Sep 07 17:18:21 ~/Oz
$ echo "Heart Shaped Watch" > TinMan.txt
  Wed Sep 07 17:24:03 ~/Oz
$ echo "Medal" > Lion.txt
  Wed Sep 07 17:24:27 ~/Oz
$

**Comment by jshawl** [comment]
👍
