### ISSUE TITLE
CLI HW (Mark Sweet

### ISSUE THREAD

**Issue by marks828** [ga-wdi-exercises/to_oz#132]
Comfort:5
Completion:5

mkdir house
cd house
touch dorothy.txt
touch toto.txt
cd ..
mkdir oz
cd oz
touch Good_witch_of_the_north.txt
touch wicked_witch_of_the_east.txt
touch good_witch_of_the_south.txt
touch wicked_witch_of_the_west.txt

rm wicked_witch_of_the_east.txt

cd ../house
mv dorothy.txt ../oz

cd oz

touch scarecrow.txt
touch tin_man.txt
touch cowardly_lion.txt

mkdir emerald_city
mv *.txt emerald_city

cd ..

touch flying_monkeys

rm touch wicked_witch_of_the_west.txt

cd emerald_city
echo "diploma" >> scarecrow.txt
echo "heart shaped watch" >> tin_man.txt
echo "gold medal" >> cowardly_lion.txt

**Comment by jshawl** [comment]
👍
