### ISSUE TITLE
CLI HW (manish pradhan)

### ISSUE THREAD

**Issue by manishP33** [ga-wdi-exercises/to_oz#133]
It was kind of confusing but finished it. Learned some great things.

**Comment by jshawl** [comment]
can you please post the output here?

**Comment by manishP33** [comment]
My-Computer-2:house admin$ tree

.

├── city

│   ├── cowardly_lion.txt

│   ├── emerald

│   ├── scarecrow.txt

│   └── tinman.txt

├── oz

│   ├── dorothy.txt

│   ├── flying_mokeys.txt

│   ├── good_witch_of_the_north.txt

│   └── good_witch_of_the_south.txt

└── toto.txt

3 directories, 8 files

**Comment by jshawl** [comment]
👍
