### ISSUE TITLE
CLI homework (Dominique Simmons)

### ISSUE THREAD

**Issue by D-giranew** [ga-wdi-exercises/to_oz#135]
giranew@giranew-HP-Pavilion-17-Notebook-PC:~$ cd wdi12
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12$ mkdir House
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12$ cd House
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/House$ touch Dorothy.txt
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/House$ touch Toto.txt
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/House$ cd ../
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12$ mkdir Oz
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12$ touch^C
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12$ ls
exercises  House  lessons  Oz  projects  sandbox
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12$ cd Oz
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ touch Good_Witch_of_the_North
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ touch Wicked_Witch_of_the_East
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ touch Good_Witch_of_the_South
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ touch Wicked_Witch_of_the_West
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ ls
Good_Witch_of_the_North  Good_Witch_of_the_South  Wicked_Witch_of_the_East  Wicked_Witch_of_the_West
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ rm  Wicked_Witch_of_the_East
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ cd House
bash: cd: House: No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ cd ../
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12$ cd House
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/House$ mv Dorothy.txt/Oz
mv: missing destination file operand after 'Dorothy.txt/Oz'
Try 'mv --help' for more information.
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/House$ mv Dorothy.txt Oz
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/House$ ls
Oz  Toto.txt
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/House$ cd../Oz
bash: cd../Oz: No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/House$ cd../
bash: cd../: No such file or directory
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/House$ cd ../Oz
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ ls
Good_Witch_of_the_North  Good_Witch_of_the_South  Wicked_Witch_of_the_West
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ touch Dorothy
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ touch Scarecrow
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ touch Tin_Man
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ touch Cowardly_Lion
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ mkdir Emerald_City
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ mv Emerald_city/Dorothy
mv: missing destination file operand after 'Emerald_city/Dorothy'
Try 'mv --help' for more information.
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ mv help
mv: missing destination file operand after 'help'
Try 'mv --help' for more information.
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ mv--help
mv--help: command not found
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ mv Dorothy Emerald_City
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ mv Scarecrow Emerald_City
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ mv Tin_Man Emerald_City
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ mv Cowardly_Lion Emerald_City
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ touch Flying_Monkeys
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ rm  Wicked_Witch_of_the_West
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ echo diploma >> scarecrow
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ echo heart shaped watch >> Tin_Man
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ echo medal >> Cowardly_Lion
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ ls
Cowardly_Lion  Flying_Monkeys           Good_Witch_of_the_South  Tin_Man
Emerald_City   Good_Witch_of_the_North  scarecrow
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz$ cd Emerald_City
giranew@giranew-HP-Pavilion-17-Notebook-PC:~/wdi12/Oz/Emerald_City$ ls
Cowardly_Lion  Dorothy  Scarecrow  Tin_Man

**Comment by jshawl** [comment]
👍
