### ISSUE TITLE
Jonathans HW

### ISSUE THREAD

**Issue by jdreiser1** [ga-wdi-exercises/to_oz#137]
mkdir House
cd House
touch Dorothy Toto
mkdir Oz
cd Oz
touch "Good Witch of the West" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
rm  "Wicked Witch of the East"
mv ../Dorothy .
touch Scarecrow
touch "Tin Man"
touch "Cowardly Lion"
mkdir "Emerald City"
mv Dorothy Scarecrow "Tin Man" "Cowardly Lion" "Emerald City"
touch "Flying Monkeys"
rm "Wicked Witch of the West"
echo "a diploma" > "Emerald City"/Scarecrow
echo "a heart shaped watch" > "Emerald City"/"Tin Man"
echo "a medal" > "Emerald City"/"Cowardly Lion"

**Comment by nayana487** [comment]
👍
