### ISSUE TITLE
Bradley Cravens HW 

### ISSUE THREAD

**Issue by bradleycravens** [ga-wdi-exercises/to_oz#138]
mkdir House
cd House
touch Dorothy Toto 
cd ..
mkdir Oz
cd Oz
touch “Good Witch of the North” “Wicked Witch of the East” “Good Witch of the South” “Wicked Witch of the West” “Wicked Witch of the East”
rm “Wicked Witch of the East”
mv ../house/Dorothy .
touch Scarecrow “Tin Man” “Cowardly Lion” 
mkdir “Emerald City”
mv  Dorothy Scarecrow “Tin man” “Cowardly Lion” “Emerald City”
touch “Flying Monkeys”
rm “Wicked Witch of the West”
cd ../“Emerald City”
echo diploma > Scarecrow
echo “heart shaped watch > “Tin Man”
echo medal > “Lion”

**Comment by andrewsunglaekim** [comment]
👍

**Comment by andrewsunglaekim** [comment]
this looks great, I would consider removing white space from file names. When we move into more technologies, the different interfaces won't play well with white space in directories/files.

```
// Underscores(snake case)
$ touch Good_Witch_of_the_North

// Hyphens(spine case)
$ touch Good-Witch-of-the-North

// CamelCase
$ touch GoodWitchOfTheNorth
```
