### ISSUE TITLE
CLI HW (Thinh Nguyen)

### ISSUE THREAD

**Issue by nguyendthinh** [ga-wdi-exercises/to_oz#139]
$ mkdir House
$ cd House
$ touch Dorothy Toto
$ mkdir Oz
$ cd Oz
$ touch GoodWitchoftheNorth WickedWitchoftheEast GoodWitchoftheSouth WickedWitchoftheWest
$ rm WickedWitchoftheEast
$ mv ../Dorothy .
$ touch Scarecrow TinMan CowardlyLion
$ mkdir EmeraldCity
$ mv CowardlyLion TinMan Dorothy Scarecrow EmeraldCity/
$ touch FlyingMonkeys
$ rm WickedWitchoftheWest
$ cd EmeraldCity
$ echo "diploma" >> Scarecrow
$ echo "heart shaped watch" >> TinMan
$ echo "medal" >> CowardlyLion

**Comment by superbuggy** [comment]
🔨 nailed it
