### ISSUE TITLE
Lyndsey Newsome Day 1 Homework

### ISSUE THREAD

**Issue by LNewsome** [ga-wdi-exercises/to_oz#14]
~/wdi 
$ ls
Exercises   Projects    Sandbox
Lessons     Rakefile    installfest.yml
~/wdi 
$ cd Exercises
~/wdi/Exercises 
$ pwd
/Users/lyndseynewsome/wdi/Exercises
~/wdi/Exercises 
$ mkdir House
~/wdi/Exercises 
$ cd House
~/wdi/Exercises/House 
$ touch Dorothy
~/wdi/Exercises/House 
$ touch Toto
~/wdi/Exercises/House 
$ ls
Dorothy Toto
~/wdi/Exercises/House 
$ cd ..
~/wdi/Exercises 
$ pwd
/Users/lyndseynewsome/wdi/Exercises
~/wdi/Exercises 
$ ls
House
~/wdi/Exercises 
$ mkdir Oz
~/wdi/Exercises 
$ ls 
House   Oz
~/wdi/Exercises 
$ cd Oz
~/wdi/Exercises/Oz 
$ touch Good Witch of the North
~/wdi/Exercises/Oz 
$ ls
Good    North   Witch   of  the
~/wdi/Exercises/Oz 
$ rm -r Good Witch of the North
~/wdi/Exercises/Oz 
$ ls
~/wdi/Exercises/Oz 
$ touch Good_Witch_of_the_North
~/wdi/Exercises/Oz 
$ ls
Good_Witch_of_the_North
~/wdi/Exercises/Oz 
$ touch Wicked_Witch_of_East
~/wdi/Exercises/Oz 
$ ls
Good_Witch_of_the_North Wicked_Witch_of_East
~/wdi/Exercises/Oz 
$ touch Good_Witch_of_the_South
~/wdi/Exercises/Oz 
$ ls
Good_Witch_of_the_North Good_Witch_of_the_South Wicked_Witch_of_East
~/wdi/Exercises/Oz 
$ touch Wicked_Witch_of_The_West
~/wdi/Exercises/Oz 
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_East
Good_Witch_of_the_South     Wicked_Witch_of_The_West
~/wdi/Exercises/Oz 
~/wdi/Exercises/Oz 
$ rm -r Wicked_Witch_of_East
~/wdi/Exercises/Oz 
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_The_West
Good_Witch_of_the_South
~/wdi/Exercises/Oz 
$ cd ..
~/wdi/Exercises 
$ ls
House   Oz
~/wdi/Exercises 
$ cd House
~/wdi/Exercises/House 
$ ls
Dorothy Toto
~/wdi/Exercises/House 
$ mv Dorothy ~/Oz
~/wdi/Exercises/House 
$ ls
Toto
~/wdi/Exercises/House 
$ $ mv Dorothy ..
~/wdi/Exercises/House 
$ ls
Toto
~/wdi/Exercises/House 
$ cd ..
~/wdi/Exercises 
$ ls
Dorothy House   Oz
~/wdi/Exercises 
$ mv Dorothy Oz
~/wdi/Exercises 
$ ls
House   Oz
~/wdi/Exercises 
$ cd Oz
~/wdi/Exercises/Oz 
$ ls
Dorothy             Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_The_West
~/wdi/Exercises/Oz 
$ touch Scarecrow
 $ touch Tin_Man
~/wdi/Exercises/Oz 
$ Touch Cowardly_Lion
~/wdi/Exercises/Oz 
$ ls
Cowardly_Lion           Scarecrow
Dorothy             Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_The_West
Good_Witch_of_the_South
~/wdi/Exercises/Oz 
$ mkdir Emerald_City
~/wdi/Exercises/Oz 
$ ls
Cowardly_Lion           Good_Witch_of_the_South
Dorothy             Scarecrow
Emerald_City            Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_The_West
~/wdi/Exercises/Oz 
$ mv Dorothy Emerald_City
~/wdi/Exercises/Oz 
$ ls
Cowardly_Lion           Scarecrow
Emerald_City            Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_The_West
Good_Witch_of_the_South
~/wdi/Exercises/Oz 
$ mv Cowardly_Lion Emerald_City
~/wdi/Exercises/Oz 
$ ls
Emerald_City            Scarecrow
Good_Witch_of_the_North     Tin_Man
Good_Witch_of_the_South     Wicked_Witch_of_The_West
~/wdi/Exercises/Oz 
$ mv Scarecrow Emerald_City
~/wdi/Exercises/Oz 
$ ls
Emerald_City            Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_The_West
Good_Witch_of_the_South
~/wdi/Exercises/Oz 
$ mv Tin_Man Emerald_City
~/wdi/Exercises/Oz 
$ ls
Emerald_City            Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_The_West
~/wdi/Exercises/Oz 
$ cd Emerald_City
~/wdi/Exercises/Oz/Emerald_City 
$ ls
Cowardly_Lion   Dorothy     Scarecrow   Tin_Man
~/wdi/Exercises/Oz/Emerald_City 
$ cd ..
~/wdi/Exercises/Oz 
$ touch Flying_Monkeys
~/wdi/Exercises/Oz 
$ ls
Emerald_City            Good_Witch_of_the_South
Flying_Monkeys          Wicked_Witch_of_The_West
Good_Witch_of_the_North
~/wdi/Exercises/Oz 
$ rm -r Wicked_Witch_of_The_West
~/wdi/Exercises/Oz 
$ ls
Emerald_City        Good_Witch_of_the_North
Flying_Monkeys      Good_Witch_of_the_South
~/wdi/Exercises/Oz 
$ cd Emerald_City
~/wdi/Exercises/oz/Emerald_City 
$ ls
Cowardly_Lion   Dorothy     Scarecrow   Tin_Man
~/wdi/Exercises/oz/Emerald_City 
$ echo "a diploma" >> Scarecrow
~/wdi/Exercises/oz/Emerald_City 
$ echo "a heart" >> Tin_Man
~/wdi/Exercises/oz/Emerald_City 
$ echo "a Medal" >> Cowardly_Lion
~/wdi/Exercises/oz/Emerald_City 
$ ls
Cowardly_Lion   Dorothy     Scarecrow   Tin_Man
~/wdi/Exercises/oz/Emerald_City 
$

**Comment by RobertAKARobin** [comment]
Nice, Lyndsey!
