### ISSUE TITLE
Sam Mans HW

### ISSUE THREAD

**Issue by sdmans** [ga-wdi-exercises/to_oz#140]
mkdir House

cd House

touch “Dorothy” “Toto”

mkdir Oz

cd Oz

touch “Good Witch of the North” “Wicked Witch of the East” “Good Witch of the South” “Wicked Witch of the West”

rm “Wicked Witch of the East”

cd ../

mv Dorothy Oz/

cd Oz

touch “Scarecrow” “Tin Man” “Cowardly Lion”

mkdir “Emerald City”

mv “Scarecrow” “Tin Man” “Cowardly Lion” “Dorothy” “Emerald City”/

cd ../

touch “Flying Monkeys”

rm “Wicked Witch of the West”

cd “Emerald City”

echo “a diploma” > Scarecrow

echo “a heart shaped watch” > “Tin Man”

echo “a medal” > “Cowardly Lion”

**Comment by superbuggy** [comment]
nailed it 👍
