### ISSUE TITLE
Angel Valant's Homework

### ISSUE THREAD

**Issue by avalant** [ga-wdi-exercises/to_oz#141]
mkdir House
cd House
touch Dorothy Toto
mkdir Oz
cd Oz
touch “Good Witch of the North” “Wicked Witch of the East” “Good Witch of the South” “Wicked Witch of the West”
rm “Wicked Witch of the East”
cd ..
mv Dorothy ./Oz/
touch “Scarecrow” “Tin Man” “Cowardly Lion”
mkdir “Emerald City”
mv “Scarecrow” “Tin Man” “Cowardly Lion” “Emerald City/“ 
cd Oz
mv Dorothy ../“Emerald City/“
touch “Flying Monkeys”
rm “Wicked Witch of the West”
cd ..
cd “Emerald City”
echo “diploma” > “Scarecrow”
echo “heart shaped watch” > “Tin Man”
echo “medal” > “Cowardly Lion”

**Comment by nayana487** [comment]
👍
