### ISSUE TITLE
Rob Z Homework

### ISSUE THREAD

**Issue by robertzehnder** [ga-wdi-exercises/to_oz#142]
**Step 1**
1. mkdir house
2. touch Dorthy.txt Toto.txt
3. mkdir Oz
4. touch good-witch-of-the-north.txt wicked-witch-of-the-east.txt good-witch-of-the-south.txt wicked-witch-of-the-west.txt

**Ding! Dong! The Witch is Dead**
1. rm wicked-witch-of-the-east.txt
2. mv Dorthy.txt Oz

**Follow The Yellow Brick Road**

1-3. touch scarecrow.txt tin-man.txt cowardly-lion.txt
4. mkdir emerald-city

_--Note for this that ".txt" and "witch" have wildcards around them to move all files with those names to the other directories_
1. mv _.txt_ emerald-city/
2. a. cd emerald-city/
3. b. mv _witch_ ../

**You Must Kill the Witch**
1.  cd ../emerald-city
2. rm wicked-witch-of-the-west.txt
3. 
         i. echo "Diploma" > scarecrow.txt 
         ii. echo "heart shaped watch" > tin-man.txt
         iii. echo "medal" >  cowardly-lion.txt

**Comment by nayana487** [comment]
👍
