### ISSUE TITLE
Kevin Herrera's First HW

### ISSUE THREAD

**Issue by herrerake** [ga-wdi-exercises/to_oz#143]
Create directory "House"
-mk dir house 

Add files: "Dorothy" and "Toto" to "House"
-cd house
-touch dorothy toto

Create directory "Oz"
- cd ..
- mkdir oz

Add files for the 4 Witches to "Oz":
-cd oz
-mk "Good Witch of the North"   "Wicked Witch of the East" "Good Witch of the South"        "Wicked Witch of the West"

Delete: "Wicked Witch of the East"
- rm "Wicked Witch of the East"

Move "Dorothy" from "House" to "Oz"
-cd ..
-mv dorothy ../
-mv dorothy house

Add file for "Scarecrow"
Add file for "Tin Man"
Add file for "Cowardly Lion"
- touch "scarecrow" "tin man" "cowardly lion" 
  Create directory "Emerald City"
- mkdir "emerald city"
  Move 'the gang' to "Emerald City"
- mv scarecrow "tin man" "cowardly lion" emerald city

Add "Flying Monkeys" to "Oz"
cd ../
cd oz
touch "flying monkeys"

Remove "Wicked Witch of the West"
- rm "Wicked Witch of the West"

Give the gifts*
Give Scarecrow a diploma
Give Tin Man a heart shaped watch
Give Lion a medal

"diploma" > "emerald city"/scarecrow
"a heart shaped watch" > "emerald city"/"tin man"
"medal" > "emerald city"/lion

**Comment by superbuggy** [comment]
`mv scarecrow "tin man" "cowardly lion" emerald city`
NICE 👍
