### ISSUE TITLE
Donovan Allen's HW1

### ISSUE THREAD

**Issue by donovanallen** [ga-wdi-exercises/to_oz#145]
Mon Oct 03 18:46:17 ~
$ cd Desktop
  Mon Oct 03 18:46:33 ~/Desktop
$ mkdir House
  Mon Oct 03 18:46:42 ~/Desktop
$ cd House
  Mon Oct 03 18:46:46 ~/Desktop/House
$ touch Dorothy Toto House.txt
  Mon Oct 03 18:47:07 ~/Desktop/House
$ ls
Dorothy     House.txt   Toto
  Mon Oct 03 18:47:08 ~/Desktop/House
$ mv Dorothy > Dorothy.txt
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Mon Oct 03 18:47:28 ~/Desktop/House
$ ls
Dorothy     Dorothy.txt House.txt   Toto
  Mon Oct 03 18:47:32 ~/Desktop/House
$ rm Dorothy
  Mon Oct 03 18:47:47 ~/Desktop/House
$ ls
Dorothy.txt House.txt   Toto
  Mon Oct 03 18:47:48 ~/Desktop/House
$ mv Toto Toto.txt
  Mon Oct 03 18:47:58 ~/Desktop/House
$ ls
Dorothy.txt House.txt   Toto.txt
  Mon Oct 03 18:47:59 ~/Desktop/House
$ mkdir Oz
  Mon Oct 03 18:49:00 ~/Desktop/House
$ cd Oz
  Mon Oct 03 18:49:09 ~/Desktop/House/Oz
$ touch 'Good With of the North.txt' 'Wicked Witch of the East.txt' 'Good Witch of the South.txt' 'Wicked Witch of the West.txt'
  Mon Oct 03 18:50:21 ~/Desktop/House/Oz
$ ls
Good Witch of the South.txt Wicked Witch of the East.txt
Good With of the North.txt  Wicked Witch of the West.txt
  Mon Oct 03 18:50:23 ~/Desktop/House/Oz
$ mv 'Good With of the North.txt' 'Good Witch of the North.txt'
  Mon Oct 03 18:51:10 ~/Desktop/House/Oz
$ ls
Good Witch of the North.txt Wicked Witch of the East.txt
Good Witch of the South.txt Wicked Witch of the West.txt
  Mon Oct 03 18:51:11 ~/Desktop/House/Oz
$ rm 'Wicked Witch of the East.txt'
  Mon Oct 03 18:51:48 ~/Desktop/House/Oz
$ ls
Good Witch of the North.txt Wicked Witch of the West.txt
Good Witch of the South.txt
  Mon Oct 03 18:51:51 ~/Desktop/House/Oz
$ cd ..
  Mon Oct 03 18:52:02 ~/Desktop/House
$ ls
Dorothy.txt House.txt   Oz      Toto.txt
  Mon Oct 03 18:52:04 ~/Desktop/House
$ mv Dorothy.txt > ./Oz
-bash: ./Oz: Is a directory
  Mon Oct 03 18:57:26 ~/Desktop/House
$ ls
Dorothy.txt House.txt   Oz      Toto.txt
  Mon Oct 03 18:57:34 ~/Desktop/House
$ mv Dorothy.txt ./Oz
  Mon Oct 03 19:02:39 ~/Desktop/House
$ ls
House.txt   Oz      Toto.txt
  Mon Oct 03 19:02:41 ~/Desktop/House
$ touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt
  Mon Oct 03 19:03:37 ~/Desktop/House
$ mkdir Emerald_City
  Mon Oct 03 19:03:55 ~/Desktop/House
$ ls
Cowardly_Lion.txt   Oz          Toto.txt
Emerald_City        Scarecrow.txt
House.txt       Tin_Man.txt
  Mon Oct 03 19:04:20 ~/Desktop/House
$ mv Scarecrow.txt Cowardly_Lion.txt Tin_Man.txt Toto.txt ./Emerald_City
  Mon Oct 03 19:05:21 ~/Desktop/House
$ ls
Emerald_City    House.txt   Oz
  Mon Oct 03 19:05:25 ~/Desktop/House
$ cd Oz
  Mon Oct 03 19:05:31 ~/Desktop/House/Oz
$ touch Flying_Monkeys.txt
  Mon Oct 03 19:05:46 ~/Desktop/House/Oz
$ ls
Dorothy.txt         Good Witch of the South.txt
Flying_Monkeys.txt      Wicked Witch of the West.txt
Good Witch of the North.txt
  Mon Oct 03 19:05:50 ~/Desktop/House/Oz
$ rm 'Wicked Witch of the West.txt' 
  Mon Oct 03 19:06:14 ~/Desktop/House/Oz
$ ls
Dorothy.txt         Good Witch of the North.txt
Flying_Monkeys.txt      Good Witch of the South.txt
  Mon Oct 03 19:06:38 ~/Desktop/House/Oz
$ cd ..
  Mon Oct 03 19:08:41 ~/Desktop/House
$ ls
Emerald_City    House.txt   Oz
  Mon Oct 03 19:08:43 ~/Desktop/House
$ cd Emerald_City
  Mon Oct 03 19:08:54 ~/Desktop/House/Emerald_City
$ ls
Cowardly_Lion.txt   Tin_Man.txt
Scarecrow.txt       Toto.txt
  Mon Oct 03 19:08:56 ~/Desktop/House/Emerald_City
$ echo 'Diploma' Scarecrow.txt 
Diploma Scarecrow.txt
  Mon Oct 03 19:09:27 ~/Desktop/House/Emerald_City
$ echo 'Diploma' > Scarecrow.txt 
  Mon Oct 03 19:09:44 ~/Desktop/House/Emerald_City
$ cat Scarecrow.txt 
Diploma
  Mon Oct 03 19:09:49 ~/Desktop/House/Emerald_City
$ echo 'heart shaped watch' > Tin_Man.txt 
  Mon Oct 03 19:10:15 ~/Desktop/House/Emerald_City
$ cat Tin_Man.txt 
heart shaped watch
  Mon Oct 03 19:10:19 ~/Desktop/House/Emerald_City
$ echo 'medal' > Cowardly_Lion.txt 
  Mon Oct 03 19:10:37 ~/Desktop/House/Emerald_City
$ cat Cowardly_Lion.txt 
medal
  Mon Oct 03 19:13:41 ~/Desktop/House/Emerald_City
$ mv Cowardly_Lion.txt Lion.txt
  Mon Oct 03 19:13:56 ~/Desktop/House/Emerald_City
$ ls
Lion.txt    Scarecrow.txt   Tin_Man.txt Toto.txt

**Comment by andrewsunglaekim** [comment]
👍 
this looks great, I would consider removing white space from file names. When we move into more technologies, the different interfaces won't play well with white space in directories/files.

```
// Underscores(snake case)
$ touch Good_Witch_of_the_North

// Hyphens(spine case)
$ touch Good-Witch-of-the-North

// CamelCase
$ touch GoodWitchOfTheNorth
```
