### ISSUE TITLE
Ej's hw

### ISSUE THREAD

**Issue by ejsorrento** [ga-wdi-exercises/to_oz#146]
**To Oz? To Oz!**

mkdir House
touch Dorothy.txt Toto.txt
mkdir Oz
touch Good-witch-of-the-north.txt Wicked-witch-of-the-east.txt Good-witch-of-the-south.txt Wicked-witch-of-the-west.txt

**Ding! Dong! The Witch is Dead**

rm Wicked-witch-of-the-east.txt
mv Dorothy.txt Oz

**Follow the Yellow Brick Road**

touch scarecrow.txt tin-man.txt cowardly-lion.txt
mkdir emerald-city
mv scarecrow.txt tin-man.txt cowardly-lion.txt Dorothy.txt oz/emerald-city

**You Must Kill the Witch**

touch flying-monkeys.txt
rm Wicked-witch-of-the-west.txt
echo "diploma" scarecrow.txt
diploma scarecrow.txt "heart-shaped-watch" tin-man.txt "medal" cowardly-lion.txt

**__Bonus:__**
mv Toto.txt oz/emerald-city :)

**Comment by nayana487** [comment]
👍
