### ISSUE TITLE
Rob Romaniw To_Oz

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/to_oz#147]
mkdir House
cd House
touch Dorothy.txt Toto.txt
mkdir Oz
cd Oz
touch Good-Witch-of-the-North.txt Wicked-Witch-of-the-East.txt Good-Witch-of-the-South.txt Wicked-Witch-of-the-West.txt
rm Wicked-Witch-of-the-East.txt
cd ..
mv Dorothy.txt Oz
touch Scarecrow.txt Tin-Man.txt Cowardly-Lion.txt
mkdir Emerald-City
mv Scarecrow.txt Cowardly-Lion.txt Tin-Man.txt Toto.txt Emerald-City
ls
Emerald-City    Oz
cd Oz
touch Flying-Monkeys.txt
rm Wicked-Witch-of-the-West.txt
Roberts-MacBook-Pro-2:Oz Mamba$ cd ..
ls
Emerald-City    Oz
cd Emerald-City
echo "Diploma" > scarecrow.txt
echo "heart shaped watch" > tin-man.txt
echo "medal" > cowardly-lion.txt

**Comment by nayana487** [comment]
👍
