### ISSUE TITLE
Drew's Homework

### ISSUE THREAD

**Issue by drewswinburne** [ga-wdi-exercises/to_oz#148]
$ mkdir House

~/wdi
$ touch Dorothy Toto ./House

~/wdi
$ cd House

~/wdi/House
$ touch Dorothy Toto

~/wdi/House
$ mkdir ../Oz

~/wdi/House
$ cd ../Oz

~/wdi/Oz
$ touch 'Good Witch of the North' 'Wicked Witch of the East' 'Good Witch of the South' 'Wicked Witch of the West'

~/wdi/Oz
$ rm 'Wicked Witch of the East'

~/wdi/Oz
$ mv ../House/Dorothy ../Oz/Dorothy

~/wdi/Oz
$ touch 'Scarecrow' 'Tin Man' 'Cowardly Lion'

~/wdi/Oz
$ mv 'Scarecrow' 'Tin Man' 'Cowardly Lion' ./'Emerald City'

~/wdi/Oz
$ touch 'Flying Monkeys'

~/wdi/Oz
$ rm 'Wicked Witch of the West'

~/wdi/Oz
$ cd 'Emerald City'

~/wdi/Oz/Emerald City
$ echo diploma > 'Scarecrow'

~/wdi/Oz/Emerald City
$ echo heart shaped watch > 'Tin Man'

~/wdi/Oz/Emerald City
$ echo medal > 'Lion'

**Comment by nayana487** [comment]
👍
