### ISSUE TITLE
Sam C's hw1

### ISSUE THREAD

**Issue by SamCatherman** [ga-wdi-exercises/to_oz#149]
Mon Oct 03 21:25:50 ~
$ mkdir House
  Mon Oct 03 21:25:55 ~
$ cd House
  Mon Oct 03 21:26:00 ~/House
$ pwd
/Users/a/House
  Mon Oct 03 21:26:02 ~/House
$ touch Dorothy.txt Toto.txt
  Mon Oct 03 21:26:58 ~/House
$ mkdir Oz
  Mon Oct 03 21:27:05 ~/House
$ cd Oz
  Mon Oct 03 21:27:12 ~/House/Oz
$ touch Good_Witch_of_the_North.txt Wicked_Witch_of_the_East.txt Good_Witch_of_the_South.txt Wicked_Witch_of_the_West.txt
  Mon Oct 03 21:28:49 ~/House/Oz
$ rm Wicked_Witch_of_the_East.txt
  Mon Oct 03 21:29:08 ~/House/Oz
$ cd ..
  Mon Oct 03 21:34:03 ~/House
$ mv Dorothy.txt Oz
  Mon Oct 03 21:36:54 ~/House
$ touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt
  Mon Oct 03 21:37:53 ~/House
$ mkdir Emerald_City
  Mon Oct 03 21:38:02 ~/House
$ mv Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt Emerald_City
  Mon Oct 03 21:38:30 ~/House
$ touch Flying_Monkeys.txt
  Mon Oct 03 21:39:15 ~/House/Oz
$ rm Wicked_Witch_of_the_West.txt
  Mon Oct 03 21:39:42 ~/House/Oz
$ echo Scarecrow.txt diploma
Scarecrow.txt diploma
  Mon Oct 03 21:49:41 ~/House/Oz
$ echo Tin_man.txt heart_shaped_watch
Tin_man.txt heart_shaped_watch
  Mon Oct 03 21:49:55 ~/House/Oz
$ echo Cowardly_Lion.txt medal
Cowardly_Lion.txt medal
  Mon Oct 03 21:50:34 ~/House/Oz
"I hereby confer upon you the honorary degree of TH.D."

**Comment by andrewsunglaekim** [comment]
👍
