### ISSUE TITLE
Matt Stevens Day 1 HW

### ISSUE THREAD

**Issue by MattLeeStevens** [ga-wdi-exercises/to_oz#15]
~/wdi/exercises/to_oz
$ mkdir House
~/wdi/exercises/to_oz
$ cd House/
~/wdi/exercises/to_oz/House
$ touch Dorothy
~/wdi/exercises/to_oz/House
$ touch Toto
~/wdi/exercises/to_oz/House
$ cd ..
~/wdi/exercises/to_oz
$ mkdir Oz
~/wdi/exercises/to_oz
$ cd Oz/
~/wdi/exercises/to_oz/Oz
$ touch Good_Witch_of_the_North
~/wdi/exercises/to_oz/Oz
$ touch Wicked_Witch_of_the_East
~/wdi/exercises/to_oz/Oz
$ touch Good_Witch_of_the_South
~/wdi/exercises/to_oz/Oz
$ touch Wicked_Witch_of_the_West
~/wdi/exercises/to_oz/Oz
$ rm Wicked_Witch_of_the_East
~/wdi/exercises/to_oz/Oz
$ cd ..
~/wdi/exercises/to_oz
$ mv ./House/Dorothy ./Oz/Dorothy
~/wdi/exercises/to_oz
$ cd Oz/
~/wdi/exercises/to_oz/Oz
$ touch Scarecrow
~/wdi/exercises/to_oz/Oz
$ touch Tin_Man
~/wdi/exercises/to_oz/Oz
$ touch Cowardly_Lion
~/wdi/exercises/to_oz/Oz
$ mkdir Emerald_City
~/wdi/exercises/to_oz/Oz
$ mv ./Dorothy ./Scarecrow ./Tin_Man ./Cowardly_Lion ./Emerald_City
~/wdi/exercises/to_oz/Oz
$ touch Flying_Monkeys
~/wdi/exercises/to_oz/Oz
$ rm Wicked_Witch_of_the_West
~/wdi/exercises/to_oz/Oz
$ echo "a diploma" >> ./Emerald_City/Scarecrow
~/wdi/exercises/to_oz/Oz
$ echo "a heart shaped watch" >> ./Emerald_City/Tin_Man
~/wdi/exercises/to_oz/Oz
$ echo "a medal" >> ./Emerald_City/Cowardly_Lion
~/wdi/exercises/to_oz/Oz
$

**Comment by RobertAKARobin** [comment]
Nice!
