### ISSUE TITLE
Robert HW1 to_oz

### ISSUE THREAD

**Issue by rob-king** [ga-wdi-exercises/to_oz#150]
1. Create directory "House"
2. Add files: "Dorothy" and "Toto" to "House"
3. Create directory "Oz"
4. Add files for the 4 Witches to "Oz":
   - Good Witch of the North
   - Wicked Witch of the East
   - Good Witch of the South
   - Wicked Witch of the West

```
cd House/
touch Dorothy Toto
cd ..
mkdir Oz
cd Oz/
touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
```

---
## Ding! Dong! The Witch is Dead
1. Delete: "Wicked Witch of the East"
2. Move "Dorothy" from "House" to "Oz"

```
rm Wicked_Witch_of_the_East
mv ../House/Dorothy .
```

---
## Follow the Yellow Brick Road
1. Add file for "Scarecrow"
2. Add file for "Tin Man"
3. Add file for "Cowardly Lion"
4. Create directory "Emerald City"
5. Move 'the gang' to "Emerald City"

```
touch Scarecrow Tin_Man Cowardly_Lion
mkdir Emerald_City
mv Tin_Man Emerald_City/
mv Dorothy Emerald_City/
mv Cowardly_Lion Emerald_City/
mv Scarecrow Emerald_City/
```

---
## You Must Kill the Witch
1. Add "Flying Monkeys" to "Oz"
2. Remove "Wicked Witch of the West"
3. Give the gifts*
   1. Give Scarecrow a diploma
   2. Give Tin Man a heart shaped watch
   3. Give Lion a medal

```
touch Flying_Monkeys
rm *West*
echo "a diploma" >> Emerald_City/Scarecrow
echo "a heart shaped watch" >> Emerald_City/Tin_Man
echo "a medal" >> Emerald_City/Cowardly_Lion
```

full console log: [here](https://gist.github.com/rob-king/c62122464113554c32139f667c5f5b26)

**Comment by superbuggy** [comment]
💯  mad bonus points for the best formatted HW i've ever seen lol. mega bonus for gist. 

v 1337 pro 💯 💯 💯 a+
