### ISSUE TITLE
CLI HMW (Ba Phan)

### ISSUE THREAD

**Issue by BaVPhan** [ga-wdi-exercises/to_oz#151]
Ding! Dong! The Witch is Dead
1. $ rm 'Wicked Witch of the East'
2. 

Follow the Yellow Brick Road
1. $ mkdir The_Gang
$ cd The_Gang
$ touch Scarecrow
2. $ touch 'Tin Man'
3. $ touch 'Cowardly Lion'
4. $ cd ..
$ mkdir 'Emerald City'
5.

You Must Kill the Witch
1. $ cd Oz
$ touch 'Flying Monkey'
2. $ rm 'Wicked Witch of the West'
3i. $ cd ..
$ cd 'Emerald City'
$ echo "diploma" >> Scarecrow
3ii. $ echo "heart shaped watch" >> 'Tin Man'
3iii. $ echo "medal" >> 'Cowardly Lion'

**Comment by superbuggy** [comment]
You have to move the gang around as well using `mv`

**Comment by superbuggy** [comment]
👍  tho!
