### ISSUE TITLE
CLI HW (Nyketha Lyken)

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-exercises/to_oz#152]
$ mkdir House
  Mon Oct 03 21:21:10 ~
$ touch Dorothy Toto
  Mon Oct 03 21:22:04 ~
$ cd House
  Mon Oct 03 21:22:32 ~/House
$ ls
  Mon Oct 03 21:22:33 ~/House
$ touch Dorothy/House
touch: Dorothy/House: No such file or directory
  Mon Oct 03 21:26:07 ~/House
$ touch Dorothy .
  Mon Oct 03 21:26:28 ~/House
$ cd House
-bash: cd: House: No such file or directory
  Mon Oct 03 21:26:40 ~/House
$ cd House
-bash: cd: House: No such file or directory
  Mon Oct 03 21:27:33 ~/House
$ cd .
  Mon Oct 03 21:27:39 ~/House
$ ls
Dorothy
  Mon Oct 03 21:27:43 ~/House
$ touch Toto .
  Mon Oct 03 21:28:29 ~/House
$ cd .
  Mon Oct 03 21:28:37 ~/House
$ ls
Dorothy Toto
  Mon Oct 03 21:28:39 ~/House
$ cd ~
  Mon Oct 03 21:28:58 ~
$ mkdir Oz
  Mon Oct 03 21:29:23 ~
$ touch Good Witch of the North .
  Mon Oct 03 21:29:51 ~
$ touch Wicked Witch of the East .
  Mon Oct 03 21:30:15 ~
$ touch Good Witch of the South .
  Mon Oct 03 21:30:30 ~
$ touch Wicked Witch of the West .
  Mon Oct 03 21:30:40 ~
$ cd .
  Mon Oct 03 21:30:46 ~
$ ls
Applications    Fundamentals    North       West        of
Desktop     Good        Oz      Wicked      the
Documents   House       Pictures    Witch       wdi
Dorothy     Library     Public      World
Downloads   Movies      South       funny_things
East        Music       Toto        myhomework
  Mon Oct 03 21:30:48 ~
$ cd Oz
  Mon Oct 03 21:31:58 ~/Oz
$ ls
  Mon Oct 03 21:31:59 ~/Oz
$ touch GoodWitchoftheNorth .
  Mon Oct 03 21:32:36 ~/Oz
$ ls
GoodWitchoftheNorth
  Mon Oct 03 21:32:40 ~/Oz
$ cd Oz
-bash: cd: Oz: No such file or directory
  Mon Oct 03 21:32:51 ~/Oz
$ cd .
  Mon Oct 03 21:32:59 ~/Oz
$ ls
GoodWitchoftheNorth
  Mon Oct 03 21:33:01 ~/Oz
$ cd Oz
-bash: cd: Oz: No such file or directory
  Mon Oct 03 21:33:45 ~/Oz
$ touch WickedWitchoftheEast .
  Mon Oct 03 21:34:12 ~/Oz
$ touch GoodWitchoftheSouth .
  Mon Oct 03 21:34:25 ~/Oz
$ touch WickedWitchoftheWest .
  Mon Oct 03 21:34:41 ~/Oz
$ cd .
  Mon Oct 03 21:34:46 ~/Oz
$ ls
GoodWitchoftheNorth WickedWitchoftheEast
GoodWitchoftheSouth WickedWitchoftheWest
  Mon Oct 03 21:34:47 ~/Oz
$ rm WickedWitchoftheEast
  Mon Oct 03 21:35:18 ~/Oz
$ ls
GoodWitchoftheNorth GoodWitchoftheSouth WickedWitchoftheWest
  Mon Oct 03 21:35:21 ~/Oz
$ cd House
-bash: cd: House: No such file or directory
  Mon Oct 03 21:35:41 ~/Oz
$ cd ..
  Mon Oct 03 21:35:48 ~
$ ls
Applications    Fundamentals    North       West        of
Desktop     Good        Oz      Wicked      the
Documents   House       Pictures    Witch       wdi
Dorothy     Library     Public      World
Downloads   Movies      South       funny_things
East        Music       Toto        myhomework
  Mon Oct 03 21:35:49 ~
$ cd House
  Mon Oct 03 21:36:03 ~/House
$ ls
Dorothy Toto
  Mon Oct 03 21:36:07 ~/House
$ mv Dorothy Oz
  Mon Oct 03 21:36:33 ~/House
$ cd Oz
-bash: cd: Oz: Not a directory
  Mon Oct 03 21:36:40 ~/House
$ cd .
  Mon Oct 03 21:36:50 ~/House
$ ls
Oz  Toto
  Mon Oct 03 21:36:51 ~/House
$ cd Oz
-bash: cd: Oz: Not a directory
  Mon Oct 03 21:37:00 ~/House
$ mv Oz Dorothy
  Mon Oct 03 21:38:32 ~/House
$ ls
Dorothy Toto
  Mon Oct 03 21:38:36 ~/House
$ mv Dorothy > Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Mon Oct 03 21:38:54 ~/House
$ ls
Dorothy Oz  Toto
  Mon Oct 03 21:39:38 ~/House
$ rm Oz
  Mon Oct 03 21:39:59 ~/House
$ ls
Dorothy Toto
  Mon Oct 03 21:40:01 ~/House
$ mv Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Mon Oct 03 21:41:30 ~/House
$ cp Dorothy Oz
  Mon Oct 03 21:44:08 ~/House
$ cd .
  Mon Oct 03 21:44:13 ~/House
$ ls
Dorothy Oz  Toto
  Mon Oct 03 21:44:14 ~/House
$ rm Oz
  Mon Oct 03 21:44:58 ~/House
$ mv Dorothy cd Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Mon Oct 03 21:48:04 ~/House
$ mv Dorothy./Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Mon Oct 03 21:49:14 ~/House
$ mv Dorothy Oz/
mv: rename Dorothy to Oz/: No such file or directory
  Mon Oct 03 21:50:50 ~/House
$ mv Dorothy/House Oz
mv: rename Dorothy/House to Oz: Not a directory
  Mon Oct 03 21:53:41 ~/House
$ mv Dorothy/House/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Mon Oct 03 21:53:56 ~/House
$ mv Dorothy/House./Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Mon Oct 03 21:54:25 ~/House
$ cd ~
  Mon Oct 03 21:55:39 ~
$ ls
Applications    Fundamentals    North       West        of
Desktop     Good        Oz      Wicked      the
Documents   House       Pictures    Witch       wdi
Dorothy     Library     Public      World
Downloads   Movies      South       funny_things
East        Music       Toto        myhomework
  Mon Oct 03 21:55:42 ~
$ rm Good Witch of the South
  Mon Oct 03 21:56:07 ~
$ rm Wicked North East West Dorothy Toto
  Mon Oct 03 21:56:42 ~
$ ls
Applications    Fundamentals    Music       World
Desktop     House       Oz      funny_things
Documents   Library     Pictures    myhomework
Downloads   Movies      Public      wdi
  Mon Oct 03 21:56:45 ~
$ mv Dorothy/House Oz/
mv: rename Dorothy/House to Oz/House: No such file or directory
  Mon Oct 03 21:57:12 ~
$ mv Dorothy/House Oz
mv: rename Dorothy/House to Oz/House: No such file or directory
  Mon Oct 03 21:57:29 ~
$ mv Dorothy/House/~ Oz/~
mv: rename Dorothy/House/~ to Oz/~: No such file or directory
  Mon Oct 03 22:01:10 ~
$ touch Scarecrow
  Mon Oct 03 22:02:59 ~
$ touch TinMan
  Mon Oct 03 22:03:09 ~
$ touch Cowardly Lion
  Mon Oct 03 22:03:24 ~
$ mkdir Emerald_City
  Mon Oct 03 22:03:56 ~
$ mv Scarecrow .
mv: Scarecrow and ./Scarecrow are identical
  Mon Oct 03 22:04:16 ~
$ cd Emerald_City
  Mon Oct 03 22:05:22 ~/Emerald_City
$ mv Scarecrow .
mv: rename Scarecrow to ./Scarecrow: No such file or directory
  Mon Oct 03 22:05:37 ~/Emerald_City
$ cd ..
  Mon Oct 03 22:05:48 ~
$ ls
Applications    Emerald_City    Movies      Scarecrow   wdi
Cowardly    Fundamentals    Music       TinMan
Desktop     House       Oz      World
Documents   Library     Pictures    funny_things
Downloads   Lion        Public      myhomework
  Mon Oct 03 22:05:50 ~
$  mv Scarecrow /Emerald_City
mv: rename Scarecrow to /Emerald_City: Permission denied
  Mon Oct 03 22:07:49 ~
$ mv man
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Mon Oct 03 22:08:23 ~
$ mv Scarecrow ~/Emerald_City
  Mon Oct 03 22:11:38 ~
$ cd Emerald_City
  Mon Oct 03 22:11:52 ~/Emerald_City
$ ls
Scarecrow
  Mon Oct 03 22:11:54 ~/Emerald_City
$ cd ~
  Mon Oct 03 22:12:05 ~
$ mv TinMan ~/Emerald_City
  Mon Oct 03 22:12:39 ~
$ touch CowardLion
  Mon Oct 03 22:13:14 ~
$ rm Cowardly Lion CowardLion
  Mon Oct 03 22:13:41 ~
$ touch CowardlyLion
  Mon Oct 03 22:13:48 ~
$ mv CowardlyLion ~/Emerald_City
  Mon Oct 03 22:14:07 ~
$ cd Emerald_City
  Mon Oct 03 22:14:19 ~/Emerald_City
$ ls
CowardlyLion    Scarecrow   TinMan
  Mon Oct 03 22:14:20 ~/Emerald_City
$ cd ~
  Mon Oct 03 22:14:50 ~
$ mv Dorothy/House/~ ~/Oz
mv: rename Dorothy/House/~ to /Users/Nykke2/Oz/~: No such file or directory
  Mon Oct 03 22:15:19 ~
$ mv House/Dorthy ~/Oz
mv: rename House/Dorthy to /Users/Nykke2/Oz/Dorthy: No such file or directory
  Mon Oct 03 22:15:49 ~
$ cd Oz
  Mon Oct 03 22:16:46 ~/Oz
$ touch FlyingMonkeys
  Mon Oct 03 22:17:20 ~/Oz
$ rm WickedWitchoftheWest
  Mon Oct 03 22:17:33 ~/Oz
$ ls
FlyingMonkeys       GoodWitchoftheNorth GoodWitchoftheSouth
  Mon Oct 03 22:17:35 ~/Oz
$ cd ~
  Mon Oct 03 22:18:15 ~
$ mv ~/House/Dorothy ~/Oz
  Mon Oct 03 22:18:39 ~
$ cd Oz
  Mon Oct 03 22:18:47 ~/Oz
$ ls
Dorothy         GoodWitchoftheNorth
FlyingMonkeys       GoodWitchoftheSouth
  Mon Oct 03 22:18:48 ~/Oz
$ cd House
-bash: cd: House: No such file or directory
  Mon Oct 03 22:18:59 ~/Oz
$ ls
Dorothy         GoodWitchoftheNorth
FlyingMonkeys       GoodWitchoftheSouth
  Mon Oct 03 22:19:00 ~/Oz
$ cd .
  Mon Oct 03 22:19:09 ~/Oz
$ ls
Dorothy         GoodWitchoftheNorth
FlyingMonkeys       GoodWitchoftheSouth
  Mon Oct 03 22:19:12 ~/Oz
$ cd ...
-bash: cd: ...: No such file or directory
  Mon Oct 03 22:19:16 ~/Oz
$ cd ..
  Mon Oct 03 22:19:19 ~
$ ls
Applications    Emerald_City    Movies      Public      wdi
Desktop     Fundamentals    Music       World
Documents   House       Oz      funny_things
Downloads   Library     Pictures    myhomework
  Mon Oct 03 22:19:21 ~
$ cd House
  Mon Oct 03 22:19:28 ~/House
$ ls
Toto
  Mon Oct 03 22:19:29 ~/House
$ cd ~
  Mon Oct 03 22:19:33 ~
$ cd Oz
  Mon Oct 03 22:19:51 ~/Oz
$ Echo diploma > Scarecrow
  Mon Oct 03 22:21:34 ~/Oz
$ Echo heart shaped watch > TinMan
  Mon Oct 03 22:22:27 ~/Oz
$ Echo medal > Lion
  Mon Oct 03 22:22:39 ~/Oz
$

**Comment by superbuggy** [comment]
👍  Way to stick with this assignment! 
I think you figured this out but I just wanted to mention that: `touch Good Witch of the South` will create 5 directories, `Good`, `Witch`, `of`, `the`, and `South.
