### ISSUE TITLE
Diana's HW

### ISSUE THREAD

**Issue by dbgobar** [ga-wdi-exercises/to_oz#153]
$ mkdir house
$ touch Dorothy Toto House
$ mkdir Oz
$ touch good-witch-of-the-north.txt wicked-witch-of-the-east.txt good-witch-of-the-south.txt wicked-witch-of-the-west.txt
$ rm 'Wicked Witch of the East'
$ mv ../house/Dorothy ../Oz/Dorothy
$ cd Oz
$ touch Scarecrow.txt Tin-Man. txt Cowardly-Lion.txt
$ mv Scarecrow.txt Tin-Man.txt Cowardly-Lion.txt ./'Emerald City'
$ touch Flying-Monkeys.txt
$ rm wicked-witch-of-the-west.txt
$ echo 'diploma' > Scarecrow.txt
$ echo 'heart shaped watch' > Tin-Man.txt
$ echo 'medal' > Cowardly-Lion.txt

**Comment by andrewsunglaekim** [comment]
👍
