### ISSUE TITLE
CLI HW (Stefany)

### ISSUE THREAD

**Issue by StefKabatova** [ga-wdi-exercises/to_oz#154]
To Oz? To Oz!
1. $ mkdir House
2. $ cd House/ $ touch Dorothy.txt Toto.txt
3. $ cd .. $ mkdir Oz
4. $ cd Oz  $ touch Good\ Witch\ of\ the\ North.txt $ touch Wicked\ Witch\ of\ the\ East.txt $ touch Good\ Witch\ of\ the\ South.txt $ touch Wicked\ Witch\ of\ the\ West.txt

Ding! Dong! The Witch is Dead
1. $ rm Wicked\ Witch\ of\ the\ East.txt
2. $ cd .. $ cd House $ mv Dorothy.txt ../Oz

Follow the Yellow Brick Road
1. $cd .. $ touch Scarecrow.txt 
2. $ touch Tin\ Man.txt 
3. $ touch Cowardly\ Lion.txt
4. $ mkdir Emerald\ City
5. $ mv  touch Scarecrow.txt  Emerald\ City/  $ mv  Tin\ Man.txt  Emerald\ City/ $ mv Cowardly\ Lion.txt  Emerald\ City/

You Must Kill the Witch
1. $ cd Oz $ touch Flying\ Monkeys.txt 
2. rm Wicked\ Witch\ of\ the\ West.txt
3. $ echo diploma > Scarecrow.txt $ echo heart\ shaped\ watch > Tin\ Man.txt  $ echo medal > Cowardly\ Lion.txt

**Comment by superbuggy** [comment]
👍 

I think you have a stray `touch` below, but otherwise this looks good!

``` bash
$ mv touch Scarecrow.txt Emerald\ City/ $ mv Tin\ Man.txt Emerald\ City/ $ mv Cowardly\ Lion.txt Emerald\ City/
```
