### ISSUE TITLE
Juliet Berman's HW1

### ISSUE THREAD

**Issue by julietberman** [ga-wdi-exercises/to_oz#155]
Part 1:
mkdir House
touch House/Dorothy
touch House/Toto
mkdir Oz
cd Oz
touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" “Wicked Witch of the West"

Part 2:
rm “Wicked Witch of the East”
cd ../House
mv Dorothy ../Oz/

Part 3:
cd ..
touch "Scarecrow.txt” "Tin Man.txt” "Cowardly Lion.txt”
mkdir “Emerald City"
mv *.txt "Emerald City”/

Part 4:
touch Oz/"Flying Monkeys"
rm Oz/"Wicked Witch of the West"
cd "Emerald City"
echo "diploma" >> Scarecrow.txt
echo "a heart shaped watch" >> "Tin Man.txt"
echo "a medal” >> “Cowardly Lion.txt"

**Comment by andrewsunglaekim** [comment]
this looks great, I would consider removing white space from file names. When we move into more technologies, the different interfaces won't play well with white space in directories/files.

```
// Underscores(snake case)
$ touch Good_Witch_of_the_North

// Hyphens(spine case)
$ touch Good-Witch-of-the-North

// CamelCase
$ touch GoodWitchOfTheNorth
```

**Comment by andrewsunglaekim** [comment]
👍
