### ISSUE TITLE
Vanessa's HW

### ISSUE THREAD

**Issue by VanessaNya** [ga-wdi-exercises/to_oz#156]
vanessas-MacBook-Air:~ vanessanya$ mkdir House
vanessas-MacBook-Air:House vanessanya$ touch Dorothy.txt Toto.txt

vanessas-MacBook-Air:~ vanessanya$ mkdir Oz
vanessas-MacBook-Air:Oz vanessanya$ touch 'Good Witch of the North' 'Wicked Witch of the East' 'Good Witch of the South' 'Wicked Witch of the West'
vanessas-MacBook-Air:Oz vanessanya$ rm 'Wicked Witch of the East'

vanessas-MacBook-Air:House vanessanya$ mv Dorothy.txt ../Oz/
vanessas-MacBook-Air:Oz vanessanya$ touch 'scarecrow' 'Tin Man' ' Cowardly Lion'

vanessas-MacBook-Air:Emerald City vanessanya$ mkdir 'Emerald City'
vanessas-MacBook-Air:Emerald City vanessanya$ mv 'Scarecrow' 'Tin Man' 'Cowardly Lion' 'Dorothy.txt' 'Emerald City'/

vanessas-MacBook-Air:Emerald City vanessanya$ touch 'Flying Monkeys'
vanessas-MacBook-Air:OZ vanessanya$ rm 'Wicked Witch Of The West' 
vanessas-MacBook-Air:Emerald City vanessanya$ echo "a diploma" >> Scarecrow
vanessa-MacBook-Air:Emerald City vanessanya$ echo "heart shaped watch" >> Tinman
vanessas-MacBook-Air:Emerald City vanessanya$ echo "medal" >> 'Cowardly Lion' 
vanessas-MacBook-Air:Emerald City vanessanya$ open Cowardly\ Lion 
vanessas-MacBook-Air:Emerald City vanessanya$

**Comment by superbuggy** [comment]
nice work! 👍
