### ISSUE TITLE
To Oz? To Oz 

### ISSUE THREAD

**Issue by adriennedao** [ga-wdi-exercises/to_oz#157]
$ mkdir House
  Tue Oct 04 00:02:45 ~/House/Oz/Oz/Emerald/Oz
$ cd House
  Tue Oct 04 00:03:01 ~/House/Oz/Oz/Emerald/Oz/House
$ touch Dorothy and Toto
  Tue Oct 04 00:03:25 ~/House/Oz/Oz/Emerald/Oz/House
$ mkdir Oz
  Tue Oct 04 00:03:38 ~/House/Oz/Oz/Emerald/Oz/House
House
  Tue Oct 04 00:30:30 ~/House
$ ls -a
.   ..  House   Oz  Toto    and
  Tue Oct 04 00:30:36 ~/House
$ cd Oz
  Tue Oct 04 00:30:56 ~/House/Oz
$ ls
Good    North   Oz  South   West    Wicked
  Tue Oct 04 00:31:02 ~/House/Oz
$ ls Oz
City        Dorothy     Lion        Scarecrow   gang
Cowardly    Emerald     Man     Tin     the
  Tue Oct 04 00:31:17 ~/House/Oz
$ touch Good Witch of the North Wicked Witch of the East Good Witch of the South Wicked Witch of the West
  Tue Oct 04 00:32:43 ~/House/Oz
$ ls
East    North   South   Wicked  Witch   the
Good    Oz  West    Wiked   of
  Tue Oct 04 00:32:49 ~/House/Oz

Ding! Dong! The Witch is Dead

$ rm Wicked Witch of the East 
  Tue Oct 04 00:33:25 ~/House/Oz
$ mv Dorothy ../Oz
  Tue Oct 04 00:23:32 ~/House

Follow The Yellow Brick Road

$ touch Scarecrow.txt
  Tue Oct 04 00:38:55 ~/House/Oz
$ touch Tin Man.txt
  Tue Oct 04 00:39:27 ~/House/Oz
$ touch Cowardly Lion.txt
  Tue Oct 04 00:39:35 ~/House/Oz
$ cd Emerald City
-bash: cd: Emerald: No such file or directory
  Tue Oct 04 00:40:13 ~/House/Oz
$ cd Oz
  Tue Oct 04 00:40:44 ~/House/Oz/Oz
$ ls -a
.       Cowardly    Lion        Tin
..      Dorothy     Man     gang
City        Emerald     Scarecrow   the
  Tue Oct 04 00:40:49 ~/House/Oz/Oz
$ cd Emerald City
  Tue Oct 04 00:41:27 ~/House/Oz/Oz/Emerald
$ rm the gang
  Tue Oct 04 00:41:55 ~/House/Oz/Oz/Emerald
$ 

You Must Kill The Witch

$ cd Oz
  Tue Oct 04 00:43:53 ~/House/Oz/Oz/Emerald/Oz
$ touch Flying Monkeys 
  Tue Oct 04 00:44:10 ~/House/Oz/Oz/Emerald/Oz
$ cd Oz
  Tue Oct 04 00:47:45 ~/house/Oz
$ ls
Cowardly    Man.txt     Scarecrow.txt   West
Good        North       South       Wiked
Lion.txt    Oz      Tin
  Tue Oct 04 00:47:54 ~/house/Oz
$ ls 
Cowardly    Man.txt     Scarecrow.txt   West
Good        North       South       Wiked
Lion.txt    Oz      Tin
  Tue Oct 04 00:48:13 ~/house/Oz
$ rm Wicked Witched of the West

**Comment by andrewsunglaekim** [comment]
be careful with white space like in this example above:

```
$ touch Good Witch of the North Wicked Witch of the East Good Witch of the South Wicked Witch of the West
```

Because this will create a several files you didn't anticipate. How does the computer know which files are which? The right way to do this is use either underscores hyphens or camel casing:

```
// Underscores(snake case)
$ touch Good_Witch_of_the_North
// Hyphens(spine case)
$ touch Good-Witch-of-the-North
// CamelCase
$ touch GoodWitchOfTheNorth
```

**Comment by andrewsunglaekim** [comment]
👍
