### ISSUE TITLE
CLI HW Alex Wandres

### ISSUE THREAD

**Issue by awandres** [ga-wdi-exercises/to_oz#158]
$ pwd
/Users/Alex/wdi
  Tue Oct 04 07:54:49 ~/wdi
$ mkdir House
  Tue Oct 04 07:54:55 ~/wdi
$ pwd
/Users/Alex/wdi
  Tue Oct 04 07:54:57 ~/wdi
$ ls
House       Rakefile    exercises   installfest.yml lessons     projects    sandbox
  Tue Oct 04 07:55:01 ~/wdi
$ cd house
  Tue Oct 04 07:55:08 ~/wdi/house
$ touch dorothy
  Tue Oct 04 07:55:25 ~/wdi/house
$ touch toto
  Tue Oct 04 07:55:30 ~/wdi/house
$ ls
dorothy toto
  Tue Oct 04 07:55:31 ~/wdi/house
$ ..
-bash: ..: command not found
  Tue Oct 04 07:55:45 ~/wdi/house
$ ../
-bash: ../: is a directory
  Tue Oct 04 07:55:50 ~/wdi/house
$ pwd
/Users/Alex/wdi/house
  Tue Oct 04 07:55:54 ~/wdi/house
$ cd ..
  Tue Oct 04 07:55:57 ~/wdi
$ ls
House       Rakefile    exercises   installfest.yml lessons     projects    sandbox
  Tue Oct 04 07:55:59 ~/wdi
$ touch good_witch_of_the_north
  Tue Oct 04 07:56:24 ~/wdi
$ mkdir Oz
  Tue Oct 04 07:56:35 ~/wdi
$ cd Oz
  Tue Oct 04 07:56:37 ~/wdi/Oz
$ touch good_witch_of_the_north
  Tue Oct 04 07:56:51 ~/wdi/Oz
$ touch wicked_witch_of_the_east
  Tue Oct 04 07:57:04 ~/wdi/Oz
$ touch good_witch_of_the_south
  Tue Oct 04 07:57:11 ~/wdi/Oz
$ touch wicked_witch_of_the_west
  Tue Oct 04 07:57:19 ~/wdi/Oz
$ ls
good_witch_of_the_north     good_witch_of_the_south     wicked_witch_of_the_east    wicked_witch_of_the_west
  Tue Oct 04 07:57:29 ~/wdi/Oz
$ rm wicked_witch_of_the_east
  Tue Oct 04 07:57:49 ~/wdi/Oz
$ ls
good_witch_of_the_north     good_witch_of_the_south     wicked_witch_of_the_west
  Tue Oct 04 07:57:51 ~/wdi/Oz
$ mv dorothy house oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Oct 04 07:58:17 ~/wdi/Oz
$ ls
good_witch_of_the_north     good_witch_of_the_south     wicked_witch_of_the_west
  Tue Oct 04 07:58:24 ~/wdi/Oz
$ cd ..
  Tue Oct 04 07:58:31 ~/wdi
$ cd house
  Tue Oct 04 07:58:38 ~/wdi/house
$ ls
dorothy toto
  Tue Oct 04 07:58:38 ~/wdi/house
$ mv dorothy oz
  Tue Oct 04 07:58:47 ~/wdi/house
$ ls
oz  toto
  Tue Oct 04 07:58:50 ~/wdi/house
$ cd ../
  Tue Oct 04 07:59:42 ~/wdi
$ ls
House       Oz      Rakefile    exercises   installfest.yml lessons     projects    sandbox
  Tue Oct 04 07:59:44 ~/wdi
$ cd Oz
  Tue Oct 04 07:59:56 ~/wdi/Oz
$ ls
good_witch_of_the_north     good_witch_of_the_south     wicked_witch_of_the_west
  Tue Oct 04 07:59:58 ~/wdi/Oz
$ cd ../
  Tue Oct 04 08:01:44 ~/wdi
$ cd House
  Tue Oct 04 08:01:55 ~/wdi/House
$ ls
oz  toto
  Tue Oct 04 08:01:58 ~/wdi/House
$ rm oz
  Tue Oct 04 08:02:02 ~/wdi/House
$ touch dorothy
  Tue Oct 04 08:02:06 ~/wdi/House
$ ls
dorothy toto
  Tue Oct 04 08:02:07 ~/wdi/House
$ mv dorothy /Oz
mv: rename dorothy to /Oz: Permission denied
  Tue Oct 04 08:02:19 ~/wdi/House
$ sudo mv dorothy /Oz
Password:
  Tue Oct 04 08:02:37 ~/wdi/House
$ ls
toto
  Tue Oct 04 08:02:38 ~/wdi/House
$ cd ../
  Tue Oct 04 08:04:52 ~/wdi
$ cd Oz
  Tue Oct 04 08:04:59 ~/wdi/Oz
$ ls
good_witch_of_the_north     good_witch_of_the_south     wicked_witch_of_the_west
  Tue Oct 04 08:05:06 ~/wdi/Oz
$ mkdir Emerald_City
  Tue Oct 04 08:06:13 ~/wdi/Oz
$ cd Emerald_City
  Tue Oct 04 08:06:22 ~/wdi/Oz/Emerald_City
$ touch Scarecrow Tin_Man Cowardly_Lion
  Tue Oct 04 08:06:44 ~/wdi/Oz/Emerald_City
$ ls
Cowardly_Lion   Scarecrow   Tin_Man
  Tue Oct 04 08:06:47 ~/wdi/Oz/Emerald_City
$ cd ..
  Tue Oct 04 08:07:02 ~/wdi/Oz
$ touch Flying_Monkeys
  Tue Oct 04 08:07:19 ~/wdi/Oz
$ cd Emerald_City
  Tue Oct 04 08:11:25 ~/wdi/Oz/Emerald_City
$ echo diploma >> Scarecrow
  Tue Oct 04 08:11:47 ~/wdi/Oz/Emerald_City
$ echo heart_shaped_watch >> Tin_Man
  Tue Oct 04 08:12:01 ~/wdi/Oz/Emerald_City
$ echo medal >> Lion
  Tue Oct 04 08:12:14 ~/wdi/Oz/Emerald_City
$ ls
Cowardly_Lion   Lion        Scarecrow   Tin_Man
  Tue Oct 04 08:12:16 ~/wdi/Oz/Emerald_City
$

**Comment by nayana487** [comment]
👍
