### ISSUE TITLE
Kevin Keller CR5 - To Oz

### ISSUE THREAD

**Issue by kkeller93** [ga-wdi-exercises/to_oz#159]
$ mkdir House
$ cd House
$ mkdir 'Dorthy' 'Toto'
$ mkdir ../Oz
$ cd ../Oz
$ mkdir 'GoodWitchOfTheNorth' 'WickedWitchOfTheEast' 'GoodWitchOfTheSouth' 'WickedWitchOfTheWest'
$ rmdir WickedWitchOfTheEast
$ cd ../House
$ mv Dorthy ~/
$ cd ..
$ mv Dorthy Oz/
$ cd ..
$ touch 'Scarecrow' 'TinMan' 'CowardlyLion'
$ mkdir 'EmeraldCity'
$ mv 'Scarecrow' 'TinMan' 'CowardlyLion' EmeraldCity/
$ cd ../Oz
$ touch 'FlyingMonkeys'
$ rmdir WickedWitchOfTheWest
$ cd ../EmeraldCity
$ echo "diploma” >> Scarecrow
$ echo "heart shaped watch" >> TinMan
$ echo "medal" >> CowardlyLion

Comfort: 5
Completeness: 5

**Comment by phantomhaircuts** [comment]
👍
