### ISSUE TITLE
Keith's: Day 1 HW

### ISSUE THREAD

**Issue by khenry10** [ga-wdi-exercises/to_oz#16]
$ mkdir House
$ cd House/
$ touch Dorothy Toto
$ cd ..
$ mkdir Oz
$ cd Oz
$ touch Good_Witch_of_the_North Good_Witch_of_the_South Wicked_Witch_of_the_East Wicked_Witch_of_the_West
$ ls
$ rm Wicked_Witch_of_the_East
$ cd ..
$ cd House
$ mv Dorothy ~/Oz
$ touch Scarecrow 
$ touch Tin_Man 
$ touch Cowardly_Lion 
$ mkdir Emerald_City
$ mv Scarecrow ~/Emerald_City
$ mv Tin_Man ~/Emerald_City
$ mv Cowardly_Lion ~/Emerald_City
$ touch Flying_Monkey
$ rm Wicked_Witch_of_the_West
$ echo "a diploma" >> Scarecrow
$ echo "a tin shaped heart" >> Tin_Man
$ echo "a medal" >> Lion

**Comment by RobertAKARobin** [comment]
Nice!
