### ISSUE TITLE
Benjamin Shapiro - To Oz

### ISSUE THREAD

**Issue by pretorben** [ga-wdi-exercises/to_oz#160]
Tue Jan 17 17:04:25 ~
$ mkdir House
  Tue Jan 17 17:04:30 ~
$ cd House
  Tue Jan 17 17:04:38 ~/House
$ touch Dorothy Toto
  Tue Jan 17 17:04:46 ~/House
$ mkdir Oz
  Tue Jan 17 17:04:51 ~/House
$ cd Oz
  Tue Jan 17 17:04:53 ~/House/Oz
$ touch 'Good Witch of the North' 'Wicked Witch of the East' 'Good Witch of the South' 'Wicked Witch of the West'
  Tue Jan 17 17:05:12 ~/House/Oz
$ rm 'Wicked Witch of the East'
  Tue Jan 17 17:05:29 ~/House/Oz
$ mv ../Dorothy Dorothy
  Tue Jan 17 17:05:50 ~/House/Oz
$ touch Scarecrow 'Tin Man' 'Cowardly Lion'
  Tue Jan 17 17:07:08 ~/House/Oz
$ mkdir 'Emerald City'
  Tue Jan 17 17:07:20 ~/House/Oz
$ mv Scarecrow Emerald City
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 17:07:31 ~/House/Oz
$ mv Scarecrow 'Emerald City'
  Tue Jan 17 17:07:37 ~/House/Oz
$ mv 'Tin Man' 'Emerald City'
  Tue Jan 17 17:07:46 ~/House/Oz
$ mv 'Cowardly Lion' 'Emerald City'
  Tue Jan 17 17:07:58 ~/House/Oz
$ touch 'Flying Monkeys'
  Tue Jan 17 17:08:28 ~/House/Oz
$ rm 'Wicked Witch of the West'
  Tue Jan 17 17:08:36 ~/House/Oz
$ cd 'Emerald City'
  Tue Jan 17 17:09:15 ~/House/Oz/Emerald City
$ echo 'a diploma' >> Scarecrow
  Tue Jan 17 17:09:40 ~/House/Oz/Emerald City
$ echo 'a heart shaped watch' >> Tin Man
  Tue Jan 17 17:09:54 ~/House/Oz/Emerald City
$ echo 'a medal' >> Cowardly Lion
  Tue Jan 17 17:10:15 ~/House/Oz/Emerald City
$ echo 'a heart shaped watch' >> 'Tin Man'
  Tue Jan 17 17:11:31 ~/House/Oz/Emerald City
$ echo 'a medal' >> 'Cowardly Lion'

**Comment by superbuggy** [comment]
nice work!
