### ISSUE TITLE
Jay HW

### ISSUE THREAD

**Issue by xgironx** [ga-wdi-exercises/to_oz#161]
213  mkdir -p Oz
  214  touch Oz/{'Good Witch of the North','Wicked Witch of the East','Good Witch of the South','Wicked Witch of the West'}
  215  ls -la Oz
  216  rm Oz/Wicked\ Witch\ of\ the\ East 
  217  mv House/Dorothy/ Oz/
  218  ls Oz
  219  touch {Scarecrow,'Tin Man','Cowardly Lion'}
  220  ls
  221  ls -ltrh
  222  mkdir -p 'Emerald City'
  223  mv {Tin*,Scar*,Cow*} Emerald\ City/
  224  ls
  225  cd Emerald\ City/
  226  ls
  227  touch Oz/'Flying Monkeys' 
  228  ls
  229  pwd
  230  touch ../Oz/'Flying Monkeys' 
  231  rm ../Oz/Wicked\ Witch\ of\ the\ West 
  232  pwd
  233  echo 'diploma' > Scarecrow 
  234  echo 'heart shaped watch' > Tin\ Man 
  235  echo 'a medal' > Cowardly\ Lion 
  236  ls -la
  237  cat *
  238  history
  Tue Jan 17 17:13:57 ~/Dropbox/3/x/wdi_on_dropbox/201701171656L_cli_intro/Emerald City
$

**Comment by superbuggy** [comment]
```
223 mv {Tin*,Scar*,Cow*} Emerald\ City/
```
NICE Jay 👍
