### ISSUE TITLE
CLI HW (Justin Shin)

### ISSUE THREAD

**Issue by Justin-Shin** [ga-wdi-exercises/to_oz#162]
$ mkdir House
$ touch House/Dorothy House/Toto
$ mkdir Oz
$ cd Oz
$ touch 'Good Witch of the North' 'Wicked Witch of the East' 'Good Witch of the South' 'Wicked Witch of the West'
$ rm 'Wicked Witch of the East'
$ mv ../House/Dorothy .
$ touch Scarecrow 'Tin Man' 'Cowardly Lion'
$ mkdir 'Emerald City'
$ mv Dorothy 'Emerald City'
$ mv Scarecrow 'Emerald City'
$ mv 'Tin Man' 'Emerald City'
$ mv 'Cowardly Lion' 'Emerald City'
$ touch 'Flying Monkeys'
$ rm 'Wicked Witch of the West'
$ cd 'Emerald City'
$ echo 'diploma' >> Scarecrow
$ echo 'heart shaped watch' >> 'Tin Man'
$ echo 'medal' >> 'Cowardly Lion'

Comfort: 5
Completeness: 5

I had an initial issue with creating the witches. For some reason touch would create each individual word with the quotes attached to it, for example there would be a ('Wicked) file.  It's because I was stupid and wrote it in a text editor, and there was formatting, so the single quote was not a single quote.  Moved it to sublime and rewrote the commands and everything ran smoothly.

**Comment by superbuggy** [comment]
Right on! Nice work Justin!
