### ISSUE TITLE
"To Oz" HW - Erica Norby

### ISSUE THREAD

**Issue by ericanorby** [ga-wdi-exercises/to_oz#164]
$ mkdir House
$ cd House
$ touch Dorothy.txt Toto.txt
$ cd ..
$ mkdir Oz
$ cd Oz
$ touch Good_Witch_of_the_North.txt Wicked_Witch_of_the_East.txt Good_Witch_of_the_South.txt Wicked_Witch_of_the_West.txt

$ rm Wicked_Witch_of_the_East.txt
$ mv ~/House/Dorothy.txt ~/Oz

$ touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt
$ mkdir Emerald_City
$ mv ~/Oz/Scarecrow.txt ~/Oz/Emerald_City
$ mv ~/Oz/Tin_Man.txt ~/Oz/Emerald_City
$ mv ~/Oz/Cowardly_Lion.txt ~/Oz/Emerald_City

$ touch Flying_Monkeys.txt
$ rm Wicked_Witch_of_the_West.txt
$ echo "diploma" >> Scarecrow.txt
$ echo "heart shaped watch" >> Tin_Man.txt
$ echo "medal" >> Cowardly_Lion.txt

**Comment by phantomhaircuts** [comment]
👍
