### ISSUE TITLE
CLI HW #1 Dominick Houston wizard_of_oz

### ISSUE THREAD

**Issue by dhouston14** [ga-wdi-exercises/to_oz#165]
cd
Mkdir House
Cd House
Touch Dorothy Toto
Cd ..
Mkdir Oz
Cd Oz
Touch Good Witch of the North
Touch  Wicked Witch of the East
Touch Good Witch of the South
Touch Wicked Witch of the West

Cd
Cd Oz
Rm “Wicked Witch of the East”
Cp -r House ~/wdi/myHomework/
mv ~/House/Dorothy ~/wdi/myHomework/Oz

Mkdir “Emerald City”
Touch “Scarecrow”
Touch “Tin Man”
Touch “Cowardly Lion”

mv ~/wdi/myHomework/wizard_of_oz/Scarecrow ~/wdi/myHomework/wizard_of_oz/"Emerald City"/
mv ~/wdi/myHomework/wizard_of_oz/“Tin Man” ~/wdi/myHomework/wizard_of_oz/"Emerald City"/
mv ~/wdi/myHomework/wizard_of_oz/“Cowardly Lion” ~/wdi/myHomework/wizard_of_oz/"Emerald City"/

touch "Flying Monkeys"
Rm “Wicked Witch of the West”
echo "Diploma" > Scarecrow
cat Scarecrow
echo "A heart shaped watch" > "Tin Man"
cat "Tin Man"
echo "A medal" > "Cowardly Lion"
cat "Cowardly Lion"

**Comment by phantomhaircuts** [comment]
👍
