### ISSUE TITLE
Collin OConnell HW

### ISSUE THREAD

**Issue by cMoney667** [ga-wdi-exercises/to_oz#167]
mkdir House
touch House/Dorothy.txt
touch House/Toto.txt
mkdir Oz
touch Oz/Good_Witch_of_the_North.txt Oz/Wicked_Witch_of_the_East.txt Oz/Good_Witch_of_the_South.txt Oz/Wicked_Witch_of_the_West.txt
cd Oz
rm Wicked_Witch_of_the_East.txt
mv ../House/Dorothy.txt
touch Scarecrow.txt Tin_man.txt Cowardly_Lion.txt
mkdir EmeraldCity
mv Cowardly_Lion.txt Dorothy.txt Scarecrow.txt Tin_man.txt EmeraldCity/
touch Flying_Monkeys.txt
rm Wicked_Witch_of_the_West.txt
cd EmeraldCity/
echo "Diploma" >> Scarecrow.txt
echo "Heart Shaped Watch" >> Tin_man.txt
echo "Medal" >> Cowardly_Lion.txt

**Comment by phantomhaircuts** [comment]
👍
