### ISSUE TITLE
Rob's Day 1 HW

### ISSUE THREAD

**Issue by Robizzy27** [ga-wdi-exercises/to_oz#17]
Last login: Mon Feb  8 15:56:08 on ttys000
~ (master #) 
$ cd ga
~/ga (master #) 
$ ls
About.html  Style.css   fundamentals
Excercises  WDI     index.html
~/ga (master #) 
$ cd wdi
~/ga/wdi (master #) 
$ ls
exercises   lessons     projects    sandbox
~/ga/wdi (master #) 
$ cd exercises
~/ga/wdi/exercises (master #) 
$ ls
~/ga/wdi/exercises (master #) 
$ mkdir house
~/ga/wdi/exercises (master #) 
$ cd house
~/ga/wdi/exercises/house (master #) 
$ touch Dorothy Toto
~/ga/wdi/exercises/house (master #) 
$ ls
Dorothy Toto
~/ga/wdi/exercises/house (master #) 
$ ls -l
total 0
-rw-r--r--  1 Enterprise  staff  0 Feb  8 21:12 Dorothy
-rw-r--r--  1 Enterprise  staff  0 Feb  8 21:12 Toto
~/ga/wdi/exercises/house (master #) 
$ ..
-bash: ..: command not found
~/ga/wdi/exercises/house (master #) 
$ cd ..
~/ga/wdi/exercises (master #) 
$ ls
house
~/ga/wdi/exercises (master #) 
$ mkdir Oz
~/ga/wdi/exercises (master #) 
$ cd oz
~/ga/wdi/exercises/oz (master #) 
$ touch Good Witch of the East
~/ga/wdi/exercises/oz (master #) 
$ ls
East    Good    Witch   of  the
~/ga/wdi/exercises/oz (master #) 
$ rm East
~/ga/wdi/exercises/oz (master #) 
$ rm Good
~/ga/wdi/exercises/oz (master #) 
$ rm Witch
~/ga/wdi/exercises/oz (master #) 
$ rm of
~/ga/wdi/exercises/oz (master #) 
$ rm the
~/ga/wdi/exercises/oz (master #) 
$ ls
~/ga/wdi/exercises/oz (master #) 
$ touch Good_Witch_of_the_East Wicked_Witch_of_the_North Good_Witch_of_the_South Wicked_Witch_of_the_West
~/ga/wdi/exercises/oz (master #) 
$ ls
Good_Witch_of_the_East      Wicked_Witch_of_the_North
Good_Witch_of_the_South     Wicked_Witch_of_the_West
~/ga/wdi/exercises/oz (master #) 
$ rm Wicked_Witch_of_the_East
rm: Wicked_Witch_of_the_East: No such file or directory
~/ga/wdi/exercises/oz (master #) 
$ mv Good_Witch_of_the_East Wicked_Witch_of_the_East
~/ga/wdi/exercises/oz (master #) 
$ mv Wicked_Witch_of_the_North Good_Witch_of_the_North
~/ga/wdi/exercises/oz (master #) 
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_East
Good_Witch_of_the_South     Wicked_Witch_of_the_West
~/ga/wdi/exercises/oz (master #) 
$ rm Wicked_Witch_of_the_East
~/ga/wdi/exercises/oz (master #) 
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
~/ga/wdi/exercises/oz (master #) 
$ cd ..
~/ga/wdi/exercises (master #) 
$ ls
Oz  house
~/ga/wdi/exercises (master #) 
$ cd house
~/ga/wdi/exercises/house (master #) 
$ ls
Dorothy Toto
~/ga/wdi/exercises/house (master #) 
$ mv Dorothy ../Oz/Dorothy
~/ga/wdi/exercises/house (master #) 
$ ls
Toto
~/ga/wdi/exercises/house (master #) 
$ cd ..
~/ga/wdi/exercises (master #) 
$ ls
Oz  house
~/ga/wdi/exercises (master #) 
$ cd os
-bash: cd: os: No such file or directory
~/ga/wdi/exercises (master #) 
$ cd oz
~/ga/wdi/exercises/oz (master #) 
$ ls
Dorothy             Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
~/ga/wdi/exercises/oz (master #) 
$ touch Scarecrow Tin_Man Cowardly_Lion
~/ga/wdi/exercises/oz (master #) 
$ mkdir Emerald_City
~/ga/wdi/exercises/oz (master #) 
$ ls
Cowardly_Lion           Good_Witch_of_the_South
Dorothy             Scarecrow
Emerald_City            Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_the_West
~/ga/wdi/exercises/oz (master #) 
$ cd Emerald_City/
~/ga/wdi/exercises/oz/Emerald_City (master #) 
$ l
-bash: l: command not found
~/ga/wdi/exercises/oz/Emerald_City (master #) 
$ ls
~/ga/wdi/exercises/oz/Emerald_City (master #) 
$ cd ..
~/ga/wdi/exercises/oz (master #) 
$ ls
Cowardly_Lion           Good_Witch_of_the_South
Dorothy             Scarecrow
Emerald_City            Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_the_West
~/ga/wdi/exercises/oz (master #) 
$ mv Cowardly_Lion /Emerald_City/Cowardly_Lion
mv: rename Cowardly_Lion to /Emerald_City/Cowardly_Lion: No such file or directory
~/ga/wdi/exercises/oz (master #) 
$ mv Cowardly_Lion Emerald_City/Cowardly_Lion
~/ga/wdi/exercises/oz (master #) 
$ ls
Dorothy             Scarecrow
Emerald_City            Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
~/ga/wdi/exercises/oz (master #) 
$ cd Emerald_City/
~/ga/wdi/exercises/oz/Emerald_City (master #) 
$ ls
Cowardly_Lion
~/ga/wdi/exercises/oz/Emerald_City (master #) 
$ cd ..
~/ga/wdi/exercises/oz (master #) 
$ mv Scarecrow Emerald_City/Scarecrow
~/ga/wdi/exercises/oz (master #) 
$ mv Tin_Man Emerald_City/Tin_Man
~/ga/wdi/exercises/oz (master #) 
$ cd Emerald_City/
~/ga/wdi/exercises/oz/Emerald_City (master #) 
$ ls
Cowardly_Lion   Scarecrow   Tin_Man
~/ga/wdi/exercises/oz/Emerald_City (master #) 
$ cd ..
~/ga/wdi/exercises/oz (master #) 
$ touch Flying_Monkeys
~/ga/wdi/exercises/oz (master #) 
$ ls
Dorothy             Good_Witch_of_the_North
Emerald_City            Good_Witch_of_the_South
Flying_Monkeys          Wicked_Witch_of_the_West
~/ga/wdi/exercises/oz (master #) 
$ rm Wicked_Witch_of_the_West
~/ga/wdi/exercises/oz (master #) 
$ ls
Dorothy         Flying_Monkeys      Good_Witch_of_the_South
Emerald_City        Good_Witch_of_the_North
~/ga/wdi/exercises/oz (master #) 
$ echo "a.diploma" >> Oz/Scarecrow
-bash: Oz/Scarecrow: No such file or directory
~/ga/wdi/exercises/oz (master #) 
$ echo "a.diploma" >> Scarecrow
~/ga/wdi/exercises/oz (master #) 
$ echo "a.heart_shaped_watch" >> Tin_Man
~/ga/wdi/exercises/oz (master #) 
$ echo "a.medal" >> Cowardly_Lion
~/ga/wdi/exercises/oz (master #) 
$

**Comment by RobertAKARobin** [comment]
Nice job!
