### ISSUE TITLE
Nyketha's Oz homework

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-exercises/to_oz#170]
Level of Completeness : 5
Level of Understanding: 4
message: a little rusty on CL, but look it took a shorter amount of time to complete this homework than the last time! like an hour shorter!

$ cd ~
  Tue Jan 17 16:51:12 ~
$ cdls
Applications	Downloads	Movies		Public		github
Desktop		Fundamentals	Music		WDI13		myHomeWork
Documents	Library		Pictures	WDI14		myPortfolio
  Tue Jan 17 16:51:15 ~
$ cdls myHomeWork/
  Tue Jan 17 16:51:29 ~/myHomeWork (master #)
$ mkdir House
  Tue Jan 17 16:51:35 ~/myHomeWork (master #)
$ cd House
  Tue Jan 17 16:51:53 ~/myHomeWork/House (master #)
$ touch Dorothy Toto 
  Tue Jan 17 16:52:01 ~/myHomeWork/House (master #)
$ cd ../
  Tue Jan 17 16:52:25 ~/myHomeWork (master #)
$ ls
House
  Tue Jan 17 16:52:27 ~/myHomeWork (master #)
$ mkdir Oz
  Tue Jan 17 16:52:42 ~/myHomeWork (master #)
$ touch GoodWitchoftheNorth WickedWitchoftheEast GoodWitchoftheSouth WickedWitchoftheWest
  Tue Jan 17 16:53:21 ~/myHomeWork (master #)
$ cdls Oz
  Tue Jan 17 16:53:45 ~/myHomeWork/Oz (master #)
$ cdls ../
GoodWitchoftheNorth	House			WickedWitchoftheEast
GoodWitchoftheSouth	Oz			WickedWitchoftheWest
  Tue Jan 17 16:53:59 ~/myHomeWork (master #)
$ mv GoodWitchoftheNorth/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 16:54:59 ~/myHomeWork (master #)
$ mv ../GoodWitchoftheNorth/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 16:55:48 ~/myHomeWork (master #)
$ mv GoodWitchoftheNorth Oz/
  Tue Jan 17 16:56:21 ~/myHomeWork (master #)
$ cdls Oz
GoodWitchoftheNorth
  Tue Jan 17 16:56:31 ~/myHomeWork/Oz (master #)
$ mv WickedWitchoftheEast GoodWitchoftheSouth WickedWitchoftheWest Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 16:57:15 ~/myHomeWork/Oz (master #)
$ mv WickedWitchoftheEast GoodWitchoftheSouth WickedWitchoftheWest Oz/
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 16:57:34 ~/myHomeWork/Oz (master #)
$ mv WickedWitchoftheEast oz/
mv: rename WickedWitchoftheEast to oz/: No such file or directory
  Tue Jan 17 16:57:49 ~/myHomeWork/Oz (master #)
$ cd ..
  Tue Jan 17 16:57:54 ~/myHomeWork (master #)
$ ls
GoodWitchoftheSouth	House			Oz			WickedWitchoftheEast	WickedWitchoftheWest
  Tue Jan 17 16:57:58 ~/myHomeWork (master #)
$ mv WickedWitchoftheEast GoodWitchoftheSouth WickedWitchoftheWest Oz/
  Tue Jan 17 16:58:11 ~/myHomeWork (master #)
$ cdls Oz
GoodWitchoftheNorth	GoodWitchoftheSouth	WickedWitchoftheEast	WickedWitchoftheWest
  Tue Jan 17 16:58:21 ~/myHomeWork/Oz (master #)
$ rm WickedWitchoftheEast
  Tue Jan 17 16:58:57 ~/myHomeWork/Oz (master #)
$ cd ..
  Tue Jan 17 16:59:05 ~/myHomeWork (master #)
$ ls
House	Oz
  Tue Jan 17 16:59:08 ~/myHomeWork (master #)
$ mv Dorothy Oz
mv: rename Dorothy to Oz/Dorothy: No such file or directory
  Tue Jan 17 16:59:31 ~/myHomeWork (master #)
$ cd House
  Tue Jan 17 16:59:48 ~/myHomeWork/House (master #)
$ mv Dorothy/../Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 17:00:06 ~/myHomeWork/House (master #)
$ mv Dorothy/..
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 17:00:22 ~/myHomeWork/House (master #)
$ mv Dorothy/../
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 17:00:57 ~/myHomeWork/House (master #)
$ mv Dorothy/../Oz/
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 17:01:09 ~/myHomeWork/House (master #)
$ cd House
-bash: cd: House: No such file or directory
  Tue Jan 17 17:01:48 ~/myHomeWork/House (master #)
$ ls
Dorothy	Toto
  Tue Jan 17 17:01:57 ~/myHomeWork/House (master #)
$ mv Dorothy Oz
  Tue Jan 17 17:02:32 ~/myHomeWork/House (master #)
$ cd Oz
-bash: cd: Oz: Not a directory
  Tue Jan 17 17:02:38 ~/myHomeWork/House (master #)
$ ls
Oz	Toto
  Tue Jan 17 17:02:46 ~/myHomeWork/House (master #)
$ cd Oz
-bash: cd: Oz: Not a directory
  Tue Jan 17 17:03:08 ~/myHomeWork/House (master #)
$ mv Oz Dorothy
  Tue Jan 17 17:03:19 ~/myHomeWork/House (master #)
$ ls
Dorothy	Toto
  Tue Jan 17 17:03:22 ~/myHomeWork/House (master #)
$ mv Dorothy oz/
mv: rename Dorothy to oz/: No such file or directory
  Tue Jan 17 17:03:38 ~/myHomeWork/House (master #)
$ cd ../Oz/Dorothy
-bash: cd: ../Oz/Dorothy: No such file or directory
  Tue Jan 17 17:04:46 ~/myHomeWork/House (master #)
$ mv Dorothy cd ../Oz
mv: rename cd to ../Oz/cd: No such file or directory
  Tue Jan 17 17:05:17 ~/myHomeWork/House (master #)
$ mv Dorothy/House/../Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 17:05:56 ~/myHomeWork/House (master #)
$ cd Oz
-bash: cd: Oz: No such file or directory
  Tue Jan 17 17:06:41 ~/myHomeWork/House (master #)
$ ls
Toto
  Tue Jan 17 17:06:46 ~/myHomeWork/House (master #)
$ cd ..
  Tue Jan 17 17:06:49 ~/myHomeWork (master #)
$ ls
House	Oz
  Tue Jan 17 17:06:50 ~/myHomeWork (master #)
$ cd Oz
  Tue Jan 17 17:06:53 ~/myHomeWork/Oz (master #)
$ touch Scarecrow Tinman CowardlyLion 
  Tue Jan 17 17:07:13 ~/myHomeWork/Oz (master #)
$ cd ..
  Tue Jan 17 17:07:21 ~/myHomeWork (master #)
$ ls
House	Oz
  Tue Jan 17 17:07:22 ~/myHomeWork (master #)
$ mkdir Emerald_City
  Tue Jan 17 17:07:35 ~/myHomeWork (master #)
$ mv Scarecrow Emerald_City/
mv: rename Scarecrow to Emerald_City/Scarecrow: No such file or directory
  Tue Jan 17 17:08:09 ~/myHomeWork (master #)
$ ls
Emerald_City	House		Oz
  Tue Jan 17 17:08:19 ~/myHomeWork (master #)
$ mv scarecrow/..
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 17:09:19 ~/myHomeWork (master #)
$ cd Oz
  Tue Jan 17 17:09:55 ~/myHomeWork/Oz (master #)
$ rm WickedWitchoftheWest
  Tue Jan 17 17:10:12 ~/myHomeWork/Oz (master #)
$ mv scarecrow/../../Emerald_city
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 17:13:04 ~/myHomeWork/Oz (master #)
$ mv scarecrow/../../Emerald_city/
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 17:13:11 ~/myHomeWork/Oz (master #)
$ mv scarecrow/../Emerald_city
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 17:13:48 ~/myHomeWork/Oz (master #)
$ ls
CowardlyLion		GoodWitchoftheNorth	Scarecrow
Dorothy			GoodWitchoftheSouth	Tinman
  Tue Jan 17 20:31:35 ~/myHomeWork/Oz (master #)
$ mv Dorothy ../Oz
mv: Dorothy and ../Oz/Dorothy are identical
  Tue Jan 17 20:32:14 ~/myHomeWork/Oz (master #)
$ pwd
/Users/Nykke2/myHomeWork/Oz
  Tue Jan 17 20:33:47 ~/myHomeWork/Oz (master #)
$ mv scarecrow ../Oz
mv: scarecrow and ../Oz/scarecrow are identical
  Tue Jan 17 20:34:57 ~/myHomeWork/Oz (master #)
$ mv scarecrow ../Emerald_city
  Tue Jan 17 20:35:15 ~/myHomeWork/Oz (master #)
$ mv GoodwitchoftheNorth ../Emerald_city
  Tue Jan 17 20:35:40 ~/myHomeWork/Oz (master #)
$ mv GoodwitchoftheNorth ../Oz
mv: rename GoodwitchoftheNorth to ../Oz/GoodwitchoftheNorth: No such file or directory
  Tue Jan 17 20:36:07 ~/myHomeWork/Oz (master #)
$ mv tinman ../Emerald_city
  Tue Jan 17 20:36:35 ~/myHomeWork/Oz (master #)
$ mv cowardlylion ../Emerald_city
  Tue Jan 17 20:36:53 ~/myHomeWork/Oz (master #)
$ ls
Dorothy			GoodWitchoftheSouth
  Tue Jan 17 20:37:43 ~/myHomeWork/Oz (master #)
$ cd Emerald_city
-bash: cd: Emerald_city: No such file or directory
  Tue Jan 17 20:38:27 ~/myHomeWork/Oz (master #)
$ pwd
/Users/Nykke2/myHomeWork/Oz
  Tue Jan 17 20:38:36 ~/myHomeWork/Oz (master #)
$ cd ..
  Tue Jan 17 20:38:39 ~/myHomeWork (master #)
$ ls
Emerald_City	House		Oz
  Tue Jan 17 20:38:41 ~/myHomeWork (master #)
$ cd Emerald_City
  Tue Jan 17 20:38:53 ~/myHomeWork/Emerald_City (master #)
$ mv GoodwitchoftheNorth ../Oz
  Tue Jan 17 20:39:07 ~/myHomeWork/Emerald_City (master #)
$ cdls oz
-bash: cd: oz: No such file or directory
  Tue Jan 17 20:39:15 ~/myHomeWork/Emerald_City (master #)
$ pwd
/Users/Nykke2/myHomeWork/Emerald_City
  Tue Jan 17 20:39:18 ~/myHomeWork/Emerald_City (master #)
$ cd ..
  Tue Jan 17 20:39:21 ~/myHomeWork (master #)
$ cdls oz
Dorothy			GoodWitchoftheSouth	GoodwitchoftheNorth
  Tue Jan 17 20:39:31 ~/myHomeWork/oz (master #)
$ pwd
/Users/Nykke2/myHomeWork/oz
  Tue Jan 17 20:39:45 ~/myHomeWork/oz (master #)
$ touch Flying_Monkeys
  Tue Jan 17 20:40:10 ~/myHomeWork/oz (master #)
$ ls
Dorothy			GoodWitchoftheSouth
Flying_Monkeys		GoodwitchoftheNorth
  Tue Jan 17 20:40:26 ~/myHomeWork/oz (master #)
$ cd ..
  Tue Jan 17 20:40:34 ~/myHomeWork (master #)
$ ls
Emerald_City	House		Oz
  Tue Jan 17 20:40:35 ~/myHomeWork (master #)
$ cd Emerald_City
  Tue Jan 17 20:40:44 ~/myHomeWork/Emerald_City (master #)
$ ls
cowardlylion	scarecrow	tinman
  Tue Jan 17 20:40:45 ~/myHomeWork/Emerald_City (master #)
$ open scarecrow
  Tue Jan 17 20:44:44 ~/myHomeWork/Emerald_City (master #)
$ cd scarecrow
-bash: cd: scarecrow: Not a directory
  Tue Jan 17 20:45:30 ~/myHomeWork/Emerald_City (master #)
$ echo diploma scarecrow
diploma scarecrow
  Tue Jan 17 20:45:49 ~/myHomeWork/Emerald_City (master #)
$ open scarecrow
  Tue Jan 17 20:46:00 ~/myHomeWork/Emerald_City (master #)
$ echo diploma > scarecrow
  Tue Jan 17 20:46:51 ~/myHomeWork/Emerald_City (master #)
$ open scarecrow
  Tue Jan 17 20:46:56 ~/myHomeWork/Emerald_City (master #)
$ echo heart shaped watch > tinman
  Tue Jan 17 20:47:24 ~/myHomeWork/Emerald_City (master #)
$ echo medal > cowardlylion
  Tue Jan 17 20:47:54 ~/myHomeWork/Emerald_City (master #)

**Comment by superbuggy** [comment]
well done! if you ever need to make a folder with spaces in its name, you can do the following:
```
mkdir "Wicked Witch of the West"
```
