### ISSUE TITLE
Chris Wightman

### ISSUE THREAD

**Issue by cjwightman** [ga-wdi-exercises/to_oz#171]
Completeness: 5 - I feel I completed the required tasks
Comfort / Confidence: 3 - I'm totally comfortable with what we've been taught thus far but I feel there are so many shortcuts and I haven't realized the full power of CLI. Hence the extent of the below submission.

Day 1 Homework

$ mkdir House
  Tue Jan 17 16:49:10 ~
$ cd House
  Tue Jan 17 16:49:15 ~/House
$ touch Dorothy Toto
  Tue Jan 17 16:49:33 ~/House
$ mkdir Oz
  Tue Jan 17 16:50:02 ~/House
$ touch 'Good Witch of the North' 'Wicked Witch of the East' 'Good Witch of the South' 'Wicked Witch of the West'
  Tue Jan 17 16:50:44 ~/House
$ cd Oz
  Tue Jan 17 16:50:49 ~/House/Oz
$ ls
  Tue Jan 17 16:50:50 ~/House/Oz
$ cd ..
  Tue Jan 17 16:51:08 ~/House
$ ls
Dorothy				Toto
Good Witch of the North		Wicked Witch of the East
Good Witch of the South		Wicked Witch of the West
Oz
  Tue Jan 17 16:51:09 ~/House
$ mv "Good Witch of the North" "Good Witch of the South" "Wicked Witch of the East" 'Wicked Witch of the West" /Oz
  Tue Jan 17 16:52:37 ~/House
$ cd Oz/
  Tue Jan 17 16:52:45 ~/House
$ ls
> pwd
> q
> 
  Tue Jan 17 16:53:37 ~/House
$ ls
Dorothy				Toto
Good Witch of the North		Wicked Witch of the East
Good Witch of the South		Wicked Witch of the West
Oz
  Tue Jan 17 16:53:40 ~/House
$ pwd
/Users/christopherwightman/House
  Tue Jan 17 16:53:42 ~/House
$ rm 'Good Witch of the North' 'Wicked Witch of the East' 'Good Witch of the South' 'Wicked Witch of the West'
  Tue Jan 17 16:54:07 ~/House
$ cd Oz
  Tue Jan 17 16:54:12 ~/House/Oz
$ touch 'Good Witch of the North' 'Wicked Witch of the East' 'Good Witch of the South' 'Wicked Witch of the West'
  Tue Jan 17 16:54:39 ~/House/Oz
$ ls
Good Witch of the North		Wicked Witch of the East
Good Witch of the South		Wicked Witch of the West
  Tue Jan 17 16:54:42 ~/House/Oz
$ rm 'Wicked Witch of the East' 
  Tue Jan 17 16:55:03 ~/House/Oz
$ cd ..
  Tue Jan 17 16:55:11 ~/House
$ pwd
/Users/christopherwightman/House
  Tue Jan 17 16:55:13 ~/House
$ ls
Dorothy	Oz	Toto
  Tue Jan 17 16:55:16 ~/House
$ mv Dorothy /Oz
mv: rename Dorothy to /Oz: Permission denied
  Tue Jan 17 16:55:24 ~/House
$ sudo mv Dorothy /Oz
Password:
  Tue Jan 17 16:56:44 ~/House
$ pwd
/Users/christopherwightman/House
  Tue Jan 17 16:57:12 ~/House
$ touch Scarecrow 'Tin Man' 'Cowardly Lion'
  Tue Jan 17 16:57:35 ~/House
$ mkdir "Emerald City'
> 
  Tue Jan 17 16:57:58 ~/House
$ mkdir 'Emerald City'
  Tue Jan 17 16:58:05 ~/House
$ mv Scarecrow 'Tin Man' 'Cowardly Lion' /'Emerald City'
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jan 17 16:58:55 ~/House
$ mv Scarecrow /'Emerald City'
mv: rename Scarecrow to /Emerald City: Permission denied
  Tue Jan 17 16:59:49 ~/House
$ sudo mv Scarecrow /'Emerald City'

  Tue Jan 17 17:00:54 ~/House
$ 
  Tue Jan 17 17:00:54 ~/House
$ sudo mv 'Tin Man' /'Emerald City'
  Tue Jan 17 17:01:54 ~/House
$ sudo mv 'Cowardly Lion' /'Emerald City'
  Tue Jan 17 17:03:13 ~/House
$ pwd
/Users/christopherwightman/House
  Tue Jan 17 17:05:32 ~/House
$ cd Oz
  Tue Jan 17 17:05:37 ~/House/Oz
$ pwd
/Users/christopherwightman/House/Oz
  Tue Jan 17 17:05:39 ~/House/Oz
$ mkdir 'Flying Monkeys'
  Tue Jan 17 17:07:22 ~/House/Oz
$ ls
Flying Monkeys			Good Witch of the South
Good Witch of the North		Wicked Witch of the West
  Tue Jan 17 17:07:29 ~/House/Oz
$ rm 'Wicked Witch of the West' 
  Tue Jan 17 17:08:00 ~/House/Oz
$ echo -help
-help
  Tue Jan 17 17:08:06 ~/House/Oz
$ echo --help
--help
  Tue Jan 17 17:08:10 ~/House/Oz
$ ls
Flying Monkeys		Good Witch of the North	Good Witch of the South
  Tue Jan 17 17:08:24 ~/House/Oz
$ cd ..
  Tue Jan 17 17:08:31 ~/House
$ ls
Emerald City	Oz		Toto
  Tue Jan 17 17:08:33 ~/House
$ cd Emerald\ City/
  Tue Jan 17 17:08:47 ~/House/Emerald City
$ pwd
/Users/christopherwightman/House/Emerald City
  Tue Jan 17 17:11:58 ~/House/Emerald City
$ ls
  Tue Jan 17 17:12:03 ~/House/Emerald City
$ touch Scarecrow 'Tin Man' 'Cowardly Lion'
  Tue Jan 17 17:13:33 ~/House/Emerald City
$ echo Scarecrow diploma
Scarecrow diploma
  Tue Jan 17 17:14:06 ~/House/Emerald City
$ echo $diploma >> Scarecrow
  Tue Jan 17 17:16:58 ~/House/Emerald City
$ echo 'diploma' >> Scarecrow
  Tue Jan 17 17:19:20 ~/House/Emerald City
$ echo 'heart shaped watch' >> 'Tin Man'
  Tue Jan 17 17:20:17 ~/House/Emerald City
$ echo 'medal' >> Lion
  Tue Jan 17 17:20:35 ~/House/Emerald City
$

**Comment by phantomhaircuts** [comment]
👍
