### ISSUE TITLE
Homework CLI HW Jared Edwards

### ISSUE THREAD

**Issue by jarededwards** [ga-wdi-exercises/to_oz#174]
Last login: Wed Jan 18 09:47:55 on ttys000
  Wed Jan 18 09:48:07 ~/wdi/myhomework (master #)
$ ls
wendy_bite
  Wed Jan 18 09:48:09 ~/wdi/myhomework (master #)
$ mkdir House
  Wed Jan 18 09:48:35 ~/wdi/myhomework (master #)
$ cd House
  Wed Jan 18 09:48:45 ~/wdi/myhomework/House (master #)
$ touch Dorothy.txt Toto.txt
  Wed Jan 18 09:49:07 ~/wdi/myhomework/House (master #)
$ ls
Dorothy.txt	Toto.txt
  Wed Jan 18 09:49:08 ~/wdi/myhomework/House (master #)
$ pwd
/Users/jared/wdi/myhomework/House
  Wed Jan 18 09:49:09 ~/wdi/myhomework/House (master #)
$ mkdir Oz
  Wed Jan 18 09:49:16 ~/wdi/myhomework/House (master #)
$ ls
Dorothy.txt	Oz		Toto.txt
  Wed Jan 18 09:49:18 ~/wdi/myhomework/House (master #)
$ rm Oz
rm: Oz: is a directory
  Wed Jan 18 09:49:22 ~/wdi/myhomework/House (master #)
$ rm -r Oz
  Wed Jan 18 09:49:27 ~/wdi/myhomework/House (master #)
$ ls
Dorothy.txt	Toto.txt
  Wed Jan 18 09:49:28 ~/wdi/myhomework/House (master #)
$ cd ..
  Wed Jan 18 09:49:30 ~/wdi/myhomework (master #)
$ ls
House		wendy_bite
  Wed Jan 18 09:49:30 ~/wdi/myhomework (master #)
$ mkdir Oz
  Wed Jan 18 09:49:33 ~/wdi/myhomework (master #)
$ cd Oz
  Wed Jan 18 09:50:04 ~/wdi/myhomework/Oz (master #)
$ touch Good\ Witch] of\ the\ North.txt
  Wed Jan 18 09:50:31 ~/wdi/myhomework/Oz (master #)
$ touch Wicked\ Witch\ of\ the\ East.txt
  Wed Jan 18 09:51:44 ~/wdi/myhomework/Oz (master #)
$ touch Good\ Witch\ of\ the\ North.txt
  Wed Jan 18 09:51:50 ~/wdi/myhomework/Oz (master #)
$ ls 
Good Witch of the North.txt	Wicked Witch of the East.txt
Good Witch]			of the North.txt
  Wed Jan 18 09:52:03 ~/wdi/myhomework/Oz (master #)
$ rm Good\ Witch] of\ the\ North.txt
  Wed Jan 18 09:52:36 ~/wdi/myhomework/Oz (master #)
$ ls
Good Witch of the North.txt	Wicked Witch of the East.txt
  Wed Jan 18 09:52:37 ~/wdi/myhomework/Oz (master #)
$ touch Good\ Witch\ of\ the\ South.txt
  Wed Jan 18 09:52:49 ~/wdi/myhomework/Oz (master #)
$ ls
Good Witch of the North.txt	Wicked Witch of the East.txt
Good Witch of the South.txt
  Wed Jan 18 09:52:51 ~/wdi/myhomework/Oz (master #)
$ touch Wicked\ Witch\ of\ the\ West.txt
  Wed Jan 18 09:53:07 ~/wdi/myhomework/Oz (master #)
$ ls
Good Witch of the North.txt	Wicked Witch of the East.txt
Good Witch of the South.txt	Wicked Witch of the West.txt
  Wed Jan 18 09:53:08 ~/wdi/myhomework/Oz (master #)
$ ls
House		Oz		wendy_bite
  Wed Jan 18 09:54:45 ~/wdi/myhomework (master #)
$ cd Oz
  Wed Jan 18 09:54:49 ~/wdi/myhomework/Oz (master #)
$ ls
Good Witch of the North.txt	Wicked Witch of the East.txt
Good Witch of the South.txt	Wicked Witch of the West.txt
  Wed Jan 18 09:54:51 ~/wdi/myhomework/Oz (master #)
$ rm Wicked\ Witch\ of\ the\ East.txt 
  Wed Jan 18 09:54:56 ~/wdi/myhomework/Oz (master #)
$ ls
Good Witch of the North.txt	Wicked Witch of the West.txt
Good Witch of the South.txt
  Wed Jan 18 09:54:57 ~/wdi/myhomework/Oz (master #)
$ cd ..
  Wed Jan 18 09:55:04 ~/wdi/myhomework (master #)
$ cd House
  Wed Jan 18 09:55:09 ~/wdi/myhomework/House (master #)
$ ls
Dorothy.txt	Toto.txt
  Wed Jan 18 09:55:09 ~/wdi/myhomework/House (master #)
$ mv Dorothy.txt ../Oz
  Wed Jan 18 09:55:19 ~/wdi/myhomework/House (master #)
$ ls
Toto.txt
  Wed Jan 18 09:55:20 ~/wdi/myhomework/House (master #)
$ cd ..
  Wed Jan 18 09:55:22 ~/wdi/myhomework (master #)
$ ls
House		Oz		wendy_bite
  Wed Jan 18 09:55:22 ~/wdi/myhomework (master #)
$ cd Oz
  Wed Jan 18 09:55:26 ~/wdi/myhomework/Oz (master #)
$ ls
Dorothy.txt			Good Witch of the South.txt
Good Witch of the North.txt	Wicked Witch of the West.txt
  Wed Jan 18 09:55:26 ~/wdi/myhomework/Oz (master #)
$ touch Scarecrow.txt
  Wed Jan 18 09:55:47 ~/wdi/myhomework/Oz (master #)
$ touch Tin\ Man.txt
  Wed Jan 18 09:55:57 ~/wdi/myhomework/Oz (master #)
$ touch Cowardly\ Lion.txt
  Wed Jan 18 09:56:09 ~/wdi/myhomework/Oz (master #)
$ ls
Cowardly Lion.txt		Scarecrow.txt
Dorothy.txt			Tin Man.txt
Good Witch of the North.txt	Wicked Witch of the West.txt
Good Witch of the South.txt
  Wed Jan 18 09:56:10 ~/wdi/myhomework/Oz (master #)
$ mkdir Emarld\ City
  Wed Jan 18 09:56:25 ~/wdi/myhomework/Oz (master #)
$ ls
Cowardly Lion.txt		Good Witch of the South.txt
Dorothy.txt			Scarecrow.txt
Emarld City			Tin Man.txt
Good Witch of the North.txt	Wicked Witch of the West.txt
  Wed Jan 18 09:56:29 ~/wdi/myhomework/Oz (master #)
$ mv Dorothy.txt Emarld\ City/
  Wed Jan 18 09:56:39 ~/wdi/myhomework/Oz (master #)
$ mv Scarecrow.txt Emarld\ City/
  Wed Jan 18 09:56:49 ~/wdi/myhomework/Oz (master #)
$ mv Tin\ Man.txt Emarld\ City/
  Wed Jan 18 09:56:53 ~/wdi/myhomework/Oz (master #)
$ mv Cowardly\ Lion.txt Emarld\ City/
  Wed Jan 18 09:56:58 ~/wdi/myhomework/Oz (master #)
$ ls
Emarld City			Good Witch of the South.txt
Good Witch of the North.txt	Wicked Witch of the West.txt
  Wed Jan 18 09:57:05 ~/wdi/myhomework/Oz (master #)
$ cd Emarld\ City/
  Wed Jan 18 09:57:08 ~/wdi/myhomework/Oz/Emarld City (master #)
$ ls
Cowardly Lion.txt	Scarecrow.txt
Dorothy.txt		Tin Man.txt
  Wed Jan 18 09:57:08 ~/wdi/myhomework/Oz/Emarld City (master #)
$ cd ..
  Wed Jan 18 09:57:17 ~/wdi/myhomework/Oz (master #)
$ touch Flying\ Monkeys
  Wed Jan 18 09:57:29 ~/wdi/myhomework/Oz (master #)
$ ls
Emarld City			Good Witch of the South.txt
Flying Monkeys			Wicked Witch of the West.txt
Good Witch of the North.txt
  Wed Jan 18 09:57:37 ~/wdi/myhomework/Oz (master #)
$ rm Wicked\ Witch\ of\ the\ West.txt 
  Wed Jan 18 09:58:06 ~/wdi/myhomework/Oz (master #)
$ ls
Emarld City			Good Witch of the North.txt
Flying Monkeys			Good Witch of the South.txt
  Wed Jan 18 09:59:25 ~/wdi/myhomework/Oz (master #)
$ cd Emarld\ City/
  Wed Jan 18 09:59:28 ~/wdi/myhomework/Oz/Emarld City (master #)
$ ls
Cowardly Lion.txt	Scarecrow.txt
Dorothy.txt		Tin Man.txt
  Wed Jan 18 09:59:29 ~/wdi/myhomework/Oz/Emarld City (master #)
$ echo "diploma" > Scarecrow.txt 
  Wed Jan 18 09:59:43 ~/wdi/myhomework/Oz/Emarld City (master #)
$ echo "heart shaped watch" > Tin\ Man.txt 
  Wed Jan 18 09:59:57 ~/wdi/myhomework/Oz/Emarld City (master #)
$ echo "medal" > Cowardly\ Lion.txt 
  Wed Jan 18 10:00:09 ~/wdi/myhomework/Oz/Emarld City (master #)
$ subl Cowardly\ Lion.txt 
  Wed Jan 18 10:00:13 ~/wdi/myhomework/Oz/Emarld City (master #)
$

**Comment by jarededwards** [comment]
comfort level -- 4
completness -- 5

**Comment by nayana487** [comment]
👍
