### ISSUE TITLE
CLI-Homework, Malcom Johnson, 

### ISSUE THREAD

**Issue by malrese1** [ga-wdi-exercises/to_oz#175]

**Comment by malrese1** [comment]
-bash: __git_ps1: command not found
  Wed Jan 18 12:05:39 ~
$ mkdir house
-bash: __git_ps1: command not found
  Wed Jan 18 12:11:40 ~
$ pwd
/Users/malcomjohnson
-bash: __git_ps1: command not found
  Wed Jan 18 12:15:33 ~
$ touch Dorothy
-bash: __git_ps1: command not found
  Wed Jan 18 12:16:45 ~
$ touch toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:16:59 ~
$ ls
2		Downloads	Public		house		wdi
Applications	Library		funny_things	myhomework
Desktop		Movies		hello		post.txt
Documents	Music		hello.txt	thinkorswim
Dorothy		Pictures	hello3.txt	toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:17:06 ~
$ mkdir Oz
-bash: __git_ps1: command not found
  Wed Jan 18 12:17:56 ~
$ ls
2		Downloads	Pictures	hello3.txt	toto
Applications	Library		Public		house		wdi
Desktop		Movies		funny_things	myhomework
Documents	Music		hello		post.txt
Dorothy		Oz		hello.txt	thinkorswim
-bash: __git_ps1: command not found
  Wed Jan 18 12:18:12 ~
$ cd oz
-bash: __git_ps1: command not found
  Wed Jan 18 12:18:36 ~/oz
$ touch good witch of the north
-bash: __git_ps1: command not found
  Wed Jan 18 12:22:18 ~/oz
$ touch wicked witch of the east
-bash: __git_ps1: command not found
  Wed Jan 18 12:22:41 ~/oz
$ touch good witch of the south
-bash: __git_ps1: command not found
  Wed Jan 18 12:23:00 ~/oz
$ touch wicked witch of the west
-bash: __git_ps1: command not found
  Wed Jan 18 12:23:20 ~/oz
$ rm wicked witch of the east
-bash: __git_ps1: command not found
  Wed Jan 18 12:24:48 ~/oz
$ cd ../
-bash: __git_ps1: command not found
  Wed Jan 18 12:25:59 ~
$ pwd
/Users/malcomjohnson
-bash: __git_ps1: command not found
  Wed Jan 18 12:26:08 ~
$ mv dorothy house
-bash: __git_ps1: command not found
  Wed Jan 18 12:27:28 ~
$ cdhouse
-bash: cdhouse: command not found
-bash: __git_ps1: command not found
  Wed Jan 18 12:29:35 ~
$ cd house
-bash: __git_ps1: command not found
  Wed Jan 18 12:29:44 ~/house
$ touch tin man
-bash: __git_ps1: command not found
  Wed Jan 18 12:30:06 ~/house
$ touch cowardly lion
-bash: __git_ps1: command not found
  Wed Jan 18 12:30:25 ~/house
$ mkdir emerald city
-bash: __git_ps1: command not found
  Wed Jan 18 12:30:56 ~/house
$ mv scarecrow emerald city
mv: rename scarecrow to city/scarecrow: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:35:46 ~/house
$ ls
city		dorothy		man
cowardly	lion		tin
-bash: __git_ps1: command not found
  Wed Jan 18 12:36:14 ~/house
$ rm tin
-bash: __git_ps1: command not found
  Wed Jan 18 12:37:44 ~/house
$ rm man
-bash: __git_ps1: command not found
  Wed Jan 18 12:37:51 ~/house
$ ls
city		cowardly	dorothy		lion
-bash: __git_ps1: command not found
  Wed Jan 18 12:37:54 ~/house
$ rm city
rm: city: is a directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:38:13 ~/house
$ touch "tin man"
-bash: __git_ps1: command not found
  Wed Jan 18 12:40:19 ~/house
$ ls
city		cowardly	dorothy		lion		tin man
-bash: __git_ps1: command not found
  Wed Jan 18 12:40:22 ~/house
$ mkdir "emerald city"
-bash: __git_ps1: command not found
  Wed Jan 18 12:40:55 ~/house
$ mv "tin man" "emerald city"
-bash: __git_ps1: command not found
  Wed Jan 18 12:41:42 ~/house
$ ls
city		cowardly	dorothy		emerald city	lion
-bash: __git_ps1: command not found
  Wed Jan 18 12:41:45 ~/house
$ rm cowardly
-bash: __git_ps1: command not found
  Wed Jan 18 12:42:50 ~/house
$ rm lion
-bash: __git_ps1: command not found
  Wed Jan 18 12:43:02 ~/house
$ mv dorothy "emerald city"
-bash: __git_ps1: command not found
  Wed Jan 18 12:43:32 ~/house
$ cd emerald city
-bash: cd: emerald: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:43:44 ~/house
$ cd "emerald city"
-bash: __git_ps1: command not found
  Wed Jan 18 12:44:01 ~/house/emerald city
$ ls
dorothy	tin man
-bash: __git_ps1: command not found
  Wed Jan 18 12:44:06 ~/house/emerald city
$ touch "cowardly lion"
-bash: __git_ps1: command not found
  Wed Jan 18 12:44:54 ~/house/emerald city
$ touch scarecrow 
-bash: __git_ps1: command not found
  Wed Jan 18 12:45:27 ~/house/emerald city
$ ls
cowardly lion	dorothy		scarecrow	tin man
-bash: __git_ps1: command not found
  Wed Jan 18 12:45:30 ~/house/emerald city
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:45:54 ~/house
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:46:01 ~
$ cdoz
-bash: cdoz: command not found
-bash: __git_ps1: command not found
  Wed Jan 18 12:46:06 ~
$ cd oz
-bash: __git_ps1: command not found
  Wed Jan 18 12:46:14 ~/oz
$ touch "flying monkeys"
-bash: __git_ps1: command not found
  Wed Jan 18 12:46:45 ~/oz
$ ls
flying monkeys	good		north		south		west
-bash: __git_ps1: command not found
  Wed Jan 18 12:47:03 ~/oz
$ rm west
-bash: __git_ps1: command not found
  Wed Jan 18 12:47:48 ~/oz
$ rmsouth
-bash: rmsouth: command not found
-bash: __git_ps1: command not found
  Wed Jan 18 12:47:54 ~/oz
$ rm north
-bash: __git_ps1: command not found
  Wed Jan 18 12:48:02 ~/oz
$ ls
flying monkeys	good		south
-bash: __git_ps1: command not found
  Wed Jan 18 12:48:06 ~/oz
$ rm south
-bash: __git_ps1: command not found
  Wed Jan 18 12:48:12 ~/oz
$ ls
flying monkeys	good
-bash: __git_ps1: command not found
  Wed Jan 18 12:48:15 ~/oz
$ touch "good witch of the north"
-bash: __git_ps1: command not found
  Wed Jan 18 12:49:38 ~/oz
$ touch "good witch of the south"
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:01 ~/oz
$ ls
flying monkeys		good witch of the north
good			good witch of the south
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:03 ~/oz
$ ..
-bash: ..: command not found
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:22 ~/oz
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:28 ~
$ ls
2		Library		Public		house		wdi
Applications	Movies		funny_things	myhomework
Desktop		Music		hello		post.txt
Documents	Oz		hello.txt	thinkorswim
Downloads	Pictures	hello3.txt	toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:31 ~
$ cd house
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:43 ~/house
$ ls
city		emerald city
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:46 ~/house
$ rm city
rm: city: is a directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:59 ~/house
$ cd emerald city
-bash: cd: emerald: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:51:09 ~/house
$ cd emerald city
-bash: cd: emerald: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:51:28 ~/house
$ cd "emerald city"
-bash: __git_ps1: command not found
  Wed Jan 18 12:52:04 ~/house/emerald city
$ ls
cowardly lion	dorothy		scarecrow	tin man
-bash: __git_ps1: command not found
  Wed Jan 18 12:52:11 ~/house/emerald city
$ cd scarecow
-bash: cd: scarecow: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:52:40 ~/house/emerald city
$ cd lion
-bash: cd: lion: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:53:03 ~/house/emerald city
$ cd "cowardly lion"
-bash: cd: cowardly lion: Not a directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:53:30 ~/house/emerald city
$ cd "cowardly lion"
-bash: cd: cowardly lion: Not a directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:54:10 ~/house/emerald city
$

**Comment by malrese1** [comment]
-bash: __git_ps1: command not found
  Wed Jan 18 12:05:39 ~
$ mkdir house
-bash: __git_ps1: command not found
  Wed Jan 18 12:11:40 ~
$ pwd
/Users/malcomjohnson
-bash: __git_ps1: command not found
  Wed Jan 18 12:15:33 ~
$ touch Dorothy
-bash: __git_ps1: command not found
  Wed Jan 18 12:16:45 ~
$ touch toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:16:59 ~
$ ls
2		Downloads	Public		house		wdi
Applications	Library		funny_things	myhomework
Desktop		Movies		hello		post.txt
Documents	Music		hello.txt	thinkorswim
Dorothy		Pictures	hello3.txt	toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:17:06 ~
$ mkdir Oz
-bash: __git_ps1: command not found
  Wed Jan 18 12:17:56 ~
$ ls
2		Downloads	Pictures	hello3.txt	toto
Applications	Library		Public		house		wdi
Desktop		Movies		funny_things	myhomework
Documents	Music		hello		post.txt
Dorothy		Oz		hello.txt	thinkorswim
-bash: __git_ps1: command not found
  Wed Jan 18 12:18:12 ~
$ cd oz
-bash: __git_ps1: command not found
  Wed Jan 18 12:18:36 ~/oz
$ touch good witch of the north
-bash: __git_ps1: command not found
  Wed Jan 18 12:22:18 ~/oz
$ touch wicked witch of the east
-bash: __git_ps1: command not found
  Wed Jan 18 12:22:41 ~/oz
$ touch good witch of the south
-bash: __git_ps1: command not found
  Wed Jan 18 12:23:00 ~/oz
$ touch wicked witch of the west
-bash: __git_ps1: command not found
  Wed Jan 18 12:23:20 ~/oz
$ rm wicked witch of the east
-bash: __git_ps1: command not found
  Wed Jan 18 12:24:48 ~/oz
$ cd ../
-bash: __git_ps1: command not found
  Wed Jan 18 12:25:59 ~
$ pwd
/Users/malcomjohnson
-bash: __git_ps1: command not found
  Wed Jan 18 12:26:08 ~
$ mv dorothy house
-bash: __git_ps1: command not found
  Wed Jan 18 12:27:28 ~
$ cdhouse
-bash: cdhouse: command not found
-bash: __git_ps1: command not found
  Wed Jan 18 12:29:35 ~
$ cd house
-bash: __git_ps1: command not found
  Wed Jan 18 12:29:44 ~/house
$ touch tin man
-bash: __git_ps1: command not found
  Wed Jan 18 12:30:06 ~/house
$ touch cowardly lion
-bash: __git_ps1: command not found
  Wed Jan 18 12:30:25 ~/house
$ mkdir emerald city
-bash: __git_ps1: command not found
  Wed Jan 18 12:30:56 ~/house
$ mv scarecrow emerald city
mv: rename scarecrow to city/scarecrow: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:35:46 ~/house
$ ls
city		dorothy		man
cowardly	lion		tin
-bash: __git_ps1: command not found
  Wed Jan 18 12:36:14 ~/house
$ rm tin
-bash: __git_ps1: command not found
  Wed Jan 18 12:37:44 ~/house
$ rm man
-bash: __git_ps1: command not found
  Wed Jan 18 12:37:51 ~/house
$ ls
city		cowardly	dorothy		lion
-bash: __git_ps1: command not found
  Wed Jan 18 12:37:54 ~/house
$ rm city
rm: city: is a directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:38:13 ~/house
$ touch "tin man"
-bash: __git_ps1: command not found
  Wed Jan 18 12:40:19 ~/house
$ ls
city		cowardly	dorothy		lion		tin man
-bash: __git_ps1: command not found
  Wed Jan 18 12:40:22 ~/house
$ mkdir "emerald city"
-bash: __git_ps1: command not found
  Wed Jan 18 12:40:55 ~/house
$ mv "tin man" "emerald city"
-bash: __git_ps1: command not found
  Wed Jan 18 12:41:42 ~/house
$ ls
city		cowardly	dorothy		emerald city	lion
-bash: __git_ps1: command not found
  Wed Jan 18 12:41:45 ~/house
$ rm cowardly
-bash: __git_ps1: command not found
  Wed Jan 18 12:42:50 ~/house
$ rm lion
-bash: __git_ps1: command not found
  Wed Jan 18 12:43:02 ~/house
$ mv dorothy "emerald city"
-bash: __git_ps1: command not found
  Wed Jan 18 12:43:32 ~/house
$ cd emerald city
-bash: cd: emerald: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:43:44 ~/house
$ cd "emerald city"
-bash: __git_ps1: command not found
  Wed Jan 18 12:44:01 ~/house/emerald city
$ ls
dorothy	tin man
-bash: __git_ps1: command not found
  Wed Jan 18 12:44:06 ~/house/emerald city
$ touch "cowardly lion"
-bash: __git_ps1: command not found
  Wed Jan 18 12:44:54 ~/house/emerald city
$ touch scarecrow 
-bash: __git_ps1: command not found
  Wed Jan 18 12:45:27 ~/house/emerald city
$ ls
cowardly lion	dorothy		scarecrow	tin man
-bash: __git_ps1: command not found
  Wed Jan 18 12:45:30 ~/house/emerald city
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:45:54 ~/house
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:46:01 ~
$ cdoz
-bash: cdoz: command not found
-bash: __git_ps1: command not found
  Wed Jan 18 12:46:06 ~
$ cd oz
-bash: __git_ps1: command not found
  Wed Jan 18 12:46:14 ~/oz
$ touch "flying monkeys"
-bash: __git_ps1: command not found
  Wed Jan 18 12:46:45 ~/oz
$ ls
flying monkeys	good		north		south		west
-bash: __git_ps1: command not found
  Wed Jan 18 12:47:03 ~/oz
$ rm west
-bash: __git_ps1: command not found
  Wed Jan 18 12:47:48 ~/oz
$ rmsouth
-bash: rmsouth: command not found
-bash: __git_ps1: command not found
  Wed Jan 18 12:47:54 ~/oz
$ rm north
-bash: __git_ps1: command not found
  Wed Jan 18 12:48:02 ~/oz
$ ls
flying monkeys	good		south
-bash: __git_ps1: command not found
  Wed Jan 18 12:48:06 ~/oz
$ rm south
-bash: __git_ps1: command not found
  Wed Jan 18 12:48:12 ~/oz
$ ls
flying monkeys	good
-bash: __git_ps1: command not found
  Wed Jan 18 12:48:15 ~/oz
$ touch "good witch of the north"
-bash: __git_ps1: command not found
  Wed Jan 18 12:49:38 ~/oz
$ touch "good witch of the south"
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:01 ~/oz
$ ls
flying monkeys		good witch of the north
good			good witch of the south
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:03 ~/oz
$ ..
-bash: ..: command not found
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:22 ~/oz
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:28 ~
$ ls
2		Library		Public		house		wdi
Applications	Movies		funny_things	myhomework
Desktop		Music		hello		post.txt
Documents	Oz		hello.txt	thinkorswim
Downloads	Pictures	hello3.txt	toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:31 ~
$ cd house
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:43 ~/house
$ ls
city		emerald city
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:46 ~/house
$ rm city
rm: city: is a directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:50:59 ~/house
$ cd emerald city
-bash: cd: emerald: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:51:09 ~/house
$ cd emerald city
-bash: cd: emerald: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:51:28 ~/house
$ cd "emerald city"
-bash: __git_ps1: command not found
  Wed Jan 18 12:52:04 ~/house/emerald city
$ ls
cowardly lion	dorothy		scarecrow	tin man
-bash: __git_ps1: command not found
  Wed Jan 18 12:52:11 ~/house/emerald city
$ cd scarecow
-bash: cd: scarecow: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:52:40 ~/house/emerald city
$ cd lion
-bash: cd: lion: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:53:03 ~/house/emerald city
$ cd "cowardly lion"
-bash: cd: cowardly lion: Not a directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:53:30 ~/house/emerald city
$ cd "cowardly lion"
-bash: cd: cowardly lion: Not a directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:54:10 ~/house/emerald city
$

**Comment by AndyWhitley** [comment]
👍
