### ISSUE TITLE
CLI-HomeWork, Savraj Singh CR6

### ISSUE THREAD

**Issue by SavrajSingh** [ga-wdi-exercises/to_oz#176]
cd desktop
mkdir house
cd house
touch dorothy.txt toto.txt
cd ..
mkdir oz
 touch gwotn.txt wwote.txt gwots.txt wwotw.txt
rm wwote.txt
cd ..
cd house
mv dorothy.txt ../oz
cd ..
cd oz
mkdir emerald_city
mv dorothy.txt emerald_city
cd emerald_city
touch scare.txt tin.txt coward.txt
cd ..
touch flyingmonkeys.txt
rm wwotw.txt
cd emerald_city
echo "diploma" >> scare.txt
echo "heartshapedwatch" >> tin.txt
echo "medal" >> coward.txt

**Comment by amaseda** [comment]
:+1:
