### ISSUE TITLE
CLI Homework, Spaces, Sam Clements

### ISSUE THREAD

**Issue by sdkclements** [ga-wdi-exercises/to_oz#177]
mkdir House
touch Dorthy Toto /House
mkdir OZ
cd OZ
touch Good Witch of the North Wicked Witch of the East Good Witch of the South Wicked Witch of the West
rm Wicked Witch East
mv house/dorthy oz/dorthy

cd ..
cd House
touch Scarecrow TinMan CowLion && mkdir EmCity
mv house/* EmCity/

cd ..
touch oz/FlyingMonkeys
rm oz/WitchWest
"echo "Diploma"" >> Scarecrow
"echo "HeartShapedHeart"" >> TinMan
"echo "Medal"" >> CowLion

**Comment by amaseda** [comment]
:+1: props on using `*`
