### ISSUE TITLE
CLI HW Bill Bobbitt CR6

### ISSUE THREAD

**Issue by wmbobbitt** [ga-wdi-exercises/to_oz#178]
mkdir House
  Wed Jan 18 11:57:28 ~/documents/wdi/exercises (master)
$ cd house
  Wed Jan 18 11:57:34 ~/documents/wdi/exercises/house (master)
$ touch Dorothy.txt Toto.txt
  Wed Jan 18 11:57:58 ~/documents/wdi/exercises/house (master)
$ ls
Dorothy.txt	Toto.txt
  Wed Jan 18 11:58:02 ~/documents/wdi/exercises/house (master)
$ cd ..
  Wed Jan 18 11:58:08 ~/documents/wdi/exercises (master)
$ mkdir Oz
  Wed Jan 18 11:58:29 ~/documents/wdi/exercises (master)
$ cd oz
  Wed Jan 18 11:58:33 ~/documents/wdi/exercises/oz (master)
$ touch goodWitchOfTheNorth.txt wickedWitchOfTheEast.txt goodWitchOfTheSouth.txt wickedWitchOfTheWest.txt
  Wed Jan 18 11:59:23 ~/documents/wdi/exercises/oz (master)
$ ls
goodWitchOfTheNorth.txt		wickedWitchOfTheEast.txt
goodWitchOfTheSouth.txt		wickedWitchOfTheWest.txt
  Wed Jan 18 11:59:23 ~/documents/wdi/exercises/oz (master)
$ rm wickedWitchOfTheEast.txt
  Wed Jan 18 11:59:53 ~/documents/wdi/exercises/oz (master)
$ ls
goodWitchOfTheNorth.txt		wickedWitchOfTheWest.txt
goodWitchOfTheSouth.txt
  Wed Jan 18 11:59:54 ~/documents/wdi/exercises/oz (master)
$ cd ..
  Wed Jan 18 12:00:07 ~/documents/wdi/exercises (master)
$ ls
House	Oz
  Wed Jan 18 12:00:12 ~/documents/wdi/exercises (master)
$ mv Dorothy.txt /Oz
mv: rename Dorothy.txt to /Oz: No such file or directory
  Wed Jan 18 12:02:12 ~/documents/wdi/exercises (master)
$ mv ./house/dorothy.txt ./oz
  Wed Jan 18 12:04:49 ~/documents/wdi/exercises (master)
$ cdls oz
dorothy.txt			goodWitchOfTheSouth.txt
goodWitchOfTheNorth.txt		wickedWitchOfTheWest.txt
  Wed Jan 18 12:04:54 ~/documents/wdi/exercises/oz (master)
$ touch Scarecrow.txt TinMan.txt CowardlyLion.txt
  Wed Jan 18 12:05:42 ~/documents/wdi/exercises/oz (master)
$ cd ..
  Wed Jan 18 12:05:49 ~/documents/wdi/exercises (master)
$ mkdir emerald city
  Wed Jan 18 12:05:55 ~/documents/wdi/exercises (master)
$ ls
House	Oz	city	emerald
  Wed Jan 18 12:05:57 ~/documents/wdi/exercises (master)
$ rm city emerald
rm: city: is a directory
rm: emerald: is a directory
  Wed Jan 18 12:06:09 ~/documents/wdi/exercises (master)
$ rmdir city emerald
  Wed Jan 18 12:06:18 ~/documents/wdi/exercises (master)
$ ls
House	Oz
  Wed Jan 18 12:06:20 ~/documents/wdi/exercises (master)
$ mkdir 'Emerald City'
  Wed Jan 18 12:06:32 ~/documents/wdi/exercises (master)
$ ls
Emerald City	House		Oz
  Wed Jan 18 12:06:33 ~/documents/wdi/exercises (master)
$ mv ./oz/Scarecrow.txt ./'Emerald City'
  Wed Jan 18 12:11:05 ~/documents/wdi/exercises (master)
$ cdls 'emerald city'
Scarecrow.txt
  Wed Jan 18 12:11:10 ~/documents/wdi/exercises/emerald city (master)
$ mv ./oz/CowardlyLion.txt ./'Emerald City'
mv: rename ./oz/CowardlyLion.txt to ./Emerald City: No such file or directory
  Wed Jan 18 12:11:32 ~/documents/wdi/exercises/emerald city (master)
$ mv ./oz/TinMan.txt ./'Emerald City'
mv: rename ./oz/TinMan.txt to ./Emerald City: No such file or directory
  Wed Jan 18 12:12:09 ~/documents/wdi/exercises/emerald city (master)
$ cd ..
  Wed Jan 18 12:12:17 ~/documents/wdi/exercises (master)
$ mv ./oz/TinMan.txt ./'Emerald City'
  Wed Jan 18 12:12:25 ~/documents/wdi/exercises (master)
$ mv ./oz/CowardlyLion.txt ./'Emerald City'
  Wed Jan 18 12:12:34 ~/documents/wdi/exercises (master)
$ cdls 'emerald city'
CowardlyLion.txt	Scarecrow.txt		TinMan.txt
  Wed Jan 18 12:12:39 ~/documents/wdi/exercises/emerald city (master)
$ cdls ../oz
dorothy.txt			goodWitchOfTheSouth.txt
goodWitchOfTheNorth.txt		wickedWitchOfTheWest.txt
  Wed Jan 18 12:14:01 ~/documents/wdi/exercises/oz (master)
$ touch FlyingMonkeys.txt
  Wed Jan 18 12:14:09 ~/documents/wdi/exercises/oz (master)
$ rm wickedWitchOfTheWest.txt
  Wed Jan 18 12:14:25 ~/documents/wdi/exercises/oz (master)
$ echo "diploma" >> Scarecrow.txt
  Wed Jan 18 12:16:27 ~/documents/wdi/exercises/oz (master)
$ echo "heart shaped watch" >> TinMan.txt
  Wed Jan 18 12:16:56 ~/documents/wdi/exercises/oz (master)
$ echo "medal" >> CowardlyLion.txt

**Comment by amaseda** [comment]
:+1:
