### ISSUE TITLE
Adam Whitehurst Homework CR6 Spaces

### ISSUE THREAD

**Issue by nairul** [ga-wdi-exercises/to_oz#179]
mkdir House
cd House
touch Dorothy Toto
cd ..
mkdir Oz

cd Oz
touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
rm Wicked_Witch_of_the_East
cd ../House
mv Dorothy ../Oz

touch Scarecrow Tin_Man Cowardly_Lion
mkdir Emerald_City
mv Scarecrow Tin_Man Cowardly_Lion ../Emerald_City

cd Oz
touch Flying_Monkeys
rm Wicked_WItch_of_the_west
cd ..
cd Emerald_City
echo "diploma" >> Scarecrow
echo "heart shaped watch" >> Tin_Man
echo "medal" >> Lion

**Comment by nayana487** [comment]
👍
