### ISSUE TITLE
Maureen Vogel's Day 1 HW

### ISSUE THREAD

**Issue by maureenv** [ga-wdi-exercises/to_oz#18]
~ 
$ mkdir House
~ 
$ cd House
~/House 
$ touch Dorothy
~/House 
$ touch Toto
~/House 
$ ls
Dorothy Toto
~/House 
$ mkdir Oz
~/House 
$ ls
Dorothy Oz  Toto
~/House 
$ cd Oz
~/House/Oz 
$ touch Good_Witch_of_the_North
~/House/Oz 
$ touch Wicked_Witch_of_the_East
~/House/Oz 
$ touch Good_Witch_of_the_South
~/House/Oz 
$ touch Wicked_Witch_of_the_West
~/House/Oz 
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_East
Good_Witch_of_the_South     Wicked_Witch_of_the_West
~/House/Oz 
$ rm -r Wicked_Witch_of_the_East
~/House/Oz 
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
~/House/Oz 
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
$ cd ~/House
~/House 
$ ls
Dorothy Oz  Toto
~/House 
$ mv Dorothy Oz
~/House 
$ ls
Oz  Toto
~/House 
$ cd Oz
~/House/Oz 
$ ls
Dorothy             Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
~/House/Oz 
$ touch Scarecrow
~/House/Oz 
$ touch Tin_Man
~/House/Oz 
$ touch Cowardly_Lion
~/House/Oz 
$ touch Emerald_City
~/House/Oz 
$ mkdir Emerald_City
mkdir: Emerald_City: File exists
~/House/Oz 
$ rm -r Emerald_City
~/House/Oz 
$ mkdir Emerald_City
~/House/Oz 
$ ls
Cowardly_Lion           Good_Witch_of_the_South
Dorothy             Scarecrow
Emerald_City            Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_the_West
~/House/Oz 
$ mv Dorothy Emerald_City
~/House/Oz 
$ mv Cowardly_Lion Emerald_City/
~/House/Oz 
$ mv Tin_Man Emerald_City/
~/House/Oz 
$ mv Scarecrow Emerald_City/
~/House/Oz 
$ ls
Emerald_City            Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
~/House/Oz 
$ touch Flying_Monkeys
~/House/Oz 
$ rm -r Wicked_Witch_of_the_West 
~/House/Oz 
$ echo "a diploma" >> Emerald_City/Scarecrow
~/House/Oz 
$ echo "heart shaped watch" >> Emerald_City/Tin_Man
~/House/Oz 
$ echo "medal" >> Emerald_City/Lion

**Comment by RobertAKARobin** [comment]
Nice!
