### ISSUE TITLE
Bedig Galladian HW CR6 Spaces

### ISSUE THREAD

**Issue by bgalladian** [ga-wdi-exercises/to_oz#180]
mkdir House
cd House
touch Dorothy Toto 
cd .. 
mkdir Oz
touch Good_Witch_of_the_North Wicked_Witch-of_the_East Good_Witch_of_the_South  
      Wicked_Witch_of_the_West
rm Wicked_Witch-of_the_East
cd ~
cd House
mv Dorothy ../Oz
cd ~
cd Oz
touch Scarecrow Tin_man Cowardly_Lion
cd ~
mkdir Emerald_City
cd Oz
mv Scarecrow Tin_man Cowardly_Lion ../Emerald_City
touch Flying_Monkeys
rm Wicked_Witch_of_the_West
echo Diploma >> Scarecrow 
echo Heart Shaped Watch >> Tin_Man
echo Medal >> Cowardly Lion

**Comment by AndyWhitley** [comment]
👍
