### ISSUE TITLE
CLI Oz HW (Taylor Scott)

### ISSUE THREAD

**Issue by taylorscott91** [ga-wdi-exercises/to_oz#181]
To Oz? To Oz!

1. $ mkdir House

2. $ cd House 
$ touch Dorothy.txt Toto.txt

3. $ cd .. 
$ mkdir Oz

4. $ cd Oz 
$ touch goodwitchnorth.txt wickedwitcheast.txt goodwitchsouth.txt wickedwitchwest.txt

Ding! Dong! The Witch is Dead

1. $ cd Oz 
$ rm wickedwitcheast.txt

2. $ cd ..
$ cd house
$ mv dorothy.txt ../oz

Follow the Yellow Brick Road

1. $ cd Oz 
$ touch scarecrow.txt

2. $ touch tinman.txt

3. $ touch lion.txt

4. $cd .. 
$ mkdir Emerald-City

5. $ mv Oz/scarecrow.txt /Emerald-City
$ mv Oz/tinman.txt /Emerald-City
$ mv Oz/lion.txt /Emerald-City

You Must Kill the Witch

1. $ cd Oz 
$ touch flyingmonkeys.txt

2. $ rm wickedwitchwest.txt

3. $ cd ../Emerald-City
$ echo “diploma” >> scarecrow.txt
$ echo “watch” >> tinman.txt
$ echo “medal” >> lion.txt

**Comment by AndyWhitley** [comment]
👍
