### ISSUE TITLE
CLI HW Vince 

### ISSUE THREAD

**Issue by vincecampanale** [ga-wdi-exercises/to_oz#182]
1. mkdir House
2. touch House/Dorothy.txt House/Toto.txt
3. mkdir ../Oz
4. touch Oz/Good_Witch_Of_The_North.txt Oz/Wicked_Witch_Of_The_East.txt Oz/Good_Witch_Of_The_South.txt Oz/Wicked_Witch_Of_The_West.txt

Ding! Dong! The Witch is Dead
1. rm Oz/Wicked_Witch_Of_The_East.txt
2. mv House/Dorothy.txt Oz/

Follow the Yellow Brick Road
1., 2., 3. touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt
4. mkdir Emerald_City
5. mv *.txt Emarld_City

You Must Kill the Witch
1. touch Oz/Flying_Monkeys.txt
2. rm Oz/Wicked_Witch_Of_The_West.txt
3. echo "Diploma" > Emerald_City/Scarecrow.txt 
4. echo "Heart-Shaped Watch" > Emerald_City/Tin_Man.txt
5. echo "Medal" > Cowardly_Lion.txt

**Comment by amaseda** [comment]
:+1: especially for using `*`
