### ISSUE TITLE
CLI Homework Spaces Wes

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/to_oz#183]
mkdir House
cd House
touch Dorthy.txt Toto.txt
cd ..
mkdir Oz
cd Oz
touch good_witch_of_the_north.txt 
touch wicked_witch_of_the_east.txt 
touch good_witch_of_the_south.txt 
touch wicked_witch_of_the_west.txt 
rm wicked_witch_of_the_east.txt
cd ../house
mv dorthy.txt ../oz
cd ../oz
touch scarecrow.txt tin_man.txt cowardly_lion.txt
mkdir emerald_city
mv dorthy.txt ./emerald_city
mv scarecrow.txt ./emerald_city
mv tin_man.txt ./emerald_city
mv cowardly_lion.txt ./emerald_city
touch flying_monkeys.txt
rm wicked_witch_of_the_west.txt 
cd emerald_city
echo diploma > scarecrow.txt 
echo heart shaped watch > tin_man.txt
echo medal > cowardly_lion.txt

**Comment by amaseda** [comment]
:+1:
