### ISSUE TITLE
CLI HW - Lisa Burr

### ISSUE THREAD

**Issue by laburr27** [ga-wdi-exercises/to_oz#184]
$ mkdir house
$ cd house
$ touch dorothy.txt toto.txt
$ cd ..
$ mkdir oz
$ cd oz
$ touch gwotn.txt gwots.txt wwoltw.txt wwote.txt
$ rm wwote.txt
$ cd ..
$ cd house
$ mv dorothy.txt ../oz
$ touch scarecrow.txt tin_man.txt cowardly_lion.txt
$ mv dorothy.txt scarecrow.txt tin_man.txt cowardly_lion.txt emerald_city
$ touch flying_monkieys.txt
$ rm wwoltw.txt
$ cd emerald_city
$ echo "diploma" > scarecrow.txt
$ echo "heart-shaped watch" > tin_man.txt
$ echo "medal" > cowardly_lion.txt

**Comment by superbuggy** [comment]
```
$ touch gwotn.txt gwots.txt wwoltw.txt wwote.txt
```

if you have to create folders or files with spaces in them, you can do so in the following way:
```
mkdir "Wicked Witch of the East"
touch "Filey McFile-File.txt"
```

good work overall!
