### ISSUE TITLE
CLI Homework, Spaces, Will Hawkins

### ISSUE THREAD

**Issue by hawkins-will** [ga-wdi-exercises/to_oz#185]
mkdir House
touch House/Dorothy.txt House/Toto.txt
mkdir Oz
touch Oz/Good_Witch_of_the_North.txt Oz/Wicked_Witch_of_the_East.txt Oz/Good_Witch_of_the_South.txt Oz/Wicked_Witch_of_the_West.txt

rm Oz/Wicked_Witch_of_the_East.txt
mv House/Dorothy.txt Oz

touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt
mkdir Emerald_City
mv {Scarecrow.txt,Tin_Man.txt,Cowardly_Lion.txt,Oz/Dorothy.txt} Emerald_City

touch Oz/Flying_Monkeys.txt
rm Oz/Wicked_Witch_of_the_West.txt
echo "Diploma" >> Emerald_City/Scarecrow.txt
echo "Heart Shaped Watch" >> Emerald_City/Tin_Man.txt 
echo "Medal" >> Emerald_City/Cowardly_Lion.txt

*****

Comfort Score: 5/5
Completeness Score: 5/5

**Comment by nayana487** [comment]
👍
