### ISSUE TITLE
Spaces_LauraG

### ISSUE THREAD

**Issue by laurkgol** [ga-wdi-exercises/to_oz#186]
$ mkdir House
$ touch Dorothy.txt Toto.txt House.txt
$ mkdir Oz
$ cd Oz
$ touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
$ rm Wicked_Witch_of_the_East
$  ../Dorothy.txt Oz/Dorothy.txt

$ touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt
$ mkdir Emerald_City
$ mv Scarecrow.txt Emerald_City/Scarecrow.txt
$ mv Tin_Man.txt Emerald_City/Tin_Man.txt
$ mv Cowardly_Lion.txt Emerald_City/Cowardly_Lion.txt

$ cd ..
$ touch Flying_Monkeys.txt
$ rm Wicked_Witch_of_the_West
$ cd Emerald_City
$ echo "Give Scarecrow a diploma" >> Scarecrow.txt
$ echo "Give Tin Man a heart shaped watch" >> Tin_Man.txt
$ echo "Give Lion a medal" >> Cowardly_Lion.txt

**Comment by AndyWhitley** [comment]
👍
