### ISSUE TITLE
CLI Homework - Elena Santana

### ISSUE THREAD

**Issue by fanelenan7** [ga-wdi-exercises/to_oz#188]
Linas-MacBook-Pro:homework lena$ mkdir to_oz
Linas-MacBook-Pro:homework lena$ cd to_oz
Linas-MacBook-Pro:to_oz lena$ ls
Linas-MacBook-Pro:to_oz lena$ mkdir House
Linas-MacBook-Pro:to_oz lena$ cd House
Linas-MacBook-Pro:House lena$ touch Dorothy touch Toto
Linas-MacBook-Pro:House lena$ cd ..
Linas-MacBook-Pro:to_oz lena$ mkdir Oz
Linas-MacBook-Pro:to_oz lena$ cd Oz
Linas-MacBook-Pro:Oz lena$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West" 
Linas-MacBook-Pro:Oz lena$ rm "Wicked Witch of the East"
Linas-MacBook-Pro:Oz lena$ ls
Good Witch of the North		Wicked Witch of the West
Good Witch of the South
Linas-MacBook-Pro:Oz lena$ cd ..
Linas-MacBook-Pro:to_oz lena$ ls
House	Oz
Linas-MacBook-Pro:to_oz lena$ cdls House
Dorothy	Toto	touch
Linas-MacBook-Pro:House lena$ mv Dorothy Oz
Linas-MacBook-Pro:House lena$ ls
Oz	Toto	touch
Linas-MacBook-Pro:House lena$ rm touch
Linas-MacBook-Pro:House lena$ ls
Oz	Toto
Linas-MacBook-Pro:House lena$ mv Oz Dorothy
Linas-MacBook-Pro:House lena$ ls
Dorothy	Toto
Linas-MacBook-Pro:House lena$ cd Oz
-bash: cd: Oz: No such file or directory
Linas-MacBook-Pro:House lena$ cd .. Oz
Linas-MacBook-Pro:to_oz lena$ ls
House	Oz
Linas-MacBook-Pro:to_oz lena$ cd Oz
Linas-MacBook-Pro:Oz lena$ ls
Good Witch of the North		Wicked Witch of the West
Good Witch of the South
Linas-MacBook-Pro:Oz lena$ mv ~/to_oz/House/Dorothy ~/Oz
mv: rename /Users/lina/to_oz/House/Dorothy to /Users/lina/Oz: No such file or directory
Linas-MacBook-Pro:Oz lena$ mv ~/to_oz/House/Dorothy ~/to_oz/Oz
mv: rename /Users/lina/to_oz/House/Dorothy to /Users/lina/to_oz/Oz: No such file or directory
Linas-MacBook-Pro:Oz lena$ pwd
/Users/lina/wdi/homework/to_oz/Oz
Linas-MacBook-Pro:Oz lena$ mv ~wdi/homework/to_oz/House/Dorothy ~wdi/homework/to_oz/Oz
mv: rename ~wdi/homework/to_oz/House/Dorothy to ~wdi/homework/to_oz/Oz: No such file or directory
Linas-MacBook-Pro:Oz lena$ mv ~wdi/homework/to_oz/House/Dorothy ~wdi/homework/to_oz/Oz/
mv: rename ~wdi/homework/to_oz/House/Dorothy to ~wdi/homework/to_oz/Oz/: No such file or directory
Linas-MacBook-Pro:Oz lena$ cdls House
-bash: cd: House: No such file or directory
Linas-MacBook-Pro:Oz lena$ cd ..
Linas-MacBook-Pro:to_oz lena$ ls
House	Oz
Linas-MacBook-Pro:to_oz lena$ House
-bash: House: command not found
Linas-MacBook-Pro:to_oz lena$ cd House
Linas-MacBook-Pro:House lena$ mv Dorothy ../Oz/
Linas-MacBook-Pro:House lena$ ls
Toto
Linas-MacBook-Pro:House lena$ ..
-bash: ..: command not found
Linas-MacBook-Pro:House lena$ cd ..
Linas-MacBook-Pro:to_oz lena$ ls
House	Oz
Linas-MacBook-Pro:to_oz lena$ cd Oz
Linas-MacBook-Pro:Oz lena$ ls
Dorothy				Good Witch of the South
Good Witch of the North		Wicked Witch of the West
Linas-MacBook-Pro:Oz lena$ touch "Scarecrow" "Tin Man" "Cowardly Lion"
Linas-MacBook-Pro:Oz lena$ ls
Cowardly Lion			Scarecrow
Dorothy				Tin Man
Good Witch of the North		Wicked Witch of the West
Good Witch of the South
Linas-MacBook-Pro:Oz lena$ mkdir "Emerald City"
Linas-MacBook-Pro:Oz lena$ mv "Cowardly Lion" "Emerald City"/
Linas-MacBook-Pro:Oz lena$ ls
Dorothy				Scarecrow
Emerald City			Tin Man
Good Witch of the North		Wicked Witch of the West
Good Witch of the South
Linas-MacBook-Pro:Oz lena$ mv "Scarecrow" "Emerald City"/
Linas-MacBook-Pro:Oz lena$ mv "Dorothy" "Emerald City"/
Linas-MacBook-Pro:Oz lena$ mv "Tin Man" "Emerald City"/
Linas-MacBook-Pro:Oz lena$ ls
Emerald City			Good Witch of the South
Good Witch of the North		Wicked Witch of the West
Linas-MacBook-Pro:Oz lena$ touch "Flying Monkeys"
Linas-MacBook-Pro:Oz lena$ ls
Emerald City			Good Witch of the South
Flying Monkeys			Wicked Witch of the West
Good Witch of the North
Linas-MacBook-Pro:Oz lena$ rm "Wicked Witch of the West"
Linas-MacBook-Pro:Oz lena$ ls
Emerald City		Good Witch of the North
Flying Monkeys		Good Witch of the South
Linas-MacBook-Pro:Oz lena$ cd "Emerald City"
Linas-MacBook-Pro:Emerald City lena$ echo "diploma" >> Scarecrow
Linas-MacBook-Pro:Emerald City lena$ echo "heart shaped watch" >> Tin Man
Linas-MacBook-Pro:Emerald City lena$ echo "medal" >> Cowardly Lion
Linas-MacBook-Pro:Emerald City lena$ mv "Cowardly Lion" "Lion"

**Comment by amaseda** [comment]
:+1:
