### ISSUE TITLE
CLI HW Mitchell Carroll CR6

### ISSUE THREAD

**Issue by mitchellcarroll** [ga-wdi-exercises/to_oz#189]
$ cd wdi
  Wed Jan 18 12:29:00 ~/wdi
$ mkdir House
  Wed Jan 18 12:29:06 ~/wdi
$ cd House
  Wed Jan 18 12:29:10 ~/wdi/House
$ touch "Dorothy"
  Wed Jan 18 12:29:20 ~/wdi/House
$ touch "Toto"
  Wed Jan 18 12:29:26 ~/wdi/House
$ cd ..
  Wed Jan 18 12:29:36 ~/wdi
$ mkdir Oz
  Wed Jan 18 12:29:44 ~/wdi
$ cd Oz
  Wed Jan 18 12:29:46 ~/wdi/Oz
$ touch "Good Witch of the North"
  Wed Jan 18 12:29:54 ~/wdi/Oz
$ touch "Wicked Witch of the East"
  Wed Jan 18 12:30:02 ~/wdi/Oz
$ touch "Good Witch of the South"
  Wed Jan 18 12:30:10 ~/wdi/Oz
$ touch "Wicked Witch of the West"
  Wed Jan 18 12:30:19 ~/wdi/Oz
$ rm "Wicked Witch of the East"
  Wed Jan 18 12:30:44 ~/wdi/Oz
$ cd ..
  Wed Jan 18 12:30:55 ~/wdi
$ cd House
  Wed Jan 18 12:31:07 ~/wdi/House
$ mv "Dorothy" ~/wdi/Oz
  Wed Jan 18 12:31:31 ~/wdi/House
$ ls
Toto
  Wed Jan 18 12:31:36 ~/wdi/House
$ cd ..
  Wed Jan 18 12:31:55 ~/wdi
$ touch "Scarecrow"
  Wed Jan 18 12:32:03 ~/wdi
$ touch "Tin Man"
  Wed Jan 18 12:32:09 ~/wdi
$ touch "Cowardly Lion"
  Wed Jan 18 12:32:16 ~/wdi
$ mkdir "Emerald City"
  Wed Jan 18 12:32:28 ~/wdi
$ mv "Scarecrow" ~/wdi/Emerald City
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Wed Jan 18 12:33:03 ~/wdi
$ ls
Cowardly Lion	Oz		Tin Man		installfest.yml	sandbox
Emerald City	Rakefile	exercises	lessons
House		Scarecrow	homework	projects
  Wed Jan 18 12:33:08 ~/wdi
$ mv "Scarecrow" "Scarecrow.txt"
  Wed Jan 18 12:35:41 ~/wdi
$ ls
Cowardly Lion	Oz		Tin Man		installfest.yml	sandbox
Emerald City	Rakefile	exercises	lessons
House		Scarecrow.txt	homework	projects
  Wed Jan 18 12:35:42 ~/wdi
$ mv "Cowardly Lion" "Cowardly_lion.txt"
  Wed Jan 18 12:36:10 ~/wdi
$ mv "Tin Man" "Tin_Man.txt"
  Wed Jan 18 12:36:30 ~/wdi
$ ls
Cowardly_lion.txt	Scarecrow.txt		lessons
Emerald City		Tin_Man.txt		projects
House			exercises		sandbox
Oz			homework
Rakefile		installfest.yml
  Wed Jan 18 12:36:31 ~/wdi
$ mv "Emerald City" "Emerald_City"
  Wed Jan 18 12:37:02 ~/wdi
$ ls
Cowardly_lion.txt	Scarecrow.txt		lessons
Emerald_City		Tin_Man.txt		projects
House			exercises		sandbox
Oz			homework
Rakefile		installfest.yml
  Wed Jan 18 12:37:03 ~/wdi
$ mv "Scarecrow.txt" ~/wdi/Emerald_City
  Wed Jan 18 12:37:29 ~/wdi
$ ls
Cowardly_lion.txt	Rakefile		installfest.yml
Emerald_City		Tin_Man.txt		lessons
House			exercises		projects
Oz			homework		sandbox
  Wed Jan 18 12:37:36 ~/wdi
$ mv "Cowardly_lion.txt" ~/wdi/Emerald_City
  Wed Jan 18 12:38:10 ~/wdi
$ mv "Tin_Man" ~/wdi/Emerald_City
mv: rename Tin_Man to /Users/mitchell/wdi/Emerald_City/Tin_Man: No such file or directory
  Wed Jan 18 12:38:27 ~/wdi
$ cd Emerald_City
  Wed Jan 18 12:38:51 ~/wdi/Emerald_City
$ ls
Cowardly_lion.txt	Scarecrow.txt
  Wed Jan 18 12:38:53 ~/wdi/Emerald_City
$ cd ..
  Wed Jan 18 12:39:08 ~/wdi
$ mv "Tin_Man.txt" ~/wdi/Emerald_City
  Wed Jan 18 12:39:30 ~/wdi
$ cd Oz
  Wed Jan 18 12:39:52 ~/wdi/Oz
$ touch "Flying_Monkeys.txt"
  Wed Jan 18 12:42:44 ~/wdi/Oz
$ cd ..
  Wed Jan 18 12:42:47 ~/wdi
$ cd Emerald_City
  Wed Jan 18 12:43:00 ~/wdi/Emerald_City
$ echo 'a heart shaped watch' >> 'Tin_Man.txt"
> echo 'diploma' >> "Scarecrow.txt"
> echo 'medal' >> "Cowardly_Lion.txt"

**Comment by mitchellcarroll** [comment]
completeness: 5/5
comfort: 5/5

**Comment by AndyWhitley** [comment]
👍
