### ISSUE TITLE
Max Kaye Day 1 HW

### ISSUE THREAD

**Issue by MaxKaye** [ga-wdi-exercises/to_oz#19]
Maxs-MacBook-Pro:~ maxkaye$ cd Desktop
Maxs-MacBook-Pro:Desktop maxkaye$ cd To_Oz
Maxs-MacBook-Pro:To_Oz maxkaye$ mkdir "House"
Maxs-MacBook-Pro:To_Oz maxkaye$ cd House
Maxs-MacBook-Pro:House maxkaye$ touch "Dorothy"
Maxs-MacBook-Pro:House maxkaye$ touch "Toto"
Maxs-MacBook-Pro:House maxkaye$ cd ~
Maxs-MacBook-Pro:~ maxkaye$ cd Desktop
Maxs-MacBook-Pro:Desktop maxkaye$ cd To_Oz
Maxs-MacBook-Pro:To_Oz maxkaye$ mkdir "Oz"
Maxs-MacBook-Pro:To_Oz maxkaye$ cd Oz
Maxs-MacBook-Pro:Oz maxkaye$ touch "Good_Witch_of_the_North"
Maxs-MacBook-Pro:Oz maxkaye$ touch "Wicked_Witch_of_the_East"
Maxs-MacBook-Pro:Oz maxkaye$ touch "Good_Witch_of_the_South"
Maxs-MacBook-Pro:Oz maxkaye$ touch "Good_Witch_of_the_West"
Maxs-MacBook-Pro:Oz maxkaye$ cd ..
Maxs-MacBook-Pro:To_Oz maxkaye$ cd ls
-bash: cd: ls: No such file or directory
Maxs-MacBook-Pro:To_Oz maxkaye$ cd Oz
Maxs-MacBook-Pro:Oz maxkaye$ rm "Wicked_Witch_of_the_East"
Maxs-MacBook-Pro:Oz maxkaye$ cd ~
Maxs-MacBook-Pro:~ maxkaye$ cd Desktop
Maxs-MacBook-Pro:Desktop maxkaye$ cd To_Oz
Maxs-MacBook-Pro:To_Oz maxkaye$ cd "House"
Maxs-MacBook-Pro:House maxkaye$ mv "Dorothy" "Oz"
Maxs-MacBook-Pro:House maxkaye$ mv "Dorothy" "Oz"
Maxs-MacBook-Pro:House maxkaye$ cd ..
Maxs-MacBook-Pro:To_Oz maxkaye$ touch "Scarecrow"
Maxs-MacBook-Pro:To_Oz maxkaye$ touch "Tin_Man"
Maxs-MacBook-Pro:To_Oz maxkaye$ touch "Cowardly_Lion"
Maxs-MacBook-Pro:To_Oz maxkaye$ mkdir "Emrald_City"
Maxs-MacBook-Pro:To_Oz maxkaye$ cd ..
Maxs-MacBook-Pro:Desktop maxkaye$ cd To_Oz
Maxs-MacBook-Pro:To_Oz maxkaye$ mv Scarecrow Emrald_City
Maxs-MacBook-Pro:To_Oz maxkaye$ mv Cowardly_Lion Emrald_City
Maxs-MacBook-Pro:To_Oz maxkaye$ mv Tin_Man Emrald_City
Maxs-MacBook-Pro:To_Oz maxkaye$ cd Oz
Maxs-MacBook-Pro:Oz maxkaye$ touch "Flying Monkeys"
Maxs-MacBook-Pro:Oz maxkaye$ rm "Wicked_Witch_of_the_West
Maxs-MacBook-Pro:wdi maxkaye$ cd To_Oz
-bash: cd: To_Oz: No such file or directory
Maxs-MacBook-Pro:wdi maxkaye$ cd exercises
Maxs-MacBook-Pro:exercises maxkaye$ cd To_Oz
Maxs-MacBook-Pro:To_Oz maxkaye$ echo "a diploma" >> Emrald_City/Scarecrow
Maxs-MacBook-Pro:To_Oz maxkaye$ echo "a heart shaped watch" >> Emrald_City/Tin_Man
Maxs-MacBook-Pro:To_Oz maxkaye$ echo "a medal" >> Emrald_City/Cowardly_Lion
Maxs-MacBook-Pro:To_Oz maxkaye$

**Comment by MaxKaye** [comment]
Couldn't find files for echo command.

**Comment by MaxKaye** [comment]
Found them!

**Comment by RobertAKARobin** [comment]
Noice!
