### ISSUE TITLE
CLI HW Habtamu Abere-CR6

### ISSUE THREAD

**Issue by HabRonan** [ga-wdi-exercises/to_oz#190]
$ mkdir House
-bash: __git_ps1: command not found
  Wed Jan 18 12:00:43 ~/wdi/homework
$ cd House
-bash: __git_ps1: command not found
  Wed Jan 18 12:03:17 ~/wdi/homework/House
$ ls
-bash: __git_ps1: command not found
  Wed Jan 18 12:03:19 ~/wdi/homework/House
$ touch Dorothy Toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:03:35 ~/wdi/homework/House
$ ls
Dorothy	Toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:03:36 ~/wdi/homework/House
$ cd homework
-bash: cd: homework: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:05:21 ~/wdi/homework/House
$ ls
Dorothy	Toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:05:29 ~/wdi/homework/House
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:06:02 ~/wdi/homework
$ cd ~
-bash: __git_ps1: command not found
  Wed Jan 18 12:06:28 ~
$ ls
Applications	Library		Public		hello2.txt
Desktop		Movies		fundamentals	hello3.txt
Documents	Music		funny_things	rubylessons
Downloads	Pictures	hello.txt	wdi
-bash: __git_ps1: command not found
  Wed Jan 18 12:06:30 ~
$ cd wdi
-bash: __git_ps1: command not found
  Wed Jan 18 12:06:42 ~/wdi
$ ls
Rakefile	homework	lessons		projects
exercises	installfest.yml	myhomework	sandbox
-bash: __git_ps1: command not found
  Wed Jan 18 12:06:43 ~/wdi
$ cd homework
-bash: __git_ps1: command not found
  Wed Jan 18 12:06:51 ~/wdi/homework
$ ls
House		wendy_bite
-bash: __git_ps1: command not found
  Wed Jan 18 12:06:55 ~/wdi/homework
$ mkdir Oz
-bash: __git_ps1: command not found
  Wed Jan 18 12:07:04 ~/wdi/homework
$ ls
House		Oz		wendy_bite
-bash: __git_ps1: command not found
  Wed Jan 18 12:07:07 ~/wdi/homework
$ cd Oz
-bash: __git_ps1: command not found
  Wed Jan 18 12:07:19 ~/wdi/homework/Oz
$ touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
-bash: __git_ps1: command not found
  Wed Jan 18 12:11:33 ~/wdi/homework/Oz
$ ls
Good_Witch_of_the_North		Wicked_Witch_of_the_East
Good_Witch_of_the_South		Wicked_Witch_of_the_West
-bash: __git_ps1: command not found
  Wed Jan 18 12:11:39 ~/wdi/homework/Oz
$ rm Wicked_Witch_of_the_East
-bash: __git_ps1: command not found
  Wed Jan 18 12:12:18 ~/wdi/homework/Oz
$ ls
Good_Witch_of_the_North		Wicked_Witch_of_the_West
Good_Witch_of_the_South
-bash: __git_ps1: command not found
  Wed Jan 18 12:12:20 ~/wdi/homework/Oz
$ cd House
-bash: cd: House: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:14:52 ~/wdi/homework/Oz
$ ls
Good_Witch_of_the_North		Wicked_Witch_of_the_West
Good_Witch_of_the_South
-bash: __git_ps1: command not found
  Wed Jan 18 12:14:54 ~/wdi/homework/Oz
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:15:03 ~/wdi/homework
$ ls
House		Oz		wendy_bite
-bash: __git_ps1: command not found
  Wed Jan 18 12:15:04 ~/wdi/homework
$ cd House
-bash: __git_ps1: command not found
  Wed Jan 18 12:15:12 ~/wdi/homework/House
$ ls
Dorothy	Toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:15:14 ~/wdi/homework/House
$ mv Dorothy admin/wdi/homework/Oz
mv: rename Dorothy to admin/wdi/homework/Oz: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:19:39 ~/wdi/homework/House
$ ls
Dorothy	Toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:19:50 ~/wdi/homework/House
$ cd homework
-bash: cd: homework: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:20:08 ~/wdi/homework/House
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:20:11 ~/wdi/homework
$ ls
House		Oz		wendy_bite
-bash: __git_ps1: command not found
  Wed Jan 18 12:20:13 ~/wdi/homework
$ cd Oz
-bash: __git_ps1: command not found
  Wed Jan 18 12:20:17 ~/wdi/homework/Oz
$ cd Oz
-bash: cd: Oz: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:20:25 ~/wdi/homework/Oz
$ cd Oz
-bash: cd: Oz: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:21:02 ~/wdi/homework/Oz
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:22:42 ~/wdi/homework
$ ls
House		Oz		wendy_bite
-bash: __git_ps1: command not found
  Wed Jan 18 12:22:44 ~/wdi/homework
$ cd Oz
-bash: __git_ps1: command not found
  Wed Jan 18 12:22:49 ~/wdi/homework/Oz
$ ls
Good_Witch_of_the_North		Wicked_Witch_of_the_West
Good_Witch_of_the_South
-bash: __git_ps1: command not found
  Wed Jan 18 12:22:51 ~/wdi/homework/Oz
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:23:04 ~/wdi/homework
$ ls
House		Oz		wendy_bite
-bash: __git_ps1: command not found
  Wed Jan 18 12:23:06 ~/wdi/homework
$ cd House
-bash: __git_ps1: command not found
  Wed Jan 18 12:24:12 ~/wdi/homework/House
$ ls
Dorothy	Toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:24:13 ~/wdi/homework/House
$ mv Dorothy ~wdi/homework/Oz
mv: rename Dorothy to ~wdi/homework/Oz: No such file or directory
-bash: __git_ps1: command not found
  Wed Jan 18 12:25:39 ~/wdi/homework/House
$ mv Dorothy ../Oz
-bash: __git_ps1: command not found
  Wed Jan 18 12:27:43 ~/wdi/homework/House
$ ls
Toto
-bash: __git_ps1: command not found
  Wed Jan 18 12:27:50 ~/wdi/homework/House
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 12:29:21 ~/wdi/homework
$ ls
House		Oz		wendy_bite
-bash: __git_ps1: command not found
  Wed Jan 18 12:29:26 ~/wdi/homework
$ touch Scarecrow Tin_man Cowardly_Lion 
-bash: __git_ps1: command not found
  Wed Jan 18 12:30:13 ~/wdi/homework
$ ls
Cowardly_Lion	Oz		Tin_man
House		Scarecrow	wendy_bite
-bash: __git_ps1: command not found
  Wed Jan 18 12:30:16 ~/wdi/homework
$ mkdir Emerald_City
-bash: __git_ps1: command not found
  Wed Jan 18 12:30:45 ~/wdi/homework
$ ls
Cowardly_Lion	House		Scarecrow	wendy_bite
Emerald_City	Oz		Tin_man
-bash: __git_ps1: command not found
  Wed Jan 18 12:30:48 ~/wdi/homework
$ mv Cowardly_Lion Scarecrow Tin_man Emerald_city
-bash: __git_ps1: command not found
  Wed Jan 18 12:58:18 ~/wdi/homework
$ ls
Emerald_City	House		Oz		wendy_bite
-bash: __git_ps1: command not found
  Wed Jan 18 12:58:22 ~/wdi/homework
$ cd Oz
-bash: __git_ps1: command not found
  Wed Jan 18 13:00:23 ~/wdi/homework/Oz
$ ls
Dorothy				Good_Witch_of_the_South
Good_Witch_of_the_North		Wicked_Witch_of_the_West
-bash: __git_ps1: command not found
  Wed Jan 18 13:00:25 ~/wdi/homework/Oz
$ touch Flying_Monkeys
-bash: __git_ps1: command not found
  Wed Jan 18 13:00:50 ~/wdi/homework/Oz
$ ls
Dorothy				Good_Witch_of_the_South
Flying_Monkeys			Wicked_Witch_of_the_West
Good_Witch_of_the_North
-bash: __git_ps1: command not found
  Wed Jan 18 13:00:52 ~/wdi/homework/Oz
$ rm Wicked_Witch_of_the_West
-bash: __git_ps1: command not found
  Wed Jan 18 13:01:14 ~/wdi/homework/Oz
$ ls
Dorothy			Good_Witch_of_the_North
Flying_Monkeys		Good_Witch_of_the_South
-bash: __git_ps1: command not found
  Wed Jan 18 13:01:17 ~/wdi/homework/Oz
$ cd ..
-bash: __git_ps1: command not found
  Wed Jan 18 13:02:47 ~/wdi/homework
$ ls
Emerald_City	House		Oz		wendy_bite
-bash: __git_ps1: command not found
  Wed Jan 18 13:02:51 ~/wdi/homework
$ cd Emerald_City
-bash: __git_ps1: command not found
  Wed Jan 18 13:03:03 ~/wdi/homework/Emerald_City
$ ls
Cowardly_Lion	Scarecrow	Tin_man
-bash: __git_ps1: command not found
  Wed Jan 18 13:03:05 ~/wdi/homework/Emerald_City
$ echo diploma Scarecrow
diploma Scarecrow
-bash: __git_ps1: command not found
  Wed Jan 18 13:03:28 ~/wdi/homework/Emerald_City
$ echo heart_shaped_watch Tin_man
heart_shaped_watch Tin_man
-bash: __git_ps1: command not found
  Wed Jan 18 13:04:04 ~/wdi/homework/Emerald_City
$ echo medal Cowardly_Lion
medal Cowardly_Lion
-bash: __git_ps1: command not found
  Wed Jan 18 13:04:33 ~/wdi/homework/Emerald_City
$ ls
Cowardly_Lion	Scarecrow	Tin_man
-bash: __git_ps1: command not found
  Wed Jan 18 13:04:45 ~/wdi/homework/Emerald_City
$

**Comment by amaseda** [comment]
:+1:

Let me know if that `-bash: __git_ps1: command not found` resurfaces, although we did take care of it IRL last week.

**Comment by HabRonan** [comment]
Hey,
yes it did resurface again. I will come and talk to you after class

**Comment by amaseda** [comment]
Sounds good.
