### ISSUE TITLE
Natasha Clark CLI HW

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/to_oz#191]
Last login: Wed Jan 18 11:51:35 on ttys002
  Wed Jan 18 11:55:26 ~
$ cd wdi
  Wed Jan 18 11:55:53 ~/wdi
$ ls
Rakefile	hello.txt	installfest.yml	myhomework	sandbox
exercises	homework	lessons		projects
  Wed Jan 18 11:55:56 ~/wdi
$ cd myhomework
  Wed Jan 18 11:56:02 ~/wdi/myhomework (master #)
$ mkdir House
  Wed Jan 18 11:56:14 ~/wdi/myhomework (master #)
$ pwd
/Users/natashaclark/wdi/myhomework
  Wed Jan 18 11:56:30 ~/wdi/myhomework (master #)
$ cd House
  Wed Jan 18 11:56:37 ~/wdi/myhomework/House (master #)
$ touch Dorothy.txt Toto.txt
  Wed Jan 18 11:56:47 ~/wdi/myhomework/House (master #)
$ ls
Dorothy.txt	Toto.txt
  Wed Jan 18 11:56:48 ~/wdi/myhomework/House (master #)
$ mkdir Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
  Wed Jan 18 11:58:19 ~/wdi/myhomework/House (master #)
$ ls
Dorothy.txt			Toto.txt
Good_Witch_of_the_North		Wicked_Witch_of_the_East
Good_Witch_of_the_South		Wicked_Witch_of_the_West
  Wed Jan 18 11:58:21 ~/wdi/myhomework/House (master #)
$ ..
-bash: ..: command not found
  Wed Jan 18 11:58:41 ~/wdi/myhomework/House (master #)
$ /..
-bash: /..: is a directory
  Wed Jan 18 11:58:43 ~/wdi/myhomework/House (master #)
$ pwd
/Users/natashaclark/wdi/myhomework/House
  Wed Jan 18 11:58:47 ~/wdi/myhomework/House (master #)
$ ../
-bash: ../: is a directory
  Wed Jan 18 11:58:53 ~/wdi/myhomework/House (master #)
$ ..
-bash: ..: command not found
  Wed Jan 18 11:58:56 ~/wdi/myhomework/House (master #)
$ cd myhomework
-bash: cd: myhomework: No such file or directory
  Wed Jan 18 11:59:09 ~/wdi/myhomework/House (master #)
$ pwd
/Users/natashaclark/wdi/myhomework/House
  Wed Jan 18 11:59:15 ~/wdi/myhomework/House (master #)
$ cd ..
  Wed Jan 18 11:59:24 ~/wdi/myhomework (master #)
$ pwd
/Users/natashaclark/wdi/myhomework
  Wed Jan 18 11:59:27 ~/wdi/myhomework (master #)
$ mkdir Oz
  Wed Jan 18 11:59:33 ~/wdi/myhomework (master #)
$ mv Good_Witch_of_the_NorthWicked_Witch_of_the_East
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Wed Jan 18 11:59:49 ~/wdi/myhomework (master #)
$ Good_Witch_of_the_SouthWicked_Witch_of_the_West
-bash: Good_Witch_of_the_SouthWicked_Witch_of_the_West: command not found
  Wed Jan 18 12:01:02 ~/wdi/myhomework (master #)
$ pwd
/Users/natashaclark/wdi/myhomework
  Wed Jan 18 12:01:22 ~/wdi/myhomework (master #)
$ cd oz
  Wed Jan 18 12:01:27 ~/wdi/myhomework/oz (master #)
$ ls
Good_Witch_of_the_North		Wicked_Witch_of_the_East
Good_Witch_of_the_South		Wicked_Witch_of_the_West
  Wed Jan 18 12:01:28 ~/wdi/myhomework/oz (master #)
$ rm Wicked_Witch_of_the_East
rm: Wicked_Witch_of_the_East: is a directory
  Wed Jan 18 12:01:44 ~/wdi/myhomework/oz (master #)
$ ls
Good_Witch_of_the_North		Wicked_Witch_of_the_East
Good_Witch_of_the_South		Wicked_Witch_of_the_West
  Wed Jan 18 12:01:46 ~/wdi/myhomework/oz (master #)
$ rm -rf Wicked_Witch_of_the_East
  Wed Jan 18 12:02:01 ~/wdi/myhomework/oz (master #)
$ ls
Good_Witch_of_the_North		Wicked_Witch_of_the_West
Good_Witch_of_the_South
  Wed Jan 18 12:02:03 ~/wdi/myhomework/oz (master #)
$ mv Dorothy Os
mv: rename Dorothy to Os: No such file or directory
  Wed Jan 18 12:02:18 ~/wdi/myhomework/oz (master #)
$ mv Dorothy Oz
mv: rename Dorothy to Oz: No such file or directory
  Wed Jan 18 12:02:27 ~/wdi/myhomework/oz (master #)
$ pwd
/Users/natashaclark/wdi/myhomework/oz
  Wed Jan 18 12:07:24 ~/wdi/myhomework/oz (master #)
$ touch Good_Witch_of_the_North/Wicked_Witch_of_the_East
  Wed Jan 18 12:07:39 ~/wdi/myhomework/oz (master #)
$ Good_Witch_of_the_South
Good_Witch_of_the_South
  Wed Jan 18 12:07:39 ~/wdi/myhomework/oz (master #)
$ touch Goodwitchofthenorth.txt wickedwitchoftheeast.txt goodwitchofthesouth.txt wickedwitchofthewest.txt
  Wed Jan 18 12:08:41 ~/wdi/myhomework/oz (master #)
$ ls
Good_Witch_of_the_North		goodwitchofthesouth.txt
Good_Witch_of_the_South		wickedwitchoftheeast.txt
Goodwitchofthenorth.txt		wickedwitchofthewest.txt
Wicked_Witch_of_the_West
  Wed Jan 18 12:08:42 ~/wdi/myhomework/oz (master #)
$ cd house
-bash: cd: house: No such file or directory
  Wed Jan 18 12:09:40 ~/wdi/myhomework/oz (master #)
$ pwd
/Users/natashaclark/wdi/myhomework/oz
  Wed Jan 18 12:09:44 ~/wdi/myhomework/oz (master #)
$ cd myhomework
-bash: cd: myhomework: No such file or directory
  Wed Jan 18 12:09:52 ~/wdi/myhomework/oz (master #)
$ pwd
/Users/natashaclark/wdi/myhomework/oz
  Wed Jan 18 12:09:57 ~/wdi/myhomework/oz (master #)
$ cd ../
  Wed Jan 18 12:10:08 ~/wdi/myhomework (master #)
$ cd House
  Wed Jan 18 12:10:13 ~/wdi/myhomework/House (master #)
$ ls
Dorothy.txt	Toto.txt
  Wed Jan 18 12:10:16 ~/wdi/myhomework/House (master #)
$ mv Dorothy.txt Oz
  Wed Jan 18 12:10:44 ~/wdi/myhomework/House (master #)
$ ls
Oz		Toto.txt
  Wed Jan 18 12:10:48 ~/wdi/myhomework/House (master #)
$ mv Oz Dorothy.txt
  Wed Jan 18 12:11:44 ~/wdi/myhomework/House (master #)
$ ls
Dorothy.txt	Toto.txt
  Wed Jan 18 12:11:45 ~/wdi/myhomework/House (master #)
$ mv Dorothy.txt ../Oz
  Wed Jan 18 12:13:21 ~/wdi/myhomework/House (master #)
$ ls
Toto.txt
  Wed Jan 18 12:13:24 ~/wdi/myhomework/House (master #)
$ cd myhomework
-bash: cd: myhomework: No such file or directory
  Wed Jan 18 12:13:36 ~/wdi/myhomework/House (master #)
$ cd ../myhomework
-bash: cd: ../myhomework: No such file or directory
  Wed Jan 18 12:14:43 ~/wdi/myhomework/House (master #)
$ cd ../
  Wed Jan 18 12:14:55 ~/wdi/myhomework (master #)
$ ls
House		Oz		wendy_bite
  Wed Jan 18 12:14:58 ~/wdi/myhomework (master #)
$ cd Oz
  Wed Jan 18 12:15:03 ~/wdi/myhomework/Oz (master #)
$ ls
Dorothy.txt			Wicked_Witch_of_the_West
Good_Witch_of_the_North		goodwitchofthesouth.txt
Good_Witch_of_the_South		wickedwitchoftheeast.txt
Goodwitchofthenorth.txt		wickedwitchofthewest.txt
  Wed Jan 18 12:15:04 ~/wdi/myhomework/Oz (master #)
$ touch scarecrow.txt tinman.txt cowardlylion.txt
  Wed Jan 18 12:15:42 ~/wdi/myhomework/Oz (master #)
$ mkdir EmeraldCity
  Wed Jan 18 12:15:53 ~/wdi/myhomework/Oz (master #)
$ ls
Dorothy.txt			cowardlylion.txt
EmeraldCity			goodwitchofthesouth.txt
Good_Witch_of_the_North		scarecrow.txt
Good_Witch_of_the_South		tinman.txt
Goodwitchofthenorth.txt		wickedwitchoftheeast.txt
Wicked_Witch_of_the_West	wickedwitchofthewest.txt
  Wed Jan 18 12:15:55 ~/wdi/myhomework/Oz (master #)
$ mv Dorothy.txt scarecrow.txt cowardlylion.txt tinman.txt ../EmeraldCity
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Wed Jan 18 12:16:57 ~/wdi/myhomework/Oz (master #)
$ ls
Dorothy.txt			cowardlylion.txt
EmeraldCity			goodwitchofthesouth.txt
Good_Witch_of_the_North		scarecrow.txt
Good_Witch_of_the_South		tinman.txt
Goodwitchofthenorth.txt		wickedwitchoftheeast.txt
Wicked_Witch_of_the_West	wickedwitchofthewest.txt
  Wed Jan 18 12:17:08 ~/wdi/myhomework/Oz (master #)
$ mv Dorothy.txt cowardlylion.txt tinman.txt scarecrow.txt /~/wdi/myhomework/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Wed Jan 18 12:19:47 ~/wdi/myhomework/Oz (master #)
$ ls
Dorothy.txt			cowardlylion.txt
EmeraldCity			goodwitchofthesouth.txt
Good_Witch_of_the_North		scarecrow.txt
Good_Witch_of_the_South		tinman.txt
Goodwitchofthenorth.txt		wickedwitchoftheeast.txt
Wicked_Witch_of_the_West	wickedwitchofthewest.txt
  Wed Jan 18 12:19:50 ~/wdi/myhomework/Oz (master #)
$ mv Dorothy.txt /Oz
mv: rename Dorothy.txt to /Oz: Permission denied
  Wed Jan 18 12:20:28 ~/wdi/myhomework/Oz (master #)
$ mv Dorothy.txt /EmeraldCity
mv: rename Dorothy.txt to /EmeraldCity: Permission denied
  Wed Jan 18 12:21:10 ~/wdi/myhomework/Oz (master #)
$ Dorothy.txt ./EmeraldCity
-bash: Dorothy.txt: command not found
  Wed Jan 18 12:21:35 ~/wdi/myhomework/Oz (master #)
$ mv Dorothy.txt ./EmraldCity
  Wed Jan 18 12:22:01 ~/wdi/myhomework/Oz (master #)
$ mv cowardlylion.txt tinman.txt .EmraldCity
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Wed Jan 18 12:22:28 ~/wdi/myhomework/Oz (master #)
$ mv cowardlylion.txt ./EmeraldCity
  Wed Jan 18 12:22:56 ~/wdi/myhomework/Oz (master #)
$ mv tinman.txt scarecrow.txt ./EmeraldCity
  Wed Jan 18 12:23:18 ~/wdi/myhomework/Oz (master #)
$ ls
EmeraldCity			Wicked_Witch_of_the_West
EmraldCity			goodwitchofthesouth.txt
Good_Witch_of_the_North		wickedwitchoftheeast.txt
Good_Witch_of_the_South		wickedwitchofthewest.txt
Goodwitchofthenorth.txt
  Wed Jan 18 12:23:28 ~/wdi/myhomework/Oz (master #)
$ touch flyingmonkeys
  Wed Jan 18 12:23:47 ~/wdi/myhomework/Oz (master #)
$ ls
EmeraldCity			Wicked_Witch_of_the_West
EmraldCity			flyingmonkeys
Good_Witch_of_the_North		goodwitchofthesouth.txt
Good_Witch_of_the_South		wickedwitchoftheeast.txt
Goodwitchofthenorth.txt		wickedwitchofthewest.txt
  Wed Jan 18 12:23:48 ~/wdi/myhomework/Oz (master #)
$ rm wickedwitchofthewest.txt
  Wed Jan 18 12:24:17 ~/wdi/myhomework/Oz (master #)
$ ls
EmeraldCity			Wicked_Witch_of_the_West
EmraldCity			flyingmonkeys
Good_Witch_of_the_North		goodwitchofthesouth.txt
Good_Witch_of_the_South		wickedwitchoftheeast.txt
Goodwitchofthenorth.txt

Wed Jan 18 12:35:21 ~/wdi/myhomework/Oz/EmeraldCity (master #)
$ echo "diploma" > scarecrow.txt
  Wed Jan 18 12:35:38 ~/wdi/myhomework/Oz/EmeraldCity (master #)
$ echo "heart shaped watch" > tinman.txt
  Wed Jan 18 12:36:22 ~/wdi/myhomework/Oz/EmeraldCity (master #)
$ echo "medal" > lion.txt
  Wed Jan 18 12:36:39 ~/wdi/myhomework/Oz/EmeraldCity (master #)
$

**Comment by amaseda** [comment]
:+1:

FYI if you would prefer to just write `..` in place of `cd ..`, you can write a bash alias for it!

https://github.com/ga-wdi-lessons/cli-intro#bash-profile-aliases-if-time-allows
