### ISSUE TITLE
CLI Homework- Spaces-  Fiona N 

### ISSUE THREAD

**Issue by nfiona** [ga-wdi-exercises/to_oz#192]
Last login: Wed Jan 18 12:09:07 on ttys000
  Wed Jan 18 12:10:13 ~
$ pwd
/Users/hafionanataprawira
  Wed Jan 18 12:10:15 ~
$ mkdir House
  Wed Jan 18 12:10:23 ~
$ cd House
  Wed Jan 18 12:10:37 ~/House
$ touch Dorothy.txt Toto.txt 
  Wed Jan 18 12:11:01 ~/House
$ ../House
-bash: ../House: is a directory
  Wed Jan 18 12:11:15 ~/House
$ ..
-bash: ..: command not found
  Wed Jan 18 12:11:20 ~/House
$ cd ~
  Wed Jan 18 12:11:29 ~
$ pwd
/Users/hafionanataprawira
  Wed Jan 18 12:11:31 ~
$ mkdir Oz
  Wed Jan 18 12:11:43 ~
$ cd Oz
  Wed Jan 18 12:11:47 ~/Oz
$ touch "Good Witch of the North".txt "Wicked Witch of the East".txt "Good Witch of the South".txt "Wicked Witch of the West".txt
  Wed Jan 18 12:12:45 ~/Oz
$ ls
Good Witch of the North.txt	Wicked Witch of the East.txt
Good Witch of the South.txt	Wicked Witch of the West.txt
  Wed Jan 18 12:12:49 ~/Oz
$ rm "Wicked Witch of the East".txt
  Wed Jan 18 12:13:11 ~/Oz
$ ls
Good Witch of the North.txt	Wicked Witch of the West.txt
Good Witch of the South.txt
  Wed Jan 18 12:13:20 ~/Oz
$ mv Dorothy.txt Oz/Dorothy.txt
  Wed Jan 18 12:14:20 ~/Oz
$ ../
-bash: ../: is a directory
  Wed Jan 18 12:14:46 ~/Oz
$ ../Oz
-bash: ../Oz: is a directory
  Wed Jan 18 12:15:04 ~/Oz
$ ../../Oz
-bash: ../../Oz: No such file or directory
  Wed Jan 18 12:15:33 ~/Oz
$ cd ~
  Wed Jan 18 12:15:38 ~
$ ls
Applications	Dropbox		Music		Rakefile	installfest.yml
Desktop		House		Oz		World		myhomework
Documents	Library		Pictures	fundamentals	wdi
Downloads	Movies		Public		funny_things
  Wed Jan 18 12:15:47 ~
$ cd House
  Wed Jan 18 12:15:50 ~/House
$ ls
Dorothy.txt	Toto.txt
  Wed Jan 18 12:15:58 ~/House
$ mv Dorothy.txt Oz/Dorothy.txt
mv: rename Dorothy.txt to Oz/Dorothy.txt: No such file or directory
  Wed Jan 18 12:16:15 ~/House
$ ls
Dorothy.txt	Toto.txt
  Wed Jan 18 12:17:35 ~/House
$ mv Dorothy.txt Oz
  Wed Jan 18 12:17:45 ~/House
$ ls
Oz		Toto.txt
  Wed Jan 18 12:17:47 ~/House
$ ls
Oz		Toto.txt
  Wed Jan 18 12:18:23 ~/House
$ cd Oz
-bash: cd: Oz: Not a directory
  Wed Jan 18 12:19:15 ~/House
$ cd ~
  Wed Jan 18 12:19:21 ~
$ ls
Applications	Dropbox		Music		Rakefile	installfest.yml
Desktop		House		Oz		World		myhomework
Documents	Library		Pictures	fundamentals	wdi
Downloads	Movies		Public		funny_things
  Wed Jan 18 12:19:22 ~
$ cd Oz
  Wed Jan 18 12:19:25 ~/Oz
$ ls
Good Witch of the North.txt	Wicked Witch of the West.txt
Good Witch of the South.txt
  Wed Jan 18 12:19:27 ~/Oz
$ cd House
-bash: cd: House: No such file or directory
  Wed Jan 18 12:19:38 ~/Oz
$ cd ~
  Wed Jan 18 12:19:45 ~
$ cd House
  Wed Jan 18 12:19:49 ~/House
$ ls
Oz		Toto.txt
  Wed Jan 18 12:19:52 ~/House
$ cd Oz
-bash: cd: Oz: Not a directory
  Wed Jan 18 12:19:56 ~/House
$ mv Oz Dorothy.txt
  Wed Jan 18 12:20:25 ~/House
$ ls
Dorothy.txt	Toto.txt
  Wed Jan 18 12:20:27 ~/House
$ mv Dorothy.txt Oz/
mv: rename Dorothy.txt to Oz/: No such file or directory
  Wed Jan 18 12:20:42 ~/House
$ ls
Dorothy.txt	Toto.txt
  Wed Jan 18 12:21:42 ~/House
$ mv ~/House/Dorothy.txt ~/Oz
  Wed Jan 18 12:22:27 ~/House
$ ls
Toto.txt
  Wed Jan 18 12:22:29 ~/House
$ cd ~
  Wed Jan 18 12:22:34 ~
$ ls
Applications	Dropbox		Music		Rakefile	installfest.yml
Desktop		House		Oz		World		myhomework
Documents	Library		Pictures	fundamentals	wdi
Downloads	Movies		Public		funny_things
  Wed Jan 18 12:22:37 ~
$ cd Oz
  Wed Jan 18 12:22:40 ~/Oz
$ ls
Dorothy.txt			Good Witch of the South.txt
Good Witch of the North.txt	Wicked Witch of the West.txt
  Wed Jan 18 12:22:41 ~/Oz
$ cd ~
  Wed Jan 18 12:23:14 ~
$ touch Scarecrow.txt "Tin Man".txt "Cowardly Lion".txt
  Wed Jan 18 12:23:41 ~
$ ls
Applications		Movies			World
Cowardly Lion.txt	Music			fundamentals
Desktop			Oz			funny_things
Documents		Pictures		installfest.yml
Downloads		Public			myhomework
Dropbox			Rakefile		wdi
House			Scarecrow.txt
Library			Tin Man.txt
  Wed Jan 18 12:23:44 ~
$ mkdir "Emerald City"
  Wed Jan 18 12:24:06 ~
$ ls
Applications		Library			Tin Man.txt
Cowardly Lion.txt	Movies			World
Desktop			Music			fundamentals
Documents		Oz			funny_things
Downloads		Pictures		installfest.yml
Dropbox			Public			myhomework
Emerald City		Rakefile		wdi
House			Scarecrow.txt
  Wed Jan 18 12:24:10 ~
$ mv ~/Scarecrow.txt "Tin Man".txt "Cowardly Lion".txt ~/"Emerald City"
  Wed Jan 18 12:25:44 ~
$ cd "Emerald City"
  Wed Jan 18 12:25:56 ~/Emerald City
$ ls
Cowardly Lion.txt	Scarecrow.txt		Tin Man.txt
  Wed Jan 18 12:25:58 ~/Emerald City
$ cd ~
  Wed Jan 18 12:26:13 ~
$ cd Oz
  Wed Jan 18 12:26:23 ~/Oz
$ ls
Dorothy.txt			Good Witch of the South.txt
Good Witch of the North.txt	Wicked Witch of the West.txt
  Wed Jan 18 12:26:27 ~/Oz
$ touch "Flying Monkeys"
  Wed Jan 18 12:27:16 ~/Oz
$ rm "Wicked Witch of the West".txt
  Wed Jan 18 12:27:37 ~/Oz
$ ls
Dorothy.txt			Good Witch of the North.txt
Flying Monkeys			Good Witch of the South.txt
  Wed Jan 18 12:27:40 ~/Oz
$ echo "diploma" > 
  Wed Jan 18 13:39:46 ~/Oz
$ cd ~
  Wed Jan 18 13:39:51 ~
$ cd Emerald City
-bash: cd: Emerald: No such file or directory
  Wed Jan 18 13:39:56 ~
$ cd "Emerald City"
  Wed Jan 18 13:40:03 ~/Emerald City
$ echo "diploma" > Scarecrow.txt
  Wed Jan 18 13:40:24 ~/Emerald City
$ cat
^C  
  Wed Jan 18 13:41:34 ~/Emerald City
$ echo

  Wed Jan 18 13:46:08 ~/Emerald City
$ echo "heart shaped watch" > "Tin Man".txt
  Wed Jan 18 13:47:52 ~/Emerald City
$ echo "medal" > "Lion".txt
  Wed Jan 18 13:48:08 ~/Emerald City
$ ls
Cowardly Lion.txt	Scarecrow.txt
Lion.txt		Tin Man.txt
  Wed Jan 18 13:48:13 ~/Emerald City
$ 
  Wed Jan 18 13:52:29 ~/Emerald City
$ cat --help
cat: illegal option -- -
usage: cat [-benstuv] [file ...]
  Wed Jan 18 13:55:18 ~/Emerald City
$ man cat
  Wed Jan 18 13:55:46 ~/Emerald City
$ cat Scarecrow.txt
diploma
  Wed Jan 18 13:56:28 ~/Emerald City
$ cat Lion.txt
medal
  Wed Jan 18 13:57:23 ~/Emerald City
$ cat "Tin Man".txt
heart shaped watch
  Wed Jan 18 13:57:38 ~/Emerald City
$

**Comment by nayana487** [comment]
👍
