### ISSUE TITLE
CLI Homework-Spaces-IsaacDuarte

### ISSUE THREAD

**Issue by Philocoder93** [ga-wdi-exercises/to_oz#193]
Comfort: 4.5/5
Completeness: 5/5

Last login: Wed Jan 18 12:57:00 on ttys001
sup g?[isaac@Isaacs-MacBook-Pro ~]$ ls 
Applications	Downloads	Music		clone		plans
Desktop		Library		Pictures	fundamentals	schellFork
Documents	Movies		Public		myhomework	wdi
sup g?[isaac@Isaacs-MacBook-Pro ~]$ wdi
-bash: wdi: command not found
sup g?[isaac@Isaacs-MacBook-Pro ~]$ cd wdi 
sup g?[isaac@Isaacs-MacBook-Pro wdi]$ ls 
Rakefile	installfest.yml	projects
exercises	lessons		sandbox
sup g?[isaac@Isaacs-MacBook-Pro wdi]$ cd sandbox
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ mkdir House
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
House
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ cd House 
sup g?[isaac@Isaacs-MacBook-Pro House]$ pwd
/Users/isaac/wdi/sandbox/House
sup g?[isaac@Isaacs-MacBook-Pro House]$ touch Dorothy.txt
sup g?[isaac@Isaacs-MacBook-Pro House]$ touch Toto.txt
sup g?[isaac@Isaacs-MacBook-Pro House]$ touch House.txt
sup g?[isaac@Isaacs-MacBook-Pro House]$ ls 
Dorothy.txt	House.txt	Toto.txt
sup g?[isaac@Isaacs-MacBook-Pro House]$ cd ..
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
House
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ mkdir Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
House	Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ cd Oz
sup g?[isaac@Isaacs-MacBook-Pro Oz]$ ls 
sup g?[isaac@Isaacs-MacBook-Pro Oz]$ touch GWN.txt
sup g?[isaac@Isaacs-MacBook-Pro Oz]$ touch GWS.txt WWE.txt WWW.txt
sup g?[isaac@Isaacs-MacBook-Pro Oz]$ ls 
GWN.txt	GWS.txt	WWE.txt	WWW.txt
sup g?[isaac@Isaacs-MacBook-Pro Oz]$ cd ..
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
House	Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ pwd
/Users/isaac/wdi/sandbox
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ rm tree
rm: tree: No such file or directory
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ tree
.
├── House
│   ├── Dorothy.txt
│   ├── House.txt
│   └── Toto.txt
└── Oz
    ├── GWN.txt
    ├── GWS.txt
    ├── WWE.txt
    └── WWW.txt

2 directories, 7 files
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ rm Oz/WWE.txt
remove Oz/WWE.txt? y
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
House	Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ cd Oz
sup g?[isaac@Isaacs-MacBook-Pro Oz]$ ls
GWN.txt	GWS.txt	WWW.txt
sup g?[isaac@Isaacs-MacBook-Pro Oz]$ cd ..
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
House	Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ cd House
sup g?[isaac@Isaacs-MacBook-Pro House]$ cd .. 
y.txt?[isaac@Isaacs-MacBook-Pro sandbox]$ mv House/Dorothy.txt Oz/Doroth 
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
House	Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls Oz
Dorothy.txt	GWN.txt		GWS.txt		WWW.txt
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ touch Scarecrow.txt TinMan.txt CowardlyLion.txt
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
CowardlyLion.txt	House			Oz			Scarecrow.txt		TinMan.txt
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ mkdir EmeraldCity
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
CowardlyLion.txt	House			Scarecrow.txt
EmeraldCity		Oz			TinMan.txt
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ mv -t EmeraldCity Scarecrow.txt TinMan.txt CowardlyLion.txt
mv: illegal option -- t
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ mv *txt EmeraldCity
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
EmeraldCity	House		Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ cd EmeraldCity
sup g?[isaac@Isaacs-MacBook-Pro EmeraldCity]$ ls 
CowardlyLion.txt	Scarecrow.txt		TinMan.txt
sup g?[isaac@Isaacs-MacBook-Pro EmeraldCity]$ cd ..
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
EmeraldCity	House		Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ touch FlyingMonkeys.txt
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
EmeraldCity		FlyingMonkeys.txt	House			Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ mv FlyingMonkeys.txt Oz/FlyingMonkeys.txt
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
EmeraldCity	House		Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ cdls Oz
Dorothy.txt		FlyingMonkeys.txt	GWN.txt			GWS.txt			WWW.txt
sup g?[isaac@Isaacs-MacBook-Pro Oz]$ rm WWW.txt
remove WWW.txt? y
sup g?[isaac@Isaacs-MacBook-Pro Oz]$ ls 
Dorothy.txt		FlyingMonkeys.txt	GWN.txt			GWS.txt
sup g?[isaac@Isaacs-MacBook-Pro Oz]$ cd .. 
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
EmeraldCity	House		Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ mv Oz/Dorothy.txt EmeraldCity/Dorothy.txt
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ ls 
EmeraldCity	House		Oz
sup g?[isaac@Isaacs-MacBook-Pro sandbox]$ cd EmeraldCity
sup g?[isaac@Isaacs-MacBook-Pro EmeraldCity]$ ls 
CowardlyLion.txt	Dorothy.txt		Scarecrow.txt		TinMan.txt
sup g?[isaac@Isaacs-MacBook-Pro EmeraldCity]$ echo diploma >> Scarecrow.txt
sup g?[isaac@Isaacs-MacBook-Pro EmeraldCity]$ cat Scarecrow.txt
diploma
sup g?[isaac@Isaacs-MacBook-Pro EmeraldCity]$ echo heartshapedwatch >> TinMan.txt
sup g?[isaac@Isaacs-MacBook-Pro EmeraldCity]$ cat TinMan.txt
heartshapedwatch
sup g?[isaac@Isaacs-MacBook-Pro EmeraldCity]$ echo medal >> CowardlyLion.txt
sup g?[isaac@Isaacs-MacBook-Pro EmeraldCity]$ cat CowardlyLion.txt
medal
sup g?[isaac@Isaacs-MacBook-Pro EmeraldCity]$

**Comment by nayana487** [comment]
👍
