### ISSUE TITLE
CLI HW (Mike)

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/to_oz#194]
Comfort score 5/5
Completeness score 5/5

**To Oz? To Oz!**
Homes-MacBook-Pro:myhomework Admin$ mkdir House
Homes-MacBook-Pro:myhomework Admin$ touch "Dorothy.txt" "Toto.txt"
Homes-MacBook-Pro:myhomework Admin$ mv "Dorothy.txt" "Toto.txt" House/
Homes-MacBook-Pro:myhomework Admin$ mkdir Oz
Homes-MacBook-Pro:myhomework Admin$ cd Oz
Homes-MacBook-Pro:Oz Admin$ touch "Good Witch of the North.txt" "Wicked Witch of the East.txt" "Good Witch of the South.txt" "Wicked Witch of the West.txt"

**Ding! Dong! The Witch is Dead**
Homes-MacBook-Pro:Oz Admin$ rm "Wicked Witch of the East.txt"
Homes-MacBook-Pro:Oz Admin$ cd ..
Homes-MacBook-Pro:myhomework Admin$ mv ./House/Dorothy.txt ./Oz/Dorothy.txt

**Follow the Yellow Brick Road**
Homes-MacBook-Pro:myhomework Admin$ touch "Scarecrow.txt" "Tin Man.txt" "Cowardly Lion.txt"
Homes-MacBook-Pro:myhomework Admin$ mkdir "Emerald City"
Homes-MacBook-Pro:myhomework Admin$ mv "Scarecrow.txt" "Tin Man.txt" "Cowardly Lion.txt" "Emerald City"/

**You Must Kill the Witch**
Homes-MacBook-Pro:myhomework Admin$ touch "Flying Monkeys.txt"
Homes-MacBook-Pro:myhomework Admin$ mv "Flying Monkeys.txt" Oz/
Homes-MacBook-Pro:myhomework Admin$ cd Oz/
Homes-MacBook-Pro:Oz Admin$ rm "Wicked Witch of the West.txt"
Homes-MacBook-Pro:Oz Admin$ cd ..
Homes-MacBook-Pro:myhomework Admin$ cd Emerald\ City/
Homes-MacBook-Pro:Emerald City Admin$ echo "diploma" > Scarecrow.txt
Homes-MacBook-Pro:Emerald City Admin$ echo "a heart shaped watch"> "Tin Man.txt"
Homes-MacBook-Pro:Emerald City Admin$ echo "medal"> "Cowardly Lion.txt"

**Comment by nayana487** [comment]
👍
