### ISSUE TITLE
CLI to oz - Andres Mbouh

### ISSUE THREAD

**Issue by ambouh** [ga-wdi-exercises/to_oz#195]
mkdir House

cd House

touch Dorothy.txt Toto.txt

cd ..
mkdir Oz

cd Oz

touch "Good Witch of the North".txt "Wicked Witch of the East".txt "Good Witch of the South".txt "Wicked Witch of the West".txt

rm "Wicked Witch of the East".txt

cd ..

mv House/Dorothy.txt Oz/

touch Scarecrow.txt "Tin Man".txt "Cowardly Lion".txt

mkdir "Emerald City".txt

mv Scarecrow.txt "Tin Man".txt "Cowardly Lion".txt -t "Emerald City"/

touch Oz/"FLying Monkeys".txt

rm Oz/"Wicked Witch of the West".txt

cd "Emerald City"

echo 'diploma' > "Scarecrow".txt

echo 'heart shaped watch' > "Tin Man".txt

echo 'medal' > "Cowardly Lion".txt

**Comment by AndyWhitley** [comment]
👍
