### ISSUE TITLE
CLI Homework CR6 Kay Ehni

### ISSUE THREAD

**Issue by ehnik** [ga-wdi-exercises/to_oz#196]
Comfort: 5/5
Completeness: 5/5

**To Oz? To Oz!**
Wed Jan 18 12:22:27 ~/wdi-fundamentals (master)
$ git clone https://github.com/ga-wdi-exercises/to_oz.git
Cloning into 'to_oz'...
remote: Counting objects: 26, done.
remote: Total 26 (delta 0), reused 0 (delta 0), pack-reused 26
Unpacking objects: 100% (26/26), done.
  Wed Jan 18 12:22:42 ~/wdi-fundamentals (master)
$ cd to_oz
  Wed Jan 18 12:23:42 ~/wdi-fundamentals/to_oz (master)
$ mkdir House
  Wed Jan 18 12:23:51 ~/wdi-fundamentals/to_oz (master)
$ cd House
  Wed Jan 18 12:24:19 ~/wdi-fundamentals/to_oz/House (master)
$ touch Dorothy.txt Toto.txt
  Wed Jan 18 12:26:49 ~/wdi-fundamentals/to_oz/House (master)
$ cd ..
  Wed Jan 18 12:27:00 ~/wdi-fundamentals/to_oz (master)
$ mkdir Oz
  Wed Jan 18 12:27:33 ~/wdi-fundamentals/to_oz (master)
$ cd Oz
  Wed Jan 18 12:27:37 ~/wdi-fundamentals/to_oz/Oz (master)
$ touch GoodWitchOfTheNorth.txt WickedWitchOfTheEast.txt GoodWitchOfTheSouth.txt WickedWitchOfTheWest.txt
  Wed Jan 18 12:27:57 ~/wdi-fundamentals/to_oz/Oz (master)

**Ding! Dong! The Witch is Dead**
$ rm WickedWitchOfTheEast.txt
  Wed Jan 18 12:28:19 ~/wdi-fundamentals/to_oz/Oz (master)
$ cd ..
  Wed Jan 18 12:28:33 ~/wdi-fundamentals/to_oz (master)
$ mv House/Dorothy.txt Oz/ 
  Wed Jan 18 12:30:58 ~/wdi-fundamentals/to_oz (master)

**Follow the Yellow Brick Road**
  Wed Jan 18 12:32:42 ~/wdi-fundamentals/to_oz (master)
$ touch Scarecrow.txt
  Wed Jan 18 12:32:48 ~/wdi-fundamentals/to_oz (master)
$ touch TinMan.txt
  Wed Jan 18 12:32:52 ~/wdi-fundamentals/to_oz (master)
$ touch CowardlyLion.txt
  Wed Jan 18 12:32:58 ~/wdi-fundamentals/to_oz (master)
$ mkdir "Emerald City"
  Wed Jan 18 12:35:41 ~/wdi-fundamentals/to_oz (master)
$ cd ..
  Wed Jan 18 12:36:08 ~/wdi-fundamentals/to_oz/
$ mv Scarecrow.txt TinMan.txt CowardlyLion.txt ./Emerald\ City/
  Wed Jan 18 12:36:08 ~/wdi-fundamentals/to_oz/
$ cd Oz
  Wed Jan 18 16:28:02 ~/wdi-fundamentals/to_oz/Oz (master)

**You Must Kill the Witch**
$ touch FlyingMonkeys.txt
  Wed Jan 18 16:28:27 ~/wdi-fundamentals/to_oz/Oz (master)
$ rm WickedWitchOfTheWest.txt
  Wed Jan 18 16:28:44 ~/wdi-fundamentals/to_oz/Oz (master)
$ cd ..
  Wed Jan 18 16:35:48 ~/wdi-fundamentals/to_oz/ (master)
$ echo "diploma" > Scarecrow.txt
  Wed Jan 18 16:36:08 ~/wdi-fundamentals/to_oz (master)
$ echo "heart-shaped watch" >  TinMan.txt
  Wed Jan 18 16:36:39 ~/wdi-fundamentals/to_oz (master)
$ echo "medal" > CowardlyLion.txt

**Comment by AndyWhitley** [comment]
👍
