### ISSUE TITLE
CLI Homework Cr 5 

### ISSUE THREAD

**Issue by pootsmagoots** [ga-wdi-exercises/to_oz#197]
mkdir house
cd into house
touch dorothy.txt toto.txt 
cd ..
mkdir Oz
cd into Oz
touch Good Witch of the East.txt Wicked Witch of the East.txt Good Witch of the South.txt Wicked witch of the West.txt

rm wicked witch of the east.txt
cd ..
cd into house
mv dorothy.txt  /user/travisbatts/wdi14/wizard/Oz

touch Scarecrow.txt
touch Tin man.txt
touch Cowardly Lion.txt
mkdir Emerald City
mv *.txt Emerald City

cd into Oz
touch Flying Monkeys.txt
rm wicked witch of the west.txt
echo “Diploma” >> scarecrow.txt
echo “heart shaped watch”  >> Tin Man.txt
echo “medal” >> Cowardly lion.txt

**Comment by superbuggy** [comment]
```
mv dorothy.txt /user/travisbatts/wdi14/wizard/Oz
```

just note that `~` is shorthand for `/user/travisbatts/`. Nice work!
