### ISSUE TITLE
CLI homework, spaces-cr6, Nat Carter

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/to_oz#198]
Comfort: 5 / 5
Completeness: 15 / 5

### Version 1 ('/'-heavy)

mkdir House
touch House/Dorothy House/Toto
mkdir Oz
touch Oz/Good_Witch_of_the_North Oz/Wicked_Witch_of_the_East Oz/Good_Witch_of_the_South Oz/Wicked_Witch_of_the_West
rm Oz/Wicked_Witch_of_the_East
mv House/Dorothy Oz
touch Scarecrow Tin_Man Cowardly_Lion
mkdir Emerald_City
mv Scarecrow Emerald_City
mv Tin_Man Emerald_City
mv Cowardly_Lion Emerald_City
touch Oz/Flying_Monkeys
rm Oz/Wicked_Witch_of_the_West
echo "diploma" >> Emerald_City/Scarecrow
echo "heart-shaped watch" >> Emerald_City/Tin_Man
echo "medal" >> Emerald_City/Cowardly_Lion

### Version 2 ('&&'-heavy; same as above, but all in one line)

mkdir House && touch House/Dorothy House/Toto && mkdir Oz && touch Oz/Good_Witch_of_the_North Oz/Wicked_Witch_of_the_East Oz/Good_Witch_of_the_South Oz/Wicked_Witch_of_the_West && rm Oz/Wicked_Witch_of_the_East && mv House/Dorothy Oz && touch Scarecrow Tin_Man Cowardly_Lion && mkdir Emerald_City && mv Scarecrow Emerald_City && mv Tin_Man Emerald_City && mv Cowardly_Lion Emerald_City && touch Oz/Flying_Monkeys && rm Oz/Wicked_Witch_of_the_West && echo "diploma" >> Emerald_City/Scarecrow && echo "heart-shaped watch" >> Emerald_City/Tin_Man && echo "medal" >> Emerald_City/Cowardly_Lion

### Version 3 ('cd'-heavy; directory changes instead of '/'-heavy arguments)

mkdir House
cd House
touch Dorothy Toto
cd ..
mkdir Oz
cd Oz
touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
rm Wicked_Witch_of_the_East
cd ..
mv House/Dorothy Oz
touch Scarecrow Tin_Man Cowardly_Lion
mkdir Emerald_City
mv Scarecrow Emerald_City
mv Tin_Man Emerald_City
mv Cowardly_Lion Emerald_City
cd Oz
touch Flying_Monkeys
rm Wicked_Witch_of_the_West
cd ..
cd Emerald_City
echo "diploma" >> Scarecrow
echo "heart-shaped watch" >> Tin_Man
echo "medal" >> Cowardly_Lion
cd ..

**Comment by amaseda** [comment]
:+1: Love this!

Curious if using `*` (wildcard selector) could condense some of these commands...

**Comment by ghost** [comment]
I wasn't aware of `*` ... that could be really helpful in the future. Thanks!
