### ISSUE TITLE
Nyron Day 1 HW

### ISSUE THREAD

**Issue by nyron** [ga-wdi-exercises/to_oz#20]
Generals-MacBook-Air-3:~ generalassembly$ ls
Applications    Downloads   Movies      Public
Desktop     Library     Music       Untitled.ipynb
Documents   Midterm     Pictures    wdi
Generals-MacBook-Air-3:~ generalassembly$ rm -r wdi
Generals-MacBook-Air-3:~ generalassembly$ ls
Applications    Downloads   Movies      Public
Desktop     Library     Music       Untitled.ipynb
Documents   Midterm     Pictures
Generals-MacBook-Air-3:~ generalassembly$ mkdir wdi
Generals-MacBook-Air-3:~ generalassembly$ ls
Applications    Downloads   Movies      Public
Desktop     Library     Music       Untitled.ipynb
Documents   Midterm     Pictures    wdi
Generals-MacBook-Air-3:~ generalassembly$ cd wdi
Generals-MacBook-Air-3:wdi generalassembly$ mkdir sandbox lessons
Generals-MacBook-Air-3:wdi generalassembly$ ls
lessons sandbox
Generals-MacBook-Air-3:wdi generalassembly$ mkdir exercises projects
Generals-MacBook-Air-3:wdi generalassembly$ ls
exercises   lessons     projects    sandbox
Generals-MacBook-Air-3:wdi generalassembly$ cd ..
Generals-MacBook-Air-3:~ generalassembly$ ls
Applications    Downloads   Movies      Public
Desktop     Library     Music       Untitled.ipynb
Documents   Midterm     Pictures    wdi
Generals-MacBook-Air-3:~ generalassembly$ mkdir House
Generals-MacBook-Air-3:~ generalassembly$ cd House
Generals-MacBook-Air-3:House generalassembly$ cd ~
Generals-MacBook-Air-3:~ generalassembly$ ls
Applications    Downloads   Midterm     Pictures    wdi
Desktop     House       Movies      Public
Documents   Library     Music       Untitled.ipynb
Generals-MacBook-Air-3:~ generalassembly$ cd wdi
Generals-MacBook-Air-3:wdi generalassembly$ ls
exercises   lessons     projects    sandbox
Generals-MacBook-Air-3:wdi generalassembly$ cd ..
Generals-MacBook-Air-3:~ generalassembly$ cd House
Generals-MacBook-Air-3:House generalassembly$ touch Dorothy Toto
Generals-MacBook-Air-3:House generalassembly$ ls
Dorothy Toto
Generals-MacBook-Air-3:House generalassembly$ cd ..
Generals-MacBook-Air-3:~ generalassembly$ mkdir Oz
Generals-MacBook-Air-3:~ generalassembly$ cd Oz
Generals-MacBook-Air-3:Oz generalassembly$ touch "Good Witch of the North" "Wicked Witch of the East"
Generals-MacBook-Air-3:Oz generalassembly$ ls
Good Witch of the North     Wicked Witch of the East
Generals-MacBook-Air-3:Oz generalassembly$ touch "Good Witch of the South" "Wicked Witch of the West"
Generals-MacBook-Air-3:Oz generalassembly$ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South     Wicked Witch of the West
Generals-MacBook-Air-3:Oz generalassembly$ rm -r "Wicked Witch of the West"
Generals-MacBook-Air-3:Oz generalassembly$ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South
Generals-MacBook-Air-3:Oz generalassembly$ cd ..
Generals-MacBook-Air-3:~ generalassembly$ cd House
Generals-MacBook-Air-3:House generalassembly$ ls
Dorothy Toto
Generals-MacBook-Air-3:House generalassembly$ mv Dorothy ~/Oz
Generals-MacBook-Air-3:House generalassembly$ ls
Toto
Generals-MacBook-Air-3:House generalassembly$ cd ..
Generals-MacBook-Air-3:~ generalassembly$ ls
Applications    Downloads   Midterm     Oz      Untitled.ipynb
Desktop     House       Movies      Pictures    wdi
Documents   Library     Music       Public
Generals-MacBook-Air-3:~ generalassembly$ cd Oz
Generals-MacBook-Air-3:Oz generalassembly$ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the East
Generals-MacBook-Air-3:Oz generalassembly$ cd ..
Generals-MacBook-Air-3:~ generalassembly$ ls
Applications    Downloads   Midterm     Oz      Untitled.ipynb
Desktop     House       Movies      Pictures    wdi
Documents   Library     Music       Public
Generals-MacBook-Air-3:~ generalassembly$ mkdir Emerald City
Generals-MacBook-Air-3:~ generalassembly$ cd Emerald City
Generals-MacBook-Air-3:Emerald generalassembly$ ls
Generals-MacBook-Air-3:Emerald generalassembly$ touch Scarecrow "Tin Man" "Cowardly Lion"
Generals-MacBook-Air-3:Emerald generalassembly$ ls
Cowardly Lion   Scarecrow   Tin Man
Generals-MacBook-Air-3:Emerald generalassembly$ cd ..
Generals-MacBook-Air-3:~ generalassembly$ ls
Applications    Downloads   Midterm     Pictures
City        Emerald     Movies      Public
Desktop     House       Music       Untitled.ipynb
Documents   Library     Oz      wdi
Generals-MacBook-Air-3:~ generalassembly$ cd Oz
Generals-MacBook-Air-3:Oz generalassembly$ touch "Flying Monkeys"
Generals-MacBook-Air-3:Oz generalassembly$ ls
Dorothy             Good Witch of the South
Flying Monkeys          Wicked Witch of the East
Good Witch of the North
Generals-MacBook-Air-3:Oz generalassembly$ rm -r "Wicked Witch of the West"
rm: Wicked Witch of the West: No such file or directory
Generals-MacBook-Air-3:Oz generalassembly$ ls
Dorothy             Good Witch of the South
Flying Monkeys          Wicked Witch of the East
Good Witch of the North
Generals-MacBook-Air-3:Oz generalassembly$ rm -r "Wicked Witch of the East"
Generals-MacBook-Air-3:Oz generalassembly$ ls
Dorothy         Good Witch of the North
Flying Monkeys      Good Witch of the South
Generals-MacBook-Air-3:Oz generalassembly$ cd ..
Generals-MacBook-Air-3:~ generalassembly$ ls
Applications    Downloads   Midterm     Pictures
City        Emerald     Movies      Public
Desktop     House       Music       Untitled.ipynb
Documents   Library     Oz      wdi
Generals-MacBook-Air-3:~ generalassembly$ cd Emerald
Generals-MacBook-Air-3:Emerald generalassembly$ ls
Cowardly Lion   Scarecrow   Tin Man
Generals-MacBook-Air-3:Emerald generalassembly$ echo "a diploma" Scarecrow
a diploma Scarecrow
Generals-MacBook-Air-3:Emerald generalassembly$ echo "a heart shaped watch" "Tin Man"
a heart shaped watch Tin Man
Generals-MacBook-Air-3:Emerald generalassembly$ echo "a medal" "Cowardly Lion"
a medal Cowardly Lion
Generals-MacBook-Air-3:Emerald generalassembly$

**Comment by RobertAKARobin** [comment]
```
echo "a medal" "Cowardly Lion"
```

That literally just puts "a medal Cowardly Lion" on your screen. To save "a medal" to a file called "Cowardly Lion", you need:

```
echo "a medal" >> "Cowardly Lion"
```
