### ISSUE TITLE
CLI HW Aaron Andrews CR5

### ISSUE THREAD

**Issue by andrews94** [ga-wdi-exercises/to_oz#200]
Mkdir House
Cd house
Touch Dorothy.txt Toto.txt
Cd ..
Mkdir oz
Cd oz
Touch ‘Good Witch of the North’ ’Wicked Witch of the East’ ’Good Witch of the South’ ‘Wicked Witch of the West’
Rm ‘Wicked Witch of the East’.
Cd ..
Mv House/Dorothy.txt oz
Touch ‘Scarecrow’ ’Tin Man’ ‘Cowardly Lion’
Mkdir ‘Emerald City’
mv ‘Scarecrow’ ‘Tin Man’ ‘Cowardly Lion’ ‘Emerald City’
Cd oz
Touch ‘Flying Monkeys’
Rm ‘Wicked Witch of the West’
Cd ..
Cd emarld_city
Echo “diploma” >> scarecrow
Echo “heart-shaped watch” >> tin_man
Echo “medal” >> cowardly_lion
Cd ..

**Comment by superbuggy** [comment]
🔨 nailed it 💅
