### ISSUE TITLE
CLI HOMEWORK SPACES CR6

### ISSUE THREAD

**Issue by rodneycurl** [ga-wdi-exercises/to_oz#201]
COMPLETENESS: 4/5
DIFFICULTY: 3/5

Last login: Mon Jan 23 12:18:52 on ttys001
  Mon Jan 23 12:19:03 ~ (master)
$ ls
Applications			VAS.plist
Desktop				Wicked Witch of the East
Documents			Wicked Witch of the West
Dorothy				flowers
Downloads			funny_things
Good Witch of the North		haiku
Good Witch of the South		hello.txt
House				hello2.txt
Library				hello3.txt
Movies				home
Music				joke.txt
Oz				resume.txt
Pictures			sandbox
Public				test
Toto				wdi
  Mon Jan 23 12:19:08 ~ (master)
$ touch 'scarecrow' 'tin man' 'cowardly lion' 
  Mon Jan 23 13:27:35 ~ (master)
$ ls
Applications			Wicked Witch of the West
Desktop				cowardly lion
Documents			flowers
Dorothy				funny_things
Downloads			haiku
Good Witch of the North		hello.txt
Good Witch of the South		hello2.txt
House				hello3.txt
Library				home
Movies				joke.txt
Music				resume.txt
Oz				sandbox
Pictures			scarecrow
Public				test
Toto				tin man
VAS.plist			wdi
Wicked Witch of the East
  Mon Jan 23 13:27:40 ~ (master)
$ mkdir Emerald City
  Mon Jan 23 13:27:50 ~ (master)
$ ls
Applications			Wicked Witch of the East
City				Wicked Witch of the West
Desktop				cowardly lion
Documents			flowers
Dorothy				funny_things
Downloads			haiku
Emerald				hello.txt
Good Witch of the North		hello2.txt
Good Witch of the South		hello3.txt
House				home
Library				joke.txt
Movies				resume.txt
Music				sandbox
Oz				scarecrow
Pictures			test
Public				tin man
Toto				wdi
VAS.plist
  Mon Jan 23 13:27:54 ~ (master)
$ ls
Applications			Wicked Witch of the East
City				Wicked Witch of the West
Desktop				cowardly lion
Documents			flowers
Dorothy				funny_things
Downloads			haiku
Emerald				hello.txt
Good Witch of the North		hello2.txt
Good Witch of the South		hello3.txt
House				home
Library				joke.txt
Movies				resume.txt
Music				sandbox
Oz				scarecrow
Pictures			test
Public				tin man
Toto				wdi
VAS.plist
  Mon Jan 23 13:28:11 ~ (master)
$ touch Flying Monkeys
  Mon Jan 23 13:28:48 ~ (master)
$ ls
Applications			VAS.plist
City				Wicked Witch of the East
Desktop				Wicked Witch of the West
Documents			cowardly lion
Dorothy				flowers
Downloads			funny_things
Emerald				haiku
Flying				hello.txt
Good Witch of the North		hello2.txt
Good Witch of the South		hello3.txt
House				home
Library				joke.txt
Monkeys				resume.txt
Movies				sandbox
Music				scarecrow
Oz				test
Pictures			tin man
Public				wdi
Toto
  Mon Jan 23 13:28:50 ~ (master)
$ touch 'scarecrow' x 'diploma'
  Mon Jan 23 13:29:58 ~ (master)
$ touch tin man 
  Mon Jan 23 13:30:28 ~ (master)
$ touch lion a medal
  Mon Jan 23 13:30:35 ~ (master)
$ echo "scarecrow" > diploma
  Mon Jan 23 13:32:55 ~ (master)
$ echo "tin man" >> 
-bash: syntax error near unexpected token `newline'
  Mon Jan 23 13:33:37 ~ (master)
$ echo "tin man" > heart shaped watch
  Mon Jan 23 13:33:51 ~ (master)
$

**Comment by nayana487** [comment]
👍
