### ISSUE TITLE
CLI HW Jonathan Wright

### ISSUE THREAD

**Issue by electricflannel** [ga-wdi-exercises/to_oz#203]
`$ mkdir House`
`$ cd House`
`$ touch Dorthy && touch Toto`
`$ cd ..`
`$ mkdir Oz`
`$ cd Oz`
`$ touch Good_Witch_of_the_North`
`$ touch Wicked_Witch_of_the_East`
`$ touch Good_Witch_of_the_West`
`$ touch Wicked_Witch_of_the_West`
`$ rm Wicked_Witch_of_the_East`
`$ cd ..`
`$ mv ./House/Dorothy ./Oz`
`$ touch Scarecrow && touch Tin_Man && touch Cowardly_Lion`
`$ mkdir Emerald_City`
`$ mv ./Cowardly_Lion ./Emerald_City`
`$ mv ./Tin_Man ./Emerald_City`
`$ mv ./Scarecrow ./Emerald_City`
`$ touch ./Oz/Flying_Monkeys`
`$ rm ./Oz/Wicked_Witch_of_the_West`
`$ echo "diploma" >> ./Emerald_City/Scarecrow`
`$ echo "heart shaped watch" >> ./Emerald_City/Tin_Man`
`$ echo "medal" >> ./Emerald_City/Cowardly_Lion`

**Comment by juancgarcia** [comment]
👍
