### ISSUE TITLE
CLI HW (Andres Arango)

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/to_oz#205]
mkdir House
cd House
touch Dorothy.txt
touch Toto.txt
mkdir Ox
cd Oz
touch Good-Witch-of-the-North.txt
touch Wicked-Witch-of-the-East.txt
touch Good-Witch-of-the-South.txt
touch Wicked-Witch-of-the-West.txt
rm Wicked-Witch-of-the-East.txt
mv ~/House/Dorothy.txt ~/Oz
touch Scarecrow.txt
touch Tin-Man.txt
touch Cowardly-Lion.txt
cd ~
mkdir Emerald-City
mv Oz/Scarecrow.txt Emerald-City/
mv Oz/Tin-Man.txt Emerald-City/
mv Oz/Cowardly-Lion.txt Emerald-City/
cd Oz
touch Flying-Monkeys.txt
rm Wicked-Witch-of-the-West.txt
cd ~
cd Emerald-City
echo diploma > Scarecrow.txt
echo heart-shaped-watch > Tin-Man.txt
echo medal > Cowardly-Lion.txt

**Comment by AndyWhitley** [comment]
👍
