### ISSUE TITLE
CLI HW (Caroline Chen)

### ISSUE THREAD

**Issue by twelve13** [ga-wdi-exercises/to_oz#209]
$ mkdir House
  Tue Mar 21 12:18:18 ~/wdi/homework/homework1
$ cd House
  Tue Mar 21 12:18:42 ~/wdi/homework/homework1/House
$ touch Dorothy
  Tue Mar 21 12:18:50 ~/wdi/homework/homework1/House
$ touch Toto
  Tue Mar 21 12:18:57 ~/wdi/homework/homework1/House
$ cd ..
  Tue Mar 21 12:19:10 ~/wdi/homework/homework1
$ mkdir Oz
  Tue Mar 21 12:19:15 ~/wdi/homework/homework1
$ cd Oz
  Tue Mar 21 12:19:34 ~/wdi/homework/homework1/Oz
$ touch Good_Witch_of_the_North
  Tue Mar 21 12:19:57 ~/wdi/homework/homework1/Oz
$ touch Wicked_Witch_of_the_East
  Tue Mar 21 12:20:08 ~/wdi/homework/homework1/Oz
$ touch Good_Witch_of_the_South
  Tue Mar 21 12:20:19 ~/wdi/homework/homework1/Oz
$ touch Wicked_Witch_of_the_West
  Tue Mar 21 12:20:35 ~/wdi/homework/homework1/Oz
$ rm Wicked_Witch_of_the_East
  Tue Mar 21 12:21:42 ~/wdi/homework/homework1/Oz
$ mv ../House/Dorothy .
  Tue Mar 21 12:22:47 ~/wdi/homework/homework1/Oz
$ touch Scarecrow
  Tue Mar 21 12:24:57 ~/wdi/homework/homework1/Oz
$ touch Tin Man
  Tue Mar 21 12:25:01 ~/wdi/homework/homework1/Oz
$ touch Tin_Man
  Tue Mar 21 12:25:08 ~/wdi/homework/homework1/Oz
$ touch Cowardly_Lion
  Tue Mar 21 12:25:20 ~/wdi/homework/homework1/Oz
$ mkdir ../Emerald_City
  Tue Mar 21 12:25:44 ~/wdi/homework/homework1/Oz
$ mv Dorothy ../Emerald_City
  Tue Mar 21 12:26:44 ~/wdi/homework/homework1/Oz
$ mv Scarecrow Tin_Man ../Emerald_City
  Tue Mar 21 12:27:23 ~/wdi/homework/homework1/Oz
$ mv Cowardly_Lion ../Emerald_City
  Tue Mar 21 12:27:53 ~/wdi/homework/homework1/Oz
$ touch Flying_Monkeys
  Tue Mar 21 12:29:10 ~/wdi/homework/homework1/Oz
$ rm Wicked_Witch_of_the_West
  Tue Mar 21 12:29:30 ~/wdi/homework/homework1/Oz
$ echo diploma >> ../Emerald_City
-bash: ../Emerald_City: Is a directory
  Tue Mar 21 12:33:58 ~/wdi/homework/homework1/Oz
$ cd ../Emerald_City
  Tue Mar 21 12:35:11 ~/wdi/homework/homework1/Emerald_City
$ ls
Cowardly_Lion	Dorothy		Scarecrow	Tin_Man
  Tue Mar 21 12:35:12 ~/wdi/homework/homework1/Emerald_City
$ echo diploma >> Scarecrow
  Tue Mar 21 12:35:38 ~/wdi/homework/homework1/Emerald_City
$ cat Scarecrow
diploma
  Tue Mar 21 12:35:42 ~/wdi/homework/homework1/Emerald_City
$ echo heart_shaped_watch >> Tin_Man
  Tue Mar 21 12:36:01 ~/wdi/homework/homework1/Emerald_City
$ cat Tin_Man
heart_shaped_watch
  Tue Mar 21 12:36:06 ~/wdi/homework/homework1/Emerald_City
$ echo medal >> Lion
  Tue Mar 21 12:36:13 ~/wdi/homework/homework1/Emerald_City
$ echo medal >> Cowardly_Lion
  Tue Mar 21 12:36:31 ~/wdi/homework/homework1/Emerald_City

**Comment by AndyWhitley** [comment]
👍
