### ISSUE TITLE
Winnie's Day 1 HW

### ISSUE THREAD

**Issue by winishahines** [ga-wdi-exercises/to_oz#21]
Winishas-MBP:~ Winnie$ cd ~/wdi
Winishas-MBP:wdi Winnie$ ls
Rakefile    installfest.yml projects
exercises   lessons     sandbox
Winishas-MBP:wdi Winnie$ cd exercises
Winishas-MBP:exercises Winnie$ mkdir House
Winishas-MBP:exercises Winnie$ ls
House
Winishas-MBP:exercises Winnie$ cd House
Winishas-MBP:House Winnie$ ls
Winishas-MBP:House Winnie$ touch Dorothy
Winishas-MBP:House Winnie$ ls
Dorothy
Winishas-MBP:House Winnie$ touch Toto
Winishas-MBP:House Winnie$ ls
Dorothy Toto
Winishas-MBP:House Winnie$ cd .
Winishas-MBP:House Winnie$ ls
Dorothy Toto
Winishas-MBP:House Winnie$ cd ..
Winishas-MBP:exercises Winnie$ mkdir Oz
Winishas-MBP:exercises Winnie$ cd Oz
Winishas-MBP:Oz Winnie$ touch Good Witch of the North
Winishas-MBP:Oz Winnie$ touch Wicked Witch of the East
Winishas-MBP:Oz Winnie$ touch Good Witch of the South
Winishas-MBP:Oz Winnie$ touch Wicked Witch of the West
Winishas-MBP:Oz Winnie$ ls
East    Good    North   South   West    Wicked  Witch   of  the
Winishas-MBP:Oz Winnie$ open Wicked Witch of the West
Winishas-MBP:Oz Winnie$ rm East
Winishas-MBP:Oz Winnie$ rm Good North of South the West Wicked Witch
Winishas-MBP:Oz Winnie$ touch "Good Witch of the North"
Winishas-MBP:Oz Winnie$ ls
Good Witch of the North
Winishas-MBP:Oz Winnie$ touch "Wicked Witch of the East"
Winishas-MBP:Oz Winnie$ touch "Good Witch of the South"
Winishas-MBP:Oz Winnie$ touch "Wicked Witch of the West"
Winishas-MBP:Oz Winnie$ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South     Wicked Witch of the West
Winishas-MBP:Oz Winnie$ rm "Wicked Witch of the East"
Winishas-MBP:Oz Winnie$ ls
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
Winishas-MBP:Oz Winnie$ mv /Users/Winnie/wdi/exercises/House/Dorothy /Users/Winnie/wdi/exercises/Oz
Winishas-MBP:Oz Winnie$ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the West
Winishas-MBP:Oz Winnie$ touch "Scarecrow"
Winishas-MBP:Oz Winnie$ ls
Dorothy             Scarecrow
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
Winishas-MBP:Oz Winnie$ touch "Tin Man"
Winishas-MBP:Oz Winnie$ touch "Cowardly Lion"
Winishas-MBP:Oz Winnie$ cd ..
Winishas-MBP:exercises Winnie$ mkdir Emerald City
Winishas-MBP:exercises Winnie$ ls
City    Emerald House   Oz
Winishas-MBP:exercises Winnie$ rm City
rm: City: is a directory
Winishas-MBP:exercises Winnie$ rm -r City
Winishas-MBP:exercises Winnie$ ls
Emerald House   Oz
Winishas-MBP:exercises Winnie$ rm -r Emerald
Winishas-MBP:exercises Winnie$ mkdir "Emerald City"
Winishas-MBP:exercises Winnie$ ls
Emerald City    House       Oz
Winishas-MBP:exercises Winnie$ cd Oz
Winishas-MBP:Oz Winnie$ ls
Cowardly Lion           Scarecrow
Dorothy             Tin Man
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
Winishas-MBP:Oz Winnie$ mv "Dorothy" "Cowardly Lion" "Scarecrow" "Tin Man" ../"Emerald City" 
Winishas-MBP:Oz Winnie$ cd ..
Winishas-MBP:exercises Winnie$ cd "Emerald City"
Winishas-MBP:Emerald City Winnie$ ls
Cowardly Lion   Dorothy     Scarecrow   Tin Man
Winishas-MBP:Emerald City Winnie$ cd ..
Winishas-MBP:exercises Winnie$ cd Oz
Winishas-MBP:Oz Winnie$ touch "Flying Monkeys"
Winishas-MBP:Oz Winnie$ ls
Flying Monkeys          Good Witch of the North     Good Witch of the South     Wicked Witch of the West
Winishas-MBP:Oz Winnie$ rm "Wicked Witch of the West"
Winishas-MBP:Oz Winnie$ ls
Flying Monkeys      Good Witch of the North Good Witch of the South
Winishas-MBP:Oz Winnie$ cd ..
Winishas-MBP:exercises Winnie$ cd "Emerald City"
Winishas-MBP:Emerald City Winnie$ ls
Cowardly Lion   Dorothy     Scarecrow   Tin Man
Winishas-MBP:Emerald City Winnie$ echo "a diploma" >> "Emerald City"/Scarecrow
-bash: Emerald City/Scarecrow: No such file or directory
Winishas-MBP:Emerald City Winnie$ echo "a diploma" >> Scarecrow
Winishas-MBP:Emerald City Winnie$ open Scarecrow
Winishas-MBP:Emerald City Winnie$ echo "a heart shaped watch" >> "Tin Man"
Winishas-MBP:Emerald City Winnie$ open "Tin Man"
Winishas-MBP:Emerald City Winnie$ echo "a medal" >> "Cowardly Lion"
Winishas-MBP:Emerald City Winnie$ open "Cowardly Lion"
Winishas-MBP:Emerald City Winnie$

**Comment by RobertAKARobin** [comment]
Nice!
