### ISSUE TITLE
CLI HW CURTIS OSTLE

### ISSUE THREAD

**Issue by Costle784** [ga-wdi-exercises/to_oz#211]
$ mkdir House
$ touch House/Dorothy House/Toto
$ mkdir Oz
$ cd Oz
$ touch	’Good Witch of the North’ ‘Good Witch of the South’ ‘Wicked Witch of the East’  ‘Wicked Witch of the West’
$ rm ‘Wicked Witch of the East’
$ mv ~/House/Dorothy . 
$ cd 
$ touch Scarecrow ‘Tin Man’ ‘Cowardly Lion’
$ mkdir ‘Emerald city’
$ mv Scarecrow ‘Tin Man’ ‘Cowardly Lion’ ./‘Emerald City’
$ touch Oz/’Flying Monkeys’
$ rm Oz/’Wicket Witch of the West’ 
$ echo diploma >> Oz/Scarecrow 
$ echo ‘heart shaped watch’ >> Oz/‘Tin Man’
$ echo medal >> Lion

**Comment by juancgarcia** [comment]
👍
