### ISSUE TITLE
CLI HW (Whitney Purdum)

### ISSUE THREAD

**Issue by wjpurdum** [ga-wdi-exercises/to_oz#214]
Create directory "House"
/Users/whitneypurdum/Documents/fundamentals
$ mkdir House

Add files: "Dorothy" and "Toto" to "House"
$ cd House
  Tue Mar 21 08:53:35 ~/Documents/fundamentals/House
$ touch Dorothy.txt
  Tue Mar 21 08:54:04 ~/Documents/fundamentals/House
$ touch Toto.txt

Create directory "Oz"
$ pwd
/Users/whitneypurdum/Documents/fundamentals
$ mkdir Oz

Add files for the 4 Witches to "Oz":
Good Witch of the North
Wicked Witch of the East
Good Witch of the South
Wicked Witch of the West

$ cd Oz
  Tue Mar 21 12:26:06 ~/Documents/fundamentals/Oz
$ touch GoodWitchOfTheNorth
  Tue Mar 21 12:26:33 ~/Documents/fundamentals/Oz
$ touch WickedWitchOfTheEast
  Tue Mar 21 12:27:01 ~/Documents/fundamentals/Oz
$ touch GoodWitchOfTheSouth
  Tue Mar 21 12:27:14 ~/Documents/fundamentals/Oz
$ touch WickedWitchOfTheWest
  Tue Mar 21 12:27:26 ~/Documents/fundamentals/Oz

Ding Dong the Witch is Dead

Delete: "Wicked Witch of the East"
$ rm WickedWitchOfTheEast

Move "Dorothy" from "House" to "Oz"
/Users/whitneypurdum/Documents/fundamentals/House
$ mv Dorothy.txt ../Oz

_Follow the Yellow Brick Road_

Add file for "Scarecrow"
Add file for "Tin Man"
Add file for "Cowardly Lion"
$ touch Scarecrow
  Tue Mar 21 12:42:12 ~/Documents/fundamentals
$ touch TinMan
  Tue Mar 21 12:42:15 ~/Documents/fundamentals
$ touch CowardlyLion
  Tue Mar 21 12:42:23 ~/Documents/fundamentals

Create directory "Emerald City"
$ mkdir "Emerald City"

Move 'the gang' to "Emerald City"
$ mv Scarecrow ./"Emerald City"
  Tue Mar 21 12:43:26 ~/Documents/fundamentals
$ mv CowardlyLion ./"Emerald City"
  Tue Mar 21 12:43:40 ~/Documents/fundamentals
$ mv TinMan ./"Emerald City"

Add "Flying Monkeys" to "Oz"
$ cd Oz
  Tue Mar 21 12:45:08 ~/Documents/fundamentals/Oz
$ touch "Flying Monkeys"

You Must Kill the Witch 
Remove "Wicked Witch of the West"
$ rm WickedWitchOfTheWest 

Give the gifts*
Give Scarecrow a diploma
Give Tin Man a heart shaped watch
Give Lion a medal
$ echo "Diploma" > Scarecrow
$ echo "Diploma" > TinMan
$ echo "Diploma" > CowardlyLion

**Comment by juancgarcia** [comment]
👍
