### ISSUE TITLE
CLI HW (Meag Doherty)

### ISSUE THREAD

**Issue by meagdoh** [ga-wdi-exercises/to_oz#215]
$ mkdir "House"
  Tue Mar 21 21:42:32 ~
$ cd "House"
  Tue Mar 21 21:42:38 ~/House
$ touch "Dorothy" "Toto"
  Tue Mar 21 21:43:02 ~/House
$ mkdir "Oz"
  Tue Mar 21 21:43:46 ~/House
$ cd Oz
  Tue Mar 21 22:09:10 ~/house/Oz
$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
  Tue Mar 21 21:46:47 ~/house/oz
$ cd ../
  Tue Mar 21 21:52:49 ~/house
$ mv Dorothy Oz
  Tue Mar 21 21:53:11 ~/house
$ touch "Scarecrow" "Tin Man" "Cowardly Lion"
  Tue Mar 21 21:54:08 ~/house
$ mkdir "Emerald City"
  Tue Mar 21 21:54:30 ~/house
$ mv "Scarecrow" "Emerald City"/
  Tue Mar 21 21:56:27 ~/house
$ mv "Cowardly Lion" "Emerald City"/
  Tue Mar 21 21:56:42 ~/house
$ mv "Tin Man" "Emerald City"/
  Tue Mar 21 21:56:59 ~/house
$ cd ./Oz
  Tue Mar 21 21:57:55 ~/house/Oz
$ touch "Flying Monkeys"
  Tue Mar 21 21:58:11 ~/house/Oz
$ rm "Wicked Witch of the West"
  Tue Mar 21 21:58:36 ~/house/Oz
$ cd ../"Emerald City"
  Tue Mar 21 22:01:10 ~/house/Emerald City
$ echo "Give Scarecrow a diploma" > Scarecrow 
  Tue Mar 21 22:06:23 ~/House/Emerald City
$ echo "Give Tin Man a heart shaped watch" > Tin\ Man 
  Tue Mar 21 22:06:50 ~/House/Emerald City
$ echo "Give Lion a medal" > Cowardly\ Lion 
  Tue Mar 21 22:07:12 ~/House/Emerald City

**Comment by AmlakBarkon** [comment]
jasons-MacBook-Pro:House owner$ touch "Dorothy" "Toto"
jasons-MacBook-Pro:House owner$ mkdir oz
jasons-MacBook-Pro:House owner$ cd oz
jasons-MacBook-Pro:oz owner$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
jasons-MacBook-Pro:oz owner$ rm "wicked witch of the East"
jasons-MacBook-Pro:oz owner$ cd house
-bash: cd: house: No such file or directory
jasons-MacBook-Pro:oz owner$ cd house
-bash: cd: house: No such file or directory
jasons-MacBook-Pro:oz owner$ cd ..
jasons-MacBook-Pro:House owner$ mv "dorothy" "oz"
jasons-MacBook-Pro:House owner$ touch Scarecrow
jasons-MacBook-Pro:House owner$ touch "tin Man" "Cowardly Lion"
jasons-MacBook-Pro:House owner$ mkdir "Emerald City"
jasons-MacBook-Pro:House owner$ cd "Emerald City"
jasons-MacBook-Pro:Emerald City owner$ touch "the gang"
jasons-MacBook-Pro:Emerald City owner$ cd ..
jasons-MacBook-Pro:House owner$ cd oz
jasons-MacBook-Pro:oz owner$ rm "wicked witch of the west"
jasons-MacBook-Pro:oz owner$ echo diploma > scarecrow
jasons-MacBook-Pro:oz owner$ echo "a heart shaped watch" "tin Man"
a heart shaped watch tin Man
jasons-MacBook-Pro:oz owner$ echo medal >Lion
jasons-MacBook-Pro:oz owner$

**Comment by jsm13** [comment]
@meagdoh 👍 great!
