### ISSUE TITLE
homeWork To_OZ

### ISSUE THREAD

**Issue by AmlakBarkon** [ga-wdi-exercises/to_oz#216]
jasons-MacBook-Pro:House owner$ touch "Dorothy" "Toto"
jasons-MacBook-Pro:House owner$ mkdir oz
jasons-MacBook-Pro:House owner$ cd oz
jasons-MacBook-Pro:oz owner$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
jasons-MacBook-Pro:oz owner$ rm "wicked witch of the East"
jasons-MacBook-Pro:oz owner$ cd house
-bash: cd: house: No such file or directory
jasons-MacBook-Pro:oz owner$ cd house
-bash: cd: house: No such file or directory
jasons-MacBook-Pro:oz owner$ cd ..
jasons-MacBook-Pro:House owner$ mv "dorothy" "oz"
jasons-MacBook-Pro:House owner$ touch Scarecrow
jasons-MacBook-Pro:House owner$ touch "tin Man" "Cowardly Lion"
jasons-MacBook-Pro:House owner$ mkdir "Emerald City"
jasons-MacBook-Pro:House owner$ cd "Emerald City"
jasons-MacBook-Pro:Emerald City owner$ touch "the gang"
jasons-MacBook-Pro:Emerald City owner$ cd ..
jasons-MacBook-Pro:House owner$ cd oz
jasons-MacBook-Pro:oz owner$ rm "wicked witch of the west"
jasons-MacBook-Pro:oz owner$ echo diploma > scarecrow
jasons-MacBook-Pro:oz owner$ echo "a heart shaped watch" "tin Man"
a heart shaped watch tin Man
jasons-MacBook-Pro:oz owner$ echo medal >Lion
jasons-MacBook-Pro:oz owner$

**Comment by AndyWhitley** [comment]
👍
