### ISSUE TITLE
Oz (Matt Caplan)

### ISSUE THREAD

**Issue by mattpcaplan** [ga-wdi-exercises/to_oz#218]
1. mkdir House
2. cd House
3. touch Dorthy Toto
4. mkdir Oz
5. cd Oz
6. touch Good_Witch_of_the_north wicked_witch_of_the_east good_witch_of_the_south wicked_witch_of_the_west
7. rm wicked_witch_of_the_west
8. cd ..
9. mv Dorothy Oz
10. touch Scarecrow Tin_Man Cowardly_Lion
11. mkdir Emerald_City
12. mv Cowardly_Lion Scarecrow Tin_Man Toto Emerald_City
13. cd Oz
14. touch flying_monkeys
15. rm wicked_witch_of_the_west
16. cd ..
17. cd Emerald_City
18. echo "Diploma" >> Scarecrow
19. echo "Heart Shaped Watch" >> Tin_Man
20. echo "a medal" >> Cowardly_Lion

**Comment by AndyWhitley** [comment]
👍
