### ISSUE TITLE
CLI HW (Conner Johnson)

### ISSUE THREAD

**Issue by cconnerj** [ga-wdi-exercises/to_oz#219]
Wed Mar 22 13:27:10 ~
$ cd
  Wed Mar 22 13:29:40 ~
$ ls
Applications	Library		Public		myhomework	wdi
Desktop		Movies		ecardly		oz
Documents	Music		fundamentals	skdjf
Downloads	Pictures	funny_things	to_oz
  Wed Mar 22 13:29:41 ~
$ cd to_oz
  Wed Mar 22 13:29:48 ~/to_oz (master)
$ mkdir house
  Wed Mar 22 13:29:54 ~/to_oz (master)
$ cd house
  Wed Mar 22 13:29:59 ~/to_oz/house (master)
$ touch Dorothy
  Wed Mar 22 13:30:10 ~/to_oz/house (master)
$ touch Toto
  Wed Mar 22 13:30:14 ~/to_oz/house (master)
$ touch House
  Wed Mar 22 13:30:19 ~/to_oz/house (master)
$ cd ..
  Wed Mar 22 13:30:29 ~/to_oz (master)
$ mkdir oz
  Wed Mar 22 13:30:43 ~/to_oz (master)
$ cd oz
  Wed Mar 22 13:30:47 ~/to_oz/oz (master)
$ touch "Good Witch of the North"
  Wed Mar 22 13:31:00 ~/to_oz/oz (master)
$ touch "Wicked Witch of the East"
  Wed Mar 22 13:31:12 ~/to_oz/oz (master)
$ touch "Good Witch of the South"
  Wed Mar 22 13:31:24 ~/to_oz/oz (master)
$ touch "Wicked Witch of the West"
  Wed Mar 22 13:31:37 ~/to_oz/oz (master)
$ rm "Wicked Witch of the East"
  Wed Mar 22 13:31:54 ~/to_oz/oz (master)
$ cd ..
  Wed Mar 22 13:32:04 ~/to_oz (master)
$ cd house
  Wed Mar 22 13:32:06 ~/to_oz/house (master)
$ mv Dorothy ../oz
  Wed Mar 22 13:33:00 ~/to_oz/house (master)
$ cd ..
  Wed Mar 22 13:33:47 ~/to_oz (master)
$ touch Scarecrow
  Wed Mar 22 13:33:56 ~/to_oz (master)
$ touch "Tin Man"
  Wed Mar 22 13:34:01 ~/to_oz (master)
$ touch "Cowardly Lion"
  Wed Mar 22 13:34:08 ~/to_oz (master)
$ mkdir "Emerald City"
  Wed Mar 22 13:34:18 ~/to_oz (master)
$ mv Scarecrow,"Tin Man","Cowardly Lion" "Emerald City"
mv: rename Scarecrow,Tin Man,Cowardly Lion to Emerald City/Scarecrow,Tin Man,Cowardly Lion: No such file or directory
  Wed Mar 22 13:35:15 ~/to_oz (master)
$ mv Scarecrow "Emerald City"
  Wed Mar 22 13:36:00 ~/to_oz (master)
$ mv "Tin Man" "Emerald City"
  Wed Mar 22 13:36:11 ~/to_oz (master)
$ mv "Cowardly Lion" "Emerald City"
  Wed Mar 22 13:36:29 ~/to_oz (master)
$ cd oz
  Wed Mar 22 13:36:43 ~/to_oz/oz (master)
$ rm "Wicked Witch of the West"
  Wed Mar 22 13:36:55 ~/to_oz/oz (master)
$ echo "diploma" >> 
-bash: syntax error near unexpected token `newline'
  Wed Mar 22 13:38:56 ~/to_oz/oz (master)
$ cd ..
  Wed Mar 22 13:39:38 ~/to_oz (master)
$ cd "Emerald City"
  Wed Mar 22 13:39:58 ~/to_oz/Emerald City (master)
$ echo "diploma" >> Scarecrow
  Wed Mar 22 13:40:17 ~/to_oz/Emerald City (master)
$ echo "Heart Shaped Watch" >> "Tin Man"
  Wed Mar 22 13:40:37 ~/to_oz/Emerald City (master)
$ echo "Medal" >> Lion
  Wed Mar 22 13:40:58 ~/to_oz/Emerald City (master)
$

**Comment by jsm13** [comment]
👍
