### ISSUE TITLE
Yun Day 1 HW

### ISSUE THREAD

**Issue by hh747hh** [ga-wdi-exercises/to_oz#22]
~ (master) 
$ mkdir House
~ (master) 
$ cd House/
~/House (master) 
$ touch Dorothy
~/House (master) 
$ touch Toto
~/House (master) 
$ cd ..
~ (master) 
$ cd House
~/House (master) 
$ mkdir Oz
~/House (master) 
$ cd Oz
~/House/Oz (master) 
$ touch Good_Witch_of_the_North Good_Witch_of_the_South Wicked_Witch_of_the_East Wicked_Witch_of_the_West
~/House/Oz (master) 
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_East
Good_Witch_of_the_South     Wicked_Witch_of_the_West
~/House/Oz (master) 
$ rm Wicked_Witch_of_the_East
~/House/Oz (master) 
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
~/House/Oz (master) 
$ cd House
-bash: cd: House: No such file or directory
~/House/Oz (master) 
$ cd ..
~/House (master) 
$ mv Dorothy ~/Oz
~/House (master) 
$ touch Scarecrow
~/House (master) 
$ touch Tin_Man
~/House (master) 
$ touch Cowardly_Lion
~/House (master) 
$ touch mkdir Emerald_City
~/House (master) 
$ mv Scarecrow Tin_Man Cowardly_Lion ~/Emerald_City
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/House (master) 
$ ls
Cowardly_Lion   Oz      Tin_Man     mkdir
Emerald_City    Scarecrow   Toto
~/House (master) 
$ mv Scarecrow ~/Emerald_City
~/House (master) 
$ mv Tin_Man ~/Emerald_City
~/House (master) 
$ mv Cowardly_Lion ~/Emerald_City
~/House (master) 
$ touch Flying_Monkey
~/House (master) 
$ rm Wicked_Witch_of_the_West
rm: Wicked_Witch_of_the_West: No such file or directory
~/House (master) 
$ ls
Emerald_City    Flying_Monkey   Oz      Toto        mkdir
~/House (master) 
$ cd Oz
~/House/Oz (master) 
$ rm Wicked_Witch_of_the_West
~/House/Oz (master) 
$ echo "a diploma">>Scarecrow
~/House/Oz (master) 
$ echo "a tin shaped heart" >> Tin_Man
~/House/Oz (master) 
$ echo "a medal">>Lion
~/House/Oz (master) 
$ ls

**Comment by RobertAKARobin** [comment]
Nice!
