### ISSUE TITLE
CLI HW Jeong Hoon Koo

### ISSUE THREAD

**Issue by jkoo87** [ga-wdi-exercises/to_oz#221]
$ mkdir House
  Wed Mar 22 21:33:33 ~ (master *+)
$ cd House
  Wed Mar 22 21:33:37 ~/House (master *+)
$ touch Dorothy Toto
  Wed Mar 22 21:33:46 ~/House (master *+)
$ mkdir Oz
  Wed Mar 22 21:33:51 ~/House (master *+)
$ cd oz
  Wed Mar 22 21:33:53 ~/House/oz (master *+)
$ touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
  Wed Mar 22 21:33:58 ~/House/oz (master *+)
$ cd ..
  Wed Mar 22 21:34:03 ~/House (master *+)
$ cd oz
  Wed Mar 22 21:34:43 ~/House/oz (master *+)
$ rm -rf Wicked_Witch_of_the_East
  Wed Mar 22 21:34:59 ~/House/oz (master *+)
$ cd ..
  Wed Mar 22 21:35:03 ~/House (master *+)
$ mv Dorothy Oz
  Wed Mar 22 21:35:14 ~/House (master *+)
$ ls
Oz	Toto
  Wed Mar 22 21:35:16 ~/House (master *+)
$ touch Scarecrow Tin_Man Cowardly_Lion
  Wed Mar 22 21:35:45 ~/House (master *+)
$ mkdir Emerald_City
  Wed Mar 22 21:35:58 ~/House (master *+)
$ mv Scarecrow Tin_Man Cowardly_Lion Emerald_city
  Wed Mar 22 21:36:12 ~/House (master *+)
$ ls
Emerald_City	Oz		Toto
  Wed Mar 22 21:36:16 ~/House (master *+)
$ cd Oz
  Wed Mar 22 21:36:54 ~/House/Oz (master *+)
$ touch Flying_Monkeys
  Wed Mar 22 21:37:03 ~/House/Oz (master *+)
$ ls
Dorothy				Good_Witch_of_the_South
Flying_Monkeys			Wicked_Witch_of_the_West
Good_Witch_of_the_North
  Wed Mar 22 21:37:06 ~/House/Oz (master *+)
$ rm -rf Wicked_Witch_of_the_West 
  Wed Mar 22 21:37:21 ~/House/Oz (master *+)
$ cd ..
  Wed Mar 22 21:37:27 ~/House (master *+)
$ cd Emerald_city
  Wed Mar 22 21:37:33 ~/House/Emerald_city (master *+)
$ echo "diploma" >> Scarecrow
  Wed Mar 22 21:44:55 ~/House/Emerald_city (master *+)
$ echo "heart shaped watch" >> Tin_Man
  Wed Mar 22 21:45:18 ~/House/Emerald_city (master *+)
$ echo "medal" >> Cowardly_Lion

**Comment by juancgarcia** [comment]
👍
