### ISSUE TITLE
Luisa Gonzalez-To OZ

### ISSUE THREAD

**Issue by lgmusic24** [ga-wdi-exercises/to_oz#222]
$ mkdir house
mkdir: house: File exists
  Thu Mar 23 10:46:55 ~
$ touch Dorothy
  Thu Mar 23 10:48:19 ~
$ touch Toto
  Thu Mar 23 10:48:42 ~
$ ls house
North	Oz	South	West
  Thu Mar 23 10:48:53 ~
$ git mv Dorothy house
fatal: Not a git repository (or any of the parent directories): .git
  Thu Mar 23 10:54:37 ~
$ mv Dorothy
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 10:54:53 ~
$ mv Dorothy to house
mv: rename to to house/to: No such file or directory
  Thu Mar 23 10:59:28 ~
$ mv Dorothy/house
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 10:59:53 ~
$ ls house
Dorothy	North	Oz	South	West
  Thu Mar 23 11:00:12 ~
$ mv Toto/house
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:00:47 ~
$ ls house
Dorothy	North	Oz	South	West
  Thu Mar 23 11:00:55 ~
$ mv Toto
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:01:32 ~
$ ls house
Dorothy	North	Oz	South	West
  Thu Mar 23 11:01:37 ~
$ mv Toto to house
mv: rename to to house/to: No such file or directory
  Thu Mar 23 11:03:39 ~
$ ls house
Dorothy	North	Oz	South	Toto	West
  Thu Mar 23 11:03:42 ~
$ mkdir Oz
  Thu Mar 23 11:04:21 ~
$ mv Good Witch of the North/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:05:50 ~
$ ls Oz
  Thu Mar 23 11:05:58 ~
$ mv Good Witch of the North to Oz
mv: rename Good to Oz/Good: No such file or directory
mv: rename Witch to Oz/Witch: No such file or directory
mv: rename of to Oz/of: No such file or directory
mv: rename the to Oz/the: No such file or directory
mv: rename North to Oz/North: No such file or directory
mv: rename to to Oz/to: No such file or directory
  Thu Mar 23 11:06:20 ~
$ ls Oz
  Thu Mar 23 11:06:28 ~
$ mkdir OZ
mkdir: OZ: File exists
  Thu Mar 23 11:07:53 ~
$ mv Good Witch of the North 
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:08:24 ~
$ mv Good Witch of the Nort/OZ
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:08:44 ~
$ ls OZ
  Thu Mar 23 11:08:53 ~
$ mv North Witch to OZ
mv: rename North to OZ/North: No such file or directory
mv: rename Witch to OZ/Witch: No such file or directory
mv: rename to to OZ/to: No such file or directory
  Thu Mar 23 11:10:35 ~
$ mv North to OZ
mv: rename North to OZ/North: No such file or directory
mv: rename to to OZ/to: No such file or directory
  Thu Mar 23 11:11:00 ~
$ ls OZ
  Thu Mar 23 11:11:23 ~
$ mv East to Oz/East
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:12:01 ~
$ ls Oz
  Thu Mar 23 11:12:10 ~
$ mkdir OZ
mkdir: OZ: File exists
  Thu Mar 23 11:12:22 ~
$ ls house
Dorothy	North	Oz	South	Toto	West
  Thu Mar 23 11:12:31 ~
$ ls Oz
  Thu Mar 23 11:12:43 ~
$ mkdir Oz
mkdir: Oz: File exists
  Thu Mar 23 11:12:59 ~
$ cd Oz
  Thu Mar 23 11:13:22 ~/Oz
$ mv East to OZ
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:13:55 ~/Oz
$ ls Oz
ls: Oz: No such file or directory
  Thu Mar 23 11:14:09 ~/Oz
$ mkdir Oz
  Thu Mar 23 11:14:19 ~/Oz
$ mv North Witch/Oz
mv: rename North to Witch/Oz: No such file or directory
  Thu Mar 23 11:15:20 ~/Oz
$ mv East Witch/Oz
mv: rename East to Witch/Oz: No such file or directory
  Thu Mar 23 11:15:36 ~/Oz
$ mv South Witch/Oz
mv: rename South to Witch/Oz: No such file or directory
  Thu Mar 23 11:15:52 ~/Oz
$ mv West Witch/Oz
mv: rename West to Witch/Oz: No such file or directory
  Thu Mar 23 11:16:03 ~/Oz
$ ls 0z
ls: 0z: No such file or directory
  Thu Mar 23 11:16:52 ~/Oz
$ ls -a
.	..	Oz
  Thu Mar 23 11:16:58 ~/Oz
$ ls ..Oz
ls: ..Oz: No such file or directory
  Thu Mar 23 11:17:13 ~/Oz
$ ls Oz 
  Thu Mar 23 11:17:36 ~/Oz
$ ls dir
ls: dir: No such file or directory
  Thu Mar 23 11:19:06 ~/Oz
$ touch North Witch
  Thu Mar 23 11:20:30 ~/Oz
$ mv North Witch/Oz
mv: rename North to Witch/Oz: Not a directory
  Thu Mar 23 11:20:43 ~/Oz
$ mv Witch of North/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:21:19 ~/Oz
$ ls Oz
  Thu Mar 23 11:21:29 ~/Oz
$ ls
North	Oz	Witch
  Thu Mar 23 11:22:18 ~/Oz
$ rmdir Witch
rmdir: Witch: Not a directory
  Thu Mar 23 11:22:45 ~/Oz
$ rm Witch
  Thu Mar 23 11:23:20 ~/Oz
$ ls 
North	Oz
  Thu Mar 23 11:23:27 ~/Oz
$ rm Oz
rm: Oz: is a directory
  Thu Mar 23 11:24:05 ~/Oz
$ rmdir Oz 
  Thu Mar 23 11:25:14 ~/Oz
$ ls
North
  Thu Mar 23 11:25:18 ~/Oz
$ touch East
  Thu Mar 23 11:25:49 ~/Oz
$ mv East/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:26:11 ~/Oz
$ ls
East	North
  Thu Mar 23 11:26:19 ~/Oz
$ touch South/Oz
touch: South/Oz: No such file or directory
  Thu Mar 23 11:27:09 ~/Oz
$ touch South
  Thu Mar 23 11:27:20 ~/Oz
$ mv South/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:27:27 ~/Oz
$ ls
East	North	South
  Thu Mar 23 11:27:30 ~/Oz
$ touch West
  Thu Mar 23 11:27:41 ~/Oz
$ mv West/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:27:56 ~/Oz
$ ls Oz
ls: Oz: No such file or directory
  Thu Mar 23 11:28:03 ~/Oz
$ ls
East	North	South	West
  Thu Mar 23 11:28:10 ~/Oz
$ rm East
  Thu Mar 23 11:28:30 ~/Oz
$ ls
North	South	West
  Thu Mar 23 11:28:32 ~/Oz
$ touch Dorothy
  Thu Mar 23 11:28:42 ~/Oz
$ mv Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:28:50 ~/Oz
$ ls 
Dorothy	North	South	West
  Thu Mar 23 11:28:56 ~/Oz
$ touch Scarecrow
  Thu Mar 23 11:29:24 ~/Oz
$ touch Tin Man
  Thu Mar 23 11:29:32 ~/Oz
$ touch Cowardly Lion
  Thu Mar 23 11:29:41 ~/Oz
$ mkdir Emerald City
  Thu Mar 23 11:29:55 ~/Oz
$ mv Scarecrow/Emerald City
mv: rename Scarecrow/Emerald to City/Emerald: Not a directory
  Thu Mar 23 11:30:35 ~/Oz
$  mkdir Emerald City
mkdir: Emerald: File exists
mkdir: City: File exists
  Thu Mar 23 11:31:29 ~/Oz
$ mv Scarecrow/Emerald City
mv: rename Scarecrow/Emerald to City/Emerald: Not a directory
  Thu Mar 23 11:31:55 ~/Oz
$ ls
City		Emerald		North		Tin
Cowardly	Lion		Scarecrow	West
Dorothy		Man		South
  Thu Mar 23 11:32:05 ~/Oz
$ rm Emerald
rm: Emerald: is a directory
  Thu Mar 23 11:40:14 ~/Oz
$ rm city
rm: city: is a directory
  Thu Mar 23 11:40:19 ~/Oz
$ ls
City		Emerald		North		Tin
Cowardly	Lion		Scarecrow	West
Dorothy		Man		South
  Thu Mar 23 11:40:22 ~/Oz
$ rmdir Emerald
  Thu Mar 23 11:40:54 ~/Oz
$ rmdir city
  Thu Mar 23 11:41:04 ~/Oz
$ ls 
Cowardly	Lion		North		South		West
Dorothy		Man		Scarecrow	Tin
  Thu Mar 23 11:41:18 ~/Oz
$ mkdir Emeraldcity
  Thu Mar 23 11:41:28 ~/Oz
$ pwd
/Users/lgmusic24/Oz
  Thu Mar 23 11:43:45 ~/Oz
$ ls
Cowardly	Emeraldcity	Man		Scarecrow	Tin
Dorothy		Lion		North		South		West
  Thu Mar 23 11:43:50 ~/Oz
$ mv Lion >> Emeraldcity
-bash: Emeraldcity: Is a directory
  Thu Mar 23 11:44:18 ~/Oz
$ ls
Cowardly	Emeraldcity	Man		Scarecrow	Tin
Dorothy		Lion		North		South		West
  Thu Mar 23 11:44:22 ~/Oz
$ mv Lion/Emeraldcity
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:44:57 ~/Oz
$ ls Emeraldcity
  Thu Mar 23 11:45:15 ~/Oz
$ mv Scarecrow to Emeraldcity
mv: rename to to Emeraldcity/to: No such file or directory
  Thu Mar 23 11:46:16 ~/Oz
$ mv Lion to Oz/Emeraldcity/
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:47:19 ~/Oz
$ ls Emeraldcity
Scarecrow
  Thu Mar 23 11:47:33 ~/Oz
$ mv Scarecrow to Oz/Emeraldcity/
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:50:51 ~/Oz
$ ls Emeraldcity
Scarecrow
  Thu Mar 23 11:50:58 ~/Oz
$ ls Emeraldcity
Scarecrow
  Thu Mar 23 11:51:42 ~/Oz
$ mv Lion to Oz/Emeraldcity/
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:52:02 ~/Oz
$ ls Emeraldcity
Scarecrow
  Thu Mar 23 11:52:09 ~/Oz
$ mv Tin Man to Oz/Emeraldcity/
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Thu Mar 23 11:52:52 ~/Oz
$ ls Emeraldcity
Scarecrow
  Thu Mar 23 11:53:04 ~/Oz
$ ls Oz
ls: Oz: No such file or directory
  Thu Mar 23 11:53:50 ~/Oz
$ ls *
Cowardly	Lion		North		Tin
Dorothy		Man		South		West

Emeraldcity:
Scarecrow
  Thu Mar 23 11:54:05 ~/Oz
$ mv Lion Emeraldcity/
  Thu Mar 23 11:54:46 ~/Oz
$ ls Emeraldcity
Lion		Scarecrow
  Thu Mar 23 11:54:54 ~/Oz
$ mv Tin Man Emeraldcity/
  Thu Mar 23 11:55:24 ~/Oz
$ ls Emeraldcity
Lion		Man		Scarecrow	Tin
  Thu Mar 23 11:55:34 ~/Oz
$ rm Tin
rm: Tin: No such file or directory
  Thu Mar 23 11:55:49 ~/Oz
$ rm Man
rm: Man: No such file or directory
  Thu Mar 23 11:55:57 ~/Oz
$ ls Emeraldcity
Lion		Man		Scarecrow	Tin
  Thu Mar 23 11:56:03 ~/Oz
$ mv "Tin Man" Emeraldcity/
mv: rename Tin Man to Emeraldcity/Tin Man: No such file or directory
  Thu Mar 23 11:57:28 ~/Oz
$ ls Emeraldcity
Lion		Man		Scarecrow	Tin
  Thu Mar 23 11:57:42 ~/Oz
$ rm Man 
rm: Man: No such file or directory
  Thu Mar 23 12:01:32 ~/Oz
$ ls 
Cowardly	Emeraldcity	South
Dorothy		North		West
  Thu Mar 23 12:01:42 ~/Oz
$ rm Emeraldcity/Man
  Thu Mar 23 12:02:19 ~/Oz
$ mv Emeraldcity/Tin Emeraldcity/"Tin Man"
  Thu Mar 23 12:04:21 ~/Oz
$ ls Emeraldcity
Lion		Scarecrow	Tin Man
  Thu Mar 23 12:04:27 ~/Oz
$ touch "Flying Monkeys"
  Thu Mar 23 12:07:04 ~/Oz
$ mv Flying_Monkeys/Emerald city
mv: rename Flying_Monkeys/Emerald to city: No such file or directory
  Thu Mar 23 12:08:29 ~/Oz
$ mv Flying Monkeys/Oz
mv: rename Flying to Monkeys/Oz: No such file or directory
  Thu Mar 23 12:09:03 ~/Oz
$ ls OZ
ls: OZ: No such file or directory
  Thu Mar 23 12:09:24 ~/Oz
$ ls Oz
ls: Oz: No such file or directory
  Thu Mar 23 12:09:34 ~/Oz
$ ls *
Cowardly	Flying Monkeys	South
Dorothy		North		West

Emeraldcity:
Lion		Scarecrow	Tin Man
  Thu Mar 23 12:09:51 ~/Oz
$ rm West
  Thu Mar 23 12:11:35 ~/Oz
$ ls *
Cowardly	Dorothy		Flying Monkeys	North		South

Emeraldcity:
Lion		Scarecrow	Tin Man
  Thu Mar 23 12:11:54 ~/Oz
$ echo "diploma" >Scarecrow
  Thu Mar 23 12:21:09 ~/Oz
$ open Scarecrow
  Thu Mar 23 12:21:33 ~/Oz
$ echo "heart shaped watch">Tin Man
  Thu Mar 23 12:22:41 ~/Oz
$ open "Tin Man"
The file /Users/lgmusic24/Oz/Tin Man does not exist.
  Thu Mar 23 12:22:52 ~/Oz
$ open Tin Man
The file /Users/lgmusic24/Oz/Man does not exist.
  Thu Mar 23 12:23:00 ~/Oz
$ echo "heart shaped watch">"Tin Man"
  Thu Mar 23 12:23:56 ~/Oz
$ open "Tin Man"
  Thu Mar 23 12:24:05 ~/Oz
$ echo "medal" >Lion
  Thu Mar 23 12:25:06 ~/Oz
$ open Lion
  Thu Mar 23 12:25:13 ~/Oz
$

**Comment by jsm13** [comment]
👍
