### ISSUE TITLE
CLI HW Scott

### ISSUE THREAD

**Issue by scottpiercew** [ga-wdi-exercises/to_oz#226]
Last login: Mon May  1 16:57:24 on ttys000
  Mon May 01 17:21:54 ~
$ cd wdi/homework
  Mon May 01 17:22:04 ~/wdi/homework
$ mkdir House
  Mon May 01 17:23:31 ~/wdi/homework
$ cd House
  Mon May 01 17:23:35 ~/wdi/homework/House
$ touch Dorothy Toto House
  Mon May 01 17:23:47 ~/wdi/homework/House
$ cd ..
  Mon May 01 17:23:56 ~/wdi/homework
$ mkdir Oz
  Mon May 01 17:24:03 ~/wdi/homework
$ cd Oz
  Mon May 01 17:24:10 ~/wdi/homework/Oz
$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
  Mon May 01 17:25:01 ~/wdi/homework/Oz
$ rm "Wicked Witch of the East"
  Mon May 01 17:25:26 ~/wdi/homework/Oz
$ cd ..
  Mon May 01 17:25:35 ~/wdi/homework
$ mv ~/wdi/homework/House/Dorothy ~/wdi/homework/Oz
  Mon May 01 17:27:51 ~/wdi/homework
$ cd OZ
  Mon May 01 17:29:07 ~/wdi/homework/OZ
$ touch "Scarecrow" "Tin Man" "Cowardly Lion"
  Mon May 01 17:30:15 ~/wdi/homework/OZ
$ mkdir "Emerald City"
  Mon May 01 17:32:29 ~/wdi/homework/OZ
$ mv Dorothy "Cowardly Lion" Scarecrow "Tin Man" -t ~/wdi/homework/Oz/"Emerald City"
mv: rename -t to /Users/scotty_pierce/wdi/homework/Oz/Emerald City/-t: No such file or directory
  Mon May 01 18:02:06 ~/wdi/homework/OZ
$ ls
Emerald City			Good Witch of the South
Good Witch of the North		Wicked Witch of the West
  Mon May 01 18:02:22 ~/wdi/homework/OZ
$ cd "Emerald City"
  Mon May 01 18:02:52 ~/wdi/homework/OZ/Emerald City
$ ls
Cowardly Lion	Dorothy		Scarecrow	Tin Man
  Mon May 01 18:02:53 ~/wdi/homework/OZ/Emerald City
$ cd ..
  Mon May 01 18:03:09 ~/wdi/homework/OZ
$ touch "Flying Monkeys.txt"
  Mon May 01 18:04:27 ~/wdi/homework/OZ
$ rm -rf "Wicked Witch of the West"
  Mon May 01 18:04:57 ~/wdi/homework/OZ
$ cd "Emerald City"
  Mon May 01 18:09:38 ~/wdi/homework/OZ/Emerald City
$ echo "diploma" >> Scarecrow
  Mon May 01 18:10:25 ~/wdi/homework/OZ/Emerald City
$ echo "heart shaped watch" 
  Mon May 01 18:10:40 ~/wdi/homework/OZ/Emerald City
$ 
  Mon May 01 18:10:40 ~/wdi/homework/OZ/Emerald City
$ echo "heart shaped watch" >> "Tin Man"
  Mon May 01 18:11:12 ~/wdi/homework/OZ/Emerald City
$ echo "medal" >> Lion
  Mon May 01 18:11:25 ~/wdi/homework/OZ/Emerald City
$

**Comment by scottpiercew** [comment]
Last login: Mon May  1 17:33:15 on ttys001
  Mon May 01 20:58:59 ~
$ cd wdi/homework
  Mon May 01 20:59:14 ~/wdi/homework
$ mkdir House
  Mon May 01 21:02:05 ~/wdi/homework
$ cd House
  Mon May 01 21:02:13 ~/wdi/homework/House
$ touch Dorothy.txt Toto.txt
  Mon May 01 21:02:42 ~/wdi/homework/House
$ cd ..
  Mon May 01 21:02:57 ~/wdi/homework
$ mkdir Oz
  Mon May 01 21:03:50 ~/wdi/homework
$ cd Oz
  Mon May 01 21:04:00 ~/wdi/homework/Oz
$ touch "Good Witch of the North.txt" "Wicked Witch of the East.txt" "Good Witch of the South.txt" "Wicked Witch of the West.txt"
  Mon May 01 21:05:45 ~/wdi/homework/Oz
$ rm -rf "Wicked Witch of the East"
  Mon May 01 21:06:34 ~/wdi/homework/Oz
$ cd ..
  Mon May 01 21:06:58 ~/wdi/homework
$ cd House
  Mon May 01 21:07:02 ~/wdi/homework/House
$ mv ~/wdi/homework/House/Dorothy ~/wdi/homework/Oz
mv: rename /Users/scotty_pierce/wdi/homework/House/Dorothy to /Users/scotty_pierce/wdi/homework/Oz/Dorothy: No such file or directory
  Mon May 01 21:08:05 ~/wdi/homework/House
$ mv ~/wdi/homework/House/Dorothy.txt ~/wdi/homework/Oz
  Mon May 01 21:11:38 ~/wdi/homework/House
$ cd ..
  Mon May 01 21:11:51 ~/wdi/homework
$ cd Oz
  Mon May 01 21:11:57 ~/wdi/homework/Oz
$ touch "Scarecrow.txt" "Tin Man.txt" "Cowardly Lion.txt"
  Mon May 01 21:12:48 ~/wdi/homework/Oz
$ mkdir "Emerald City"
  Mon May 01 21:13:01 ~/wdi/homework/Oz
$ mv Dorothy.txt "Cowardly Lion.txt" "Tin Man.txt" Scarecrow.txt -t ~/wdi/homework/Oz/"Emerald City"
mv: rename -t to /Users/scotty_pierce/wdi/homework/Oz/Emerald City/-t: No such file or directory
  Mon May 01 21:15:53 ~/wdi/homework/Oz
$ touch "Flying Monkeys.txt" 
  Mon May 01 21:18:29 ~/wdi/homework/Oz
$ rm -rf "Wicked Witch of the West.txt"
  Mon May 01 21:19:25 ~/wdi/homework/Oz
$ cd "Emerald City"
  Mon May 01 21:19:42 ~/wdi/homework/Oz/Emerald City
$ echo "diploma" >> Scarecrow.txt
  Mon May 01 21:20:36 ~/wdi/homework/Oz/Emerald City
$ echo "heart shaped watch" >> "Tin Man.txt"
  Mon May 01 21:21:55 ~/wdi/homework/Oz/Emerald City
$ echo "medal" >> Lion.txt
  Mon May 01 21:23:02 ~/wdi/homework/Oz/Emerald City
$

**Comment by nayana487** [comment]
👍
