### ISSUE TITLE
CLI HW (Danielle Fricke)

### ISSUE THREAD

**Issue by daniellefricke** [ga-wdi-exercises/to_oz#227]
Last login: Mon May  1 18:50:14 on ttys000
Danielles-MacBook-Pro:~ daniellefricke$ mkdir House
Danielles-MacBook-Pro:~ daniellefricke$ cd House
Danielles-MacBook-Pro:House daniellefricke$ touch Dorothy Toto
Danielles-MacBook-Pro:House daniellefricke$ mkdir Oz
Danielles-MacBook-Pro:House daniellefricke$ cd Oz
Danielles-MacBook-Pro:Oz daniellefricke$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
Danielles-MacBook-Pro:Oz daniellefricke$ rm "Wicked Witch of the East"
Danielles-MacBook-Pro:Oz daniellefricke$ cd ..
Danielles-MacBook-Pro:House daniellefricke$ mv Dorothy Oz
Danielles-MacBook-Pro:House daniellefricke$ ls
Oz	Toto
Danielles-MacBook-Pro:House daniellefricke$ cd Oz
Danielles-MacBook-Pro:Oz daniellefricke$ ls
Dorothy				Good Witch of the South
Good Witch of the North		Wicked Witch of the West
Danielles-MacBook-Pro:Oz daniellefricke$ touch "Scarecrow" "Tin Man" "Cowardly Lion"
Danielles-MacBook-Pro:Oz daniellefricke$ mkdir "Emerald City"
Danielles-MacBook-Pro:Oz daniellefricke$ mv "Scarecrow" "Tin Man" "Cowardly Lion" "Emerald City"
Danielles-MacBook-Pro:Oz daniellefricke$ cd Emerald City
-bash: cd: Emerald: No such file or directory
Danielles-MacBook-Pro:Oz daniellefricke$ cd "Emerald City"
Danielles-MacBook-Pro:Emerald City daniellefricke$ ls
Cowardly Lion	Scarecrow	Tin Man
Danielles-MacBook-Pro:Emerald City daniellefricke$ cd ..
Danielles-MacBook-Pro:Oz daniellefricke$ touch "Flying Monkeys"
Danielles-MacBook-Pro:Oz daniellefricke$ ls
Dorothy				Good Witch of the North
Emerald City			Good Witch of the South
Flying Monkeys			Wicked Witch of the West
Danielles-MacBook-Pro:Oz daniellefricke$ rm "Wicked Witch of the West"
Danielles-MacBook-Pro:Oz daniellefricke$ echo "Diploma" > "Scarecrow"
Danielles-MacBook-Pro:Oz daniellefricke$ echo " Heart shoped watch" > "Tin Man"
Danielles-MacBook-Pro:Oz daniellefricke$ echo "Medal" > "Cowardly Lion"
Danielles-MacBook-Pro:Oz daniellefricke$

**Comment by amaseda** [comment]
:+1:
