### ISSUE TITLE
CLI HW (Tarik Kazanci)

### ISSUE THREAD

**Issue by tarkzc** [ga-wdi-exercises/to_oz#229]
Tue May 02 00:36:13 ~
$ pwd
/Users/tarikkazanci
  Tue May 02 00:36:14 ~
$ mkdir House
  Tue May 02 00:36:20 ~
$ cd House
  Tue May 02 00:36:25 ~/House
$ touch "Dorothy" "Toto" 
  Tue May 02 00:36:30 ~/House
$ ls
Dorothy	Toto
  Tue May 02 00:36:31 ~/House
$ mkdir Oz 
  Tue May 02 00:36:37 ~/House
$ cd Oz 
  Tue May 02 00:36:43 ~/House/Oz
$  touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
  Tue May 02 00:36:54 ~/House/Oz
$ ls
Good Witch of the North		Wicked Witch of the East
Good Witch of the South		Wicked Witch of the West
  Tue May 02 00:37:00 ~/House/Oz
$ rm "Wicked Witch of the East"
  Tue May 02 00:37:43 ~/House/Oz
$ ls
Good Witch of the North		Wicked Witch of the West
Good Witch of the South
  Tue May 02 00:37:45 ~/House/Oz
$ ../
-bash: ../: is a directory
  Tue May 02 00:38:04 ~/House/Oz
$ cd ../
  Tue May 02 00:38:12 ~/House
$ mv ./"Dorothy" Oz 
  Tue May 02 00:39:58 ~/House
$ touch "Scarecrow" "Tin Man" "Cowardly Lion" 
  Tue May 02 00:41:49 ~/House
$ mkdir "Emerald City" 
  Tue May 02 00:42:00 ~/House
$ touch "the gang" 
  Tue May 02 00:42:38 ~/House
$ mv ./"the gang" "Emerald City" 
  Tue May 02 00:43:18 ~/House
$ cd "Emerald City"
  Tue May 02 00:43:28 ~/House/Emerald City
$ ls
the gang
  Tue May 02 00:43:30 ~/House/Emerald City
$ cd ../
  Tue May 02 00:43:52 ~/House
$ cd Oz 
  Tue May 02 00:44:05 ~/House/Oz
$ touch "Flying Monkeys" 
  Tue May 02 00:44:24 ~/House/Oz
$ ls
Dorothy				Good Witch of the South
Flying Monkeys			Wicked Witch of the West
Good Witch of the North
  Tue May 02 00:44:52 ~/House/Oz
$ rm "Wicked Witch of the West"
  Tue May 02 00:45:26 ~/House/Oz
$ ls
Dorothy			Good Witch of the North
Flying Monkeys		Good Witch of the South
  Tue May 02 00:45:28 ~/House/Oz
$ 
  [Restored May 2, 2017, 8:21:23 AM]
Last login: Tue May  2 08:21:23 on ttys000
Restored session: Tue May  2 00:55:06 EDT 2017
  Tue May 02 08:21:24 ~/House/Oz
$ echo "diploma" > "Scarecrow"
  Tue May 02 08:29:01 ~/House/Oz
$ echo "heart shaped watch" > "Tin Man" 
  Tue May 02 08:31:25 ~/House/Oz
$ echo "medal" > "Cowardly Lion" 
  Tue May 02 08:32:42 ~/House/Oz

**Comment by superbuggy** [comment]
Perfect! 👌
