### ISSUE TITLE
CLI HW (Sonny Keobounphanh)

### ISSUE THREAD

**Issue by sonnykbp** [ga-wdi-exercises/to_oz#230]
$ mkdir House
$ cd House
$ touch Dorothy Toto
$ cd ../
$ mkdir Oz
$ cd Oz
$ touch Good-Witch-of-the-North Wicked-Witch-of-the-East Good-Witch-of-the-South Wicked-Witch-of-the-West
$ rm Wicked-Witch-of-the-East
$ cd ../House
$ mv Dorothy ../Oz
$ cd ../Oz
$ touch Scarecrow Tin-Man Cowardly-Lion
$ cd ../
$ mkdir Emerald-City
$ cd Oz
$ mv Scarecrow Tin-Man Cowardly-Lion ../Emerald-City
$ cd ../Oz
$ touch Flying-Monkeys
$ rm Wicked-Witch-of-the-West
$ cd ../Emerald-City
$ echo "diploma" >> Scarecrow
$ echo "heart shaped watch" >> Tin-Man
$ echo "medal" >> Cowardly-Lion

**Comment by nayana487** [comment]
👍
