### ISSUE TITLE
CLI HW TO OZ

### ISSUE THREAD

**Issue by AskForTheWolf** [ga-wdi-exercises/to_oz#231]
wolf@WOLF:~/Desktop/wdi/homework$ mkdir to_oz
wolf@WOLF:~/Desktop/wdi/homework$ cd to_oz/
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ mkdir House
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ touch Dorothy Toto
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ ls
Dorothy  House  Toto
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ mv Dorothy House
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ mv Toto House
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ mkdir Oz
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ cd Oz
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ touch Good_Witch_Of_The_North
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ touch Good_Witch_Of_The_South
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ touch Wicked_Witch_Of_The_East
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ touch Wicked_Witch_Of_The_West
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ rm Wicked_Witch_Of_The_East 
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ cd..
cd..: command not found
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ cd House
bash: cd: House: No such file or directory
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ ls
Good_Witch_Of_The_North  Good_Witch_Of_The_South  Wicked_Witch_Of_The_West
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ cd ..
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ cd House
wolf@WOLF:~/Desktop/wdi/homework/to_oz/House$ mv Dorothy ../Oz
wolf@WOLF:~/Desktop/wdi/homework/to_oz/House$ cd ..
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ touch Scarecrow
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ touch Tin_Man
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ touch Cowardly_Lion
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ mkdir Emerald_City
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ mv Scarecrow Emerald_City/
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ mv Tin_Man Emerald_City/
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ mv Cowardly_Lion Emerald_City/
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ cd Oz
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ touch Flying_Monkeys
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ rm Wicked_Witch_Of_The_West 
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ ls
Dorothy  Flying_Monkeys  Good_Witch_Of_The_North  Good_Witch_Of_The_South
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ cd..
cd..: command not found
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ ls
Dorothy  Flying_Monkeys  Good_Witch_Of_The_North  Good_Witch_Of_The_South
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Oz$ cd ..
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ ls
Emerald_City  House  Oz
wolf@WOLF:~/Desktop/wdi/homework/to_oz$ cd Emerald_City/
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Emerald_City$ ls
Cowardly_Lion  Scarecrow  Tin_Man
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Emerald_City$ echo "diploma" >> Scarecrow 
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Emerald_City$ echo "heart_shaped_watch" >> Tin_Man 
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Emerald_City$ echo "medal" >> Cowardly_Lion 
wolf@WOLF:~/Desktop/wdi/homework/to_oz/Emerald_City$

**Comment by superbuggy** [comment]
👌 Nice!

```bash
 $ mkdir "Wicked Witch of the West"
 $ touch File\ Name\ With\ Spaces\ Using\ Backslash
```

`\` is used here as an ***escape character***, meaning that it causes the character immediately after it to be designated as a character or symbol, in this case, a space (` `), rather than a separator that goes between arguments.

If we entered mkdir Good Witch of the East, we'd get 5 folders respectively named `Good`, `Witch`, `of`, `the`, and `East`.

---

> Side Note on `~`

`~` in GitHub flavored markdown, `~` is used as a ~strike through~ delimiter (actual text: `~strike through~`).
