### ISSUE TITLE
CLI HW (Tim Chase)

### ISSUE THREAD

**Issue by Tchase44** [ga-wdi-exercises/to_oz#232]
$ mkdir House 
$ cd House
$ touch Dorothy.txt Toto.txt
$ cd ..
$ mkdir Oz
$ cd Oz
$ touch good_witch_of_the_north.txt wicked_witch_of_the_east.txt good_witch_of_the_south.txt wicked_witch_of_the_west.txt
$ rm wicked_witch_of_the_east.txt
$ mv ../House/Dorothy.txt
$ touch Scarecrow.txt Tin-man.txt Cowardly-lion.txt
$ mkdir Emerald-City
$ cd Emerald-City
$ mv ../Scarecrow.txt .
$ mv ../Tin-man.txt .
$ mv ../Cowardly-lion.txt . 
$ mv ../Dorothy.txt .
$ cd ..
$ touch Flying-Monkeys.txt
$  rm -rf wicked_witch_of_the_west.txt
$ cd Emerald-City
$ echo "Dimpola" >> Scarecrow.txt
$ echo "Heart Shaped Watch" >> Tin-man.txt
$ echo "Medal" >> Cowardly-lion.txt

**Comment by amaseda** [comment]
:+1:
