### ISSUE TITLE
To Oz, from Bao

### ISSUE THREAD

**Issue by BaoPham92** [ga-wdi-exercises/to_oz#233]
$ ls
  Tue May 02 17:46:54 ~/wdi/homework
$ mkdir "TO OZ"
  Tue May 02 17:47:32 ~/wdi/homework
$ cd "TO OZ"
  Tue May 02 17:47:40 ~/wdi/homework/TO OZ
$ mkdir house
  Tue May 02 17:48:48 ~/wdi/homework/TO OZ
$ mkdir oz
  Tue May 02 17:48:52 ~/wdi/homework/TO OZ
$ cd house
  Tue May 02 17:49:00 ~/wdi/homework/TO OZ/house
$ touch dorothy.txt
  Tue May 02 17:49:20 ~/wdi/homework/TO OZ/house
$ touch toto.txt
  Tue May 02 17:49:32 ~/wdi/homework/TO OZ/house
$ cd ..
  Tue May 02 17:49:36 ~/wdi/homework/TO OZ
$ cd oz
  Tue May 02 17:49:42 ~/wdi/homework/TO OZ/oz
$ touch "Good Witch of the North".txt
  Tue May 02 17:51:07 ~/wdi/homework/TO OZ/oz
$ touch "Good Witch of the South".txt
  Tue May 02 17:51:15 ~/wdi/homework/TO OZ/oz
$ touch "Wicked Witch Of The East".txt
  Tue May 02 17:51:38 ~/wdi/homework/TO OZ/oz
$ touch "Wicked Witch Of The West".txt
  Tue May 02 17:51:45 ~/wdi/homework/TO OZ/oz
$ pwd
/Users/haven/wdi/homework/TO OZ/oz
  Tue May 02 17:52:56 ~/wdi/homework/TO OZ/oz
$ mv ~/w
wdi/   world/
  Tue May 02 17:52:56 ~/wdi/homework/TO OZ/oz
$ mv ~/wdi/homework/TO\ OZ/house/dorothy.txt .
  Tue May 02 17:55:34 ~/wdi/homework/TO OZ/oz
$ ls
Good Witch of the North.txt	Wicked Witch Of The East.txt	dorothy.txt
Good Witch of the South.txt	Wicked Witch Of The West.txt
  Tue May 02 17:55:39 ~/wdi/homework/TO OZ/oz
$ rm  "Wicked Witch Of The East".txt
  Tue May 02 18:02:21 ~/wdi/homework/TO OZ/oz
$ touch Scarecrow.txt
  Tue May 02 18:03:09 ~/wdi/homework/TO OZ/oz
$ touch "Tin Man".txt
  Tue May 02 18:03:26 ~/wdi/homework/TO OZ/oz
$ touch "Cowardly Lion".txt
  Tue May 02 18:03:40 ~/wdi/homework/TO OZ/oz
$ mkdir "Emerald City"
  Tue May 02 18:04:17 ~/wdi/homework/TO OZ/oz
$ mv "Tin Man".txt "Cowardly Lion".txt Scarecrow.txt /"Emerald City"
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue May 02 18:07:20 ~/wdi/homework/TO OZ/oz
$ mv "Tin Man".txt "Cowardly Lion".txt Scarecrow.txt "Emerald City"
  Tue May 02 18:09:14 ~/wdi/homework/TO OZ/oz
$ ls
Emerald City			Good Witch of the South.txt	dorothy.txt
Good Witch of the North.txt	Wicked Witch Of The West.txt
  Tue May 02 18:09:17 ~/wdi/homework/TO OZ/oz
$ cd "Emerald City"
  Tue May 02 18:09:27 ~/wdi/homework/TO OZ/oz/Emerald City
$ ls
Cowardly Lion.txt	Scarecrow.txt		Tin Man.txt
  Tue May 02 18:09:28 ~/wdi/homework/TO OZ/oz/Emerald City
$ cd ..
  Tue May 02 18:09:47 ~/wdi/homework/TO OZ/oz
$ touch "Flying Monkeys"
  Tue May 02 18:10:15 ~/wdi/homework/TO OZ/oz
$ ls
Emerald City			Good Witch of the North.txt	Wicked Witch Of The West.txt
Flying Monkeys			Good Witch of the South.txt	dorothy.txt
  Tue May 02 18:10:18 ~/wdi/homework/TO OZ/oz
$ rm "Wicked Witch of the West".txt
  Tue May 02 18:15:07 ~/wdi/homework/TO OZ/oz
$ echo "DIPLOMA" >> "Emerald City"/Scarecrow
  Tue May 02 18:23:35 ~/wdi/homework/TO OZ/oz
$ echo "DIPLOMA" >> "Emerald City"/Scarecrow.txt
  Tue May 02 18:23:49 ~/wdi/homework/TO OZ/oz
$ cd "EMERALD CITY"
  Tue May 02 18:24:03 ~/wdi/homework/TO OZ/oz/EMERALD CITY
$ ls
Cowardly Lion.txt	Scarecrow		Scarecrow.txt		Tin Man.txt
  Tue May 02 18:24:05 ~/wdi/homework/TO OZ/oz/EMERALD CITY
$ rm scarecrow
  Tue May 02 18:24:21 ~/wdi/homework/TO OZ/oz/EMERALD CITY
$ ls
Cowardly Lion.txt	Scarecrow.txt		Tin Man.txt
  Tue May 02 18:24:24 ~/wdi/homework/TO OZ/oz/EMERALD CITY
$ cat scarecrow.txt
DIPLOMA
  Tue May 02 18:24:46 ~/wdi/homework/TO OZ/oz/EMERALD CITY
$ echo "DIPLOMA" >> "TIN MAN".txt
  Tue May 02 18:25:56 ~/wdi/homework/TO OZ/oz/EMERALD CITY
$ echo "Heart Shaped Watch" >> "TIN MAN".txt
  Tue May 02 18:27:43 ~/wdi/homework/TO OZ/oz/EMERALD CITY
$ echo "Medal" >> "COWARDLY LION".txt
  Tue May 02 18:28:15 ~/wdi/homework/TO OZ/oz/EMERALD CITY
$

**Comment by nayana487** [comment]
👍
