### ISSUE TITLE
CLI HW (USMAN AHMED)

### ISSUE THREAD

**Issue by usmanahmed090** [ga-wdi-exercises/to_oz#234]
mkdir house
cd house
touch dorothy toto
cd ..
mkdir oz
cd oz
touch good_witch_of_the_north
touch wicked_witch_of_the_east
touch good_witch_of_the_south
touch wicked_witch_of_the_west
rm wicked_witch_of_the_east
cd ..
mv /house/dorothy /desktop/oz
touch scarecrow tin_man cowardly_lion 
mkdir emerald_city
mv scarecrow emerald_city
mv tin_man emerald_city
mv cowardly_lion emerald_city
cd oz
touch flying_monkeys
rm oz/wicked_witch_of_the_east
cd emerald_city
echo diploma > scarecrow
echo heart_shaped_watch > tin_man
echo medal > cowardly_lion

**Comment by amaseda** [comment]
:+1:
