### ISSUE TITLE
CLI HW (Robert Lowe)

### ISSUE THREAD

**Issue by RobLowe1992** [ga-wdi-exercises/to_oz#235]
$ mkdir House
  Wed May 03 16:32:12 ~/wdi/homework/to_oz (master)
$ touch House/Dorothy House/Toto
  Wed May 03 16:33:06 ~/wdi/homework/to_oz (master *)
$ mkdir Oz
  Wed May 03 16:33:53 ~/wdi/homework/to_oz (master *)
$ cd Oz/
  Wed May 03 16:34:07 ~/wdi/homework/to_oz/Oz (master *)
$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"

$ rm "Wicked Witch of the East"
  Wed May 03 16:39:13 ~/wdi/homework/to_oz/Oz (master *)
$ mv ~/wdi/homework/to_oz/House/Dorothy .
  Wed May 03 16:39:44 ~/wdi/homework/to_oz/Oz (master *)

$ touch Scarecrow "Tin Man" "Cowardly Lion"
  Wed May 03 16:41:01 ~/wdi/homework/to_oz/Oz (master *)
$ mkdir "Emerald City"
  Wed May 03 16:43:22 ~/wdi/homework/to_oz/Oz (master *)
$ mv Scarecrow "Cowardly Lion" "Tin Man" Emerald\ City/
  Wed May 03 16:43:36 ~/wdi/homework/to_oz/Oz (master *)

$ touch "Flying Monkeys"
  Wed May 03 16:46:48 ~/wdi/homework/to_oz/Oz (master *)
$ rm Wicked\ Witch\ of\ the\ West 
  Wed May 03 16:47:21 ~/wdi/homework/to_oz/Oz (master *)
$ echo "diploma" >> Emerald\ City/Scarecrow 
  Wed May 03 16:48:13 ~/wdi/homework/to_oz/Oz (master *)
$ echo "heart shaped watch" >> Emerald\ City/Tin\ Man 
  Wed May 03 16:49:02 ~/wdi/homework/to_oz/Oz (master *)
$ echo "medal" >> Emerald\ City/Cowardly\ Lion 
  Wed May 03 16:49:37 ~/wdi/homework/to_oz/Oz (master *)

**Comment by superbuggy** [comment]
Well done! 👍
