### ISSUE TITLE
CLI Homework (Matt Filbert)

### ISSUE THREAD

**Issue by mattcfilbert** [ga-wdi-exercises/to_oz#238]
1. cd wdi
2. cd sandbox
3. mkdir house
4. cd house
5. touch Dorothy Toto
6. mkdir Oz
7. cd Oz
8. touch "Good Witch of the North" "Wicked Witch of the East” "Good Witch of the South" "Wicked Witch of the West”
9. rm “Wicked Witch of the East”
10. mv ../Dorothy ./
11. touch “Scarecrow” “Tin Man” “Cowardly Lion”
12. mkdir “Emerald City”
13. mv "Scarecrow" "Dorothy" "Cowardly Lion" “Tin Man” “Emerald City”
14. touch “Flying Monkeys”
15. rm “Wicked Witch of the West”
16. cd “Emerald City”
17. echo “diploma” >> Scarecrow
18. echo “heart shaped watch” >> “Tin Man”
19. echo “medal” >> “Cowardly Lion”

**Comment by AndyWhitley** [comment]
👍
