### ISSUE TITLE
CLI HW (Perry)

### ISSUE THREAD

**Issue by perryf** [ga-wdi-exercises/to_oz#239]
**To Oz?  To Oz!**

1.  mkdir house
2.  cd house
	touch Dorothy Toto
3.  mkdir Oz
4.  cd house
	touch ‘Good Witch of the North’ ‘Wicked Witch of the East’ ‘Good Witch of the South’ ‘Wicked Witch of the West’

**Ding Dong the Witch is Dead**

1.  rm ‘Wicked Witch of the East’
2.  cd ..
	mv Dorothy Oz/

**Follow the Yellow Brick Road**

1.  touch Scarecrow
2.  touch ‘Tin Man’
3.  touch ‘Cowardly Lion’
4.  mkdir ‘Emerald City’
5.  mv Dorothy ‘Emerald City’
	mv Scarecrow ‘Emerald City’
	mv ‘Tin Man’ ‘Emerald City’
	mv ‘Cowardly Lion’ ‘Emerald City’

**You Must Kill the Witch**

1.  touch ‘Flying Monkeys’
2.  rm ‘Wicked Witch of the West’
3.  i. echo ‘diploma’ >> Scarecrow
	ii. echo ‘heart shaped watch’ >> ‘Tin Man’
	iii. echo ‘medal’ >> ’Cowardly Lion’

**Comment by AndyWhitley** [comment]
👍
