### ISSUE TITLE
Fatai Day 1 HW

### ISSUE THREAD

**Issue by yinkaagiri** [ga-wdi-exercises/to_oz#24]
~/wdi
$ mkdir House; 
$ cd House; 
$ touch Dorothy Toto

$ cd ..; mkdir Oz; 
$ cd Oz; touch Good_Witch_of_the_North Wicked_witch_of_the_East Good_witch_of_the_South Wicked_witch_of_the_West

$ cd ..; rm -r Wicked_Witch_of_the_East; mv ~/wdi/House/Dortothy ~/wdi/Oz; 

$ cd Oz; touch Scarecrow Tin_Man Cowardly_Lion; mkdir Emerald_City; mv Scarecrow Tin_Man Cowardly_Lion ~/wdi/Emerald_City

$ cd Oz;  touch Flying_Monkeys; rm -r Wicked_witch_of the_West

$ echo “a diploma” >> Oz/Scarecrow; “ a heart shaped watch” >> wdi/Emerald_City/Tim_Man “a medal” >> wdi/Emerald_City/Cowardly_Lion

**Comment by RobertAKARobin** [comment]
I'm having trouble executing these commands. The second line throws an error.
