### ISSUE TITLE
Richard S.

### ISSUE THREAD

**Issue by RustyJackson** [ga-wdi-exercises/to_oz#241]
Last login: Mon Jun 26 16:26:51 on ttys003
Richards-MacBook-Pro:~ richardschram$ ls
Applications	Downloads	Music		fundimentals	wdi
Desktop		Library		Pictures	funny_things	world
Documents	Movies		Public		post.txt
Richards-MacBook-Pro:~ richardschram$ mkdir House
Richards-MacBook-Pro:~ richardschram$ pwd
/Users/richardschram
Richards-MacBook-Pro:~ richardschram$ cd House
Richards-MacBook-Pro:House richardschram$ touch Dorthy Toto
Richards-MacBook-Pro:House richardschram$ mkdir Oz
Richards-MacBook-Pro:House richardschram$ cd Oz
Richards-MacBook-Pro:Oz richardschram$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
Richards-MacBook-Pro:Oz richardschram$ rm Wicked Witch of the East
rm: Wicked: No such file or directory
rm: Witch: No such file or directory
rm: of: No such file or directory
rm: the: No such file or directory
rm: East: No such file or directory
Richards-MacBook-Pro:Oz richardschram$ rm "Wicked witch of the East"
Richards-MacBook-Pro:Oz richardschram$ cd -
/Users/richardschram/House
Richards-MacBook-Pro:House richardschram$ mv Dorothy Oz
mv: rename Dorothy to Oz/Dorothy: No such file or directory
Richards-MacBook-Pro:House richardschram$ mv Dorthy z
Richards-MacBook-Pro:House richardschram$ touch Scarecrow
Richards-MacBook-Pro:House richardschram$ touch "Tin Man"
Richards-MacBook-Pro:House richardschram$ touch "Cowardly Lion"
Richards-MacBook-Pro:House richardschram$ mkdir Emerald City"
> 
> q
> 
Richards-MacBook-Pro:House richardschram$ mkdir "Emerald City"
Richards-MacBook-Pro:House richardschram$ mv Scarecrow "Tin Man" "Emerald City"
Richards-MacBook-Pro:House richardschram$ mv "Cowardly Lion" "Emerald City"
Richards-MacBook-Pro:House richardschram$ cd Oz
Richards-MacBook-Pro:Oz richardschram$ touch "Flying Monkeys"
Richards-MacBook-Pro:Oz richardschram$ ls
Flying Monkeys			Good Witch of the South
Good Witch of the North		Wicked Witch of the West
Richards-MacBook-Pro:Oz richardschram$ rm "Wicked Witch of the West"
Richards-MacBook-Pro:Oz richardschram$ echo "diploma" > Scarecrow
Richards-MacBook-Pro:Oz richardschram$ echo "Heart shaped watch" > "Tin Man"
Richards-MacBook-Pro:Oz richardschram$ echo "medal" > "Cowardly Lion"
Richards-MacBook-Pro:Oz richardschram$ cat Tin\ Man 
Heart shaped watch
Richards-MacBook-Pro:Oz richardschram$ mv Tin\ Man tin-man.txt
Richards-MacBook-Pro:Oz richardschram$ echo "test" > new-file
Richards-MacBook-Pro:Oz richardschram$ echo "medal" > "../Emerald City/Cowardly Lion"
Richards-MacBook-Pro:Oz richardschram$ echo "heart shaped watch" > "../Emerald City/"Tin Man"
> 
Richards-MacBook-Pro:Oz richardschram$ echo "heart shaped watch" > "../Emerald City/Tin Man"
Richards-MacBook-Pro:Oz richardschram$ echo "diploma" > "../Emerald City/Scarecrow"
Richards-MacBook-Pro:Oz richardschram$

**Comment by AndyWhitley** [comment]
👍
