### ISSUE TITLE
CLI HW (Liz Jewell)

### ISSUE THREAD

**Issue by lizardbird** [ga-wdi-exercises/to_oz#243]
mkdir House
touch House/Dorothy House/Toto
mkdir Oz
touch Oz/"Good Witch of the North" Oz/"Wicked Witch of the East" Oz/"Good Witch of the South" Oz/"Wicked Witch of the West"
rm Oz/"Wicked Witch of the East"
mv House/Dorothy Oz/
touch Scarecrow "Tin Man" "Cowardly Lion"
mv Scarecrow "Emerald City"
mv "Tin Man" "Emerald City"
mv "Cowardly Lion" "Emerald City"
touch Oz/"Flying Monkeys"
rm Oz/"Wicked Witch of the West"
echo "A diploma for the Scarecrow" > "Emerald City"/Scarecrow
echo "A heart shaped watch for the Tin Man" > "Emerald City"/"Tin Man"
echo "A medal of courage for the Cowardly Lion" > "Emerald City"/"Cowardly Lion"

**Comment by AndyWhitley** [comment]
👍
