### ISSUE TITLE
CLI HW (Jessica Marie Barre)

### ISSUE THREAD

**Issue by jessamarie** [ga-wdi-exercises/to_oz#245]
$ mkdir House && cd House
$ touch Dorothy && touch Toto
$ cd ..
$ mkdir Oz && cd Oz
$ touch "Good Witch of the North"
$ touch "Wicked Witch of the East”
$ touch "Good Witch of the South"
$ touch "Wicked Witch of the West"
$ rm Wicked\ Witch\ of\ the\ East 
$ cd ..
$ mv House/Dorothy Oz/
$ touch Scarecrow
$ touch "Tin Man"
$ touch "Cowardly Lion"
$ mkdir "Emerald City"
$ mv Cowardly\ Lion Scarecrow Tin\ Man Emerald\ City/
$ cd Oz
$ touch "Flying Monkeys"
$ rm Wicked\ Witch\ of\ the\ West 
$ cd .. && cd Emerald\ City/
$ echo "diploma" > Scarecrow 
$ echo "heart-shaped watch" > Tin\ Man 
$ echo "medal" > Cowardly\ Lion

**Comment by juancgarcia** [comment]
Good Job!
