### ISSUE TITLE
CLI HW (alexKelly)

### ISSUE THREAD

**Issue by akelly92** [ga-wdi-exercises/to_oz#248]
Mon Jun 26 16:45:50 ~
$ mkdir house
  Mon Jun 26 16:46:03 ~
$ cd house
  Mon Jun 26 16:46:08 ~/house
$ touch dorthy.txt toto.txt
  Mon Jun 26 16:46:29 ~/house
$ cd ../
  Mon Jun 26 16:49:48 ~
$ mkdir oz
  Mon Jun 26 16:49:58 ~
$ cd oz
  Mon Jun 26 16:52:09 ~/oz
$ touch good_witch_of_the_north.txt wicked_witch_of_the_east.txt good_witch_of_the_south.txt wicked_witch_of_the_west.txt
  Mon Jun 26 16:52:22 ~/oz
$ rm wicked_witch_of_the_west.txt
  Mon Jun 26 16:55:19 ~/oz
$ cd ..
  Mon Jun 26 16:57:02 ~
$ mv house/dorthy.txt oz
  Mon Jun 26 16:58:06 ~
$ cd oz
  Mon Jun 26 16:58:15 ~/oz
$ ls
dorthy.txt			good_witch_of_the_south.txt
good_witch_of_the_north.txt	wicked_witch_of_the_east.txt
  Mon Jun 26 16:58:17 ~/oz
$ cd ..
  Mon Jun 26 17:01:47 ~
$ touch scareCrow.txt tinMan.txt cowardlyLion.txt
  Mon Jun 26 17:03:52 ~
$ mkdir emerald_city
  Mon Jun 26 17:04:07 ~
$ mv scareCrow.txt emerald_city
  Mon Jun 26 17:04:39 ~
$ ls
Applications		Movies			emerald_city		tinMan.txt
Desktop			Music			funny_things		wdi
Documents		Pictures		house			wdi_fundamentals
Downloads		Public			myhomework		world
Library			cowardlyLion.txt	oz
  Mon Jun 26 17:04:42 ~
$ mv tinMan.txt emerald_city
  Mon Jun 26 17:05:12 ~
$ mv cowardlyLion.txt emerald_city
  Mon Jun 26 17:05:53 ~
$ cd oz
  Mon Jun 26 17:06:32 ~/oz
$ touch flyingMonkeys.txt
  Mon Jun 26 17:06:59 ~/oz
$ ls
dorthy.txt			good_witch_of_the_north.txt	wicked_witch_of_the_east.txt
flyingMonkeys.txt		good_witch_of_the_south.txt
  Mon Jun 26 17:07:02 ~/oz
$ rm wicked_witch_of_the_east.txt
  Mon Jun 26 17:07:38 ~/oz
$ ls
dorthy.txt			good_witch_of_the_north.txt
flyingMonkeys.txt		good_witch_of_the_south.txt
  Tue Jun 27 08:43:52 ~/oz
$ cd ../
  Tue Jun 27 08:43:59 ~
$ cd emerald_city
  Tue Jun 27 08:44:28 ~/emerald_city
$ echo "diploma" > cowardlyLion.txt
  Tue Jun 27 08:45:23 ~/emerald_city
$ echo "heartShapedWatch" > tinMan.txt
  Tue Jun 27 08:46:17 ~/emerald_city
$ echo "medal" > scareCrow.txt
  Tue Jun 27 08:47:25 ~/emerald_city
$

**Comment by AndyWhitley** [comment]
👍
