### ISSUE TITLE
CLI Homework

### ISSUE THREAD

**Issue by TimGafvert** [ga-wdi-exercises/to_oz#249]
mkdir House
touch House/Toto
touch House/Dorothy
mkdir Oz
touch Oz/"Good Witch of the North"
touch Oz/"Wicked Witch of the East"
touch Oz/"Good Witch of the South"
touch Oz/"Wicked Witch of the West"
rm Oz/"Wicked Witch of the East"
mv House/Dorothy Oz/
touch Scarecrow "Tin Man" "Cowardly Lion" 
mkdir "Emerald City"
mv Scarecrow "Tin Man" "Cowardly Lion" "Emerald City"/
touch Oz/"Flying Monkeys"
rm Oz/"Wicked Witch of the West"
echo "diploma" >> "Emerald City"/Scarecrow
echo "heart" >> "Emerald City"/"Tin Man"
echo "medal" >> "Emerald City"/Lion

**Comment by juancgarcia** [comment]
Good Job!
