### ISSUE TITLE
CLI HW (Alex Wandres)

### ISSUE THREAD

**Issue by awandres** [ga-wdi-exercises/to_oz#250]
$ cd homework/
  Tue Jun 27 12:24:38 ~/Documents/wdi/homework
$ mkdir House
  Tue Jun 27 12:24:43 ~/Documents/wdi/homework
$ cd House/
  Tue Jun 27 12:24:50 ~/Documents/wdi/homework/House
$ touch Dorothy Toto
  Tue Jun 27 12:24:58 ~/Documents/wdi/homework/House
$ ls
Dorothy	Toto
  Tue Jun 27 12:24:59 ~/Documents/wdi/homework/House
$ cd ../
  Tue Jun 27 12:25:30 ~/Documents/wdi/homework
$ mkdir Oz
  Tue Jun 27 12:25:35 ~/Documents/wdi/homework
$ cd Oz
  Tue Jun 27 12:25:39 ~/Documents/wdi/homework/Oz
$ touch "Good Witch of the North"
  Tue Jun 27 12:25:48 ~/Documents/wdi/homework/Oz
$ ls
Good Witch of the North
  Tue Jun 27 12:25:49 ~/Documents/wdi/homework/Oz
$ touch "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
  Tue Jun 27 12:26:08 ~/Documents/wdi/homework/Oz
$ ls
Good Witch of the North		Good Witch of the South		Wicked Witch of the East	Wicked Witch of the West
  Tue Jun 27 12:26:09 ~/Documents/wdi/homework/Oz
$ rm Wicked\ Witch\ of\ the\ East 
  Tue Jun 27 12:26:39 ~/Documents/wdi/homework/Oz
$ cd ../House/
  Tue Jun 27 12:26:48 ~/Documents/wdi/homework/House
$ mv Dorothy ../Oz/
  Tue Jun 27 12:27:03 ~/Documents/wdi/homework/House
$ ls
Toto
  Tue Jun 27 12:27:07 ~/Documents/wdi/homework/House
$ cd ../Oz/
  Tue Jun 27 12:27:25 ~/Documents/wdi/homework/Oz
$ ls
Dorothy				Good Witch of the North		Good Witch of the South		Wicked Witch of the West
  Tue Jun 27 12:27:27 ~/Documents/wdi/homework/Oz
$ touch Scarecrow "Tin Man" "Cowardly Lion"
  Tue Jun 27 12:27:48 ~/Documents/wdi/homework/Oz
$ mkdir "Emerald City"
  Tue Jun 27 12:27:55 ~/Documents/wdi/homework/Oz
$ mv Scarecrow "Tin Man" "Cowardly Lion" Emerald\ City/
  Tue Jun 27 12:28:13 ~/Documents/wdi/homework/Oz
$ ls
Dorothy				Good Witch of the North		Wicked Witch of the West
Emerald City			Good Witch of the South
  Tue Jun 27 12:28:14 ~/Documents/wdi/homework/Oz
$ cd Emerald\ City/
  Tue Jun 27 12:28:19 ~/Documents/wdi/homework/Oz/Emerald City
$ ls
Cowardly Lion	Scarecrow	Tin Man
  Tue Jun 27 12:28:20 ~/Documents/wdi/homework/Oz/Emerald City
$ cd ../
  Tue Jun 27 12:28:41 ~/Documents/wdi/homework/Oz
$ touch "Flying Monkeys"
  Tue Jun 27 12:28:48 ~/Documents/wdi/homework/Oz
$ rm Wicked\ Witch\ of\ the\ West 
  Tue Jun 27 12:28:53 ~/Documents/wdi/homework/Oz
$ cd Emerald\ City/
  Tue Jun 27 12:37:59 ~/Documents/wdi/homework/Oz/Emerald City
$ echo "diploma" Scarecrow 
diploma Scarecrow
  Tue Jun 27 12:38:08 ~/Documents/wdi/homework/Oz/Emerald City
$ echo "diploma" > Scarecrow 
  Tue Jun 27 12:38:17 ~/Documents/wdi/homework/Oz/Emerald City
$ echo "heart shaped watch" > Tin\ Man 
  Tue Jun 27 12:38:27 ~/Documents/wdi/homework/Oz/Emerald City
$ echo "medal" > Lion
  Tue Jun 27 12:38:34 ~/Documents/wdi/homework/Oz/Emerald City
$ ls
Cowardly Lion	Lion		Scarecrow	Tin Man
  Tue Jun 27 12:38:35 ~/Documents/wdi/homework/Oz/Emerald City
$ echo "medal" > Cowardly\ Lion 
  Tue Jun 27 12:38:49 ~/Documents/wdi/homework/Oz/Emerald City
$

**Comment by juancgarcia** [comment]
Good Job!
