### ISSUE TITLE
CLI Homework (Jacob Greenwald)

### ISSUE THREAD

**Issue by jacobg1** [ga-wdi-exercises/to_oz#252]
mkdir House
touch House/Dorothy
touch House/Toto
mkdir Oz
touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
mv "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West" ~/Oz
rm Oz/"Wicked Witch of the East"
mv Dorothy Oz
touch Scarecrow "Tin Man" "Cowardly Lion"
mkdir "Emerald City"
mv Scarecrow "Tin Man" "Cowardly Lion" ~/"Emerald City"
touch Oz/"Flying Monkeys"
rm Oz/"Wicked Witch of the West"
echo "diploma" >> ~/"Emerald City"/Scarecrow
echo "heart shaped watch" >> ~/"Emerald City"/"Tin Man"
echo "medal" >> ~/"Emerald City"/"Cowardly Lion"

**Comment by jacobg1** [comment]
woo hoo!!

**Comment by juancgarcia** [comment]
Good Job!
