### ISSUE TITLE
CLI Homework

### ISSUE THREAD

**Issue by vsweeney** [ga-wdi-exercises/to_oz#254]
List of items for HW #1
mkdir House
cd house
touch Dorthy/Toto
mkdir Oz
touch Good Witch of the North
touch Wicked Witch of the East
touch Good Witch of the South
touch Wicked Witch of the West
rm Wicked Witch of the East
mv dorthy oz
touch  scarecrow
touch tin man
mkdir emerald city 
mv scarecrow emerald city
mv tim man emerald city
mv dorthy emerald city
mv toto emerald city
touch flying monkeys
rm wicked witch of the west
echo “diploma” > scarecrow
echo “heart shaped watch “ > tin man
echo “medal” > lion

**Comment by juancgarcia** [comment]
Good Job!

Be careful to check your directory every so ofter with `pwd`. It looks to me that you created `oz` inside of `house`. There should have been a command like `cd ../` to back out of the `house` folder before creating `oz`
