### ISSUE TITLE
CLI HW ( Josue Rosales)

### ISSUE THREAD

**Issue by jhosuedeveloper** [ga-wdi-exercises/to_oz#255]
$ pwd
/Users/user/wdi/homework
  Tue Jun 27 18:07:36 ~/wdi/homework
$ mkdir House
  Tue Jun 27 18:08:00 ~/wdi/homework
$ cd House
  Tue Jun 27 18:08:07 ~/wdi/homework/House
$ touch Dorothy Toto
  Tue Jun 27 18:08:31 ~/wdi/homework/House
$ mkdir Oz
  Tue Jun 27 18:08:44 ~/wdi/homework/House
$ cd Oz
  Tue Jun 27 18:08:46 ~/wdi/homework/House/Oz
$ touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
  Tue Jun 27 18:08:59 ~/wdi/homework/House/Oz
$ 
  Tue Jun 27 18:09:11 ~/wdi/homework/House/Oz
$ rm Wicked_Witch_of_the_East
  Tue Jun 27 18:09:44 ~/wdi/homework/House/Oz
$ mv cd ..
mv: rename cd to ../cd: No such file or directory
  Tue Jun 27 18:12:16 ~/wdi/homework/House/Oz
$ pwd
/Users/user/wdi/homework/House/Oz
  Tue Jun 27 18:12:18 ~/wdi/homework/House/Oz
$ cd ..
  Tue Jun 27 18:12:22 ~/wdi/homework/House
$ pwd
/Users/user/wdi/homework/House
  Tue Jun 27 18:12:24 ~/wdi/homework/House
$ ls
Dorothy	Oz	Toto
  Tue Jun 27 18:12:27 ~/wdi/homework/House
$ mv Dorothy Oz
  Tue Jun 27 18:40:55 ~/wdi/homework/House
$ pwd
/Users/user/wdi/homework/House
  Tue Jun 27 18:43:22 ~/wdi/homework/House
$ cd Oz
  Tue Jun 27 18:43:35 ~/wdi/homework/House/Oz
$ pwd
/Users/user/wdi/homework/House/Oz
  Tue Jun 27 18:43:42 ~/wdi/homework/House/Oz
$ touch Scarecrow
  Tue Jun 27 18:44:33 ~/wdi/homework/House/Oz
$ touch Tin_Man
  Tue Jun 27 18:44:41 ~/wdi/homework/House/Oz
$ touch Cowardly_Lion
  Tue Jun 27 18:44:51 ~/wdi/homework/House/Oz
$ mkdir Emerald_City
  Tue Jun 27 18:45:06 ~/wdi/homework/House/Oz
$ mv Scarecrow Tin_Man Cowardly_Lion /Emerald_City/
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jun 27 18:49:43 ~/wdi/homework/House/Oz
$ pwd
/Users/user/wdi/homework/House/Oz
  Tue Jun 27 18:50:15 ~/wdi/homework/House/Oz
$ touch Flying_Monkeys
  Tue Jun 27 18:50:28 ~/wdi/homework/House/Oz
$ rm Wicked_Witch_of_the_West
  Tue Jun 27 18:51:41 ~/wdi/homework/House/Oz
$ mv Scarecrow Tin_Man Coardly_Lion /Emerald_City/
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jun 27 18:52:27 ~/wdi/homework/House/Oz
$ mv Scarecrow.Tin_Man.Coardly_Lion /Emerald_City/
mv: rename Scarecrow.Tin_Man.Coardly_Lion to /Emerald_City/: No such file or directory
  Tue Jun 27 18:53:00 ~/wdi/homework/House/Oz
$ mv Scarecrow Tin_Man Coardly_Lion Emerald_City
mv: rename Coardly_Lion to Emerald_City/Coardly_Lion: No such file or directory
  Tue Jun 27 18:55:13 ~/wdi/homework/House/Oz
$ touch Scarecrow
  Tue Jun 27 18:56:12 ~/wdi/homework/House/Oz
$ rm Scarecrow
  Tue Jun 27 18:57:03 ~/wdi/homework/House/Oz
$ cd Emerald_city
  Tue Jun 27 18:57:15 ~/wdi/homework/House/Oz/Emerald_city
$ rm Scarecrow Tin_Man
  Tue Jun 27 18:57:25 ~/wdi/homework/House/Oz/Emerald_city
$ ls
  Tue Jun 27 18:57:27 ~/wdi/homework/House/Oz/Emerald_city
$ cd ..
  Tue Jun 27 18:57:29 ~/wdi/homework/House/Oz
$ ls
Cowardly_Lion		Emerald_City		Good_Witch_of_the_North
Dorothy			Flying_Monkeys		Good_Witch_of_the_South
  Tue Jun 27 18:57:32 ~/wdi/homework/House/Oz
$ touch Scarecrow Tin_Man Cowardly_lion
  Tue Jun 27 18:58:02 ~/wdi/homework/House/Oz
$ ls
Cowardly_Lion		Emerald_City		Good_Witch_of_the_North	Scarecrow
Dorothy			Flying_Monkeys		Good_Witch_of_the_South	Tin_Man
  Tue Jun 27 18:58:03 ~/wdi/homework/House/Oz
$ pwd
/Users/user/wdi/homework/House/Oz
  Tue Jun 27 18:58:46 ~/wdi/homework/House/Oz
$ ls
Cowardly_Lion		Emerald_City		Good_Witch_of_the_North	Scarecrow
Dorothy			Flying_Monkeys		Good_Witch_of_the_South	Tin_Man
  Tue Jun 27 18:58:49 ~/wdi/homework/House/Oz
$ mv Scarecrow Cowardly_Lion Tin_Man Emerald_City
  Tue Jun 27 19:00:02 ~/wdi/homework/House/Oz
$ pwd
/Users/user/wdi/homework/House/Oz
  Tue Jun 27 19:01:16 ~/wdi/homework/House/Oz
$ cd Emerald_City
  Tue Jun 27 19:01:34 ~/wdi/homework/House/Oz/Emerald_City
$ echo 'a diploma' > Scarecrow
  Tue Jun 27 19:02:32 ~/wdi/homework/House/Oz/Emerald_City
$ echo 'a heart shaped watch' > Tin_Man
  Tue Jun 27 19:02:54 ~/wdi/homework/House/Oz/Emerald_City
$ echo 'a Medal' >> CowardLy_Lion
  Tue Jun 27 19:03:23 ~/wdi/homework/House/Oz/Emerald_City
$ atom Cowardly_Lion
  Tue Jun 27 19:03:39 ~/wdi/homework/House/Oz/Emerald_City

**Comment by jhosuedeveloper** [comment]
zorry for the length, I had to go back some steps.

**Comment by AndyWhitley** [comment]
👍
