### ISSUE TITLE
CLI HW (Jonathan Polakoff)

### ISSUE THREAD

**Issue by jdpolakoff** [ga-wdi-exercises/to_oz#256]
$ cd /users
  Tue Jun 27 13:38:31 /users
$ ls
Guest	Shared	burrito
  Tue Jun 27 13:38:33 /users
$ cd burrito
  Tue Jun 27 13:38:37 /users/burrito
$ cd wdi
  Tue Jun 27 13:38:48 /users/burrito/wdi
$ cd homework
  Tue Jun 27 13:38:54 /users/burrito/wdi/homework
$ mkdir House
  Tue Jun 27 13:39:10 /users/burrito/wdi/homework
$ ls
House
  Tue Jun 27 13:39:17 /users/burrito/wdi/homework
$ mkdir Oz
  Tue Jun 27 13:39:47 /users/burrito/wdi/homework
$ touch goodwitchofthenorth
  Tue Jun 27 13:40:08 /users/burrito/wdi/homework
$ touch wickedwitchoftheeast
  Tue Jun 27 13:40:23 /users/burrito/wdi/homework
$ touch goodwitchofthesouth
  Tue Jun 27 13:40:32 /users/burrito/wdi/homework
$ touchwickedwitchofthewest
-bash: touchwickedwitchofthewest: command not found
  Tue Jun 27 13:40:39 /users/burrito/wdi/homework
$ touch wickedwitchofthewest
  Tue Jun 27 13:40:47 /users/burrito/wdi/homework
$ rm wickedwitchoftheeast
  Tue Jun 27 13:41:08 /users/burrito/wdi/homework
$ mv dorothy House Oz
mv: rename dorothy to Oz/dorothy: No such file or directory
  Tue Jun 27 13:43:12 /users/burrito/wdi/homework
$ mvdir dorothy Oz
-bash: mvdir: command not found
  Tue Jun 27 13:43:47 /users/burrito/wdi/homework
$ pwd
/users/burrito/wdi/homework
  Tue Jun 27 13:43:51 /users/burrito/wdi/homework
$ ls
Oz			goodwitchofthesouth
goodwitchofthenorth	wickedwitchofthewest
  Tue Jun 27 13:43:53 /users/burrito/wdi/homework
$ tree homework
homework [error opening dir]

0 directories, 0 files
  Tue Jun 27 13:44:09 /users/burrito/wdi/homework
$ tree /homework
/homework [error opening dir]

0 directories, 0 files
  Tue Jun 27 13:44:17 /users/burrito/wdi/homework
$ tree ../homework
../homework
├── Oz
│   └── House
├── goodwitchofthenorth
├── goodwitchofthesouth
└── wickedwitchofthewest

2 directories, 3 files
  Tue Jun 27 13:44:24 /users/burrito/wdi/homework
$ rm goodwitchofthenorth
  Tue Jun 27 13:44:58 /users/burrito/wdi/homework
$ rm goodwitchofthesouth
  Tue Jun 27 13:45:04 /users/burrito/wdi/homework
$ rm wickedwitchofthewest
  Tue Jun 27 13:45:21 /users/burrito/wdi/homework
$ tree ../homework
../homework
└── Oz
    └── House

2 directories, 0 files
  Tue Jun 27 13:45:28 /users/burrito/wdi/homework
$ rm -r House
rm: House: No such file or directory
  Tue Jun 27 13:45:38 /users/burrito/wdi/homework
$ rm -r /House
rm: /House: No such file or directory
  Tue Jun 27 13:45:44 /users/burrito/wdi/homework
$ cd ../homework
  Tue Jun 27 13:45:53 /users/burrito/wdi/homework
$ cd Oz
  Tue Jun 27 13:45:57 /users/burrito/wdi/homework/Oz
$ ls
House
  Tue Jun 27 13:45:58 /users/burrito/wdi/homework/Oz
$ rm -r House
  Tue Jun 27 13:46:03 /users/burrito/wdi/homework/Oz
$ cd ../homework
-bash: cd: ../homework: No such file or directory
  Tue Jun 27 13:46:14 /users/burrito/wdi/homework/Oz
$ ../
-bash: ../: is a directory
  Tue Jun 27 13:46:22 /users/burrito/wdi/homework/Oz
$ pwd
/users/burrito/wdi/homework/Oz
  Tue Jun 27 13:46:31 /users/burrito/wdi/homework/Oz
$ ./Oz
-bash: ./Oz: No such file or directory
  Tue Jun 27 13:46:35 /users/burrito/wdi/homework/Oz
$ cd ~
  Tue Jun 27 13:47:03 ~
$ cd users
-bash: cd: users: No such file or directory
  Tue Jun 27 13:47:05 ~
$ cd Users
-bash: cd: Users: No such file or directory
  Tue Jun 27 13:47:08 ~
$ cd ~
  Tue Jun 27 13:47:11 ~
$ ls
Applications	Downloads	Music		myhomework
Desktop		Library		Pictures	wdi
Documents	Movies		Public
  Tue Jun 27 13:47:12 ~
$ cd Public
  Tue Jun 27 13:47:27 ~/Public
$ ls
Drop Box
  Tue Jun 27 13:47:29 ~/Public
$ cd /Users/burrito
  Tue Jun 27 13:47:56 ~
$ ls
Applications	Downloads	Music		myhomework
Desktop		Library		Pictures	wdi
Documents	Movies		Public
  Tue Jun 27 13:48:00 ~
$ cd ~
  Tue Jun 27 13:48:03 ~
$ cd /Users/burrito
  Tue Jun 27 13:48:10 ~
$ ls
Applications	Downloads	Music		myhomework
Desktop		Library		Pictures	wdi
Documents	Movies		Public
  Tue Jun 27 13:48:11 ~
$ cd ~/homework
-bash: cd: /Users/burrito/homework: No such file or directory
  Tue Jun 27 13:51:12 ~
$ cd ~
  Tue Jun 27 13:51:19 ~
$ cd /Users/burrito
  Tue Jun 27 13:51:28 ~
$ ls
Applications	Downloads	Music		myhomework
Desktop		Library		Pictures	wdi
Documents	Movies		Public
  Tue Jun 27 13:51:29 ~
$ cd wdi
  Tue Jun 27 13:51:48 ~/wdi
$ ls
Rakefile	installfest.yml	projects
homework	labs		sandbox
  Tue Jun 27 13:51:50 ~/wdi
$ cd homework
  Tue Jun 27 13:51:53 ~/wdi/homework
$ ls
Oz
  Tue Jun 27 13:51:55 ~/wdi/homework
$ mkdir House
  Tue Jun 27 13:52:13 ~/wdi/homework
$ ls
House	Oz
  Tue Jun 27 13:52:15 ~/wdi/homework
$ cd House
  Tue Jun 27 13:52:25 ~/wdi/homework/House
$ touch Dorothy
  Tue Jun 27 13:52:34 ~/wdi/homework/House
$ touch Toto
  Tue Jun 27 13:52:37 ~/wdi/homework/House
$ cd /Users/burrito
  Tue Jun 27 14:14:57 ~
$ ls
Applications	Downloads	Music		myhomework
Desktop		Library		Pictures	wdi
Documents	Movies		Public
  Tue Jun 27 14:14:58 ~
$ cd wdi
  Tue Jun 27 14:15:02 ~/wdi
$ ls
Rakefile	installfest.yml	projects
homework	labs		sandbox
  Tue Jun 27 14:15:04 ~/wdi
$ cd homework
  Tue Jun 27 14:15:08 ~/wdi/homework
$ ls
House	Oz
  Tue Jun 27 14:15:10 ~/wdi/homework
$ cd House
  Tue Jun 27 14:15:17 ~/wdi/homework/House
$ ls
Dorothy	Toto
  Tue Jun 27 14:15:18 ~/wdi/homework/House
$ cd ../House
  Tue Jun 27 14:16:23 ~/wdi/homework/House
$ cd ../House
  Tue Jun 27 14:16:29 ~/wdi/homework/House
$ cd ../homework
-bash: cd: ../homework: No such file or directory
  Tue Jun 27 14:16:33 ~/wdi/homework/House
$ cd ..
  Tue Jun 27 14:16:42 ~/wdi/homework
$ ls
House	Oz
  Tue Jun 27 14:20:20 ~/wdi/homework
$ cd Oz
  Tue Jun 27 14:20:30 ~/wdi/homework/Oz
$ touch goodwitchofthenorth
  Tue Jun 27 14:20:46 ~/wdi/homework/Oz
$ touch wickedwitchoftheeast
  Tue Jun 27 14:21:15 ~/wdi/homework/Oz
$ touch goodwitchofthesouth
  Tue Jun 27 14:21:21 ~/wdi/homework/Oz
$ touch wickedwitchofthewest
  Tue Jun 27 14:21:28 ~/wdi/homework/Oz
$ rm wickedwitchoftheeast
  Tue Jun 27 14:21:43 ~/wdi/homework/Oz
$ cd ..
  Tue Jun 27 14:22:01 ~/wdi/homework
$ cd House
  Tue Jun 27 14:22:08 ~/wdi/homework/House
$ mv Dorothy Oz
  Tue Jun 27 14:22:15 ~/wdi/homework/House
$ pwd
/Users/burrito/wdi/homework/House
  Tue Jun 27 14:22:43 ~/wdi/homework/House
$ touch Scarecrow
  Tue Jun 27 14:23:30 ~/wdi/homework/House
$ touch TinMan
  Tue Jun 27 14:23:34 ~/wdi/homework/House
$ touch CowardlyLion
  Tue Jun 27 14:23:51 ~/wdi/homework/House
$ cd ..
  Tue Jun 27 14:24:35 ~/wdi/homework
$ mkdir EmeraldCity
  Tue Jun 27 14:25:04 ~/wdi/homework
$ cd ..
  Tue Jun 27 14:25:20 ~/wdi
$ cd House
-bash: cd: House: No such file or directory
  Tue Jun 27 14:25:42 ~/wdi
$ cd ..
  Tue Jun 27 14:25:45 ~
$ cd homework
-bash: cd: homework: No such file or directory
  Tue Jun 27 14:25:49 ~
$ cd ..
  Tue Jun 27 14:25:56 /Users
$ cd /burrito
-bash: cd: /burrito: No such file or directory
  Tue Jun 27 14:26:01 /Users
$ ls
Guest	Shared	burrito
  Tue Jun 27 14:26:03 /Users
$ cd burrito
  Tue Jun 27 14:26:06 ~
$ ls
Applications	Downloads	Music		myhomework
Desktop		Library		Pictures	wdi
Documents	Movies		Public
  Tue Jun 27 14:26:13 ~
$ cd wdi
  Tue Jun 27 14:26:16 ~/wdi
$ ls
Rakefile	installfest.yml	projects
homework	labs		sandbox
  Tue Jun 27 14:26:17 ~/wdi
$ cd homework
  Tue Jun 27 14:26:23 ~/wdi/homework
$ ls
EmeraldCity	House		Oz
  Tue Jun 27 14:26:25 ~/wdi/homework
$ tree homework
homework [error opening dir]

0 directories, 0 files
  Tue Jun 27 14:26:34 ~/wdi/homework
$ cd House
  Tue Jun 27 14:27:08 ~/wdi/homework/House
$ mv Scarecrow TinMan CowardlyLion EmeraldCity
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
  Tue Jun 27 14:27:27 ~/wdi/homework/House
$ ls
CowardlyLion	Oz		Scarecrow	TinMan		Toto
  Tue Jun 27 14:27:31 ~/wdi/homework/House
$ cd ..
  Tue Jun 27 14:28:32 ~/wdi/homework
$ cd House
  Tue Jun 27 14:29:21 ~/wdi/homework/House
$ ls
CowardlyLion	Oz		Scarecrow	TinMan		Toto
  Tue Jun 27 14:29:24 ~/wdi/homework/House
$ mv CowardlyLion Scarecrow TinMan ../EmeraldCity
  Tue Jun 27 14:30:28 ~/wdi/homework/House
$ ls
Oz	Toto
  Tue Jun 27 14:30:30 ~/wdi/homework/House
$ cd ..
  Tue Jun 27 14:30:36 ~/wdi/homework
$ ls
EmeraldCity	House		Oz
  Tue Jun 27 14:30:37 ~/wdi/homework
$ cd EmeraldCity
  Tue Jun 27 14:30:41 ~/wdi/homework/EmeraldCity
$ ls
CowardlyLion	Scarecrow	TinMan
  Tue Jun 27 14:30:43 ~/wdi/homework/EmeraldCity
$ cd
  Wed Jun 28 08:11:46 ~
$ ls
Applications	Downloads	Music		myhomework
Desktop		Library		Pictures	wdi
Documents	Movies		Public
  Wed Jun 28 08:11:48 ~
$ cd wdi
  Wed Jun 28 08:11:51 ~/wdi
$ ls
Rakefile	installfest.yml	projects
homework	labs		sandbox
  Wed Jun 28 08:11:53 ~/wdi
$ cd homework
  Wed Jun 28 08:11:56 ~/wdi/homework
$ ls
EmeraldCity	House		Oz
  Wed Jun 28 08:11:57 ~/wdi/homework
$ cd Oz
  Wed Jun 28 08:12:00 ~/wdi/homework/Oz
$ touch FlyingMonkeys
  Wed Jun 28 08:12:16 ~/wdi/homework/Oz
$ ls
FlyingMonkeys		goodwitchofthesouth
goodwitchofthenorth	wickedwitchofthewest
  Wed Jun 28 08:12:18 ~/wdi/homework/Oz
$ rm wickedwitchofthewest
  Wed Jun 28 08:12:32 ~/wdi/homework/Oz
$ ls
FlyingMonkeys		goodwitchofthenorth	goodwitchofthesouth
  Wed Jun 28 08:12:34 ~/wdi/homework/Oz
$ cd ..
  Wed Jun 28 08:14:01 ~/wdi/homework
$ cd EmeraldCity
  Wed Jun 28 08:14:19 ~/wdi/homework/EmeraldCity
$ ls
CowardlyLion	Scarecrow	TinMan
  Wed Jun 28 08:15:40 ~/wdi/homework/EmeraldCity
$ echo "A Diploma" >> Scarecrow
  Wed Jun 28 08:15:54 ~/wdi/homework/EmeraldCity
$ atom Scarecrow
  Wed Jun 28 08:16:10 ~/wdi/homework/EmeraldCity
$ echo "Heart Shaped Watch" >> TinMan
  Wed Jun 28 08:16:43 ~/wdi/homework/EmeraldCity
$ atom TinMan
  Wed Jun 28 08:16:48 ~/wdi/homework/EmeraldCity
$ echo "A Medal" >> CowardlyLion
  Wed Jun 28 08:17:21 ~/wdi/homework/EmeraldCity
$ atom CowardlyLion
  Wed Jun 28 08:17:28 ~/wdi/homework/EmeraldCity
$

**Comment by AndyWhitley** [comment]
👍
