### ISSUE TITLE
CLI HW (Charles Cox)

### ISSUE THREAD

**Issue by cwcox** [ga-wdi-exercises/to_oz#257]
Wed Jun 28 08:42:13 ~/wdi/homework/toOz
$ mkdir House
Wed Jun 28 08:43:00 ~/wdi/homework/tooz
$ cd House
  Wed Jun 28 08:43:06 ~/wdi/homework/tooz/House
$ touch Dorothy Toto
Wed Jun 28 08:43:29 ~/wdi/homework/tooz/House
$ mkdir Oz
  Wed Jun 28 08:43:53 ~/wdi/homework/tooz/House
$ cd oz
Wed Jun 28 08:43:53 ~/wdi/homework/tooz/House
$ cd oz
Wed Jun 28 08:43:57 ~/wdi/homework/tooz/House/oz
$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
Wed Jun 28 08:44:43 ~/wdi/homework/tooz/House/oz
$ rm "Wicked Witch of the East"
Wed Jun 28 08:45:43 ~/wdi/homework/tooz/House/oz
$ cd ..
  Wed Jun 28 08:46:12 ~/wdi/homework/tooz/House
$ cp Dorothy Oz
Wed Jun 28 08:46:49 ~/wdi/homework/tooz/House
$ Touch Scarecrow "Tin Man" "Cowardly Lion"
  Wed Jun 28 08:47:52 ~/wdi/homework/tooz/House
$ mkdir "Emerald City"
  Wed Jun 28 08:47:58 ~/wdi/homework/tooz/House
$ cp Scarecrow "Emerald City"
  Wed Jun 28 08:48:11 ~/wdi/homework/tooz/House
$ cp "Tin Man" "Emerald City"
  Wed Jun 28 08:48:19 ~/wdi/homework/tooz/House
$ cp "Cowardly Lion" "Emerald City"
Wed Jun 28 08:48:31 ~/wdi/homework/tooz/House
$ cd oz
  Wed Jun 28 08:48:52 ~/wdi/homework/tooz/House/oz
$ touch "Flying Monkeys"
  Wed Jun 28 08:49:12 ~/wdi/homework/tooz/House/oz
$ rm "Wicked Witch of the West"
Wed Jun 28 08:49:36 ~/wdi/homework/tooz/House/oz
$ cd ../"Emerald City"
Wed Jun 28 08:50:26 ~/wdi/homework/tooz/House/Emerald City
$ echo 'diploma' >> Scarecrow
  Wed Jun 28 08:50:57 ~/wdi/homework/tooz/House/Emerald City
$ echo 'heart shaped watch' >> 'Tin Man'
  Wed Jun 28 08:51:13 ~/wdi/homework/tooz/House/Emerald City
$ echo 'medal' >> 'Cowardly Lion'

**Comment by juancgarcia** [comment]
Good Job!

We we're looking for `oz` to be created outside of `house`, but that's subject to interpretation of the instructions.
