### ISSUE TITLE
To OZ

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/to_oz#258]
To Oz? To Oz!

•	Create directory house, create directory oz

From wdi/

		$ mkdir sandbox/house sandbox/oz

$ cd sandbox
 
From sandbox/

•	Add file dorothy and toto to house

		$touch house/Dorothy house/toto

•	Add 4 files :

•	Good Witch of the North
•	Wicked Witch of the East
•	Good Witch of the South
•	Wicked Witch of the West

$ touch oz/good_witch_of_the_north   oz/wicked_witch_of_the_east   oz/good_witch_of_the_east oz/wicked_witch_of_the_west

Ding! Dong! The Witch is Dead

•	Delete “wicked witch of the east”

 		$ rm oz/wicked_witch_of_the_east	

•	Move “dorothy” from house to Oz
	
		$ mv house/dorothy oz/dorothy

Follow the Yellow Brick Road

•	Add file for:

•	Scarecrow
•	Tin Man
•	Cowardly Lion

		$ touch scarecrow   tin_man   cowardly_lion 
 
•	Create a directory “emerald city”

		$ mkdir  emerald_city

•	Move the gang to emerald city

		$ mv scarecrow tin_man cowardly_lion emerald_city/

You Must Kill the Witch

•	Add “flying monkeys” to oz

		$ touch oz/flying_monkeys

•	Remove “wicked witch of the west” from oz

		$ rm oz/wicked_witch_of_the_west
	

•	Give gifts to:

•	Diploma to SCARECROW

		$ echo Diploma > emerald_city/scarecrow

•	Watch to TIN MAN

		$ echo Hearth Shaped Watch > emerald_city/tin_man

•	Medal to LION

		$ echo Medal > emerald_city/lion

**Comment by AndyWhitley** [comment]
Nice use of code syntax formatting! 👍
