### ISSUE TITLE
Day 1 Homework-Kabir Rai

### ISSUE THREAD

**Issue by kabirrai** [ga-wdi-exercises/to_oz#26]
To Oz? To Oz!
1. Kabirs-MacBook-Pro:~ Kabir$ mkdir House

Kabirs-MacBook-Pro:house Kabir$ touch Dorothy
Kabirs-MacBook-Pro:house Kabir$ touch Toto
Kabirs-MacBook-Pro:house Kabir$ ls
Dorothy Toto

Kabirs-MacBook-Pro:house Kabir$ mkdir Oz
Kabirs-MacBook-Pro:house Kabir$ cd Oz

4.Kabirs-MacBook-Pro:Oz Kabir$ touch Good Witch of the North
Kabirs-MacBook-Pro:Oz Kabir$ touch Wicked Witch of the East
Kabirs-MacBook-Pro:Oz Kabir$ touch Good Witch of the South
Kabirs-MacBook-Pro:Oz Kabir$ touch Wicked Witch of the West
Kabirs-MacBook-Pro:Oz Kabir$ ls
East Good North South West Wicked Witch of the
Kabirs-MacBook-Pro:Oz Kabir$

Ding! Dong! The Witch is Dead

Kabirs-MacBook-Pro:Oz Kabir$ rm Wicked Witch of the East Kabirs-MacBook-Pro:Oz Kabir$ ls Good North South West
2.Kabirs-MacBook-Pro:Oz Kabir$ mv ~/Kabir/House/Dorothy ~/Kabir/House/Oz
mv: rename /Users/Kabir/Kabir/House/Dorothy to /Users/Kabir/Kabir/House/Oz: No such file or directory

Follow the Yellow Brick Road

1,2,3.
Kabirs-MacBook-Pro:Oz Kabir$ touch Scarecrow
Kabirs-MacBook-Pro:Oz Kabir$ touch Tin Man
Kabirs-MacBook-Pro:Oz Kabir$ touch Cowardly Lion
Kabirs-MacBook-Pro:Oz Kabir$ ls
Cowardly Lion North South West
Good Man Scarecrow Tin

4.Kabirs-MacBook-Pro:Oz Kabir$ mkdir Emerald City
Kabirs-MacBook-Pro:Oz Kabir$ ls
City Good North Tin
Cowardly Lion Scarecrow West
Emerald Man South

Kabirs-MacBook-Pro:Oz Kabir$ mv Scarecrow Emerald City Kabirs-MacBook-Pro:Oz Kabir$ ls City Good Man South West Cowardly Lion North Tin
You Must Kill the Witch

Kabirs-MacBook-Pro:Oz Kabir$ touch Flying Monkeys
2.Give the gifts*
i) Kabirs-MacBook-Pro:Oz Kabir$ echo "a diploma" >> Oz/City/Scarecrow
ii) Kabirs-MacBook-Pro:Oz Kabir$ echo "a heart shaped watch" >> Oz/Tin Man
-bash: Oz/Tin: No such file or directory

iii) Kabirs-MacBook-Pro:Oz Kabir$ echo "a medal" >> Oz/Lion
-bash: Oz/Lion: No such file or directory
Kabirs-MacBook-Pro:Oz Kabir$

**Comment by RobertAKARobin** [comment]
`Oz/Tin: No such file or directory` means these files weren't working. Files and directories with spaces in them need to be treated differently:

```
$ echo "a heart shaped watch" >> Oz/Tin\ Man
# or
$ echo "a heart shaped watch" >> Oz/"Tin Man"
```
