### ISSUE TITLE
CLI HW (Kieran)

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/to_oz#261]
To Oz?to Oz!
1. mkdir House
2. touch Dorothy Toto
3. mkdir Oz
4. touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"

Ding Dong The Witch is Dead:
1. rm "Wicked Witch of the East"
2. mv House/Dorothy Oz

Follow the YBR
1&2&3. touch "Scarecrow" "Tin Man" "Cowardly Lion"
4.mkdir "Emerald City"
5. go into Oz then : mv "Dorothy" "Cowardly Lion" "Scarecrow" "Tin Man" "Emerald City"

YMKtW
1. touch "Flying Monkeys"
2. rm "Wicked Witch of the West"
3.	i. when in Emerald city echo "diploma" >> "Scarecrow"
  	ii.when in Emerald city echo "watch" >> "Tin Man"
  	iii.when in Emerald city "medal" >> "Cowardly Lion"

**Comment by juancgarcia** [comment]
Good Job!

Remember to pay attention to your current working directory.

If you never step into `House` with `cd House` then `Dorothy` and `Toto` are created next to the house, but not inside. This will cause the later command `mv House/Dorothy Oz` to fail for not being able to find the file `House/Dorothy`
