### ISSUE TITLE
To Oz homework

### ISSUE THREAD

**Issue by vsweeney** [ga-wdi-exercises/to_oz#266]
cd myhomework
mkdir House
cd /House
$ touch Dorothy
$ touch Toto
$ mkdir Oz
$ cd Oz
$ touch Good Witch of the North
$ touch Wicked Witch of the East
$ touch Good Witch of the South
$ touch Wicked Witch of the West
$ rm Wicked Witch of the East
$ cd ..
mv Dorothy Oz
$ cd Oz
$ touch Scarecrow
$ touch Tin Man
$ touch Cowardly Lion
$ mkdir Emerald City
$ mv Tin Man Scarecrow Cowardly Lion Dorothy/Emerald City
cd ..
$ touch Flying Monkeys
$rm Wicked Witch of the West
$ echo "diploma" > Scarecrow
$ echo "heart shaped watch" > Tin Man
$ echo "medal" > Lion

**Comment by superbuggy** [comment]
👍
