### ISSUE TITLE
CLI Homework (Max Oppenheimer)

### ISSUE THREAD

**Issue by comrade-kirby** [ga-wdi-exercises/to_oz#269]
pwd
/Users/Max/wdi/homework
$ cd to_oz
$ pwd
/Users/Max/wdi/homework/to_oz
$ ls
readme.md	solution.txt	spec
$ clear
$ pwd
/Users/Max/wdi/homework/to_oz
$ mkdir House
$ cd House
$ touch Dorothy
$ touch Toto
$ cd ..
$ mkdir Oz
$ cd Oz
$ touch "Good Witch of the North"
$ touch "Wicked Witch of the East"
$ touch "Good Witch of the South"
$ touch "Wicked Witch of the West"
$ rm "Wicked Witch of the West"
$ cd ../House
$ mv Dorothy ../Oz
$ cd ../Oz
$ touch Scarecrow
$ touch "Tin Man" "Cowardly Lion"
$ mkdir "Emerald City"
$ mv Dorothy Scarecrow "Emerald City"
$ mv "Cowardly Lion" "Tin Man" "Emerald City"
$ touch "Flying Monkeys"
$ rm "Wicked Witch of the East"
$ echo diploma > Scarecrow
$ rm Scarecrow
$ cd "Emerald City"
$ echo diploma > Scarecrow
$ echo "heart shaped watch" > "Tin Man"
$ echo medal > Lion
$ rm Lion
$ echo medal > "Cowardly Lion"

**Comment by superbuggy** [comment]
👎

**Comment by superbuggy** [comment]
jk <3
