### ISSUE TITLE
CLI HW (Megan McNeilly)

### ISSUE THREAD

**Issue by mcneillymeg** [ga-wdi-exercises/to_oz#274]
Tue Oct 10 17:08:55 ~/wdi
$ cd homework
  Tue Oct 10 17:10:43 ~/wdi/homework
$ mkdir to_oz
  Tue Oct 10 17:12:57 ~/wdi/homework
$ cd to_oz
  Tue Oct 10 17:13:06 ~/wdi/homework/to_oz
$ mkdir House
  Tue Oct 10 17:13:22 ~/wdi/homework/to_oz
$ cd House
  Tue Oct 10 17:13:33 ~/wdi/homework/to_oz/House
$ touch Dorothy.txt
  Tue Oct 10 17:15:02 ~/wdi/homework/to_oz/House
$ touch Toto.txt
  Tue Oct 10 17:15:32 ~/wdi/homework/to_oz/House
$ mkdir Oz
  Tue Oct 10 17:15:56 ~/wdi/homework/to_oz/House
$ cd Oz
  Tue Oct 10 17:17:19 ~/wdi/homework/to_oz/House/Oz
$ touch good_witch_of_the_north.txt
  Tue Oct 10 17:18:16 ~/wdi/homework/to_oz/House/Oz
$ touch wiched_witch_of_the_east.txt
  Tue Oct 10 17:18:44 ~/wdi/homework/to_oz/House/Oz
$ touch good_witch_of_the_south.txt
  Tue Oct 10 17:19:05 ~/wdi/homework/to_oz/House/Oz
$ touch wicked_witch_of_the_west.txt
  Tue Oct 10 17:19:50 ~/wdi/homework/to_oz/House/Oz
$ ls
good_witch_of_the_north.txt	wiched_witch_of_the_east.txt
good_witch_of_the_south.txt	wicked_witch_of_the_west.txt
  Tue Oct 10 17:19:53 ~/wdi/homework/to_oz/House/Oz
$ mv wiched_witch_of_the_east.txt wicked_witch_of_the_east.txt
  Tue Oct 10 17:22:35 ~/wdi/homework/to_oz/House/Oz
$ ls
good_witch_of_the_north.txt	wicked_witch_of_the_east.txt
good_witch_of_the_south.txt	wicked_witch_of_the_west.txt
  Tue Oct 10 17:22:37 ~/wdi/homework/to_oz/House/Oz
$ rm wicked_witch_of_the_east.txt
  Tue Oct 10 17:23:52 ~/wdi/homework/to_oz/House/Oz
$ ls
good_witch_of_the_north.txt	wicked_witch_of_the_west.txt
good_witch_of_the_south.txt
  Tue Oct 10 17:23:54 ~/wdi/homework/to_oz/House/Oz
$ mv ../Dorothy ./Oz
mv: rename ../Dorothy to ./Oz: No such file or directory
  Tue Oct 10 17:24:46 ~/wdi/homework/to_oz/House/Oz
$ ls
good_witch_of_the_north.txt	wicked_witch_of_the_west.txt
good_witch_of_the_south.txt
  Tue Oct 10 17:24:52 ~/wdi/homework/to_oz/House/Oz
$ cd ..
  Tue Oct 10 17:25:12 ~/wdi/homework/to_oz/House
$ ls
Dorothy.txt	Oz		Toto.txt
  Tue Oct 10 17:25:15 ~/wdi/homework/to_oz/House
$ cd Oz
  Tue Oct 10 17:25:27 ~/wdi/homework/to_oz/House/Oz
$ mv ../Dorothy.txt .
  Tue Oct 10 17:27:30 ~/wdi/homework/to_oz/House/Oz
$ ls
Dorothy.txt			good_witch_of_the_south.txt
good_witch_of_the_north.txt	wicked_witch_of_the_west.txt
  Tue Oct 10 17:27:35 ~/wdi/homework/to_oz/House/Oz
$ touch Scarecrow.txt
  Tue Oct 10 17:31:22 ~/wdi/homework/to_oz/House/Oz
$ touch Tin_Man.txt
  Tue Oct 10 17:31:37 ~/wdi/homework/to_oz/House/Oz
$ touch Cowardly_Lion.txt
  Tue Oct 10 17:31:56 ~/wdi/homework/to_oz/House/Oz
$ la
-bash: la: command not found
  Tue Oct 10 17:32:00 ~/wdi/homework/to_oz/House/Oz
$ ls
Cowardly_Lion.txt		good_witch_of_the_north.txt
Dorothy.txt			good_witch_of_the_south.txt
Scarecrow.txt			wicked_witch_of_the_west.txt
Tin_Man.txt
  Tue Oct 10 17:32:02 ~/wdi/homework/to_oz/House/Oz
$ mkdir Emerald_City
  Tue Oct 10 17:32:27 ~/wdi/homework/to_oz/House/Oz
$ ls
Cowardly_Lion.txt		Tin_Man.txt
Dorothy.txt			good_witch_of_the_north.txt
Emerald_City			good_witch_of_the_south.txt
Scarecrow.txt			wicked_witch_of_the_west.txt
  Tue Oct 10 17:32:50 ~/wdi/homework/to_oz/House/Oz
$ mv Cowardly_Lion.txt Dorothy.txt Scarecrow.txt Tin_Man.txt ./Emerald_City
  Tue Oct 10 17:34:20 ~/wdi/homework/to_oz/House/Oz
$ ls
Emerald_City			good_witch_of_the_south.txt
good_witch_of_the_north.txt	wicked_witch_of_the_west.txt
  Tue Oct 10 17:34:22 ~/wdi/homework/to_oz/House/Oz
$ mkdir Flying_Monkeys
  Tue Oct 10 17:35:15 ~/wdi/homework/to_oz/House/Oz
$ rm wicked_witch_of_the_west.txt
  Tue Oct 10 17:35:34 ~/wdi/homework/to_oz/House/Oz
$ ls
Emerald_City			good_witch_of_the_north.txt
Flying_Monkeys			good_witch_of_the_south.txt
  Tue Oct 10 17:35:36 ~/wdi/homework/to_oz/House/Oz
$ cd Emerald_City
  Tue Oct 10 17:40:20 ~/wdi/homework/to_oz/House/Oz/Emerald_City
$ echo "a diploma" > Scarecrow.txt
  Tue Oct 10 17:41:21 ~/wdi/homework/to_oz/House/Oz/Emerald_City
$ echo "a heart shaped watch" > Tin_Man.txt
  Tue Oct 10 17:42:08 ~/wdi/homework/to_oz/House/Oz/Emerald_City
$ echo "a medal" > Cowardly_Lion.txt
  Tue Oct 10 17:42:43 ~/wdi/homework/to_oz/House/Oz/Emerald_City
$

**Comment by mcneillymeg** [comment]
$ cd homework
$ mkdir to_oz
$ cd to_oz
$ mkdir House
$ cd House
$ touch Dorothy.txt
$ touch Toto.txt
$ mkdir Oz
$ cd Oz
$ touch good_witch_of_the_north.txt
$ touch wiched_witch_of_the_east.txt
$ touch good_witch_of_the_south.txt
$ touch wicked_witch_of_the_west.txt
$ ls
good_witch_of_the_north.txt	wiched_witch_of_the_east.txt
good_witch_of_the_south.txt	wicked_witch_of_the_west.txt
$ mv wiched_witch_of_the_east.txt wicked_witch_of_the_east.txt
$ ls
good_witch_of_the_north.txt	wicked_witch_of_the_east.txt
good_witch_of_the_south.txt	wicked_witch_of_the_west.txt
$ rm wicked_witch_of_the_east.txt
$ ls
good_witch_of_the_north.txt	wicked_witch_of_the_west.txt
good_witch_of_the_south.txt
$ mv ../Dorothy ./Oz
mv: rename ../Dorothy to ./Oz: No such file or directory
$ ls
good_witch_of_the_north.txt	wicked_witch_of_the_west.txt
good_witch_of_the_south.txt
$ cd ..
$ ls
Dorothy.txt	Oz	Toto.txt
$ cd Oz
$ mv ../Dorothy.txt .
$ ls
Dorothy.txt	good_witch_of_the_south.txt
good_witch_of_the_north.txt	wicked_witch_of_the_west.txt
$ touch Scarecrow.txt
$ touch Tin_Man.txt
$ touch Cowardly_Lion.txt
$ la
-bash: la: command not found
$ ls
Cowardly_Lion.txt	good_witch_of_the_north.txt
Dorothy.txt	good_witch_of_the_south.txt
Scarecrow.txt	wicked_witch_of_the_west.txt
Tin_Man.txt
$ mkdir Emerald_City
$ ls
Cowardly_Lion.txt	Tin_Man.txt
Dorothy.txt	good_witch_of_the_north.txt
Emerald_City	good_witch_of_the_south.txt
Scarecrow.txt	wicked_witch_of_the_west.txt
$ mv Cowardly_Lion.txt Dorothy.txt Scarecrow.txt Tin_Man.txt ./Emerald_City
$ ls
Emerald_City	good_witch_of_the_south.txt
good_witch_of_the_north.txt	wicked_witch_of_the_west.txt
$ mkdir Flying_Monkeys
$ rm wicked_witch_of_the_west.txt
$ ls
Emerald_City	good_witch_of_the_north.txt
Flying_Monkeys	good_witch_of_the_south.txt
$ cd Emerald_City
$ echo "a diploma" > Scarecrow.txt
$ echo "a heart shaped watch" > Tin_Man.txt
$ echo "a medal" > Cowardly_Lion.txt

**Comment by AndyWhitley** [comment]
👍
