### ISSUE TITLE
CLI HW _Angie Spears

### ISSUE THREAD

**Issue by AMSpears** [ga-wdi-exercises/to_oz#276]
mkdir House
cd House
touch Dorothy
touch Toto
mkdir Oz
cd oz
touch Good_Witch_ of_ the_ North
touch Wicked_ Witch_ of_ the_ East
touch Good_Witch_ of_the_ South
touch Wicked_ Witch_ of_ the_West

rm Wicked_Witch_ of_ the_East
mv ../ Dorothy .

touch scarecrow
touch Tin_Man
touch Cowardly_Lion
mkdir  Emerald_ City
mv dorothy Emerald_City/
mv Cowardly_Lion  Emerald_city/
mv ../Tin_Man Emerald_city/
mv ../toto Emerald_city/
mv good_witch_of_the_north Emerald_city/
mv good_witch_of_the_south Emerald_city/
mv  Scarecrow  Emerald_city/
mv wicked_witch_of_the_west Emerald_city/

touch flying Monkeys
cd emerald_city
rm wicked_witch_of_the_west
echo “diploma” > scarecrow
echo “heart_shaped_watch” >Tin_Man
echo “medal” >lion

**Comment by perryf** [comment]
Good job!
