### ISSUE TITLE
Ryan Day 1 HW

### ISSUE THREAD

**Issue by rkrolick** [ga-wdi-exercises/to_oz#3]
zero@zero-VirtualBox:~/wdi$ cd exercises
zero@zero-VirtualBox:~/wdi/exercises$ mkdir day1
zero@zero-VirtualBox:~/wdi/exercises$ ls
day1
zero@zero-VirtualBox:~/wdi/exercises$ cd day1
zero@zero-VirtualBox:~/wdi/exercises/day1$ mkdir House
zero@zero-VirtualBox:~/wdi/exercises/day1$ cd House
zero@zero-VirtualBox:~/wdi/exercises/day1/House$ touch Dorothy
zero@zero-VirtualBox:~/wdi/exercises/day1/House$ touch Toto
zero@zero-VirtualBox:~/wdi/exercises/day1/House$ touch House
zero@zero-VirtualBox:~/wdi/exercises/day1/House$ ls
Dorothy  House  Toto
zero@zero-VirtualBox:~/wdi/exercises/day1/House$ cd ..
zero@zero-VirtualBox:~/wdi/exercises/day1$ mkdir Oz
zero@zero-VirtualBox:~/wdi/exercises/day1$ ls
House  Oz
zero@zero-VirtualBox:~/wdi/exercises/day1$ cd Oz
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ touch "Good Witch of the North"
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ ls
Good Witch of the North
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ touch "Wicked Witch of the East"
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ touch "Good Witch of the South"
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ touch "Wicked Witch of the West"
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ ls
Good Witch of the North  Wicked Witch of the East
Good Witch of the South  Wicked Witch of the West
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ rm "Wicked Witch of the East"
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ ls
Good Witch of the North  Good Witch of the South  Wicked Witch of the West
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ mv ../House/Dorothy .
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ ls
Dorothy                  Good Witch of the South
Good Witch of the North  Wicked Witch of the West
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ cd ..
zero@zero-VirtualBox:~/wdi/exercises/day1$ touch Scarecrow
zero@zero-VirtualBox:~/wdi/exercises/day1$ touch "Tin Man"
zero@zero-VirtualBox:~/wdi/exercises/day1$ touch "Cowardly Lion"
zero@zero-VirtualBox:~/wdi/exercises/day1$ ls
Cowardly Lion  House  Oz  Scarecrow  Tin Man
zero@zero-VirtualBox:~/wdi/exercises/day1$ mkdir "Emerald City"
zero@zero-VirtualBox:~/wdi/exercises/day1$ mv Scarecrow "Emerald City"
zero@zero-VirtualBox:~/wdi/exercises/day1$ mv "Tin Man" "Emerald City"
zero@zero-VirtualBox:~/wdi/exercises/day1$ mv "Cowardly Lion" "Emerald City"
zero@zero-VirtualBox:~/wdi/exercises/day1$ ls
Emerald City  House  Oz
zero@zero-VirtualBox:~/wdi/exercises/day1$ cdls "Emerald City"
Cowardly Lion  Scarecrow  Tin Man
zero@zero-VirtualBox:~/wdi/exercises/day1/Emerald City$ touch ../Oz/"Flying Monkeys"
zero@zero-VirtualBox:~/wdi/exercises/day1/Emerald City$ cd ..
zero@zero-VirtualBox:~/wdi/exercises/day1$ cd Oz
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ ls
Dorothy         Good Witch of the North  Wicked Witch of the West
Flying Monkeys  Good Witch of the South
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ rm "Wicked Witch of the West"
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ ls
Dorothy  Flying Monkeys  Good Witch of the North  Good Witch of the South
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ echo "a diploma" >> ../"Emerald City"/Scarecrow
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ echo "a heart shaped watch" >> ../"Emerald City"/"Tin Man"
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ echo "a medal" >> ../"Emerald City"/"Cowardly Lion"
zero@zero-VirtualBox:~/wdi/exercises/day1/Oz$ cdls ..
Emerald City  House  Oz
zero@zero-VirtualBox:~/wdi/exercises/day1$ cd "Emerald City"
zero@zero-VirtualBox:~/wdi/exercises/day1/Emerald City$ ls
Cowardly Lion  Scarecrow  Tin Man
zero@zero-VirtualBox:~/wdi/exercises/day1/Emerald City$ nano "Cowardly Lion"
zero@zero-VirtualBox:~/wdi/exercises/day1/Emerald City$ nano "Tin Man"
zero@zero-VirtualBox:~/wdi/exercises/day1/Emerald City$ nano Scarecrow
zero@zero-VirtualBox:~/wdi/exercises/day1/Emerald City$

**Comment by RobertAKARobin** [comment]
Nice, Ryan!

**Comment by RobertAKARobin** [comment]
vim > nano
