### ISSUE TITLE
Day 1 HW Brittany

### ISSUE THREAD

**Issue by Dibbledl01** [ga-wdi-exercises/to_oz#32]
Comfort Level: 3 (<-- during this exercise, but I feel if I did it over I could be a 5)

Last login: Tue Feb  9 17:09:02 on ttys000
~ 
$ pwd
/Users/brittanydibble
~ 
$ cd ~
~ 
$ ls
Applications        Library         World.zip
Creative Cloud Files    Movies          fundamentals
Desktop         Music           wdi
Documents       Pictures        wdi-fundamentals-rps
Downloads       Public
House           World
~ 
$ cd House
~/House 
$ touch Dorothy.txt
~/House 
$ ls
Dorothy
~/House 
$ touch Toto.txt
~/House 
$ ls
Dorothy.txt Toto.txt
~/House 
$ cd ~
~ 
$ mkdir Oz
~ 
$ cd Oz
~/Oz 
$ touch “Good Witch of the North.txt”
~/Oz 
$ touch “Wicked Witch of the East.txt”
~/Oz 
$ touch “Good Witch of the South.txt”
~/Oz 
$ touch “Wicked Witch of the West.txt”
~/Oz 
$ rm “Wicked Witch of the East.txt”
~/Oz 
$ cd ../House
~/House 
$ mv Dorothy.txt ../Oz
~/House
$ ls
Toto.txt
~/House
$ cd../Oz
~/Oz
$ ls
Dorothy.txt         Good Witch of the South.txt
Good Witch of the North.txt Wicked Witch of the West.txt
~/Oz 
$ touch Scarecrow.txt
~/Oz 
$ touch "Tin Man.txt"
~/Oz 
$ touch "Cowardly Lion.txt"
~/Oz 
$ cd ~
~ 
$ mkdir "Emerald City"
~ 
$ cd ../Oz
~/Oz 
$ mv Dorothy.txt ../"Emerald City"
~/Oz 
$ mv "Cowardly Lion.txt" ../"Emerald City"
~/Oz 
$ mv Scarecrow.txt ../"Emerald City"
~/Oz 
$ mv "Tin Man.txt" ../"Emerald City"
~/Oz 
$ cd ../"Emerald City"
~/Emerald City 
$ ls
Cowardly Lion.txt   Scarecrow.txt
Dorothy.txt     Tin Man.txt
~/Emerald City 
 cd ../Oz
~/Oz 
$ touch "Flying Monkeys.txt"
~/Oz 
$ rm "Wicked Witch of the West.txt"
~/Oz 
$ ls
Flying Monkeys.txt      Good Witch of the South.txt
Good Witch of the North.txt
~/Oz 
$ cd ../"Emerald City"
~/Emerald City
echo "a diploma" >> Scarecrow
~/Emerald City 
$ echo "heart shaped watch" >> "Tin Man"
~/Emerald City 
$ echo "medal" >> "Cowardly Lion"
~/Emerald City

**Comment by RobertAKARobin** [comment]
Nice job!
