### ISSUE TITLE
cli homework 2-9-16 hilary masland

### ISSUE THREAD

**Issue by hilarymasland** [ga-wdi-exercises/to_oz#37]
comfort- 3.75 - 4 

complete- 5

'''
Last login: Tue Feb  9 20:18:52 on ttys000
hilarymasland~ 
$ ls
Desktop     Library     Pictures    fundamentals    test
Documents   Movies      Public      funny_things    test.txt
Downloads   Music       banana.txt  src     wdi
hilarymasland~ 
$ cd wdi
hilarymasland~/wdi 
$ ls
Rakefile            installfest.yml
css-review-master       lessons
exercises           projects
ghosty-css          sandbox
ghosty-css.zip          wendy_bite
hyrule_potion_shop-master-2
hilarymasland~/wdi 
$ cd exercises
hilarymasland~/wdi/exercises 
$ mkdir House
hilarymasland~/wdi/exercises 
$ ls
House
hilarymasland~/wdi/exercises 
$ cd House
hilarymasland~/wdi/exercises/House 
$ touch Dorothy
hilarymasland~/wdi/exercises/House 
$ touch Toto
hilarymasland~/wdi/exercises/House 
$ cd ..
hilarymasland~/wdi/exercises 
$ mkdir Oz
hilarymasland~/wdi/exercises 
$ ls
House   Oz
hilarymasland~/wdi/exercises 
$ cd Oz
hilarymasland~/wdi/exercises/Oz 
$ touch Good_Witch_of_the_North
hilarymasland~/wdi/exercises/Oz 
$ touch Wicked_Witch_of_the_East
hilarymasland~/wdi/exercises/Oz 
$ touch Good_Witch_of_the_South
hilarymasland~/wdi/exercises/Oz 
$ touch Wicked_Witch_of_the_West
hilarymasland~/wdi/exercises/Oz 
$ rm Wicked_Witch_of_the_East
hilarymasland~/wdi/exercises/Oz 
$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
hilarymasland~/wdi/exercises/Oz 
$ cd .
hilarymasland~/wdi/exercises/Oz 
$ cd ..
hilarymasland~/wdi/exercises 
$ ls
House   Oz
hilarymasland~/wdi/exercises 
$ cd House
hilarymasland~/wdi/exercises/House 
$ ls
Dorothy Toto
hilarymasland~/wdi/exercises/House 
$ mv Dorothy ../Oz
hilarymasland~/wdi/exercises/House 
$ ls
Toto
hilarymasland~/wdi/exercises/House 
$ cd ..
hilarymasland~/wdi/exercises 
$ ls
House   Oz
hilarymasland~/wdi/exercises 
$ cd Oz
hilarymasland~/wdi/exercises/Oz 
$ ls
Dorothy             Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
hilarymasland~/wdi/exercises/Oz 
$ touch Scarecrow
hilarymasland~/wdi/exercises/Oz 
$ touch Tin Man
hilarymasland~/wdi/exercises/Oz 
$ touch Cowardly Lion
hilarymasland~/wdi/exercises/Oz 
$ cd ..
hilarymasland~/wdi/exercises 
$ mkdir Emerald City
hilarymasland~/wdi/exercises 
$ ls
City    Emerald House   Oz
hilarymasland~/wdi/exercises 
$ cd Emerald_City
-bash: cd: Emerald_City: No such file or directory
hilarymasland~/wdi/exercises 
$ rm Emerald City
rm: Emerald: is a directory
rm: City: is a directory
hilarymasland~/wdi/exercises 
$ ls
City    Emerald House   Oz
hilarymasland~/wdi/exercises 
$ rm Emerald
rm: Emerald: is a directory
hilarymasland~/wdi/exercises 
$ ls
City    Emerald House   Oz
hilarymasland~/wdi/exercises 
$ mkdir Emerald_City
hilarymasland~/wdi/exercises 
$ ls
City        Emerald     Emerald_City    House       Oz
hilarymasland~/wdi/exercises 
$ rm City
rm: City: is a directory
hilarymasland~/wdi/exercises 
$ ls
City        Emerald     Emerald_City    House       Oz
hilarymasland~/wdi/exercises 
$ cd Oz
hilarymasland~/wdi/exercises/Oz 
$ ls
Cowardly            Man
Dorothy             Scarecrow
Good_Witch_of_the_North     Tin
Good_Witch_of_the_South     Wicked_Witch_of_the_West
Lion
hilarymasland~/wdi/exercises/Oz 
$ mv Dorothy ./Emerald_City
hilarymasland~/wdi/exercises/Oz 
$ ls
Cowardly            Man
Emerald_City            Scarecrow
Good_Witch_of_the_North     Tin
Good_Witch_of_the_South     Wicked_Witch_of_the_West
Lion
hilarymasland~/wdi/exercises/Oz 
$ cd Emerald City
-bash: cd: Emerald: No such file or directory
hilarymasland~/wdi/exercises/Oz 
$ cd Emerald_City
-bash: cd: Emerald_City: Not a directory
hilarymasland~/wdi/exercises/Oz 
$ pwd
/Users/hilarymasland/wdi/exercises/Oz
hilarymasland~/wdi/exercises/Oz 
$ ls
Cowardly            Man
Emerald_City            Scarecrow
Good_Witch_of_the_North     Tin
Good_Witch_of_the_South     Wicked_Witch_of_the_West
Lion
hilarymasland~/wdi/exercises/Oz 
$ touch Dorothy
hilarymasland~/wdi/exercises/Oz 
$ cd ..
hilarymasland~/wdi/exercises 
$ ls
City        Emerald     Emerald_City    House       Oz
hilarymasland~/wdi/exercises 
$ cd Emerald_City
hilarymasland~/wdi/exercises/Emerald_City 
$ ls
hilarymasland~/wdi/exercises/Emerald_City 
$ cd Oz
-bash: cd: Oz: No such file or directory
hilarymasland~/wdi/exercises/Emerald_City 
$ cd ..
hilarymasland~/wdi/exercises 
$ ls
City        Emerald     Emerald_City    House       Oz
hilarymasland~/wdi/exercises 
$ cd Oz
hilarymasland~/wdi/exercises/Oz 
$ ls
Cowardly            Lion
Dorothy             Man
Emerald_City            Scarecrow
Good_Witch_of_the_North     Tin
Good_Witch_of_the_South     Wicked_Witch_of_the_West
hilarymasland~/wdi/exercises/Oz 
$ mv Dorothy ../Emerald_City
hilarymasland~/wdi/exercises/Oz 
$ mv Lion ../Emerald_City
hilarymasland~/wdi/exercises/Oz 
$ mv Tin ../Emerald_City
hilarymasland~/wdi/exercises/Oz 
$ mv Scarecrow ../Emerald_City
hilarymasland~/wdi/exercises/Oz 
$ cd ..
hilarymasland~/wdi/exercises 
$ ls
City        Emerald     Emerald_City    House       Oz
hilarymasland~/wdi/exercises 
$ cd Emerald_City
hilarymasland~/wdi/exercises/Emerald_City 
$ ls
Dorothy     Lion        Scarecrow   Tin
hilarymasland~/wdi/exercises/Emerald_City 
$ mv Tin Tin_Man
hilarymasland~/wdi/exercises/Emerald_City 
$ ls
Dorothy     Lion        Scarecrow   Tin_Man
hilarymasland~/wdi/exercises/Emerald_City 
$ cd ..
hilarymasland~/wdi/exercises 
$ ls
City        Emerald     Emerald_City    House       Oz
hilarymasland~/wdi/exercises 
$ cd Oz
hilarymasland~/wdi/exercises/Oz 
$ touch Flying_Monkeys
hilarymasland~/wdi/exercises/Oz 
$ ls
Cowardly            Good_Witch_of_the_South
Emerald_City            Man
Flying_Monkeys          Wicked_Witch_of_the_West
Good_Witch_of_the_North
hilarymasland~/wdi/exercises/Oz 
$ rm Wicked_Witch_of_the_West
hilarymasland~/wdi/exercises/Oz 
$ echo "a diploma" >> Oz/Scarecrow
-bash: Oz/Scarecrow: No such file or directory
hilarymasland~/wdi/exercises/Oz 
$ echo "a diploma" >> Emerald_City/Scarecrow
-bash: Emerald_City/Scarecrow: Not a directory
hilarymasland~/wdi/exercises/Oz 
$ ls
Cowardly        Flying_Monkeys      Good_Witch_of_the_South
Emerald_City        Good_Witch_of_the_North Man
hilarymasland~/wdi/exercises/Oz 
$ cd Emarld_City
-bash: cd: Emarld_City: No such file or directory
hilarymasland~/wdi/exercises/Oz 
$ ls
Cowardly        Flying_Monkeys      Good_Witch_of_the_South
Emerald_City        Good_Witch_of_the_North Man
hilarymasland~/wdi/exercises/Oz 
$ cd Emerald_City
-bash: cd: Emerald_City: Not a directory
hilarymasland~/wdi/exercises/Oz 
$ cd ..
hilarymasland~/wdi/exercises 
$ ls
City        Emerald     Emerald_City    House       Oz
hilarymasland~/wdi/exercises 
$ cd Emerald_City
hilarymasland~/wdi/exercises/Emerald_City 
$ ls
Dorothy     Lion        Scarecrow   Tin_Man
hilarymasland~/wdi/exercises/Emerald_City 
$ echo "a diploma" >> Scarecrow
hilarymasland~/wdi/exercises/Emerald_City 
$ echo "a diploma" >> Dorothy
hilarymasland~/wdi/exercises/Emerald_City 
$ echo "a diploma" >> Tin_Man
hilarymasland~/wdi/exercises/Emerald_City 
$ echo "a diploma" >> Lion
hilarymasland~/wdi/exercises/Emerald_City 
$ 
'''

**Comment by RobertAKARobin** [comment]
Good try with the backtics! You actually used single quotes instead, though. You want ```, which is the same key as `~`.
