### ISSUE TITLE
CLI HW Alexa Klein 2-9-16 Day 2 (TO OZ)

### ISSUE THREAD

**Issue by aklein916** [ga-wdi-exercises/to_oz#38]
~/wdi/homework/to_oz-master (master #) 
$ pwd
/Users/lexiklein/wdi/homework/to_oz-master
~/wdi/homework/to_oz-master (master #) 
$ mkdir House
~/wdi/homework/to_oz-master (master #) 
$ cd House
~/wdi/homework/to_oz-master/House (master #) 
$ touch Dorothy Toto
~/wdi/homework/to_oz-master/House (master #) 
$ cd ..
~/wdi/homework/to_oz-master (master #) 
$ pwd
/Users/lexiklein/wdi/homework/to_oz-master
~/wdi/homework/to_oz-master (master #) 
$ mkdir Oz
~/wdi/homework/to_oz-master (master #) 
$ cd Oz
~/wdi/homework/to_oz-master/Oz (master #) 
$ touch "Good Witch of the North" "Wicked Witch of the South" "Good Witch of the South" "Wicked Witch of the West"
~/wdi/homework/to_oz-master/Oz (master #) 
$ ls
Good Witch of the North     Wicked Witch of the South
Good Witch of the South     Wicked Witch of the West
~/wdi/homework/to_oz-master/Oz (master #) 
$ mv "Wicked Witch of the South" "Wicked Witch of the East"
~/wdi/homework/to_oz-master/Oz (master #) 
$ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South     Wicked Witch of the West
~/wdi/homework/to_oz-master/Oz (master #) 
$ rm "Wicked Witch of the East"
~/wdi/homework/to_oz-master/Oz (master #) 
$ mv ~/wdi/homework/to_oz-master/House/Dorothy ~/wdi/homework/to_oz-master/Oz
~/wdi/homework/to_oz-master/Oz (master #) 
$ pwd
/Users/lexiklein/wdi/homework/to_oz-master/Oz
~/wdi/homework/to_oz-master/Oz (master #) 
$ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the West
~/wdi/homework/to_oz-master/Oz (master #) 
$ cd to_oz-master
-bash: cd: to_oz-master: No such file or directory
~/wdi/homework/to_oz-master/Oz (master #) 
$ cd ..
~/wdi/homework/to_oz-master (master #) 
$ ls
House       Oz      readme.md
~/wdi/homework/to_oz-master (master #) 
$ touch "Scarecrow" "Tin Man" "Cowardly Lion"
~/wdi/homework/to_oz-master (master #) 
$ mkdir "Emerald City"
~/wdi/homework/to_oz-master (master #) 
$ ls
Cowardly Lion   House       Scarecrow   readme.md
Emerald City    Oz      Tin Man
~/wdi/homework/to_oz-master (master #) 
$ mv "Scarecrow" "Emerald City"
~/wdi/homework/to_oz-master (master #) 
$ ls
Cowardly Lion   House       Tin Man
Emerald City    Oz      readme.md
~/wdi/homework/to_oz-master (master #) 
$ mv "Tin Man" "Emerald City"
~/wdi/homework/to_oz-master (master #) 
$ mv "Cowardly Lion" "Emerald City"
~/wdi/homework/to_oz-master (master #) 
$ cd "Emerald City"
~/wdi/homework/to_oz-master/Emerald City (master #) 
$ ls
Cowardly Lion   Scarecrow   Tin Man
~/wdi/homework/to_oz-master/Emerald City (master #) 
$ cd ..
~/wdi/homework/to_oz-master (master #) 
$ cd Oz
~/wdi/homework/to_oz-master/Oz (master #) 
$ touch "Flying Monkeys"
~/wdi/homework/to_oz-master/Oz (master #) 
$ rm "Wicked Witch of the West"
~/wdi/homework/to_oz-master/Oz (master #) 
$ cd ..
~/wdi/homework/to_oz-master (master #) 
$ cd "Emerald City"
~/wdi/homework/to_oz-master/Emerald City (master #) 
$ echo "a diploma" >> Oz/Scarecrow
-bash: Oz/Scarecrow: No such file or directory
~/wdi/homework/to_oz-master/Emerald City (master #) 
$ echo "a diploma" >> "Emerald City"/Scarecrow
-bash: Emerald City/Scarecrow: No such file or directory
~/wdi/homework/to_oz-master/Emerald City (master #) 
$ echo "a diploma" >> Scarecrow
~/wdi/homework/to_oz-master/Emerald City (master #) 
$ echo "a heart shaped watch" >> "Tin Man"
~/wdi/homework/to_oz-master/Emerald City (master #) 
$ echo "a medal" >> "Cowardly Lion"
~/wdi/homework/to_oz-master/Emerald City (master #) 
$ 

comfort: 4/5-- would like to be more comfortable moving things and doing more difficult commands with multiple files.

**Comment by RobertAKARobin** [comment]
Nice!
