### ISSUE TITLE
CLI HW OZ Casey Gil

### ISSUE THREAD

**Issue by caseyagil** [ga-wdi-exercises/to_oz#39]
Comfort Level : 4/5
Understanding: 4/5

Last login: Wed Feb 10 08:41:08 on ttys001
Loading .profile
~ 
$ cd wdi-fundamentals
~/wdi-fundamentals (master) 
$ mkdir house
~/wdi-fundamentals (master) 
$ cd house
~/wdi-fundamentals/house (master) 
$ touch "Dorothy"
~/wdi-fundamentals/house (master) 
$ touch "Toto"
~/wdi-fundamentals/house (master) 
$ cd ../
~/wdi-fundamentals (master) 
$ mkdir Oz
~/wdi-fundamentals (master) 
$ cd Oz
~/wdi-fundamentals/Oz (master) 
$ touch 
usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...
~/wdi-fundamentals/Oz (master) 
$ touch "Good Witch of the North"
~/wdi-fundamentals/Oz (master) 
$ touch "Wicked Witch of the East"
~/wdi-fundamentals/Oz (master) 
$ touch "Good Witch of the South"
~/wdi-fundamentals/Oz (master) 
$ touch "Wicked Witch of the West"
~/wdi-fundamentals/Oz (master) 
$ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South     Wicked Witch of the West
~/wdi-fundamentals/Oz (master) 
$ rm "Wicked Witch of the East"
Wicked Witch of the East
~/wdi-fundamentals/Oz (master) 
$ cd ../
~/wdi-fundamentals (master) 
$ cd House
~/wdi-fundamentals/House (master) 
$ ls
Dorothy     Toto
~/wdi-fundamentals/House (master) 
$ mv "Dorothy" ../Oz
Dorothy -> ../Oz/Dorothy
~/wdi-fundamentals/House (master) 
$ ls
Toto
~/wdi-fundamentals/House (master) 
$ cd ../
~/wdi-fundamentals (master) 
$ cd oz
~/wdi-fundamentals/oz (master) 
$ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the West
~/wdi-fundamentals/oz (master) 
$ cd ../
~/wdi-fundamentals (master) 
$ touch "Scarecrow"
~/wdi-fundamentals (master) 
$ touch "Tin Man"
~/wdi-fundamentals (master) 
$ touch "Cowardly Lion"
~/wdi-fundamentals (master) 
$ mkdir "Emerald City"
~/wdi-fundamentals (master) 
$ ls
Cowardly Lion           git-practice/
Emerald City/           house/
Oz/             hyrule_potion_shop-master/
Scarecrow           readme.txt
Tin Man             src/
css-review-master/      wdi-fundamentals-rps/
ghosty-css/         wendy_bite/
~/wdi-fundamentals (master) 
$ mv "Scarecrow" ../"Emerald City"
Scarecrow -> ../Emerald City
~/wdi-fundamentals (master) 
$ mv "Tin Man" ../"Emerald City"
Tin Man -> ../Emerald City
~/wdi-fundamentals (master) 
$ mv "Cowardly Lion" ../"Emerald City"
Cowardly Lion -> ../Emerald City
~/wdi-fundamentals (master) 
$ cd Emerald City
-bash: cd: Emerald: No such file or directory
~/wdi-fundamentals (master) 
$ cd "Emerald City"
~/wdi-fundamentals/Emerald City (master) 
$ ls
~/wdi-fundamentals/Emerald City (master) 
$ ls -a
./  ../
~/wdi-fundamentals/Emerald City (master) 
$ cd ../
~/wdi-fundamentals (master) 
$ ls
Emerald City/           hyrule_potion_shop-master/
Oz/             readme.txt
css-review-master/      src/
ghosty-css/         wdi-fundamentals-rps/
git-practice/           wendy_bite/
house/
~/wdi-fundamentals (master) 
$ cd Emerald City
-bash: cd: Emerald: No such file or directory
~/wdi-fundamentals (master) 
$ cd Emerald_City
-bash: cd: Emerald_City: No such file or directory
~/wdi-fundamentals (master) 
$ cd "Emerald City"
~/wdi-fundamentals/Emerald City (master) 
$ ls
~/wdi-fundamentals/Emerald City (master) 
$ touch "Scarecrow"
~/wdi-fundamentals/Emerald City (master) 
$ touch "Cowardly Lion"
~/wdi-fundamentals/Emerald City (master) 
$ touch "Tin Man"
~/wdi-fundamentals/Emerald City (master) 
$ ls
Cowardly Lion   Scarecrow   Tin Man
~/wdi-fundamentals/Emerald City (master) 
$ cd ..
~/wdi-fundamentals (master) 
$ cd Oz
~/wdi-fundamentals/Oz (master) 
$ touch "Flying Monkeys"
~/wdi-fundamentals/Oz (master) 
$ rm "Wicked Witch of the West"
Wicked Witch of the West
~/wdi-fundamentals/Oz (master) 
$ cd ..
~/wdi-fundamentals (master) 
$ cd "Emerald City"
~/wdi-fundamentals/Emerald City (master) 
$ ls
Cowardly Lion   Scarecrow   Tin Man
~/wdi-fundamentals/Emerald City (master) 
$ echo "A brain" >> "Emerald City"/"Scarecrow"
-bash: Emerald City/Scarecrow: No such file or directory
~/wdi-fundamentals/Emerald City (master) 
$ ls
Cowardly Lion   Scarecrow   Tin Man
~/wdi-fundamentals/Emerald City (master) 
$ echo "a dilpoma" >>EmeraldCity/Scarecrow
-bash: EmeraldCity/Scarecrow: No such file or directory
~/wdi-fundamentals/Emerald City (master) 
$ echo "a diploma" >> "Scarecrow"
~/wdi-fundamentals/Emerald City (master) 
$ echo "a heart" >> "Cowardly Lion"
~/wdi-fundamentals/Emerald City (master) 
$ echo "a heart" >> "Tin Man"
~/wdi-fundamentals/Emerald City (master) 
$ echo "courage" > "Cowardly Lion"
~/wdi-fundamentals/Emerald City (master)

**Comment by RobertAKARobin** [comment]
Nice!
