### ISSUE TITLE
Toni Langley: Day 1 HW

### ISSUE THREAD

**Issue by tvcrawley** [ga-wdi-exercises/to_oz#4]
$ cd homework
~/wdi/homework 
$ mkdir House
~/wdi/homework 
$ cd House
~/wdi/homework/House 
$ ls
~/wdi/homework/House 
$ touch Dorothy
~/wdi/homework/House 
$ ls
Dorothy
~/wdi/homework/House 
$ touch House
~/wdi/homework/House 
$ rm House
~/wdi/homework/House 
$ ls
Dorothy
~/wdi/homework/House 
$ touch Toto
~/wdi/homework/House 
$ ls
Dorothy Toto
~/wdi/homework/House 
$ cd ..
~/wdi/homework 
$ ls
House
~/wdi/homework 
$ pwd
/Users/Chibia/wdi/homework
~/wdi/homework 
$ mkdir Oz
~/wdi/homework 
$ cd Oz
~/wdi/homework/Oz 
$ ls
~/wdi/homework/Oz 
$ touch Good Witch of the North
~/wdi/homework/Oz 
$ touch Wicked Witch of the East
~/wdi/homework/Oz 
$ touch Good Witch of the South
~/wdi/homework/Oz 
$ touch Wicked Witch of the West
~/wdi/homework/Oz 
$ ls
East    North   West    Witch   the
Good    South   Wicked  of
~/wdi/homework/Oz 
$ cd ..
~/wdi/homework 
$ ls
House   Oz
~/wdi/homework 
$ rm -r Oz
~/wdi/homework 
$ ls
House
~/wdi/homework 
$ mkdir Oz
~/wdi/homework 
$ ls
House   Oz
~/wdi/homework 
$ cd Oz
~/wdi/homework/Oz 
$ touch Good-Witch-of-the-North
~/wdi/homework/Oz 
$ touch Wicked-Witch-of-the-East
~/wdi/homework/Oz 
$ touch Good-Witch-of-the-South
~/wdi/homework/Oz 
$ touch Wicked-Witch-of-the-West
~/wdi/homework/Oz 
$ ls
Good-Witch-of-the-North     Wicked-Witch-of-the-East
Good-Witch-of-the-South     Wicked-Witch-of-the-West
~/wdi/homework/Oz 
$ rm Wicked-Witch-of-the-East
~/wdi/homework/Oz 
$ ls
Good-Witch-of-the-North     Wicked-Witch-of-the-West
Good-Witch-of-the-South
~/wdi/homework/Oz 
$ cd ..
~/wdi/homework 
$ move House/Dorothy Oz/Dorothy
-bash: move: command not found
~/wdi/homework 
$ mv House/Dorothy Oz/Dorothy
~/wdi/homework 
$ cd House
~/wdi/homework/House 
$ ls
Toto
~/wdi/homework/House 
$ cd..
-bash: cd..: command not found
~/wdi/homework/House 
$ cd ..
~/wdi/homework 
$ cd Oz
~/wdi/homework/Oz 
$ ls
Dorothy             Good-Witch-of-the-South
Good-Witch-of-the-North     Wicked-Witch-of-the-West
~/wdi/homework/Oz 
$ mv Good-Witch-of-the-North "Good Witch of the North"
~/wdi/homework/Oz 
$ ls
Dorothy             Good-Witch-of-the-South
Good Witch of the North     Wicked-Witch-of-the-West
~/wdi/homework/Oz 
$ mv Good-Witch-of-the-South "Good Witch of the South"
~/wdi/homework/Oz 
$ mv Wicked-Witch-of-the-West "Wicked Witch of the West"
~/wdi/homework/Oz 
$ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the West
~/wdi/homework/Oz 
$ touch Scarecrow
~/wdi/homework/Oz 
$ touch "Tin Man"
~/wdi/homework/Oz 
$ touch "Cowardly Lion"
~/wdi/homework/Oz 
$ mkdir "Emerald City"
~/wdi/homework/Oz 
$ mv Scarecrow "Emerald City"
~/wdi/homework/Oz 
$ ls
Cowardly Lion           Good Witch of the South
Dorothy             Tin Man
Emerald City            Wicked Witch of the West
Good Witch of the North
~/wdi/homework/Oz 
$ mv "Tin Man" "Emerald City"
~/wdi/homework/Oz 
$ ls
Cowardly Lion           Good Witch of the North
Dorothy             Good Witch of the South
Emerald City            Wicked Witch of the West
~/wdi/homework/Oz 
$ mv "Cowardly Lion" "Emerald City"
~/wdi/homework/Oz 
$ ls
Dorothy             Good Witch of the South
Emerald City            Wicked Witch of the West
Good Witch of the North
~/wdi/homework/Oz 
$ mv Dorothy "Emerald City"
~/wdi/homework/Oz 
$ ls
Emerald City            Good Witch of the South
Good Witch of the North     Wicked Witch of the West
~/wdi/homework/Oz 
$ touch "Flying Monkeys"
~/wdi/homework/Oz 
$ rm "Wicked Witch of the West" 
~/wdi/homework/Oz 
$ ls
Emerald City        Good Witch of the North
Flying Monkeys      Good Witch of the South
~/wdi/homework/Oz 
$ cd "Emerald City"
~/wdi/homework/Oz/Emerald City 
$ ls
Cowardly Lion   Dorothy     Scarecrow   Tin Man
~/wdi/homework/Oz/Emerald City 
$ echo "a diploma" >> Scarecrow
~/wdi/homework/Oz/Emerald City 
$ ls
Cowardly Lion   Dorothy     Scarecrow   Tin Man
~/wdi/homework/Oz/Emerald City 
$ echo "a heart shaped watch" >> "Tin Man"
~/wdi/homework/Oz/Emerald City 
$ echo "a medal" >> "Cowardly Lion"
~/wdi/homework/Oz/Emerald City 
$ mv "Cowardly Lion" "Lion"
~/wdi/homework/Oz/Emerald City 
$ ls
Dorothy     Lion        Scarecrow   Tin Man

**Comment by RobertAKARobin** [comment]
Nice job, Toni!
