### ISSUE TITLE
Day 1 HW 

### ISSUE THREAD

**Issue by Crunchwrap78** [ga-wdi-exercises/to_oz#40]
Comfortability scale from 1-5: 4

...
$ mkdir House
...
$ touch Dorothy
...
$ touch Toto
...
$ mkdir Oz
...
$ cd Oz
...
$ touch Good Witch of the North
...
$ touch Wicked Witch of the East
...
$ touch Good Witch of the South
... 
$ touch Wicked Witch of the West
... 
$ rm Wicked Witch of the East
...
$ mv ../House/Dorothy ~/wdi/lessons/Oz
... 
$ touch Scarecrow
...
$ touch Tin Man
...
$ touch Cowardly Lion
...
$ mkdir Emerald City
... 
$ mv Tin Man ~/wdi/lessons/Oz/Emerald
... 
$ mv Cowardly Lion ~/wdi/lessons/Oz/Emerald/
... 
$ mv Dorothy ~/wdi/lessons/Oz/Emerald/
... 
$ mv Scarecrow ~/wdi/lessons/Oz/Emerald/
... 
$ touch Flying Monkeys
... 
$ rm Wicked Witch of the West
...
$ echo "a diploma" >> ~/wdi/lessons/Oz/Emerald/Scarecrow
...
$ echo "heart shaped watch" >> ~/wdi/lessons/Oz/Emerald/Tin Man
...
$ echo "medal" >> ~/wdi/lessons/Oz/Emerald/Cowardly Lion
...

**Comment by RobertAKARobin** [comment]
Nice!
