### ISSUE TITLE
Oz - Bipin Neupane

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/to_oz#41]
*_To Oz? To Oz!
*_
~/wdi/hw/cli 
$ mkdir house
~/wdi/hw/cli 
$ cd house
~/wdi/hw/cli/house 
$ touch dorothy.txt toto.txt
~/wdi/hw/cli/house 
$ cd ..
~/wdi/hw/cli 
$ mkdir oz
~/wdi/hw/cli 
$ cd oz
~/wdi/hw/cli/oz 
$ touch good-north wicked-east good-south wicked-west
~/wdi/hw/cli/oz 

*_Ding! Dong! The Witch is Dead
*_

~/wdi/hw/cli/oz 
$ rm wicked-east 
~/wdi/hw/cli/oz 
$ cd ..
~/wdi/hw/cli 
$ cd house
~/wdi/hw/cli/house 
$ mv dorothy.txt ../oz
~/wdi/hw/cli/house 

*_Follow the Yellow Brick Road
*_
~/wdi/hw/cli 
$ cd house
~/wdi/hw/cli/house 
$ touch scarecrow tin-man cowardly-lion
~/wdi/hw/cli/house 
$ cd ..
~/wdi/hw/cli 
$ mkdir emerald-city
~/wdi/hw/cli 
$ cd ..
~/wdi/hw 
$ cd cli/house
~/wdi/hw/cli/house 
$ mv scarecrow tin-man cowardly-lion ../emerald-city
~/wdi/hw/cli/house 

*_You Must Kill the Witch
*_~/wdi/hw/cli/house 
$ cd ..
~/wdi/hw/cli 
$ cd oz
~/wdi/hw/cli/oz 
$ touch flying-monkyes.txt
~/wdi/hw/cli/oz 
$ rm wicked-west 
~/wdi/hw/cli/oz 
$ cd ..
~/wdi/hw/cli 
$ cd emerald-city/
~/wdi/hw/cli/emerald-city 
$ echo "diploma" >> scarecrow 
~/wdi/hw/cli/emerald-city 
$ open scarecrow 
~/wdi/hw/cli/emerald-city 
$ echo "heart shaped watch" >> tin-man
~/wdi/hw/cli/emerald-city 
$ open tin-man 
~/wdi/hw/cli/emerald-city 
$ echo "medal" >> cowardly-lion 
~/wdi/hw/cli/emerald-city 
$ open cowardly-lion 
~/wdi/hw/cli/emerald-city 
$

**Comment by RobertAKARobin** [comment]
Nice!

**Comment by Bneupane** [comment]
Thanks Robin I feel 5 out of 5 for this  :-D
