### ISSUE TITLE
Caitlin Daitch CLI Homework

### ISSUE THREAD

**Issue by caitlindaitch** [ga-wdi-exercises/to_oz#42]
Comfort level: 4

$ mkdir house
$ cd house
$ touch dorothy.txt
$ touch toto.txt
$ cd ..
$ mkdir oz
$ cd oz
$ touch "good witch of the north"
$ touch "wicked witch of the east"
$ touch "good witch of the south"
$ touch "wicked witch of the west"
$ rm "wicked witch of the east"
$ cd ../house
$ mv dorothy.txt ../oz
$ touch "scarecrow"
$ touch "tin man"
$ touch "cowardly lion"
$ mkdir emerald_city
$ mv "scarecrow" emerald_city
$ mv "tin man" emerald_city
$ mv "cowardly lion" emerald_city
$ mv dorothy.txt emerald_city
$ cd ..
$ touch "flying monkeys"
$ rm "wicked witch of the west"
$ echo "a diploma" >> emerald_city/"scarecrow"
$ echo "heart shaped watch" >> emerald_city/"tin man"
$ echo "medal" >> emerald_city/"cowardly lion"

**Comment by RobertAKARobin** [comment]
Nice!
