### ISSUE TITLE
Day 1 HW (To Oz) - Charles Hwang

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/to_oz#43]
~ 
$ cd wdi
~/wdi 
$ cd homework
~/wdi/homework 
$ mkdir House
~/wdi/homework 
$ cd House
~/wdi/homework/House 
$ touch Dorothy.txt Toto.txt
~/wdi/homework/House 
$ cd ..
~/wdi/homework 
$ mkdir Oz
~/wdi/homework 
$ cd Oz
~/wdi/homework/Oz 
$ touch "Good Witch of the North.txt"
~/wdi/homework/Oz 
$ touch "Wicked Witch of the East.txt"
~/wdi/homework/Oz 
$ touch "Good Witch of the South.txt"
~/wdi/homework/Oz 
$ touch "Wicked Witch of the West.txt"
~/wdi/homework/Oz 
$ cd ..
~/wdi/homework 
$ cd House
~/wdi/homework/House 
$ mv Dorothy.txt ~/wdi/homework/Oz
~/wdi/homework/House
$ touch Scarecrow.txt "Tin Man.txt" "Cowardly Lion.txt"
~/wdi/homework/House 
$ cd ..
~/wdi/homework 
$ cd House
~/wdi/homework/House 
$ ls
Cowardly Lion.txt   Tin Man.txt
Scarecrow.txt       Toto.txt
~/wdi/homework/House 
$ mv Scarecrow.txt Toto.txt "Cowardly Lion.txt" "Tin Man.txt" ~/wdi/homework/"Emerald City"
~/wdi/homework/House 
$ cd ..
~/wdi/homework 
$ cd Oz
~/wdi/homework/Oz 
$ touch "Flying Monkeys.txt"
~/wdi/homework/Oz 
$ rm "Wicked Witch of the West.txt"
~/wdi/homework/Oz 
$ cd ..
~/wdi/homework 
$ cd "Emerald City"
~/wdi/homework/Emerald City 
$ echo "a diploma" >> Scarecrow.txt
~/wdi/homework/Emerald City 
$ echo "a heart shaped watch" >> "Tin Man.txt"
~/wdi/homework/Emerald City 
$ echo "a medal" >> "Cowardly Lion.txt"
~/wdi/homework/Emerald City

Comfort score, 5/5
Completeness score, 5/5

**Comment by RobertAKARobin** [comment]
Nice!
