### ISSUE TITLE
Week 1 Homework - Andrew Smith-Mui

### ISSUE THREAD

**Issue by arsm800** [ga-wdi-exercises/to_oz#44]
---

mkdir House
cd House
touch "Dorothy" "Toto"
cd ..
mkdir Oz
cd Oz
touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West" 
cd ..
touch "Scarecrow" "Tin Man" "Cowardly Lion" 
mkdir "Emerald City"
mv "Scarecrow" "Tin Man" "Cowardly Lion" ./"Emerald City"
cd Oz
touch "Flying Monkeys"
rm "Wicked Witch of the West"
cd ../"Emerald_City"
echo "a diploma" Scarecrow
echo "a heart-shaped watch" Tin_Man
echo "a medal" Lion

---

comfort: 4
completeness: 5

**Comment by RobertAKARobin** [comment]
`echo "a diploma" Scarecrow` won't work. You need `echo "a diploma" > Scarecrow`. Make sure you test these out!
