### ISSUE TITLE
Martin Terskin - HW #1

### ISSUE THREAD

**Issue by 7ruth** [ga-wdi-exercises/to_oz#46]
completeness rating: 5
comfort rating: 5

$ cd House
$ touch Dorothy.txt Toto.txt House.txt
$ mkdir Oz
$ touch Good\ Witch\ of\ the\ North.txt Wicked\ Witch\ of\ the\ East.txt Good\ Witch\ of\ the\ South.txt Wicked\ Witch\ of\ the\ West.txt

$ rm Wicked\ Witch\ of\ the\ East.txt
$ cd ..
$ mv Dorothy.txt Oz

$ touch Scarecrow.txt Tin\ Man.txt Cowardly\ Lion.txt 
$ mkdir Emerald\ City
$ mv Scarecrow.txt Tin\ Man.txt Cowardly\ Lion.txt Emerald\ City

$ touch Flying\ Monkeys.txt
$ rm Wicked\ Witch\ of\ the\ West.txt
$ echo "a diploma" >> Emerald\ City/Scarecrow.txt
$ echo "a heart shaped watch" >> Emerald\ City/Tin\ Man.txt
$ echo "a medal" >> Emerald\ City/Cowardly\ Lion.txt

**Comment by andrewsunglaekim** [comment]
:+1: I would caution against utilizing spaces for files and folders going forward. Great work though!

**Comment by 7ruth** [comment]
Loud and clear, was just following directions as closely as possible such as “wicked witch…” etc. But usually I do “-“ per convention Adam mentioned last night. Thank you for feedback.
