### ISSUE TITLE
Homework 03-14-16

### ISSUE THREAD

**Issue by jball23** [ga-wdi-exercises/to_oz#47]
completeness: 5
comfort: 5

mkdir House
cd House
touch Dorothy Toto
mkdir Oz
touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
rm Wicked_Witch_of_the_East
mv House/Dorothy Oz/Dorothy
touch Scarecrow Tin_Man Cowardly_Lion
mkdir Emerald_City
mv Scarecrow Emerald_City/Scarecrow
mv Tin_Man Emerald_City/Tin_Man
mv Cowardly_Lion Emerald_City/Cowardly_Lion
touch Flying_Monkeys
rm Wicked_Witch_of_the_West
echo "a diploma" >> Emerald_City/Scarecrow
echo "a heart shaped watch" >> Emerald_City/Tin_Man
echo "a medal" >> Emerald_City/Cowardly_Lion

**Comment by jball23** [comment]
I'm not so sure about the echo stuff!

**Comment by adambray** [comment]
Good job overall!

Few suggestions:

```
mv House/Dorothy Oz/Dorothy
# could be shortened to 
mv House/Dorothy Oz/
```

```
mv Scarecrow Emerald_City/Scarecrow
mv Tin_Man Emerald_City/Tin_Man
mv Cowardly_Lion Emerald_City/Cowardly_Lion

# could be shortened to 
mv Scarecrow  Tin_Man Cowardly_Lion Emerald_City/
```

This is because if you move a file to a folder, it preserves the filename. You can also move multiple files at once, if you're moving them all to the same folder.

**Comment by adambray** [comment]
(oh and the echo stuff looks good to me!)
