### ISSUE TITLE
First assignment

### ISSUE THREAD

**Issue by MichaelNahum** [ga-wdi-exercises/to_oz#48]
completeness: 5
comfort: 5

 mkdir House
  504  cd House
  505  touch Dorothy Toto
  507  wdi
  508  mkdir Oz
  509  cd Oz/
  510  touch Good\Witch\of\the\North Wicked\Witch\of\the\East Good\Witch\of\the\South Wicked\Witch\of\the\West
  512  rm WickedWitchoftheEast 
  545  touch Dorothy
  547  touch Scarecrow Tin\Man Cowardly\Lion
  548  mkdir Emerald City
  554  mkdir Emerald\City
  575  mv Dorothy ~/wdi/Oz/EmeraldCity 
  579  mv CowardlyLion ~/wdi/Oz/EmeraldCity 
  580  mv TinMan ~/wdi/Oz/EmeraldCity 
  581  mv Scarecrow ~/wdi/Oz/EmeraldCity 
  587  touch Flying\Monkeys
  589  rm WickedWitchoftheWest 
  591  cd EmeraldCity/
  593  echo "a diploma" >> Scarecrow
  597  echo "a heart shaped watch" >> TinMan 
  599  echo "a medal" >> CowardlyLion

**Comment by tylercrosse** [comment]
Great work it looks like you have this down! :+1:  I added a little feedback + additional tips

I like how you named the Witches without any spaces, avoiding spaces in file and directory names is a great habit to get into. If for some reason you need to create or access a file with spaces in the name you  can use quotes or backslash+space
e.x.

``` shell
touch 'Good Witch of the North'
# OR
touch Wicked\ Witch\ of\ the\ East
```
