### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by marygriffus** [ga-wdi-exercises/to_oz#49]
comfort: 5
completeness: 5

mkdir House

cd House
touch Dorothy
touch Toto

cd ..
mkdir Oz

cd Oz
touch ‘Good Witch of the North’
touch ‘Wicked Witch of the East’
touch ‘Good Witch of the South’
touch ‘Wicked Witch of the West’

rm ‘Wicked Witch of the East’
mv Dorothy ../Oz

cd Oz
touch Scarecrow
touch ‘Tin Man’
touch ‘Cowardly Lion’
mkdir ‘Emerald City’
mv Dorothy Scarecrow ‘Tin Man’ ‘Cowardly Lion’ ‘Emerald City’

touch ‘Flying Monkeys’
rm ‘Wicked Witch of the West’
cd ‘Emerald City’
echo ‘a diploma’ >> Scarecrow
echo ‘a heart shaped watch’ >> ‘Tin Man’
echo ‘a medal’ >> lion

**Comment by tylercrosse** [comment]
Mary this looks great! :+1: 
The only thing I can see as a possible, but unnecessary improvement is the ability to combine your touch commands in a single line 

```
touch Dorothy Toto
```

Another cool bonus technique is that commands can also be chained on the same line using semicolons e.x. `cd ..; mkdir OZ`

**Comment by marygriffus** [comment]
Great, thanks for the feedback.
