### ISSUE TITLE
Jeff's Day 1 Homework - Oz

### ISSUE THREAD

**Issue by jeffreyeaton76** [ga-wdi-exercises/to_oz#5]
Last login: Mon Feb  8 15:59:48 on ttys000
~ 
$ cd wdi
~/wdi 
$ cd exercises
~/wdi/exercises 
$ mkdir house
~/wdi/exercises 
$ cd house
~/wdi/exercises/house 
$ touch Dorothy
~/wdi/exercises/house 
$ touch Toto
~/wdi/exercises/house 
$ cd ..
~/wdi/exercises 
$ mkdir Oz
~/wdi/exercises 
$ cd Oz
~/wdi/exercises/Oz 
$ touch Good_Witch_of_the_North
~/wdi/exercises/Oz 
$ touch Wicked_Witch_of_the_East
~/wdi/exercises/Oz 
$ touch Good_Witch_of_the_South
~/wdi/exercises/Oz 
$ touch Wicked_Witch_of_the_West
~/wdi/exercises/Oz 
$ rm Wicked_Witch_of_the_East
~/wdi/exercises/Oz 
$ cd ..
~/wdi/exercises 
$ cd house
~/wdi/exercises/house 
$ mv Dorothy ../Oz
~/wdi/exercises/house 
$ cd ../Oz
~/wdi/exercises/Oz 
$ touch Scarecrow Tin_Man Cowardly_Lion
~/wdi/exercises/Oz 
$ ls
Cowardly_Lion           Scarecrow
Dorothy             Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
~/wdi/exercises/Oz 
$ mkdir Emerald_City
~/wdi/exercises/Oz 
$ mv Dorothy /Emerald_City
mv: rename Dorothy to /Emerald_City: Permission denied
~/wdi/exercises/Oz 
$ mv Dorothy ~wdi/exercises/Oz/Emerald_City
mv: rename Dorothy to ~wdi/exercises/Oz/Emerald_City: No such file or directory
~/wdi/exercises/Oz 
$ mv Dorothy ~/wdi/exercises/Oz/Emerald_City
~/wdi/exercises/Oz 
$ mv Cowardly_Lion ~/wdi/exercises/Oz/Emerald_City
~/wdi/exercises/Oz 
$ mv Scarecrow ~/wdi/exercises/Oz/Emerald_City
~/wdi/exercises/Oz 
$ mv Tin_Man ~/wdi/exercises/Oz/Emerald_City
~/wdi/exercises/Oz 
$ ls
Emerald_City            Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
~/wdi/exercises/Oz 
$ cd Emerald_City
~/wdi/exercises/Oz/Emerald_City 
$ ls
Cowardly_Lion   Dorothy     Scarecrow   Tin_Man
~/wdi/exercises/Oz/Emerald_City 
$ cd ..
~/wdi/exercises/Oz 
$ touch Flying_Monkeys
~/wdi/exercises/Oz 
$ rm Wicked_Witch_of_the_West
~/wdi/exercises/Oz 
$ ls
Emerald_City        Good_Witch_of_the_North
Flying_Monkeys      Good_Witch_of_the_South
~/wdi/exercises/Oz 
$ cd Emerald_City
~/wdi/exercises/Oz/Emerald_City 
$ echo "a diploma" >> Scarecrow
~/wdi/exercises/Oz/Emerald_City 
$ echo "a heart-shaped watch" >> Tin_Man
~/wdi/exercises/Oz/Emerald_City 
$ echo "a medal" >> Cowardly_Lion
~/wdi/exercises/Oz/Emerald_City 
$

**Comment by RobertAKARobin** [comment]
Nice job!
