### ISSUE TITLE
to_oz hw

### ISSUE THREAD

**Issue by lknapalolo** [ga-wdi-exercises/to_oz#51]
Last login: Mon Mar 14 19:22:04 on ttys002
~ 
$ pwd
/Users/laurenckennedy
~ 
$ cd wdi
~/wdi 
$ mkdir house
~/wdi 
$ cd house
~/wdi/house 
$ touch dorothy.txt toto.txt
~/wdi/house 
$ cd ..
~/wdi 
$ mkdir oz
~/wdi 
$ cd oz
~/wdi/oz 
$ touch goodwitch_n.txt wickedwitch_e.txt goodwitch_s.txt wickedwitch_w.txt
~/wdi/oz 
$ rm wickedwitch_e.txt
~/wdi/oz 
$ mv -v ~/wdi/house/dorothy.txt ./dorothy.txt
/Users/laurenckennedy/wdi/house/dorothy.txt -> ./dorothy.txt
~/wdi/oz 
$ ls
dorothy.txt     goodwitch_s.txt
goodwitch_n.txt     wickedwitch_w.txt
~/wdi/oz 
$ touch scarecrow.txt tin_man.txt cowardly_lion.txt
~/wdi/oz 
$ mkdir emerald_city
~/wdi/oz 
$ mv dorothy.txt emerald_city/dorothy.txt
~/wdi/oz 
$ mv scarecrow.txt emerald-city/scarecrow.txt
mv: rename scarecrow.txt to emerald-city/scarecrow.txt: No such file or directory
~/wdi/oz 
$ mv scarecrow.txt emerald_city/scarecrow.txt
~/wdi/oz 
$ mv cowardly_lion.txt emerald_city/cowardly_lion.txt
~/wdi/oz 
$ cd emerald_city
~/wdi/oz/emerald_city 
$ ls
cowardly_lion.txt   dorothy.txt     scarecrow.txt
~/wdi/oz/emerald_city 
$ cd ..
~/wdi/oz 
$ mv tin_man.txt emerald_city/tin_man.txt
~/wdi/oz 
$ cd emerald_city
~/wdi/oz/emerald_city 
$ ls
cowardly_lion.txt   scarecrow.txt
dorothy.txt     tin_man.txt
~/wdi/oz/emerald_city 
$ cd ..
~/wdi/oz 
$ touch flying_monkeys
~/wdi/oz 
$ rm wickedwitch_w.txt
~/wdi/oz 
$ cd emerald_city
~/wdi/oz/emerald_city 
$ echo "a diploma" >> scarecrow.txt
~/wdi/oz/emerald_city 
$ echo "a heart shaped watch" >> tin_man.txt
~/wdi/oz/emerald_city 
$ echo "a medal" >> cowardly_lion.txt
~/wdi/oz/emerald_city 
$ mv dorothy.txt ~/wdi/house/dorothy.txt

Completeness - 5
Comfort - 5

Good practice exercise! Getting more comfortable with the command line. Send Dorothy home at the end! :))

**Comment by andrewsunglaekim** [comment]
great to hear! Good work! :+1:
