### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by zanehmw** [ga-wdi-exercises/to_oz#52]
completeness: 5
comfort: 4

comments: I got more comfortable moving files without using absolute paths towards the end of the assignment. I was unsure whether or not the files were supposed to be in txt form or not. But everything else was pretty easy to do.

mkdir House
cd House
touch Dorothy.txt House.txt
cd ..
mkdir Oz
cd Oz
touch GoodWitchoftheNorth.txt WickedWitchoftheEast.txt GoodWitchoftheSouth.txt WickedWitchoftheWest.txt
rm WickedWitchoftheEast.txt
mv /Users/zanehwilliams/wdi/House/Dorothy.txt /Users/zanehwilliams/wdi/Oz
cd ..
cd wdi
cd oz
ls
touch Scarecrow.txt TinMan.txt CowardlyLion.txt
mkdir EmeraldCity
mv scarecrow.txt emeraldcity/scarecrow.txt
mv tinman.txt emeraldcity/tinman.txt
mv cowardlylion.txt emeraldcity/cowardlylion.txt
cd ..
touch Flyingmonkeys.txt
rm wickedwitchofthewest.txt
echo "a diploma" >> Emeraldcity/scarecrow.txt
echo "a heart shaped watch" >> emeraldcity/tinman.txt
echo "a medal" >> emeraldcity/cowardlylion.txt

**Comment by tylercrosse** [comment]
This looks great! :+1: 

OSX actually allows you to create files without an extension, they just usually aren't very useful. So calling them .txt was a perfectly reasonable solution :smile:
