### ISSUE TITLE
HW #1

### ISSUE THREAD

**Issue by superbuggy** [ga-wdi-exercises/to_oz#53]
completeness: 5
comfort: 5

Melinda-Diachenkos-MacBook-Pro:HW1 spicylegato$ mkdir House House/Dorothy
Melinda-Diachenkos-MacBook-Pro:HW1 spicylegato$ cd house
Melinda-Diachenkos-MacBook-Pro:house spicylegato$ ls
Dorothy
Melinda-Diachenkos-MacBook-Pro:house spicylegato$ mkdir Toto
Melinda-Diachenkos-MacBook-Pro:house spicylegato$ cd ..
Melinda-Diachenkos-MacBook-Pro:HW1 spicylegato$ mk dir Oz Oz/"Good Witch of the North"
-bash: mk: command not found
Melinda-Diachenkos-MacBook-Pro:HW1 spicylegato$ mkdir Oz Oz/"Good Witch of the North"
Melinda-Diachenkos-MacBook-Pro:HW1 spicylegato$ cd oz
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ ls
Good Witch of the North
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ mkdir "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South     Wicked Witch of the West
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ rmdir "Wicked Witch of the East"
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ mv ../House/Dorothy ./
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the West
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ touch Scarecrow
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ touch "Tin Man"
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ touch "Cowardly Lion"
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ mkdir "Emerald City"
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ mv Scarecrow "Emerald City"
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ mv "Tin Man" "Emerald City"
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ mv "Cowardly Lion" "Emerald City" 
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ cd emerald city
-bash: cd: emerald: No such file or directory
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ cd "emerald city"
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ mv Dorothy "Emerald City"
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ cd ..
Melinda-Diachenkos-MacBook-Pro:hw1 spicylegato$ ls
House   Oz
Melinda-Diachenkos-MacBook-Pro:hw1 spicylegato$ touch "Flying Monkeys" Oz
Melinda-Diachenkos-MacBook-Pro:hw1 spicylegato$ ls
Flying Monkeys  House       Oz
Melinda-Diachenkos-MacBook-Pro:hw1 spicylegato$ mv "Flying Monkeys" Oz
Melinda-Diachenkos-MacBook-Pro:hw1 spicylegato$ ls
House   Oz
Melinda-Diachenkos-MacBook-Pro:hw1 spicylegato$ cd ozz
-bash: cd: ozz: No such file or directory
Melinda-Diachenkos-MacBook-Pro:hw1 spicylegato$ cd oz
Melinda-Diachenkos-MacBook-Pro:oz spicylegato$ cd Emerald\ City/
Melinda-Diachenkos-MacBook-Pro:Emerald City spicylegato$ echo "a diploma"
a diploma
Melinda-Diachenkos-MacBook-Pro:Emerald City spicylegato$ echo "a diploma" >>Scarecrow

Melinda-Diachenkos-MacBook-Pro:Emerald City spicylegato$ echo "a heart shaped watch" >> "Tin Man"
Melinda-Diachenkos-MacBook-Pro:Emerald City spicylegato$ ecoh "a medal" >> Lion
-bash: ecoh: command not found
Melinda-Diachenkos-MacBook-Pro:Emerald City spicylegato$ echo "a medal" >> Lion

**Comment by adambray** [comment]
Hey James! 

Good job overall, here's a few suggestions though:
1. I'd avoid using spaces in file names when possible. Instead, prefer underscores and lower-case, e.g. wicked_witch_of_the_west. This way you don't have to worry about using quotes around file names, etc.
2. The instructions weren't clear, but I think the intent was for characters to be created as _files_, and locations as _folders_. So for characters, you'd use _touch_ and _rm_ instead of _mkdir_ and _rmdir_.

**Comment by adambray** [comment]
Oh, also, you forgot to delete the witch of the west in the last section! (But no big deal).
