### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by mvaden** [ga-wdi-exercises/to_oz#54]
Last login: Mon Mar 14 17:22:35 on ttys002
Matthews-MacBook-Air:~ MrVaden$ mkdir House
Matthews-MacBook-Air:~ MrVaden$ cd House
Matthews-MacBook-Air:House MrVaden$ touch Dorothy.txt Toto.txt House.txt
Matthews-MacBook-Air:House MrVaden$ ls
Dorothy.txt House.txt   Toto.txt
Matthews-MacBook-Air:House MrVaden$ mkdir Oz
Matthews-MacBook-Air:House MrVaden$ cd Oz
Matthews-MacBook-Air:Oz MrVaden$ touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
Matthews-MacBook-Air:Oz MrVaden$ ls
Good_Witch_of_the_North
Good_Witch_of_the_South
Wicked_Witch_of_the_East
Wicked_Witch_of_the_West
Matthews-MacBook-Air:Oz MrVaden$ rm Wicked_Witch_of_the_East
Matthews-MacBook-Air:Oz MrVaden$ ls
Good_Witch_of_the_North
Good_Witch_of_the_South
Wicked_Witch_of_the_West
Matthews-MacBook-Air:Oz MrVaden$ pwd
/Users/MrVaden/House/Oz
Matthews-MacBook-Air:Oz MrVaden$ cd ..
Matthews-MacBook-Air:House MrVaden$ pwd
/Users/MrVaden/House
Matthews-MacBook-Air:House MrVaden$ ls
Dorothy.txt Oz
House.txt   Toto.txt
Matthews-MacBook-Air:House MrVaden$ mv Dorothy.txt Oz
Matthews-MacBook-Air:House MrVaden$ cd Oz
Matthews-MacBook-Air:Oz MrVaden$ pwd
/Users/MrVaden/House/Oz
Matthews-MacBook-Air:Oz MrVaden$ ls
Dorothy.txt
Good_Witch_of_the_North
Good_Witch_of_the_South
Wicked_Witch_of_the_West
Matthews-MacBook-Air:Oz MrVaden$ cd ~
Matthews-MacBook-Air:~ MrVaden$ pwd
/Users/MrVaden
Matthews-MacBook-Air:~ MrVaden$ ls
Applications        Public
Desktop         World
Documents       bob
Downloads       fundamentals
Dropbox         funny_things
Google Drive        github.io
House           hello1.txt
Library         leena
Movies          wdi
Music           wdi-fundamentals-rps
Pictures
Matthews-MacBook-Air:~ MrVaden$ touch Scarecrow Tin_Man Cowardly_Lion
Matthews-MacBook-Air:~ MrVaden$ ls
Applications        Public
Cowardly_Lion       Scarecrow
Desktop         Tin_Man
Documents       World
Downloads       bob
Dropbox         fundamentals
Google Drive        funny_things
House           github.io
Library         hello1.txt
Movies          leena
Music           wdi
Pictures        wdi-fundamentals-rps
Matthews-MacBook-Air:~ MrVaden$ mkdir Emerald_Cit
y
Matthews-MacBook-Air:~ MrVaden$ cd Emerald_City/
Matthews-MacBook-Air:Emerald_City MrVaden$ pwd
/Users/MrVaden/Emerald_City
Matthews-MacBook-Air:Emerald_City MrVaden$ cd ..
Matthews-MacBook-Air:~ MrVaden$ mv Scarecrow Emerald_City
Matthews-MacBook-Air:~ MrVaden$ Mv Tin_Man Emerald_City
Matthews-MacBook-Air:~ MrVaden$ mv Cowardly_Lion Emerald_City
Matthews-MacBook-Air:~ MrVaden$ ls
Applications        Pictures
Desktop         Public
Documents       World
Downloads       bob
Dropbox         fundamentals
Emerald_City        funny_things
Google Drive        github.io
House           hello1.txt
Library         leena
Movies          wdi
Music           wdi-fundamentals-rps
Matthews-MacBook-Air:~ MrVaden$ cd Emerald_City/
Matthews-MacBook-Air:Emerald_City MrVaden$ ls
Cowardly_Lion   Scarecrow   Tin_Man
Matthews-MacBook-Air:Emerald_City MrVaden$ cd ~
Matthews-MacBook-Air:~ MrVaden$ pwd
/Users/MrVaden
Matthews-MacBook-Air:~ MrVaden$ ls
Applications        Pictures
Desktop         Public
Documents       World
Downloads       bob
Dropbox         fundamentals
Emerald_City        funny_things
Google Drive        github.io
House           hello1.txt
Library         leena
Movies          wdi
Music           wdi-fundamentals-rps
Matthews-MacBook-Air:~ MrVaden$ cd House 
Matthews-MacBook-Air:House MrVaden$ ls
House.txt   Oz      Toto.txt
Matthews-MacBook-Air:House MrVaden$ cd Oz
Matthews-MacBook-Air:Oz MrVaden$ touch Flying_Mokeys
Matthews-MacBook-Air:Oz MrVaden$ ls
Dorothy.txt
Flying_Mokeys
Good_Witch_of_the_North
Good_Witch_of_the_South
Wicked_Witch_of_the_West
Matthews-MacBook-Air:Oz MrVaden$ rm Wicked_Witch_
of_the_West
Matthews-MacBook-Air:Oz MrVaden$ cd ..
Matthews-MacBook-Air:House MrVaden$ ls
House.txt   Oz      Toto.txt
Matthews-MacBook-Air:House MrVaden$ cd ..
Matthews-MacBook-Air:~ MrVaden$ ls
Applications        Pictures
Desktop         Public
Documents       World
Downloads       bob
Dropbox         fundamentals
Emerald_City        funny_things
Google Drive        github.io
House           hello1.txt
Matthews-MacBook-Air:Emerald_City MrVaden$ echo 'a medal' >> Oz/Scarecrow
-bash: Oz/Scarecrow: No such file or directory
Matthews-MacBook-Air:Emerald_City MrVaden$ echo 'a heart shaped watch' >> Oz/Tin_man
-bash: Oz/Tin_man: No such file or directory
Matthews-MacBook-Air:Emerald_City MrVaden$ echo 'a heart shaped watch' >> Oz/Tin_man/
-bash: Oz/Tin_man/: No such file or directory
Matthews-MacBook-Air:Emerald_City MrVaden$ echo 'a medal' >> Oz/Cowardly_Lion/
-bash: Oz/Cowardly_Lion/: No such file or directory
Matthews-MacBook-Air:Emerald_City MrVaden$ cd /House/Oz/
-bash: cd: /House/Oz/: No such file or directory
Matthews-MacBook-Air:Emerald_City MrVaden$ cd MrVaden$/House/Oz
-bash: cd: MrVaden$/House/Oz: No such file or directory
Matthews-MacBook-Air:Emerald_City MrVaden$ cd ~
Matthews-MacBook-Air:~ MrVaden$ ls
Applications        Google Drive        Public          hello1.txt
Desktop         House           World           leena
Documents       Library         bob         wdi
Downloads       Movies          fundamentals        wdi-fundamentals-rps
Dropbox         Music           funny_things
Emerald_City        Pictures        github.io
Matthews-MacBook-Air:~ MrVaden$ cd House
Matthews-MacBook-Air:House MrVaden$ ls
House.txt   Oz      Toto.txt
Matthews-MacBook-Air:House MrVaden$ cd Oz
Matthews-MacBook-Air:Oz MrVaden$ ls
Dorothy.txt     Flying_Mokeys       Good_Witch_of_the_North Good_Witch_of_the_South
Matthews-MacBook-Air:Oz MrVaden$ cd ..
Matthews-MacBook-Air:House MrVaden$ cd ..
Matthews-MacBook-Air:~ MrVaden$ ls
Applications        Google Drive        Public          hello1.txt
Desktop         House           World           leena
Documents       Library         bob         wdi
Downloads       Movies          fundamentals        wdi-fundamentals-rps
Dropbox         Music           funny_things
Emerald_City        Pictures        github.io
Matthews-MacBook-Air:~ MrVaden$ cd Emerald_City
Matthews-MacBook-Air:Emerald_City MrVaden$ echo 'A diploma for Scarecrow'
A diploma for Scarecrow
Matthews-MacBook-Air:Emerald_City MrVaden$ echo 'A heart shaped watch for Tin Man'
A heart shaped watch for Tin Man
Matthews-MacBook-Air:Emerald_City MrVaden$ echo 'A medal for Cowardly_Lion'
A medal for Cowardly_Lion
Matthews-MacBook-Air:Emerald_City MrVaden$

**Comment by tylercrosse** [comment]
Nice job! :+1:  In the future make sure you also include your comfort_level: and completeness: for each HW. I made a couple small suggestions about things that might help moving forward.

I would definitely encourage you to make a directory in root for all of you wdi or development related work. It's nice to have everything contained and organized especially when you start having to worry about what levels are being tracked by git. This file structure has worked really well for me:
- ~/wdi
  - sandbox
  - exercises
  - lessons
  - projects

Another thing that might be helpful is noting that your prompt (the prompt is what's before the `$`) currently has info about the directory you're in. There are ways to update this to show the full path you're in and we're planning on discussing that in a mini-lesson next Wednesday. In the time being this should save you a couple `pwd`
e.x. here you started in the root directory `~` and moved to `Emerald_City`

Matthews-MacBook-Air:**~** MrVaden$ cd Emerald_City/
Matthews-MacBook-Air:**Emerald_City** MrVaden$ pwd
