### ISSUE TITLE
Day 1 HW 

### ISSUE THREAD

**Issue by wesareed** [ga-wdi-exercises/to_oz#55]
Completion: 5
Comfortability: 5 

bruisedreed ~ $ cd desktop
bruisedreed desktop $ mkdir House
bruisedreed desktop $ cd House
bruisedreed House $ touch Dorothy Toto
bruisedreed House $ cd ..
bruisedreed desktop $ mkdir Oz
bruisedreed desktop $ cd Oz
bruisedreed Oz $ touch GoodWitchOfTheNorth WickedWitchOfTheEast GoodWitchOfTheSouth WickedWitchOfTheWest
bruisedreed Oz $ rm WickedWitchOfTheEast
bruisedreed Oz $ cd ..
bruisedreed desktop $ mv House/Dorothy Oz/Dorothy
bruisedreed desktop $ cd Oz
bruisedreed Oz $ ls
Dorothy         GoodWitchOfTheSouth
GoodWitchOfTheNorth WickedWitchOfTheWest
bruisedreed Oz $ touch Scarecrow.txt TinMan.txt CowardlyLion.txt
bruisedreed Oz $ cd ..
bruisedreed desktop $ mkdir Emerald_City
bruisedreed desktop $ mv Oz/*.txt Emerald_City
bruisedreed desktop $ cd Oz
bruisedreed Oz $ touch FlyingMonkeys
bruisedreed Oz $ rm WickedWitchOfTheWest
bruisedreed Oz $ cd ..
bruisedreed desktop $ cd Emerald_City
bruisedreed Emerald_City $ ls
CowardlyLion.txt    Scarecrow.txt       TinMan.txt
bruisedreed Emerald_City $ echo "a diploma" >> Scarecrow.txt
bruisedreed Emerald_City $ echo "a heart shaped watch" >> TinMan.txt
bruisedreed Emerald_City $ echo "a medal" >> CowardlyLion.txt
bruisedreed Emerald_City $

**Comment by tylercrosse** [comment]
Great work I can tell you know what you're doing here! :+1:

I would definitely encourage you to make a directory in root for all of you wdi or development related work. It's nice to have everything contained and organized especially when you start having to worry about what levels are being tracked by git. This file structure has worked really well for me:
- ~/wdi
  - sandbox
  - exercises
  - lessons
  - projects

**Comment by wesareed** [comment]
Thanks! I'll make directory root tonight.
