### ISSUE TITLE
Day 1 HW Oz

### ISSUE THREAD

**Issue by lelandjordon** [ga-wdi-exercises/to_oz#56]
completeness: 5-5
comfort: 2-5

I'm still worried about messing up other files on my computer.  I wanted to mv a bunch of files at once (moving Dorothy and the guys into the directory the_gang), but haven't found a way to do it; I also didn't want to guess and type something like "mv *.txt the_gang/" only to have it select, then move, all the text files on my hard drive.

$ mkdir house
$ touch house/dorothy.txt house/toto.txt
$ mkdir oz
$ touch oz/goodWitchOfTheNorth.txt oz/wickedWitchOfTheEast.txt oz/goodWitchOfTheSouth.txt oz/wickedWitchOfTheWest.txt
$ cd oz
$ rm -v wickedWitchOfTheEast.txt
$ cd ..
$ mv -v house/dorothy.txt oz/dorothy.txt
$ mv -v house/toto.txt oz/toto.txt
$ cd oz
$ mkdir yellow_brick_road
$ mv -v dorothy.txt yellow_brick_road/dorothy.txt
$ mv -v toto.txt yellow_brick_road/toto.txt
$ cd yellow_brick_road
$ touch scarecrow.txt tinMan.txt cowardlyLion.txt
$ mkdir the_gang
$ mv -v dorothy.txt the_gang/dorothy.txt
$ mv -v toto.txt the_gang/toto.txt
$ mv -v scarecrow.txt the_gang/scarecrow.txt
$ mv -v tinMan.txt the_gang/tinMan.txt
$ mv -v cowardlyLion.txt the_gang/cowardlyLion.txt
$ mkdir -v emerald_city
$ mv -v the_gang/ emerald_city/
$ cd ..
$ touch flyingMonkeys.txt
$ rm -v wickedWitchOfTheWest.txt
$ cd yellow_brick_road/emerald_city/the_gang
$ echo "a diploma" >> scarecrow.txt
$ echo "a heart shaped watch" >> tinMan.txt
$ echo "a medal" >> cowardlyLion.txt
$ echo "there's no place like home" >> dorothy.txt
$ echo "arf" >> toto.txt

**Comment by andrewsunglaekim** [comment]
http://askubuntu.com/questions/214560/how-to-move-multiple-files-at-once-to-a-specific-destination-directory is a link i Found that gives you a good idea on how to move files en masse.

Another thing to note! We may have learned recently about a tool that will allow us to try things and not fear failure! That tool is git! Create a repository, then create lots of files and folders in that repo. Commit, then change whatever you want, you can always go back in time without fear of losing anything you committed.

Other than that HW looks good! :+1:

**Comment by lelandjordon** [comment]
Part of doing it this way was wanting to make the commands look like the storyline.
But yeah, I also didn't know how to move bunches of files at once.
