### ISSUE TITLE
Issues with Oz

### ISSUE THREAD

**Issue by LOHankins** [ga-wdi-exercises/to_oz#58]
louis@louis-HP-ENVY-Notebook:~$ mkdir House
louis@louis-HP-ENVY-Notebook:~$ cd House
louis@louis-HP-ENVY-Notebook:~/House$ touch Dorothy.txt Toto.txt
louis@louis-HP-ENVY-Notebook:~/House$ cd ..
louis@louis-HP-ENVY-Notebook:~$ mkdir Oz
louis@louis-HP-ENVY-Notebook:~$ touch /Oz/Good Witch of the East.txt /Oz/Wicked Witch of the East.txt /Oz/Good Witch of the South.txt /Oz/Wicked Witch of the West.txt 
touch: cannot touch ‘/Oz/Good’: No such file or directory
touch: cannot touch ‘/Oz/Wicked’: No such file or directory
touch: cannot touch ‘/Oz/Good’: No such file or directory
touch: cannot touch ‘/Oz/Wicked’: No such file or directory
louis@louis-HP-ENVY-Notebook:~$ touch /Oz/GoodWitchoftheEast.txt /Oz/WickedWitchoftheEast.txt /Oz/GoodWitchoftheSouth.txt /Oz/WickedWitchoftheWest.txt 
touch: cannot touch ‘/Oz/GoodWitchoftheEast.txt’: No such file or directory
touch: cannot touch ‘/Oz/WickedWitchoftheEast.txt’: No such file or directory
touch: cannot touch ‘/Oz/GoodWitchoftheSouth.txt’: No such file or directory
touch: cannot touch ‘/Oz/WickedWitchoftheWest.txt’: No such file or directory
louis@louis-HP-ENVY-Notebook:~$ touch Oz/GoodWitchoftheEast.txt Oz/WickedWitchoftheEast.txt Oz/GoodWitchoftheSouth.txt Oz/WickedWitchoftheWest.txt 
louis@louis-HP-ENVY-Notebook:~$ rm Oz/WickedWitchoftheEast.txt 
louis@louis-HP-ENVY-Notebook:~$ mv House/Dorothy.txt Oz/Dorothy.txt
louis@louis-HP-ENVY-Notebook:~$ touch Scarecrow.txt "Tin Man" "Cowardly Lion"
louis@louis-HP-ENVY-Notebook:~$ mkdir "Emerald City"
louis@louis-HP-ENVY-Notebook:~$ mv Scarecrow.txt "Emerald City"/Scarecrow.txt
louis@louis-HP-ENVY-Notebook:~$ mv "Tin Man".txt "Emerald City"/"Tin Man".txt
mv: cannot stat ‘Tin Man.txt’: No such file or directory
louis@louis-HP-ENVY-Notebook:~$ mv "Tin Man" "Emerald City/Tin Man"
louis@louis-HP-ENVY-Notebook:~$ mv "Cowardly Lion" "Emerald City/Cowardly Lion"
louis@louis-HP-ENVY-Notebook:~$ touch "Oz/Flying Monkees"
louis@louis-HP-ENVY-Notebook:~$ rm Oz/WickedWitchoftheWest.txt
louis@louis-HP-ENVY-Notebook:~$ echo "a diploma" >> "Emerald City/Scarecrow.txt"
louis@louis-HP-ENVY-Notebook:~$ echo "a heart shaped watch" >> "Emerald City/Tin Man"
louis@louis-HP-ENVY-Notebook:~$ echo "a medal" >> "Emerald City/Cowardly Lion"
louis@louis-HP-ENVY-Notebook:~$

**Comment by andrewsunglaekim** [comment]
Hey louis, I think a large portion of these issues is because you're trying to create files/folders with spaces in the middle. A convention you'll want to follow is to use underscores or hypens instead! Let me know if you have any questions

**Comment by andrewsunglaekim** [comment]
@l
