### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by JoshNezi** [ga-wdi-exercises/to_oz#59]
![image](https://cloud.githubusercontent.com/assets/8755620/13776529/ff22bd96-ea80-11e5-8b56-583e4b3d7bba.png)

**Comment by andrewsunglaekim** [comment]
:+1: looks great, was curious why you had a comfort of just 3? Let me know if there's anything I can shed some light on

**Comment by JoshNezi** [comment]
Hi Andy, it just took me a bit longer than I thought. I think that I just have to go over and use some of the commands a bit more.
