### ISSUE TITLE
Mohamed's HW

### ISSUE THREAD

**Issue by mohamedrchalal** [ga-wdi-exercises/to_oz#6]
$ pwd
/Users/fatman570
~ 
$ cd fundamentals/
~/fundamentals 
$ mkdir House
~/fundamentals 
$ touch Dorothy.txt
~/fundamentals 
$ touch Toto.txt
~/fundamentals 
$ ls
Dorothy.txt     Toto.txt        wdi-fundamentals-rps
House           git-practice
~/fundamentals 
$ cd House/
~/fundamentals/House 
$ cd ..
~/fundamentals 
$ mkdir Oz
~/fundamentals 
$ cd Oz
~/fundamentals/Oz 
$ touch Good Witch of the North
~/fundamentals/Oz 
$ Good Witch of the South
-bash: Good: command not found
~/fundamentals/Oz 
$ touch Good Witch of the South
~/fundamentals/Oz 
$ touch Wicked Witch of the East
~/fundamentals/Oz 
$ touch Wicked Witch of the West
~/fundamentals/Oz 
$ ls
East    Good    North   South   West    Wicked  Witch   of  the
~/fundamentals/Oz 
$ touch Good Witch of the North
~/fundamentals/Oz 
$ touch Good Witch of the North.txt
~/fundamentals/Oz 
$ touch Good Witch of the South.txt
~/fundamentals/Oz 
$ touch Wicked Witch of the West.txt
~/fundamentals/Oz 
$ touch Wicked Witch of the East.txt
~/fundamentals/Oz 
$ rm Wicked Witch of the East.txt
~/fundamentals/Oz 
$ ls
Good        North       North.txt   South.txt   West.txt
~/fundamentals/Oz 
$ touch WickedWitchoftheWest.txt
~/fundamentals/Oz 
$ touch WickedWitchoftheWest
~/fundamentals/Oz 
$ touch GoodWitchoftheSouth
~/fundamentals/Oz 
$ touch GoodWitchoftheNorth
~/fundamentals/Oz 
$ touch scarecrow
~/fundamentals/Oz 
$ touch TinMan
~/fundamentals/Oz 
$ touch CowardlyLion
~/fundamentals/Oz 
$ mkdir Emerald City
~/fundamentals/Oz 
$ ls
CowardlyLion        GoodWitchoftheSouth scarecrow
Emerald City        TinMan
GoodWitchoftheNorth WickedWitchoftheWest
~/fundamentals/Oz 
$ mv TinMan CowardlyLion scarecrow "Emerald City"
~/fundamentals/Oz 
$ ls
Emerald City        GoodWitchoftheSouth
GoodWitchoftheNorth WickedWitchoftheWest
~/fundamentals/Oz 
$ touch "Flying Monkeys"
~/fundamentals/Oz 
$ rm WickedWitchoftheWest
~/fundamentals/Oz 
$ echo "a diploma" >> scarecrow
~/fundamentals/Oz 
$ echo "a heart shaped watch" >> TinMan
~/fundamentals/Oz 
$ cd "Emerald City"
~/fundamentals/Oz/Emerald City 
$ cat TinMan
~/fundamentals/Oz/Emerald City 
$ echo "a Diploma >> scarecrow

> cat scarecrow
> echo "a Diploma" >> scarecrow
> cat scarecrow
> 
> ~/fundamentals/Oz/Emerald City 
> $ echo "a Diploma" >> scarecrow
> ~/fundamentals/Oz/Emerald City 
> $ cat scarecrow
> a Diploma
> ~/fundamentals/Oz/Emerald City 
> $ echo "a heart shaped watch" >> TinMan
> ~/fundamentals/Oz/Emerald City 
> $ echo "a medal" >> CowardlyLion
> ~/fundamentals/Oz/Emerald City 
> $

**Comment by RobertAKARobin** [comment]
Nice job!
