### ISSUE TITLE
CLI HW Julia Schultz

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/to_oz#61]
comfort: 4/5, I could have  done all of these in far fewer steps but typically opted to do one 'action' at a time. 
complete: 5/5

Last login: Mon May 23 11:42:38 on ttys000
~ (master #) 
$ pwd
/Users/juliaschultz
~ (master #) 
$ ls
Applications        Library         fundamentals
Desktop         Movies          funny_things
Documents       Music           wdi
Downloads       MySecureBackup3160.dmg  world
Downloads-2     Pictures
Dropbox         Public
~ (master #) 
$ cd wdi
~/wdi (master #) 
$ mkdir House
~/wdi (master #) 
$ ls
House       Rakefile    installfest.yml
~/wdi (master #) 
$ cd House
~/wdi/House (master #) 
$ touch Dorothy.txt
~/wdi/House (master #) 
$ ls
Dorothy.txt
~/wdi/House (master #) 
$ touch Toto.txt
~/wdi/House (master #) 
$ mkdir Oz
~/wdi/House (master #) 
$ ls
Dorothy.txt Oz      Toto.txt
~/wdi/House (master #) 
$ touch GoodWitch_North.txt
~/wdi/House (master #) 
$ touch touch WickedWitch_South.txt
~/wdi/House (master #) 
$ rm WickedWitch_South.txt
~/wdi/House (master #) 
$ ls
Dorothy.txt     Oz          touch
GoodWitch_North.txt Toto.txt
~/wdi/House (master #) 
$ ls -a
.           GoodWitch_North.txt touch
..          Oz
Dorothy.txt     Toto.txt
~/wdi/House (master #) 
$ cd touch
-bash: cd: touch: Not a directory
~/wdi/House (master #) 
$ rm touch
~/wdi/House (master #) 
$ ls
Dorothy.txt     Oz
GoodWitch_North.txt Toto.txt
~/wdi/House (master #) 
$ ls
Dorothy.txt     Oz
GoodWitch_North.txt Toto.txt
~/wdi/House (master #) 
$ pwd
/Users/juliaschultz/wdi/House
~/wdi/House (master #) 
$ ../
-bash: ../: is a directory
~/wdi/House (master #) 
$ ls
Dorothy.txt     Oz
GoodWitch_North.txt Toto.txt
~/wdi/House (master #) 
$ /..
-bash: /..: is a directory
~/wdi/House (master #) 
$ ls
Dorothy.txt     Oz
GoodWitch_North.txt Toto.txt
~/wdi/House (master #) 
$ cd ..
~/wdi (master #) 
$ ls
House       Rakefile    installfest.yml
~/wdi (master #) 
$ mkdir HW1
~/wdi (master #) 
$ ls
HW1     House       Rakefile    installfest.yml
~/wdi (master #) 
$ mvdir House HW1
-bash: mvdir: command not found
~/wdi (master #) 
$ mv House HW1
~/wdi (master #) 
$ ls
HW1     Rakefile    installfest.yml
~/wdi (master #) 
$ cd HW1
~/wdi/HW1 (master #) 
$ ls
House
~/wdi/HW1 (master #) 
$ cd House
~/wdi/HW1/House (master #) 
$ ls
Dorothy.txt     Oz
GoodWitch_North.txt Toto.txt
~/wdi/HW1/House (master #) 
$ mv GoodWitch_North.txt Oz
~/wdi/HW1/House (master #) 
$ cd Oz
~/wdi/HW1/House/Oz (master #) 
$ ls
GoodWitch_North.txt
~/wdi/HW1/House/Oz (master #) 
$ ls
GoodWitch_North.txt
~/wdi/HW1/House/Oz (master #) 
$ touch WickedWitch_East.txt 
~/wdi/HW1/House/Oz (master #) 
$ touch GoodWitch_South.txt
~/wdi/HW1/House/Oz (master #) 
$ touch WickedWitch_West.txt
~/wdi/HW1/House/Oz (master #) 
$ ls
GoodWitch_North.txt WickedWitch_East.txt
GoodWitch_South.txt WickedWitch_West.txt
~/wdi/HW1/House/Oz (master #) 
$ rm WickedWitch_East.txt
~/wdi/HW1/House/Oz (master #) 
$ mv Dorothy.txt House Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/HW1/House/Oz (master #) 
$ ls
GoodWitch_North.txt GoodWitch_South.txt WickedWitch_West.txt
~/wdi/HW1/House/Oz (master #) 
$ ../
-bash: ../: is a directory
~/wdi/HW1/House/Oz (master #) 
$ ls
GoodWitch_North.txt GoodWitch_South.txt WickedWitch_West.txt
~/wdi/HW1/House/Oz (master #) 
$ ..
-bash: ..: command not found
~/wdi/HW1/House/Oz (master #) 
$ cd ..
~/wdi/HW1/House (master #) 
$ ls
Dorothy.txt Oz      Toto.txt
~/wdi/HW1/House (master #) 
$ mv Dorothy.txt House Oz
mv: rename House to Oz/House: No such file or directory
~/wdi/HW1/House (master #) 
$ mv Dorothy.txt Oz
mv: Dorothy.txt: No such file or directory
~/wdi/HW1/House (master #) 
$ ls
Oz      Toto.txt
~/wdi/HW1/House (master #) 
$ ls
Oz      Toto.txt
~/wdi/HW1/House (master #) 
$ cd Oz
~/wdi/HW1/House/Oz (master #) 
$ ls
Dorothy.txt     GoodWitch_South.txt
GoodWitch_North.txt WickedWitch_West.txt
~/wdi/HW1/House/Oz (master #) 
$ pwd
/Users/juliaschultz/wdi/HW1/House/Oz
~/wdi/HW1/House/Oz (master #) 
$ cd ..
~/wdi/HW1/House (master #) 
$ ls
Oz      Toto.txt
~/wdi/HW1/House (master #) 
$ pwd
/Users/juliaschultz/wdi/HW1/House
~/wdi/HW1/House (master #) 
$ cd ..
~/wdi/HW1 (master #) 
$ ls
House
~/wdi/HW1 (master #) 
$ touch Scarecrow.txt
~/wdi/HW1 (master #) 
$ touch TinMan.txt
~/wdi/HW1 (master #) 
$ touch Cowardlylion.txt
~/wdi/HW1 (master #) 
$ mv Scarecrow.txt TinMan.txt CowardlyLion.txt Emerald City
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/HW1 (master #) 
$ ls
Cowardlylion.txt    House           Scarecrow.txt       TinMan.txt
~/wdi/HW1 (master #) 
$ mkdir Emerald_City
~/wdi/HW1 (master #) 
$ mv TinMan.txt Scarecrow.txt Cowardlylion.txt Emerald_City
~/wdi/HW1 (master #) 
$ ls
Emerald_City    House
~/wdi/HW1 (master #) 
$ ls Emerald_City
Cowardlylion.txt    Scarecrow.txt       TinMan.txt
~/wdi/HW1 (master #) 
$ pwd
/Users/juliaschultz/wdi/HW1
~/wdi/HW1 (master #) 
$ ls
Emerald_City    House
~/wdi/HW1 (master #) 
$ cd House
~/wdi/HW1/House (master #) 
$ ls
Oz      Toto.txt
~/wdi/HW1/House (master #) 
$ mv Oz HW1
~/wdi/HW1/House (master #) 
$ ls
HW1     Toto.txt
~/wdi/HW1/House (master #) 
$ pwd
/Users/juliaschultz/wdi/HW1/House
~/wdi/HW1/House (master #) 
$ cd ..
~/wdi/HW1 (master #) 
$ ls
Emerald_City    House
~/wdi/HW1 (master #) 
$ cd House
~/wdi/HW1/House (master #) 
$ ls
HW1     Toto.txt
~/wdi/HW1/House (master #) 
$ cd HW1
~/wdi/HW1/House/HW1 (master #) 
$ ls
Dorothy.txt     GoodWitch_North.txt GoodWitch_South.txt WickedWitch_West.txt
~/wdi/HW1/House/HW1 (master #) 
$ pwd
/Users/juliaschultz/wdi/HW1/House/HW1
~/wdi/HW1/House/HW1 (master #) 
$ mv Dorothy.txt GoodWitch_North.txt GoodWitch_South.txt WickedWitch_West.txt
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/HW1/House/HW1 (master #) 
$ mv Dorothy.txt GoodWitch_North.txt GoodWitch_South.txt WickedWitch_West.txt
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/HW1/House/HW1 (master #) 
$ ls
Dorothy.txt     GoodWitch_North.txt GoodWitch_South.txt WickedWitch_West.txt
~/wdi/HW1/House/HW1 (master #) 
$ pwd
/Users/juliaschultz/wdi/HW1/House/HW1
~/wdi/HW1/House/HW1 (master #) 
$ cd ../
~/wdi/HW1/House (master #) 
$ ls
HW1     Toto.txt
~/wdi/HW1/House (master #) 
$ c
-bash: c: command not found
d~/wdi/HW1/House (master #) 
$ dpwd
-bash: dpwd: command not found
~/wdi/HW1/House (master #) 
$ pwd
/Users/juliaschultz/wdi/HW1/House
~/wdi/HW1/House (master #) 
$ cd ../
~/wdi/HW1 (master #) 
$ ls
Emerald_City    House
~/wdi/HW1 (master #) 
$ cd house
~/wdi/HW1/house (master #) 
$ ls
HW1     Toto.txt
~/wdi/HW1/house (master #) 
$ cd HW1
~/wdi/HW1/house/HW1 (master #) 
$ ls
Dorothy.txt     GoodWitch_North.txt GoodWitch_South.txt WickedWitch_West.txt
~/wdi/HW1/house/HW1 (master #) 
$ cd ../
~/wdi/HW1/house (master #) 
$ ls
HW1     Toto.txt
~/wdi/HW1/house (master #) 
$ mv HW1 Oz
~/wdi/HW1/house (master #) 
$ ls
Oz      Toto.txt
~/wdi/HW1/house (master #) 
$ cd Oz
~/wdi/HW1/house/Oz (master #) 
$ ls
Dorothy.txt     GoodWitch_North.txt GoodWitch_South.txt WickedWitch_West.txt
~/wdi/HW1/house/Oz (master #) 
$ cd ../
~/wdi/HW1/house (master #) 
$ cd ../
~/wdi/HW1 (master #) 
$ ls
Emerald_City    House
~/wdi/HW1 (master #) 
$ cd House 
~/wdi/HW1/House (master #) 
$ ls
Oz      Toto.txt
~/wdi/HW1/House (master #) 
$ mv Oz ~/wdi/HW1/House/Oz
mv: rename Oz to /Users/juliaschultz/wdi/HW1/House/Oz/Oz: Invalid argument
~/wdi/HW1/House (master #) 
$ cp Oz /House
cp: Oz is a directory (not copied).
~/wdi/HW1/House (master #) 
$ mv /wdi/HW1/House/Oz /wdi/HW1
mv: rename /wdi/HW1/House/Oz to /wdi/HW1: No such file or directory
~/wdi/HW1/House (master #) 
$ pwd
/Users/juliaschultz/wdi/HW1/House
~/wdi/HW1/House (master #) 
$ ls
Oz      Toto.txt
~/wdi/HW1/House (master #) 
$ mv Oz /HW1/House
mv: rename Oz to /HW1/House: No such file or directory
~/wdi/HW1/House (master #) 
$ pwd
/Users/juliaschultz/wdi/HW1/House
~/wdi/HW1/House (master #) 
$ ls
Oz      Toto.txt
~/wdi/HW1/House (master #) 
$ cd Oz
~/wdi/HW1/House/Oz (master #) 
$ mv ~/wdi/HW1/House/Oz /House
mv: rename /Users/juliaschultz/wdi/HW1/House/Oz to /House: Permission denied
~/wdi/HW1/House/Oz (master #) 
$ mv ~/wdi/HW1/House/Oz ~/wdi/HW1
~/wdi/HW1/House/Oz (master #) 
$ ls
Dorothy.txt     GoodWitch_North.txt GoodWitch_South.txt WickedWitch_West.txt
~/wdi/HW1/House/Oz (master #) 
$ cd ../../
~/wdi (master #) 
$ ls
HW1     Rakefile    installfest.yml
~/wdi (master #) 
$ cd HW1
~/wdi/HW1 (master #) 
$ pwd
/Users/juliaschultz/wdi/HW1
~/wdi/HW1 (master #) 
$ ls
Emerald_City    House       Oz
~/wdi/HW1 (master #) 
$ ls Oz
Dorothy.txt     GoodWitch_North.txt GoodWitch_South.txt WickedWitch_West.txt
~/wdi/HW1 (master #) 
$ ls Emerald_city
Cowardlylion.txt    Scarecrow.txt       TinMan.txt
~/wdi/HW1 (master #) 
$ pwd
/Users/juliaschultz/wdi/HW1
~/wdi/HW1 (master #) 
$ cd Oz
~/wdi/HW1/Oz (master #) 
$ touch Flying_Monkeys.txt
~/wdi/HW1/Oz (master #) 
$ ls
Dorothy.txt     GoodWitch_North.txt WickedWitch_West.txt
Flying_Monkeys.txt  GoodWitch_South.txt
~/wdi/HW1/Oz (master #) 
$ rm WickedWitch_West.txt
~/wdi/HW1/Oz (master #) 
$ ls
Dorothy.txt     Flying_Monkeys.txt  GoodWitch_North.txt GoodWitch_South.txt
~/wdi/HW1/Oz (master #) 
$ ls
Dorothy.txt     Flying_Monkeys.txt  GoodWitch_North.txt GoodWitch_South.txt
~/wdi/HW1/Oz (master #) 
$ cd ../
~/wdi/HW1 (master #) 
$ ls
Emerald_City    House       Oz
~/wdi/HW1 (master #) 
$ cd Emerald_City
~/wdi/HW1/Emerald_City (master #) 
$ ls
Cowardlylion.txt    Scarecrow.txt       TinMan.txt
~/wdi/HW1/Emerald_City (master #) 
$ echo "a diploma" >> Emerald_city/Scarecrow.txt
-bash: Emerald_city/Scarecrow.txt: No such file or directory
~/wdi/HW1/Emerald_City (master #) 
$ ls
Cowardlylion.txt    Scarecrow.txt       TinMan.txt
~/wdi/HW1/Emerald_City (master #) 
$ echo "a diploma" >> scarecrow.txt
~/wdi/HW1/Emerald_City (master #) 
$ ls
Cowardlylion.txt    Scarecrow.txt       TinMan.txt
~/wdi/HW1/Emerald_City (master #) 
$ echo "a heart shaped watch" >> TinMan.txt
~/wdi/HW1/Emerald_City (master #) 
$ echo "a medal for bravery" >> Cowardlylion.txt
~/wdi/HW1/Emerald_City (master #) 
$

**Comment by RobertAKARobin** [comment]
✅
