### ISSUE TITLE
CLI HW (James Hughes)

### ISSUE THREAD

**Issue by jhugheswebdev** [ga-wdi-exercises/to_oz#62]

**Comment by jhugheswebdev** [comment]
Last login: Mon May 23 14:26:47 on ttys000
Heez-Magnif:~ jameshughes$ mkdir House
mkdir: House: File exists
Heez-Magnif:~ jameshughes$ ls
Applications    Downloads   House       Music       fundamentals
Desktop     Dropbox     Library     Pictures    funny_things
Documents   GA-Blog     Movies      Public      wdi
Heez-Magnif:~ jameshughes$ touch Dorothy Toto/House
touch: Toto/House: No such file or directory
Heez-Magnif:~ jameshughes$ cd House
Heez-Magnif:House jameshughes$ ls
Heez-Magnif:House jameshughes$ mkdir Dorothy Toto
Heez-Magnif:House jameshughes$ ls
Dorothy Toto
Heez-Magnif:House jameshughes$ cd Toto
Heez-Magnif:Toto jameshughes$ cd ..
Heez-Magnif:House jameshughes$ mkdir Oz
Heez-Magnif:House jameshughes$ ls
Dorothy Oz  Toto
Heez-Magnif:House jameshughes$ touch GoodWitch_North.txt WickedWitch_East.txt
Heez-Magnif:House jameshughes$ ls
Dorothy         Oz          WickedWitch_East.txt
GoodWitch_North.txt Toto
Heez-Magnif:House jameshughes$ rm GoodWitch_North.txt WickedWitch_East.txt
Heez-Magnif:House jameshughes$ ls
Dorothy Oz  Toto
Heez-Magnif:House jameshughes$ cd Oz
Heez-Magnif:Oz jameshughes$ touch GoodWitch_North.txt WickedWitch_East.txt GoodWitch_South.txt WickedWitch_West.txt
Heez-Magnif:Oz jameshughes$ ls
GoodWitch_North.txt WickedWitch_East.txt
GoodWitch_South.txt WickedWitch_West.txt
Heez-Magnif:Oz jameshughes$ rm WickedWitch_East.txt
Heez-Magnif:Oz jameshughes$ cd ..
Heez-Magnif:House jameshughes$ mv Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Heez-Magnif:House jameshughes$ mv -v Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Heez-Magnif:House jameshughes$ mv House/Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Heez-Magnif:House jameshughes$ ls
Dorothy Oz  Toto
Heez-Magnif:House jameshughes$ mv -n Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Heez-Magnif:House jameshughes$ mv -f Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Heez-Magnif:House jameshughes$ mv Dorothy Oz
Heez-Magnif:House jameshughes$ ls
Oz  Toto
Heez-Magnif:House jameshughes$ cd Oz
Heez-Magnif:Oz jameshughes$ touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt
Heez-Magnif:Oz jameshughes$ ls
Cowardly_Lion.txt   GoodWitch_South.txt WickedWitch_West.txt
Dorothy         Scarecrow.txt
GoodWitch_North.txt Tin_Man.txt
Heez-Magnif:Oz jameshughes$ mkdir Emerald_City
Heez-Magnif:Oz jameshughes$ mv Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt Emerald_City
Heez-Magnif:Oz jameshughes$ cd Emerald_City
Heez-Magnif:Emerald_City jameshughes$ ls
Cowardly_Lion.txt   Scarecrow.txt       Tin_Man.txt
Heez-Magnif:Emerald_City jameshughes$ cd ..
Heez-Magnif:Oz jameshughes$ touch Flying_Monkeys.txt
Heez-Magnif:Oz jameshughes$ ls
Dorothy         Flying_Monkeys.txt  GoodWitch_South.txt
Emerald_City        GoodWitch_North.txt WickedWitch_West.txt
Heez-Magnif:Oz jameshughes$ rm WickedWitch_West.txt
Heez-Magnif:Oz jameshughes$ ls
Dorothy         Flying_Monkeys.txt  GoodWitch_South.txt
Emerald_City        GoodWitch_North.txt
Heez-Magnif:Oz jameshughes$ echo "a diploma" >> Oz/Scarecrow.txt
-bash: Oz/Scarecrow.txt: No such file or directory
Heez-Magnif:Oz jameshughes$ cd Emerald_City
Heez-Magnif:Emerald_City jameshughes$ ls
Cowardly_Lion.txt   Scarecrow.txt       Tin_Man.txt
Heez-Magnif:Emerald_City jameshughes$ echo "a diploma" >> Scarecrow.txt
Heez-Magnif:Emerald_City jameshughes$ echo "a heart shaped watch" >>Tin_Man.txt
Heez-Magnif:Emerald_City jameshughes$ echo "a medal" >>Cowardly_Lion.txt
Heez-Magnif:Emerald_City jameshughes$ ls
Cowardly_Lion.txt   Scarecrow.txt       Tin_Man.txt

**Comment by heezmagnif** [comment]
Last login: Mon May 23 14:26:47 on ttys000
Heez-Magnif:~ jameshughes$ mkdir House
mkdir: House: File exists
Heez-Magnif:~ jameshughes$ ls
Applications	Downloads	House		Music		fundamentals
Desktop		Dropbox		Library		Pictures	funny_things
Documents	GA-Blog		Movies		Public		wdi
Heez-Magnif:~ jameshughes$ touch Dorothy Toto/House
touch: Toto/House: No such file or directory
Heez-Magnif:~ jameshughes$ cd House
Heez-Magnif:House jameshughes$ ls
Heez-Magnif:House jameshughes$ mkdir Dorothy Toto
Heez-Magnif:House jameshughes$ ls
Dorothy	Toto
Heez-Magnif:House jameshughes$ cd Toto
Heez-Magnif:Toto jameshughes$ cd ..
Heez-Magnif:House jameshughes$ mkdir Oz
Heez-Magnif:House jameshughes$ ls
Dorothy	Oz	Toto
Heez-Magnif:House jameshughes$ touch GoodWitch_North.txt WickedWitch_East.txt
Heez-Magnif:House jameshughes$ ls
Dorothy			Oz			WickedWitch_East.txt
GoodWitch_North.txt	Toto
Heez-Magnif:House jameshughes$ rm GoodWitch_North.txt WickedWitch_East.txt
Heez-Magnif:House jameshughes$ ls
Dorothy	Oz	Toto
Heez-Magnif:House jameshughes$ cd Oz
Heez-Magnif:Oz jameshughes$ touch GoodWitch_North.txt WickedWitch_East.txt GoodWitch_South.txt WickedWitch_West.txt
Heez-Magnif:Oz jameshughes$ ls
GoodWitch_North.txt	WickedWitch_East.txt
GoodWitch_South.txt	WickedWitch_West.txt
Heez-Magnif:Oz jameshughes$ rm WickedWitch_East.txt
Heez-Magnif:Oz jameshughes$ cd ..
Heez-Magnif:House jameshughes$ mv Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Heez-Magnif:House jameshughes$ mv -v Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Heez-Magnif:House jameshughes$ mv House/Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Heez-Magnif:House jameshughes$ ls
Dorothy	Oz	Toto
Heez-Magnif:House jameshughes$ mv -n Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Heez-Magnif:House jameshughes$ mv -f Dorothy/Oz
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Heez-Magnif:House jameshughes$ mv Dorothy Oz
Heez-Magnif:House jameshughes$ ls
Oz	Toto
Heez-Magnif:House jameshughes$ cd Oz
Heez-Magnif:Oz jameshughes$ touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt
Heez-Magnif:Oz jameshughes$ ls
Cowardly_Lion.txt	GoodWitch_South.txt	WickedWitch_West.txt
Dorothy			Scarecrow.txt
GoodWitch_North.txt	Tin_Man.txt
Heez-Magnif:Oz jameshughes$ mkdir Emerald_City
Heez-Magnif:Oz jameshughes$ mv Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt Emerald_City
Heez-Magnif:Oz jameshughes$ cd Emerald_City
Heez-Magnif:Emerald_City jameshughes$ ls
Cowardly_Lion.txt	Scarecrow.txt		Tin_Man.txt
Heez-Magnif:Emerald_City jameshughes$ cd ..
Heez-Magnif:Oz jameshughes$ touch Flying_Monkeys.txt
Heez-Magnif:Oz jameshughes$ ls
Dorothy			Flying_Monkeys.txt	GoodWitch_South.txt
Emerald_City		GoodWitch_North.txt	WickedWitch_West.txt
Heez-Magnif:Oz jameshughes$ rm WickedWitch_West.txt
Heez-Magnif:Oz jameshughes$ ls
Dorothy			Flying_Monkeys.txt	GoodWitch_South.txt
Emerald_City		GoodWitch_North.txt
Heez-Magnif:Oz jameshughes$ echo "a diploma" >> Oz/Scarecrow.txt
-bash: Oz/Scarecrow.txt: No such file or directory
Heez-Magnif:Oz jameshughes$ cd Emerald_City
Heez-Magnif:Emerald_City jameshughes$ ls
Cowardly_Lion.txt	Scarecrow.txt		Tin_Man.txt
Heez-Magnif:Emerald_City jameshughes$ echo "a diploma" >> Scarecrow.txt
Heez-Magnif:Emerald_City jameshughes$ echo "a heart shaped watch" >>Tin_Man.txt
Heez-Magnif:Emerald_City jameshughes$ echo "a medal" >>Cowardly_Lion.txt
Heez-Magnif:Emerald_City jameshughes$ ls
Cowardly_Lion.txt	Scarecrow.txt		Tin_Man.txt

**Comment by RobertAKARobin** [comment]
✅ 

Any chance you could change your Github username to something resembling your real name a bit more closely? Thanks!

**Comment by jhugheswebdev** [comment]
okay, I changed it to jameshughesmagnif
