### ISSUE TITLE
CLI HW Matt Scott

### ISSUE THREAD

**Issue by chapel-of-bools** [ga-wdi-exercises/to_oz#63]
Completeness 5 / 5
Comfort Level 4 / 5

$ cd wdi
~/wdi 
$ cd Exercises
~/wdi/Exercises 
$ ls
To_Oz
~/wdi/Exercises 
$ cd To_Oz
~/wdi/Exercises/To_Oz 
$ ls
~/wdi/Exercises/To_Oz 
$ mkdir House
~/wdi/Exercises/To_Oz 
$ cd House
~/wdi/Exercises/To_Oz/House 
$ touch Dorothy Toto
~/wdi/Exercises/To_Oz/House 
$ cd ..
~/wdi/Exercises/To_Oz 
$ mkdir Oz
~/wdi/Exercises/To_Oz 
$ cd Oz
~/wdi/Exercises/To_Oz/Oz 
$ touch GoodWitchoftheNorth WickedWitchoftheEast GoodWitchoftheSouth WickedWitchoftheWest
~/wdi/Exercises/To_Oz/Oz 
$ rm WickedWitchoftheEast
~/wdi/Exercises/To_Oz/Oz 
$ cd ..
~/wdi/Exercises/To_Oz 
$ mv House/Dorothy Oz/Dorothy
~/wdi/Exercises/To_Oz 
$ cd Oz
~/wdi/Exercises/To_Oz/Oz 
$ touch Scarecrow.txt TinMan.txt CowardlyLion.txt
~/wdi/Exercises/To_Oz/Oz 
$ cd ..
~/wdi/Exercises/To_Oz 
$ mkdir Emerald_City
~/wdi/Exercises/To_Oz 
$ mv Oz/*.txt Emerald_City
~/wdi/Exercises/To_Oz 
$ cd ..
~/wdi/Exercises 
$ cd To_Oz
~/wdi/Exercises/To_Oz 
$ cd Oz
~/wdi/Exercises/To_Oz/Oz 
$ touch Flying_Monkeys
~/wdi/Exercises/To_Oz/Oz 
$ rm WickedWitchoftheWest
~/wdi/Exercises/To_Oz/Oz 
$ cd ..
~/wdi/Exercises/To_Oz 
$ cd Emerald_City
~/wdi/Exercises/To_Oz/Emerald_City 
$ echo "a diploma" >> Scarecrow.txt
~/wdi/Exercises/To_Oz/Emerald_City 
$ echo "a heart shaped watch" >> TinMan.txt
~/wdi/Exercises/To_Oz/Emerald_City 
$ echo "a medal" >> CowardlyLion.txt
~/wdi/Exercises/To_Oz/Emerald_City 
$

**Comment by RobertAKARobin** [comment]
✅
