### ISSUE TITLE
CLI HW (Andrew Young)

### ISSUE THREAD

**Issue by gandyland** [ga-wdi-exercises/to_oz#64]
Comfort: 5 / 5
Completeness: 5 / 5

Day 1 HW "To Oz"

Andrews-MacBook-Air:~ GandyYoung$ mkdir house
Andrews-MacBook-Air:~ GandyYoung$ ls
Applications    Downloads   Library     Pictures    house
Desktop     Fundamentals    Movies      Public      wdi
Documents   GA-Blog     Music       funny_things    world
Andrews-MacBook-Air:~ GandyYoung$ cd house
Andrews-MacBook-Air:house GandyYoung$ touch dorothy.txt
Andrews-MacBook-Air:house GandyYoung$ touch Toto.txt
Andrews-MacBook-Air:house GandyYoung$ mkdir Oz
Andrews-MacBook-Air:house GandyYoung$ cd oz
Andrews-MacBook-Air:oz GandyYoung$ cd ..
Andrews-MacBook-Air:house GandyYoung$ cd Oz
Andrews-MacBook-Air:Oz GandyYoung$ touch good_witch_of_the_north.txt
Andrews-MacBook-Air:Oz GandyYoung$ touch wicked_witch_of_the_east.txt
Andrews-MacBook-Air:Oz GandyYoung$ touch good_witch_of_the_south.txt
Andrews-MacBook-Air:Oz GandyYoung$ touch wicked_witch_of_the_west.txt
Andrews-MacBook-Air:Oz GandyYoung$ ls
good_witch_of_the_north.txt wicked_witch_of_the_east.txt
good_witch_of_the_south.txt wicked_witch_of_the_west.txt
Andrews-MacBook-Air:Oz GandyYoung$ rm wicked_witch_of_the_east.txt
Andrews-MacBook-Air:Oz GandyYoung$ ls
good_witch_of_the_north.txt wicked_witch_of_the_west.txt
good_witch_of_the_south.txt
Andrews-MacBook-Air:Oz GandyYoung$ cd ..
Andrews-MacBook-Air:house GandyYoung$ ls
Oz      Toto.txt    dorothy.txt
Andrews-MacBook-Air:house GandyYoung$ mv dorothy.txt oz/
Andrews-MacBook-Air:house GandyYoung$ cd oz
Andrews-MacBook-Air:oz GandyYoung$ ls
dorothy.txt         good_witch_of_the_south.txt
good_witch_of_the_north.txt wicked_witch_of_the_west.txt
Andrews-MacBook-Air:oz GandyYoung$ touch scarecrow.txt
Andrews-MacBook-Air:oz GandyYoung$ touch tin_man.txt
Andrews-MacBook-Air:oz GandyYoung$ touch cowardly_lion.txt
Andrews-MacBook-Air:oz GandyYoung$ mkdir emerald_city
Andrews-MacBook-Air:oz GandyYoung$ mv scarecrow.txt emerald_city/
Andrews-MacBook-Air:oz GandyYoung$ mv tin_man.txt emerald_city/
Andrews-MacBook-Air:oz GandyYoung$ mv cowardly_lion.txt emerald_city/
Andrews-MacBook-Air:oz GandyYoung$ ls
dorothy.txt         good_witch_of_the_south.txt
emerald_city            wicked_witch_of_the_west.txt
good_witch_of_the_north.txt
Andrews-MacBook-Air:oz GandyYoung$ cd emerald_city
Andrews-MacBook-Air:emerald_city GandyYoung$ ls
cowardly_lion.txt   scarecrow.txt       tin_man.txt
Andrews-MacBook-Air:emerald_city GandyYoung$ cd ..
Andrews-MacBook-Air:oz GandyYoung$ touch flying_monkeys.txt
Andrews-MacBook-Air:oz GandyYoung$ rm wicked_witch_of_the_west.txt
Andrews-MacBook-Air:oz GandyYoung$ ls
dorothy.txt         good_witch_of_the_north.txt
emerald_city            good_witch_of_the_south.txt
flying_monkeys.txt
Andrews-MacBook-Air:oz GandyYoung$ cd emerald_city
Andrews-MacBook-Air:emerald_city GandyYoung$ ls
cowardly_lion.txt   scarecrow.txt       tin_man.txt
Andrews-MacBook-Air:emerald_city GandyYoung$ echo "a diploma" >> scarecrow.txt
Andrews-MacBook-Air:emerald_city GandyYoung$ echo "a heart shaped watch" >> tin_man.txt
Andrews-MacBook-Air:emerald_city GandyYoung$ echo "a medal" >> cowardly_lion.txt
Andrews-MacBook-Air:emerald_city GandyYoung$

**Comment by RobertAKARobin** [comment]
✅
