### ISSUE TITLE
CLI HW (Adina Pollack)

### ISSUE THREAD

**Issue by adina-pollack** [ga-wdi-exercises/to_oz#65]
~ 
$ mkdir House
~ 
$ cd House
~/House 
$ touch Dorothy.txt
~/House 
$ touch Toto.txt
~/House 
$ mkdir Oz
~/House 
$ cd Oz
~/House/Oz 
$ touch Good_Witch_North.txt
~/House/Oz 
$ touch Wicked_Witch_East.txt
~/House/Oz 
$ touch Good_Witch_South.txt
~/House/Oz 
$ touch Wicked_Witch_West.txt
~/House/Oz 
$ ls
Good_Witch_North.txt    Wicked_Witch_East.txt
Good_Witch_South.txt    Wicked_Witch_West.txt
~/House/Oz 
$ rm Wicked_Witch_East
rm: Wicked_Witch_East: No such file or directory
~/House/Oz 
$ rm Wicked_Witch_East.txt
~/House/Oz 
$ cd .
~/House/Oz 
$ cd ..
~/House 
$ mv Dorothy.txt Oz/
~/House 
$ cd Oz
~/House/Oz 
$ ls
Dorothy.txt     Good_Witch_South.txt
Good_Witch_North.txt    Wicked_Witch_West.txt
~/House/Oz 
$ touch Scarecrow.txt
~/House/Oz 
$ touch Tin_Man.txt
~/House/Oz 
$ touch Cowardly_Lion.txt
~/House/Oz 
$ mkdir Emerald_City
~/House/Oz 
$ mv Scarecrow.txt Emerald_City/
~/House/Oz 
$ mv Tin_Man.txt Emerald_City/
~/House/Oz 
$ mv Cowardly_Lion.txt Emerald_City/
~/House/Oz 
$ touch Flying_Monkeys.txt
~/House/Oz 
$ rm Wicked_Witch_West.txt
~/House/Oz 
$ pwd
/Users/adinapollack/House/Oz
~/House/Oz 
$ ls
Dorothy.txt     Flying_Monkeys.txt  Good_Witch_South.txt
Emerald_City        Good_Witch_North.txt
~/House/Oz 
$ echo "a diploma" >> Scarecrow
~/House/Oz 
$ ls
Dorothy.txt     Flying_Monkeys.txt  Good_Witch_South.txt
Emerald_City        Good_Witch_North.txt    Scarecrow
~/House/Oz 
$ cd Emerald_City
~/House/Oz/Emerald_City 
$ ls
Cowardly_Lion.txt   Scarecrow.txt       Tin_Man.txt
~/House/Oz/Emerald_City 
$ cd ..
~/House/Oz 
$ rm Scarecrow
~/House/Oz 
$ ls
Dorothy.txt     Flying_Monkeys.txt  Good_Witch_South.txt
Emerald_City        Good_Witch_North.txt
~/House/Oz 
$ echo "a diploma" >> Emerald_City/Scarecrow.txt
~/House/Oz 
$ echo "a heart shaped watch" >> Emerald_City/Tin_Man.txt
~/House/Oz 
$ echo "a medal" >> Emerald_City/Cowardly_Lion.txt
~/House/Oz 
$ cd Emerald_City
~/House/Oz/Emerald_City 
$ ls
Cowardly_Lion.txt   Scarecrow.txt       Tin_Man.txt
~/House/Oz/Emerald_City

**Comment by RobertAKARobin** [comment]
✅
