### ISSUE TITLE
CLI HW Michael L Parks

### ISSUE THREAD

**Issue by ayespi** [ga-wdi-exercises/to_oz#67]
Completeness #/5
Comfort Level #/4

Last login: Mon May 23 09:28:14 on console
Michaels-MacBook-Pro:~ michaelparks$ ls
Applications        Google Drive        World
Creative Cloud Files    Library         fundamentals
Desktop         Movies          funny_things
Documents       Music           wdi
Downloads       Pictures
Dropbox         Public
Michaels-MacBook-Pro:~ michaelparks$ cd fundamentals
Michaels-MacBook-Pro:fundamentals michaelparks$ ls
git-practice        wdi-fundamentals-rps
Michaels-MacBook-Pro:fundamentals michaelparks$ ls
git-practice        wdi-fundamentals-rps
Michaels-MacBook-Pro:fundamentals michaelparks$ cd wdi-fundamentals-rps
Michaels-MacBook-Pro:wdi-fundamentals-rps michaelparks$ cd ..
Michaels-MacBook-Pro:fundamentals michaelparks$ ls
git-practice        wdi-fundamentals-rps
Michaels-MacBook-Pro:fundamentals michaelparks$ mkdir House
Michaels-MacBook-Pro:fundamentals michaelparks$ ls
House           git-practice        wdi-fundamentals-rps
Michaels-MacBook-Pro:fundamentals michaelparks$ ls
House           git-practice        wdi-fundamentals-rps
Michaels-MacBook-Pro:fundamentals michaelparks$ pwd
/Users/michaelparks/fundamentals
Michaels-MacBook-Pro:fundamentals michaelparks$ cd House
Michaels-MacBook-Pro:House michaelparks$ pwd
/Users/michaelparks/fundamentals/House
Michaels-MacBook-Pro:House michaelparks$ touch Dorothy
Michaels-MacBook-Pro:House michaelparks$ ls
Dorothy
Michaels-MacBook-Pro:House michaelparks$ pwd
/Users/michaelparks/fundamentals/House
Michaels-MacBook-Pro:House michaelparks$ touch Toto
Michaels-MacBook-Pro:House michaelparks$ ls
Dorothy Toto
Michaels-MacBook-Pro:House michaelparks$ mkdir Oz
Michaels-MacBook-Pro:House michaelparks$ ls
Dorothy Oz  Toto
Michaels-MacBook-Pro:House michaelparks$ cd Oz
Michaels-MacBook-Pro:Oz michaelparks$ ls
Michaels-MacBook-Pro:Oz michaelparks$ touch Good-Witch-of-the-North
Michaels-MacBook-Pro:Oz michaelparks$ ls
Good-Witch-of-the-North
Michaels-MacBook-Pro:Oz michaelparks$ touch Wicked-Witch-of-the-East
Michaels-MacBook-Pro:Oz michaelparks$ touch Good-Witch-of-the-South
Michaels-MacBook-Pro:Oz michaelparks$ touch Wicked-Witch-of-the-West
Michaels-MacBook-Pro:Oz michaelparks$ ls
Good-Witch-of-the-North     Wicked-Witch-of-the-East
Good-Witch-of-the-South     Wicked-Witch-of-the-West
Michaels-MacBook-Pro:Oz michaelparks$ rm Wicked-Witch-of-the-East
Michaels-MacBook-Pro:Oz michaelparks$ ls
Good-Witch-of-the-North     Wicked-Witch-of-the-West
Good-Witch-of-the-South
Michaels-MacBook-Pro:Oz michaelparks$ cd ..
Michaels-MacBook-Pro:House michaelparks$ ls
Dorothy Oz  Toto
Michaels-MacBook-Pro:House michaelparks$ mv Dorothy /Oz
mv: rename Dorothy to /Oz: Permission denied
Michaels-MacBook-Pro:House michaelparks$ ls
Dorothy Oz  Toto
Michaels-MacBook-Pro:House michaelparks$ pwd
/Users/michaelparks/fundamentals/House
Michaels-MacBook-Pro:House michaelparks$ cd ~
Michaels-MacBook-Pro:~ michaelparks$ ls
Applications        Google Drive        World
Creative Cloud Files    Library         fundamentals
Desktop         Movies          funny_things
Documents       Music           wdi
Downloads       Pictures
Dropbox         Public
Michaels-MacBook-Pro:~ michaelparks$ mv Dorothy ~/fundamentals/House/Oz
mv: rename Dorothy to /Users/michaelparks/fundamentals/House/Oz/Dorothy: No such file or directory
Michaels-MacBook-Pro:~ michaelparks$ ls
Applications        Google Drive        World
Creative Cloud Files    Library         fundamentals
Desktop         Movies          funny_things
Documents       Music           wdi
Downloads       Pictures
Dropbox         Public
Michaels-MacBook-Pro:~ michaelparks$ cd fundamentals
Michaels-MacBook-Pro:fundamentals michaelparks$ ls
House           git-practice        wdi-fundamentals-rps
Michaels-MacBook-Pro:fundamentals michaelparks$ cd House
Michaels-MacBook-Pro:House michaelparks$ ls
Dorothy Oz  Toto
Michaels-MacBook-Pro:House michaelparks$ rm Dorothy
Michaels-MacBook-Pro:House michaelparks$ ls
Oz  Toto
Michaels-MacBook-Pro:House michaelparks$ rm Toto
Michaels-MacBook-Pro:House michaelparks$ ls
Oz
Michaels-MacBook-Pro:House michaelparks$ touch Dorothy.txt
Michaels-MacBook-Pro:House michaelparks$ touch Toto.txt
Michaels-MacBook-Pro:House michaelparks$ ls
Dorothy.txt Oz      Toto.txt
Michaels-MacBook-Pro:House michaelparks$ cd Oz
Michaels-MacBook-Pro:Oz michaelparks$ ls
Good-Witch-of-the-North     Wicked-Witch-of-the-West
Good-Witch-of-the-South
Michaels-MacBook-Pro:Oz michaelparks$ touch Good-Witch-of-the-North.txt
Michaels-MacBook-Pro:Oz michaelparks$ touch Good-Witch-of-the-South.txt
Michaels-MacBook-Pro:Oz michaelparks$ touch Wicked-Witch-of-the-West.txt
Michaels-MacBook-Pro:Oz michaelparks$ touch Wicked-Witch-of-the-East.txt
Michaels-MacBook-Pro:Oz michaelparks$ ls
Good-Witch-of-the-North     Wicked-Witch-of-the-East.txt
Good-Witch-of-the-North.txt Wicked-Witch-of-the-West
Good-Witch-of-the-South     Wicked-Witch-of-the-West.txt
Good-Witch-of-the-South.txt
Michaels-MacBook-Pro:Oz michaelparks$ rm Good-Witch-of-the-North
Michaels-MacBook-Pro:Oz michaelparks$ ls
Good-Witch-of-the-North.txt Wicked-Witch-of-the-East.txt
Good-Witch-of-the-South     Wicked-Witch-of-the-West
Good-Witch-of-the-South.txt Wicked-Witch-of-the-West.txt
Michaels-MacBook-Pro:Oz michaelparks$ rm Good-Witch-of-the-South
Michaels-MacBook-Pro:Oz michaelparks$ ls
Good-Witch-of-the-North.txt Wicked-Witch-of-the-West
Good-Witch-of-the-South.txt Wicked-Witch-of-the-West.txt
Wicked-Witch-of-the-East.txt
Michaels-MacBook-Pro:Oz michaelparks$ rm Wicked-Witch-of-the-West
Michaels-MacBook-Pro:Oz michaelparks$ ls
Good-Witch-of-the-North.txt Wicked-Witch-of-the-East.txt
Good-Witch-of-the-South.txt Wicked-Witch-of-the-West.txt
Michaels-MacBook-Pro:Oz michaelparks$ rm Wicked-Witch-of-the-East.txt
Michaels-MacBook-Pro:Oz michaelparks$ ls
Good-Witch-of-the-North.txt Wicked-Witch-of-the-West.txt
Good-Witch-of-the-South.txt
Michaels-MacBook-Pro:Oz michaelparks$ cd ..
Michaels-MacBook-Pro:House michaelparks$ ls
Dorothy.txt Oz      Toto.txt
Michaels-MacBook-Pro:House michaelparks$ mv Dorothy.txt Oz/Dorothy.txt
Michaels-MacBook-Pro:House michaelparks$ ls
Oz      Toto.txt
Michaels-MacBook-Pro:House michaelparks$ cd Oz
Michaels-MacBook-Pro:Oz michaelparks$ ls
Dorothy.txt         Good-Witch-of-the-South.txt
Good-Witch-of-the-North.txt Wicked-Witch-of-the-West.txt
Michaels-MacBook-Pro:Oz michaelparks$ pwd
/Users/michaelparks/fundamentals/House/Oz
Michaels-MacBook-Pro:Oz michaelparks$ touch Scarecrow.txt
Michaels-MacBook-Pro:Oz michaelparks$ touch Tin-Man.txt
Michaels-MacBook-Pro:Oz michaelparks$ touch Cowardly-Lion.txt
Michaels-MacBook-Pro:Oz michaelparks$ mkdir Emerald-City
Michaels-MacBook-Pro:Oz michaelparks$ ls
Cowardly-Lion.txt       Good-Witch-of-the-South.txt
Dorothy.txt         Scarecrow.txt
Emerald-City            Tin-Man.txt
Good-Witch-of-the-North.txt Wicked-Witch-of-the-West.txt
Michaels-MacBook-Pro:Oz michaelparks$ mv Scarecrow.txt /Emerald-City/Scarecrow.txt
mv: rename Scarecrow.txt to /Emerald-City/Scarecrow.txt: No such file or directory
Michaels-MacBook-Pro:Oz michaelparks$ ls
Cowardly-Lion.txt       Good-Witch-of-the-South.txt
Dorothy.txt         Scarecrow.txt
Emerald-City            Tin-Man.txt
Good-Witch-of-the-North.txt Wicked-Witch-of-the-West.txt
Michaels-MacBook-Pro:Oz michaelparks$ mv Scarecrow.txt ~/fundamentals/House/Oz/Emerald-City/
Michaels-MacBook-Pro:Oz michaelparks$ ls
Cowardly-Lion.txt       Good-Witch-of-the-South.txt
Dorothy.txt         Tin-Man.txt
Emerald-City            Wicked-Witch-of-the-West.txt
Good-Witch-of-the-North.txt
Michaels-MacBook-Pro:Oz michaelparks$ cd Emerald-City
Michaels-MacBook-Pro:Emerald-City michaelparks$ ls
Scarecrow.txt
Michaels-MacBook-Pro:Emerald-City michaelparks$ cd ..
Michaels-MacBook-Pro:Oz michaelparks$ ls
Cowardly-Lion.txt       Good-Witch-of-the-South.txt
Dorothy.txt         Tin-Man.txt
Emerald-City            Wicked-Witch-of-the-West.txt
Good-Witch-of-the-North.txt
Michaels-MacBook-Pro:Oz michaelparks$ mv Tin-Man.txt ~/fundamentals/House/Oz/Emerald-City/
Michaels-MacBook-Pro:Oz michaelparks$ mv Cowardly-Lion.txt ~/fundamentals/House/Oz/Emerald-City/
Michaels-MacBook-Pro:Oz michaelparks$ ls
Dorothy.txt         Good-Witch-of-the-South.txt
Emerald-City            Wicked-Witch-of-the-West.txt
Good-Witch-of-the-North.txt
Michaels-MacBook-Pro:Oz michaelparks$ cd Emerald-City
Michaels-MacBook-Pro:Emerald-City michaelparks$ ls
Cowardly-Lion.txt   Scarecrow.txt       Tin-Man.txt
Michaels-MacBook-Pro:Emerald-City michaelparks$ pwd
/Users/michaelparks/fundamentals/House/Oz/Emerald-City
Michaels-MacBook-Pro:Emerald-City michaelparks$ cd ..
Michaels-MacBook-Pro:Oz michaelparks$ pwd
/Users/michaelparks/fundamentals/House/Oz
Michaels-MacBook-Pro:Oz michaelparks$ touch Flying-Monkeys.txt
Michaels-MacBook-Pro:Oz michaelparks$ ls
Dorothy.txt         Good-Witch-of-the-North.txt
Emerald-City            Good-Witch-of-the-South.txt
Flying-Monkeys.txt      Wicked-Witch-of-the-West.txt
Michaels-MacBook-Pro:Oz michaelparks$ rm Wicked-Witch-of-the-West.txt
Michaels-MacBook-Pro:Oz michaelparks$ ls
Dorothy.txt         Good-Witch-of-the-North.txt
Emerald-City            Good-Witch-of-the-South.txt
Flying-Monkeys.txt
Michaels-MacBook-Pro:Oz michaelparks$ echo "a diploma" >>Oz/Scarecrow.txt
-bash: Oz/Scarecrow.txt: No such file or directory
Michaels-MacBook-Pro:Oz michaelparks$ ls
Dorothy.txt         Good-Witch-of-the-North.txt
Emerald-City            Good-Witch-of-the-South.txt
Flying-Monkeys.txt
Michaels-MacBook-Pro:Oz michaelparks$ cd Emerald-City
Michaels-MacBook-Pro:Emerald-City michaelparks$ ls
Cowardly-Lion.txt   Scarecrow.txt       Tin-Man.txt
Michaels-MacBook-Pro:Emerald-City michaelparks$ echo "a diploma" >> Emerald-City/Scarecrow.txt
-bash: Emerald-City/Scarecrow.txt: No such file or directory
Michaels-MacBook-Pro:Emerald-City michaelparks$ ls
Cowardly-Lion.txt   Scarecrow.txt       Tin-Man.txt
Michaels-MacBook-Pro:Emerald-City michaelparks$ pwd
/Users/michaelparks/fundamentals/House/Oz/Emerald-City
Michaels-MacBook-Pro:Emerald-City michaelparks$ ls
Cowardly-Lion.txt   Scarecrow.txt       Tin-Man.txt
Michaels-MacBook-Pro:Emerald-City michaelparks$ cat Scarecrow.txt 
Michaels-MacBook-Pro:Emerald-City michaelparks$ echo "a diploma" >> Scarecrow.txt
Michaels-MacBook-Pro:Emerald-City michaelparks$ ls
Cowardly-Lion.txt   Scarecrow.txt       Tin-Man.txt
Michaels-MacBook-Pro:Emerald-City michaelparks$ cat Scarecrow.txt 
a diploma
Michaels-MacBook-Pro:Emerald-City michaelparks$ echo "a heart shaped watch" >> Tin-Man.txt
Michaels-MacBook-Pro:Emerald-City michaelparks$ cat Tin-Man.txt 
a heart shaped watch
Michaels-MacBook-Pro:Emerald-City michaelparks$ echo "a medal" >> Cowardly-Lion.txt
Michaels-MacBook-Pro:Emerald-City michaelparks$ cat Cowardly-Lion.txt 
a medal
Michaels-MacBook-Pro:Emerald-City michaelparks$

**Comment by RobertAKARobin** [comment]
✅
