### ISSUE TITLE
CLI HW Kristin Pasive

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/to_oz#68]
Completeness: 5/5
Comfort level: 2/5

Kristins-MacBook-Air:exercises kristinpasive$ mkdir House
Kristins-MacBook-Air:exercises kristinpasive$ cd House
Kristins-MacBook-Air:House kristinpasive$ touch Dorothy Toto
Kristins-MacBook-Air:House kristinpasive$ mkdir Oz
Kristins-MacBook-Air:House kristinpasive$ cd Oz
Kristins-MacBook-Air:Oz kristinpasive$ touch Good-Witch-of-the-North Wicked-Witch-of-the-East Good-Witch-of-the-South Wicked-Witch-of-the-West
Kristins-MacBook-Air:Oz kristinpasive$ ls
total 0
-rw-r--r--  1 kristinpasive  staff  0 May 23 16:58 Good-Witch-of-the-North
-rw-r--r--  1 kristinpasive  staff  0 May 23 16:58 Good-Witch-of-the-South
-rw-r--r--  1 kristinpasive  staff  0 May 23 16:58 Wicked-Witch-of-the-East
-rw-r--r--  1 kristinpasive  staff  0 May 23 16:58 Wicked-Witch-of-the-West
Kristins-MacBook-Air:Oz kristinpasive$ rm -rf Wicked-Witch-of-the-East
Kristins-MacBook-Air:Oz kristinpasive$ mv ../Dorothy .
Kristins-MacBook-Air:Oz kristinpasive$ touch Scarecrow Tin-Man Cowardly-Lion
Kristins-MacBook-Air:Oz kristinpasive$ cd Emerald-City
Kristins-MacBook-Air:Emerald-City kristinpasive$ mv ../Scarecrow .
Kristins-MacBook-Air:Emerald-City kristinpasive$ mv ../Tin-Man .
Kristins-MacBook-Air:Emerald-City kristinpasive$ mv ../Cowardly-Lion .
Kristins-MacBook-Air:Emerald-City kristinpasive$ cd ..
Kristins-MacBook-Air:Oz kristinpasive$ touch Flying-Monkeys
Kristins-MacBook-Air:Oz kristinpasive$ rm Wicked-Witch-of-the-West
Kristins-MacBook-Air:Oz kristinpasive$ cd ..
Kristins-MacBook-Air:House kristinpasive$ echo "a diploma" >> Oz/Scarecrow
Kristins-MacBook-Air:House kristinpasive$ echo "a heart shaped watch" >> Oz/Tin-Man
Kristins-MacBook-Air:House kristinpasive$ echo "a medal" >> Oz/Cowardly-Lion

**Comment by RobertAKARobin** [comment]
✅
