### ISSUE TITLE
CLI HW Dave Corderman

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/to_oz#69]
Yovotome:dropbox david$ mkdir House
Yovotome:dropbox david$ ls
Camera Uploads  House       Icon?       wdi
Yovotome:dropbox david$ touch House/Dorothy House/Toto
Yovotome:dropbox david$ ls House
Dorothy Toto
Yovotome:dropbox david$ mkdir Oz
Yovotome:dropbox david$ touch Oz/GoodWitchOfTheNorth
Yovotome:dropbox david$ touch Oz/WickedWitchOfTheEast
Yovotome:dropbox david$ touch Oz/WickedWitchOfTheWest
Yovotome:dropbox david$ touch Oz/GoodWitchOfTheSouth
Yovotome:dropbox david$ ls Oz
GoodWitchOfTheNorth WickedWitchOfTheEast
GoodWitchOfTheSouth WickedWitchOfTheWest
Yovotome:dropbox david$ rm Oz/WickedWitchOfTheEast
Yovotome:dropbox david$ mv House/Dorothy Oz
Yovotome:dropbox david$ ls Oz
Dorothy         GoodWitchOfTheSouth
GoodWitchOfTheNorth WickedWitchOfTheWest
Yovotome:dropbox david$ ls House
Toto
Yovotome:dropbox david$ touch Scarecrow TinMan CowardlyLion
Yovotome:dropbox david$ ls
Camera Uploads  House       Oz      TinMan
CowardlyLion    Icon?       Scarecrow   wdi
Yovotome:dropbox david$ cd Scarecrow
-bash: cd: Scarecrow: Not a directory
Yovotome:dropbox david$ mkdir Emerald_City
Yovotome:dropbox david$ mv Scarecrow Emerald_City
Yovotome:dropbox david$ ls
Camera Uploads  Emerald_City    Icon?       TinMan
CowardlyLion    House       Oz      wdi
Yovotome:dropbox david$ mv CowardlyLion Emerald_City
Yovotome:dropbox david$ mv TinMan Emerald_City
Yovotome:dropbox david$ ls Emerald_City
CowardlyLion    Scarecrow   TinMan
Yovotome:dropbox david$ touch Oz/Flying_Monkeys
Yovotome:dropbox david$ ls Oz
Dorothy         GoodWitchOfTheNorth WickedWitchOfTheWest
Flying_Monkeys      GoodWitchOfTheSouth
Yovotome:dropbox david$ rm Oz/WickedWitchOfTheWest
Yovotome:dropbox david$ echo "a diploma" >> Oz/Scarecrow
Yovotome:dropbox david$ ls Oz
Dorothy         GoodWitchOfTheNorth Scarecrow
Flying_Monkeys      GoodWitchOfTheSouth
Yovotome:dropbox david$ echo "a diploma" >> Oz/Scarecrow
Yovotome:dropbox david$ cat Oz/Scarecrow
a diploma
a diploma
Yovotome:dropbox david$ less Oz/Scarecrow
Yovotome:dropbox david$ more Oz/Scarecrow
a diploma
a diploma
Yovotome:dropbox david$ echo "a heart shaped wrench" >> Oz/TinMan
Yovotome:dropbox david$ echo "a medal" >> Oz/CowardlyLion
Yovotome:dropbox david$ less Oz/TinMan
Yovotome:dropbox david$

**Comment by dcordz** [comment]
Question: Is it possible to "touch" multiple files into one directory with one command?

Completeness 5/5
Comfort 5/5

**Comment by RobertAKARobin** [comment]
Yep!

```
$ touch thing1 thing2
```

✅
