### ISSUE TITLE
Matt K Day 1 HW

### ISSUE THREAD

**Issue by mkernsNCR** [ga-wdi-exercises/to_oz#7]
~/wdi/homework/assignment1 (master #) 
$ mkdir House
~/wdi/homework/assignment1 (master #) 
$ ls
House
~/wdi/homework/assignment1 (master #) 
$ cd House/
~/wdi/homework/assignment1/House (master #) 
$ touch Dorothy
~/wdi/homework/assignment1/House (master #) 
$ ls
Dorothy
~/wdi/homework/assignment1/House (master #) 
$ touch Toto
~/wdi/homework/assignment1/House (master #) 
$ mkdir Oz
~/wdi/homework/assignment1/House (master #) 
$ ls
Dorothy Oz  Toto
~/wdi/homework/assignment1/House (master #) 
$ cd Oz/
~/wdi/homework/assignment1/House/Oz (master #) 
$ touch "Good Witch of the North"
~/wdi/homework/assignment1/House/Oz (master #) 
$ touch "Wicked Witch of the East"
~/wdi/homework/assignment1/House/Oz (master #) 
$ touch "Good Witch of the South"
~/wdi/homework/assignment1/House/Oz (master #) 
$ touch "Wicked Witch of the West"
~/wdi/homework/assignment1/House/Oz (master #) 
$ rm -I "Wicked Witch of the East"
rm: illegal option -- I
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
~/wdi/homework/assignment1/House/Oz (master #) 
$ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South     Wicked Witch of the West
~/wdi/homework/assignment1/House/Oz (master #) 
$ rm -i "Wicked Witch of the East"
remove Wicked Witch of the East? 
~/wdi/homework/assignment1/House/Oz (master #) 
$ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South     Wicked Witch of the West
~/wdi/homework/assignment1/House/Oz (master #) 
$ rm -i "Wicked Witch of the East"
remove Wicked Witch of the East? yes
~/wdi/homework/assignment1/House/Oz (master #) 
$ ls
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
~/wdi/homework/assignment1/House/Oz (master #) 
$ cd ..
~/wdi/homework/assignment1/House (master #) 
$ ls
Dorothy Oz  Toto
~/wdi/homework/assignment1/House (master #) 
$ mv Dorothy ~/wdi/homework/assignment1/House/Oz/
~/wdi/homework/assignment1/House (master #) 
$ ls
Oz  Toto
~/wdi/homework/assignment1/House (master #) 
$ cd Oz
~/wdi/homework/assignment1/House/Oz (master #) 
$ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the West
~/wdi/homework/assignment1/House/Oz (master #) 
$ touch Scarecrow
~/wdi/homework/assignment1/House/Oz (master #) 
$ ls
Dorothy             Scarecrow
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
~/wdi/homework/assignment1/House/Oz (master #) 
$ touch "Tin Man"
~/wdi/homework/assignment1/House/Oz (master #) 
$ ls
Dorothy             Scarecrow
Good Witch of the North     Tin Man
Good Witch of the South     Wicked Witch of the West
~/wdi/homework/assignment1/House/Oz (master #) 
$ touch "Cowardly Lion"
~/wdi/homework/assignment1/House/Oz (master #) 
$ ls
Cowardly Lion           Scarecrow
Dorothy             Tin Man
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
~/wdi/homework/assignment1/House/Oz (master #) 
$ mkdir "Emerald City"
~/wdi/homework/assignment1/House/Oz (master #) 
$ ls
Cowardly Lion           Good Witch of the South
Dorothy             Scarecrow
Emerald City            Tin Man
Good Witch of the North     Wicked Witch of the West
~/wdi/homework/assignment1/House/Oz (master #) 
$ mv Scarecrow ~/wdi/homework/assignment1/House/Oz/Emerald\ City/
~/wdi/homework/assignment1/House/Oz (master #) 
$ mv "Cowardly Lion" ~/wdi/homework/assignment1/House/Oz/Emerald\ City/
~/wdi/homework/assignment1/House/Oz (master #) 
$ mv "Tin Man" ~/wdi/homework/assignment1/House/Oz/Emerald\ City/
~/wdi/homework/assignment1/House/Oz (master #) 
$ ls
Dorothy             Good Witch of the South
Emerald City            Wicked Witch of the West
Good Witch of the North
~/wdi/homework/assignment1/House/Oz (master #) 
$ touch "Flying Monkeys"
~/wdi/homework/assignment1/House/Oz (master #) 
$ ls
Dorothy             Good Witch of the North
Emerald City            Good Witch of the South
Flying Monkeys          Wicked Witch of the West
~/wdi/homework/assignment1/House/Oz (master #) 
$ rm -i "Wicked Witch of the West" 
remove Wicked Witch of the West? yes
~/wdi/homework/assignment1/House/Oz (master #) 
$ ls
Dorothy         Flying Monkeys      Good Witch of the South
Emerald City        Good Witch of the North
~/wdi/homework/assignment1/House/Oz (master #) 
$ echo "a diploma" >> Oz/Scarecrow
-bash: Oz/Scarecrow: No such file or directory
~/wdi/homework/assignment1/House/Oz (master #) 
$ cd Emerald\ City/
~/wdi/homework/assignment1/House/Oz/Emerald City (master #) 
$ ls
Cowardly Lion   Scarecrow   Tin Man
~/wdi/homework/assignment1/House/Oz/Emerald City (master #) 
$ echo "a diploma" >> Oz/Scarecrow
-bash: Oz/Scarecrow: No such file or directory
~/wdi/homework/assignment1/House/Oz/Emerald City (master #) 
$ echo "a diploma" >> Scarecrow
~/wdi/homework/assignment1/House/Oz/Emerald City (master #) 
$ ls
Cowardly Lion   Scarecrow   Tin Man
~/wdi/homework/assignment1/House/Oz/Emerald City (master #) 
$ echo "a heart shaped watch" >> "Tin Man" 
~/wdi/homework/assignment1/House/Oz/Emerald City (master #) 
$ echo "a medal" >> "Cowardly Lion" 
~/wdi/homework/assignment1/House/Oz/Emerald City (master #)

**Comment by RobertAKARobin** [comment]
Nice!
