### ISSUE TITLE
CLI Homework To Oz Mara Sanders

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/to_oz#71]
Completeness # / 5
Comfort Level: # / 3.5

Maras-MacBook-Air-2:excercises marasanders$ mkdir -p House/Oz/"Emerald City"
(I fixed the spelling of Exercise and went through some stuff with Robin deleted that code irrelevant to project)
Maras-MacBook-Air-2:wdi marasanders$ cd exercises
Maras-MacBook-Air-2:exercises marasanders$ ls
House
Maras-MacBook-Air-2:exercises marasanders$ cd House
Maras-MacBook-Air-2:House marasanders$ touch Dorothy Toto
Maras-MacBook-Air-2:House marasanders$ ls
Dorothy Oz  Toto
Maras-MacBook-Air-2:exercises marasanders$ cd House/Oz
Maras-MacBook-Air-2:Oz marasanders$ ls
Emerald City
Maras-MacBook-Air-2:Oz marasanders$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West"
Maras-MacBook-Air-2:Oz marasanders$ ls
Emerald City            Wicked Witch of the East
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
Maras-MacBook-Air-2:Oz marasanders$ rm -f "Wicked Witch of the East"
Maras-MacBook-Air-2:Oz marasanders$ ls
Emerald City            Good Witch of the South
Good Witch of the North     Wicked Witch of the West
Maras-MacBook-Air-2:Oz marasanders$ pwd
/Users/marasanders/wdi/exercises/House/Oz
Maras-MacBook-Air-2:Oz marasanders$ mv ../Dorothy .
Maras-MacBook-Air-2:Oz marasanders$ ls
Dorothy             Good Witch of the South
Emerald City            Wicked Witch of the West
Good Witch of the North
Maras-MacBook-Air-2:Oz marasanders$ touch Scarecrow "Tin Man" "Cowardly Lion"
Maras-MacBook-Air-2:Oz marasanders$ touch "Flying Monkeys"
Maras-MacBook-Air-2:Oz marasanders$ ls
Cowardly Lion           Good Witch of the South
Dorothy             Scarecrow
Emerald City            Tin Man
Flying Monkeys          Wicked Witch of the West
Good Witch of the North
Maras-MacBook-Air-2:Oz marasanders$ rm -f "Wicked Witch of the West"
Maras-MacBook-Air-2:Oz marasanders$ echo "a diploma" >> Oz/Scarecrow
-bash: Oz/Scarecrow: No such file or directory
Maras-MacBook-Air-2:Oz marasanders$ echo "a diploma" >> Scarecrow
Maras-MacBook-Air-2:Oz marasanders$ cat Scarecrow
a diploma
Maras-MacBook-Air-2:Oz marasanders$ echo "a heart shaped watch" >> "Tin Man"
Maras-MacBook-Air-2:Oz marasanders$ echo "a medal" >> "Cowardly Lion"
Maras-MacBook-Air-2:Oz marasanders$ mv \* "Emerald City"
mv: rename Emerald City to Emerald City/Emerald City: Invalid argument
Maras-MacBook-Air-2:Oz marasanders$ ls
Emerald City
Maras-MacBook-Air-2:Oz marasanders$ cd Emerald\ City/
Maras-MacBook-Air-2:Emerald City marasanders$ ls
Cowardly Lion       Good Witch of the North Tin Man
Dorothy         Good Witch of the South
Flying Monkeys      Scarecrow
Maras-MacBook-Air-2:Emerald City marasanders$ mv "Flying Monkeys" ../.
Maras-MacBook-Air-2:Emerald City marasanders$ ls
Cowardly Lion       Good Witch of the North Scarecrow
Dorothy         Good Witch of the South Tin Man
Maras-MacBook-Air-2:Emerald City marasanders$ cd ..
Maras-MacBook-Air-2:Oz marasanders$ ls
Emerald City    Flying Monkeys
Maras-MacBook-Air-2:Oz marasanders$ cd Emerald City
-bash: cd: Emerald: No such file or directory
Maras-MacBook-Air-2:Oz marasanders$ cd Emerald\ City/
Maras-MacBook-Air-2:Emerald City marasanders$ cat "Cowardly Lion"
a medal
Maras-MacBook-Air-2:Emerald City marasanders$

**Comment by RobertAKARobin** [comment]
✅
