### ISSUE TITLE
CLI HW Michael Holzheimer

### ISSUE THREAD

**Issue by alpha2262** [ga-wdi-exercises/to_oz#72]
Comfort 5
Completeness 5

$ mkdir House
$ cd House
$ touch Dorothy.txt
$ touch Toto.txt
$ mkdir Oz
$ cd Oz
$ touch Good_Witch_of_the_North.txt
$ touch Wicked_Witch_of_the_East.txt
$ touch Good_Witch_of_the_South.txt
$ touch Wicked_Witch_of_the_West.txt
$ rm Wicked_Witch_of_the_East.txt
$ mv .. /dorthy.txt .
$ touch Scarecrow.txt
$ touch Tin_Man.txt
$ touch Cowardly_Lion.txt
$ mkdir Emerald_City
$ cd Emerald_City
$ mv ../Scarecrow.txt .
$ mv ../Tin_Man.txt .
$ mv ../Cowardly_Lion.txt .
$ touch .. /Flying_Monkeys.txt
$ rm ../Wicked_Witch_of_the_West.txt
$ echo “a diploma” >> Scarecrow.txt 
$ echo “a heart shaped watch” >> Tin_Man.txt
$ echo “a medal” >> Cowardly_Lion.txt

**Comment by RobertAKARobin** [comment]
✅
