### ISSUE TITLE
HW to_oz Sean Tay

### ISSUE THREAD

**Issue by SeanTay** [ga-wdi-exercises/to_oz#74]
$ mkdir House
===== ~/wdi/exercises/HW1
$ touch Dorothy.txt Toto.txt House.txt
===== ~/wdi/exercises/HW1
$ mkdir Oz
===== ~/wdi/exercises/HW1
$ cd Oz
===== ~/wdi/exercises/HW1/Oz
$ touch Good\ Witch\ of\ the\ North.txt
===== ~/wdi/exercises/HW1/Oz
$ ls
Good Witch of the North.txt
===== ~/wdi/exercises/HW1/Oz
$ touch Wicked\ Witch\ of\ the\ East.txt Good\ Witch\ of\ the\ South.txt Wicked\ Witch\ of\ the\ West.txt
===== ~/wdi/exercises/HW1/Oz
$ ls
Good Witch of the North.txt Good Witch of the South.txt Wicked Witch of the East.txt    Wicked Witch of the West.txt
===== ~/wdi/exercises/HW1/Oz
$ rm Wicked\ Witch\ of\ the\ East.txt
===== ~/wdi/exercises/HW1/Oz
$ cd ../House
===== ~/wdi/exercises/HW1/House
$ mv Dorothy.txt ../Oz
mv: rename Dorothy.txt to ../Oz/Dorothy.txt: No such file or directory
===== ~/wdi/exercises/HW1/House
$ ls
===== ~/wdi/exercises/HW1/House
$ cd ..
===== ~/wdi/exercises/HW1
$ ls
Dorothy.txt House       House.txt   Oz      Toto.txt
===== ~/wdi/exercises/HW1
$ mv Dorothy.txt House.txt Toto.txt ./House
===== ~/wdi/exercises/HW1
$ cd House
===== ~/wdi/exercises/HW1/House
$ mv Dorothy.txt ../Oz
===== ~/wdi/exercises/HW1/House
$ cd ../Oz
===== ~/wdi/exercises/HW1/Oz
$ ls
Dorothy.txt         Good Witch of the North.txt Good Witch of the South.txt Wicked Witch of the West.txt
===== ~/wdi/exercises/HW1/Oz
$ touch Scarecrow.txt Tin\ Man.txt Cowardly\ Lion.txt the\ gang.txt
===== ~/wdi/exercises/HW1/Oz
$ ls
Cowardly Lion.txt       Good Witch of the North.txt Scarecrow.txt           Wicked Witch of the West.txt
Dorothy.txt         Good Witch of the South.txt Tin Man.txt         the gang.txt
===== ~/wdi/exercises/HW1/Oz
$ mkdir ../Emerald City
===== ~/wdi/exercises/HW1/Oz
$ cd ..
===== ~/wdi/exercises/HW1
$ ls
Emerald House   Oz
===== ~/wdi/exercises/HW1
$ mv Emerald Emerald\ City
===== ~/wdi/exercises/HW1
$ ls
Emerald City    House       Oz
===== ~/wdi/exercises/HW1
$ cd Oz
===== ~/wdi/exercises/HW1/Oz
$ ls
City                Dorothy.txt         Good Witch of the South.txt Tin Man.txt         the gang.txt
Cowardly Lion.txt       Good Witch of the North.txt Scarecrow.txt           Wicked Witch of the West.txt
===== ~/wdi/exercises/HW1/Oz
$ rm -r City
===== ~/wdi/exercises/HW1/Oz
$ ls
Cowardly Lion.txt       Good Witch of the North.txt Scarecrow.txt           Wicked Witch of the West.txt
Dorothy.txt         Good Witch of the South.txt Tin Man.txt         the gang.txt
===== ~/wdi/exercises/HW1/Oz
$ mv the\ gang.txt ../Emerald City
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
===== ~/wdi/exercises/HW1/Oz
$ ls
Cowardly Lion.txt       Good Witch of the North.txt Scarecrow.txt           Wicked Witch of the West.txt
Dorothy.txt         Good Witch of the South.txt Tin Man.txt         the gang.txt
===== ~/wdi/exercises/HW1/Oz
$ mv the\ gang.txt ../Emerald\ City
===== ~/wdi/exercises/HW1/Oz
$ cd ../Emerald\ City
===== ~/wdi/exercises/HW1/Emerald City
$ ls
the gang.txt
===== ~/wdi/exercises/HW1/Emerald City
$ cd ../Oz
===== ~/wdi/exercises/HW1/Oz
$ touch Flying\ Monkeys.txt
===== ~/wdi/exercises/HW1/Oz
$ rm Wicked\ Witch\ of\ the\ West.txt 
===== ~/wdi/exercises/HW1/Oz
$ echo "a diploma" >> Oz/Scarecrow
-bash: Oz/Scarecrow: No such file or directory
===== ~/wdi/exercises/HW1/Oz
$ echo "a diploma" >> Scarecrow.txt
===== ~/wdi/exercises/HW1/Oz
$ echo "a heart shaped watch" >> Tin\ Man.txt
===== ~/wdi/exercises/HW1/Oz
$ echo "a medal" >> Cowardly\ Lion.txt
===== ~/wdi/exercises/HW1/Oz

**Comment by RobertAKARobin** [comment]
✅
