### ISSUE TITLE
CLI HW Joe Calvillo

### ISSUE THREAD

**Issue by joecal** [ga-wdi-exercises/to_oz#75]
Macs-MacBook:~ Mac$ pwd
/Users/Mac
Macs-MacBook:~ Mac$ ls
Desktop     Downloads   Movies      Pictures    fundamentals
Documents   Library     Music       Public      wdi
Macs-MacBook:~ Mac$ cd wdi/lessons
Macs-MacBook:lessons Mac$ mkdir The_CLI
Macs-MacBook:lessons Mac$ cd The_CLI
Macs-MacBook:The_CLI Mac$ mkdir To_Oz
Macs-MacBook:The_CLI Mac$ mkdir house
Macs-MacBook:The_CLI Mac$ cd house
Macs-MacBook:house Mac$ touch dorothy.txt toto.txt
Macs-MacBook:house Mac$ mkdir oz
Macs-MacBook:house Mac$ cd oz
Macs-MacBook:oz Mac$ touch goodWitchOfTheNorth.txt wikedWitchOfTheEast.txt goodWitchOfTheSouth.txt wikedWitchOfTheWest.txt
Macs-MacBook:oz Mac$ ls
goodWitchOfTheNorth.txt wikedWitchOfTheEast.txt
goodWitchOfTheSouth.txt wikedWitchOfTheWest.txt
Macs-MacBook:oz Mac$ rm wikedWitchOfTheEast.txt
Macs-MacBook:oz Mac$ cd ..
Macs-MacBook:house Mac$ pwd
/Users/Mac/wdi/lessons/The_CLI/house
Macs-MacBook:house Mac$ ls
dorothy.txt oz      toto.txt
Macs-MacBook:house Mac$ mv dorothy.txt ./oz
Macs-MacBook:house Mac$ cd oz
Macs-MacBook:oz Mac$ ls
dorothy.txt     goodWitchOfTheSouth.txt
goodWitchOfTheNorth.txt wikedWitchOfTheWest.txt
Macs-MacBook:oz Mac$ touch scarecrow.txt tinMan.txt cowardlyLion.txt 
Macs-MacBook:oz Mac$ mkdir emeraldcity
Macs-MacBook:oz Mac$ mv dorothy.txt scarecrow.txt tinman.txt cowardlylion.txt ./emeraldcity
Macs-MacBook:oz Mac$ cd emeraldcity
Macs-MacBook:emeraldcity Mac$ ls
cowardlylion.txt    scarecrow.txt
dorothy.txt     tinman.txt
Macs-MacBook:emeraldcity Mac$ cd ../../
Macs-MacBook:house Mac$ pwd
/Users/Mac/wdi/lessons/The_CLI/house
Macs-MacBook:house Mac$ mv toto.txt ././
mv: toto.txt and ././toto.txt are identical
Macs-MacBook:house Mac$ ls
oz      toto.txt
Macs-MacBook:house Mac$ mv toto.txt ./emeraldcity
Macs-MacBook:house Mac$ cd ./emeraldcity
-bash: cd: ./emeraldcity: Not a directory
Macs-MacBook:house Mac$ cd oz
Macs-MacBook:oz Mac$ cd emeraldcity
Macs-MacBook:emeraldcity Mac$ ls
cowardlylion.txt    scarecrow.txt
dorothy.txt     tinman.txt
Macs-MacBook:emeraldcity Mac$ cd ..
Macs-MacBook:oz Mac$ ls
emeraldcity     goodWitchOfTheSouth.txt
goodWitchOfTheNorth.txt wikedWitchOfTheWest.txt
Macs-MacBook:oz Mac$ cd emeraldcity
Macs-MacBook:emeraldcity Mac$ ls
cowardlylion.txt    scarecrow.txt
dorothy.txt     tinman.txt
Macs-MacBook:emeraldcity Mac$ cd ..
Macs-MacBook:oz Mac$ pwd
/Users/Mac/wdi/lessons/The_CLI/house/oz
Macs-MacBook:oz Mac$ touch flyingMonkeys.txt
Macs-MacBook:oz Mac$ cd emeraldcity
Macs-MacBook:emeraldcity Mac$ ls
cowardlylion.txt    scarecrow.txt
dorothy.txt     tinman.txt
Macs-MacBook:emeraldcity Mac$ cd ..
Macs-MacBook:oz Mac$ ls
emeraldcity     goodWitchOfTheNorth.txt wikedWitchOfTheWest.txt
flyingMonkeys.txt   goodWitchOfTheSouth.txt
Macs-MacBook:oz Mac$ rm wikedWitchOfTheWest.txt
Macs-MacBook:oz Mac$ echo "a diploma" >> oz/scarecrow.txt
-bash: oz/scarecrow.txt: No such file or directory
Macs-MacBook:oz Mac$ pwd
/Users/Mac/wdi/lessons/The_CLI/house/oz
Macs-MacBook:oz Mac$ cd ..
Macs-MacBook:house Mac$ echo "a diploma" >> oz/scarecrow.txt
Macs-MacBook:house Mac$ echo "a heart shaped watch" >> oz/tinman.txt
Macs-MacBook:house Mac$ echo "a medal" >> oz/cowardlylion.txt

Completeness: 4.95/5
Comfort: 5/5
How do you move toto.txt from house directory to emerald city directory?

**Comment by RobertAKARobin** [comment]
You were getting `.` and `..` mixed up. `.` is the current directory. `..` is one directory "up". So `mv toto ././` would move Toto into the current directory -- that is, it wouldn't move Toto at all.

✅
