### ISSUE TITLE
CLI Homework Arthur Adams

### ISSUE THREAD

**Issue by arthuradams** [ga-wdi-exercises/to_oz#76]
completion: 5/5 -- everything requested and a little more i did just to amuse myself at home last night because I was bored
confidence: 5/5 -- I've been using the Unix/Linux command line for over two decades. Any errors are probably just typos or me not paying close enough attention to the instructions. 
# To Oz? To Oz!

Follow the steps below. Copy and paste your terminal commands into a github issue on this repository, like this one: https://github.com/ga-dc/to_oz/issues/1

Queue the music
As you wish: https://www.youtube.com/watch?v=3g4ekwTd6Ig

Create directory "House"
`% mkdir House`

Add files: "Dorothy" and "Toto" to "House"
`% touch House/Dorothy`
And Toto too
`% touch House/Toto`

Create directory "Oz"
`% mkdir Oz`

Add files for the 4 Witches to "Oz":
1. Good Witch of the North
2. Wicked Witch of the East
3. Good Witch of the South
4. Wicked Witch of the West

`% cd Oz`
`% touch Glinda WickedWitch-East GoodWitch-South Elphaba`
`% mv Elphaba WickedWitch-West`
`% mv Glinda GoodWitch-North`
`% cd ..`
# Ding! Dong! The Witch is Dead

Delete: "Wicked Witch of the East"
Move "Dorothy" from "House" to "Oz"

`% cd Oz`
`% rm WickedWitch-East`
`% mv ../House/Dorothy .`
`% cd ..`
# Follow the Yellow Brick Road

Add file for "Scarecrow"
Add file for "Tin Man"
Add file for "Cowardly Lion"

`% touch Scarecrow TinMan CowardlyLion`

Create directory "Emerald City"

`% mkdir EmeraldCity`

Move 'the gang' to "Emerald City"

`% mv Scarecrow TinMan CowardlyLion EmeraldCity/`
# You Must Kill the Witch

Add "Flying Monkeys" to "Oz"
`% touch Oz/FlyingMonkeys`

Remove "Wicked Witch of the West"
`% alias throw-water='rm'`
`% throw-water Oz/WickedWitch-West`
# Give the gifts*
- Give Scarecrow a diploma
- Give Tin Man a heart shaped watch
- Give Lion a medal

`% echo "Doctor of Thinkology Diploma" >> EmeraldCity/Scarecrow`
`% echo "Practical Unbreakable Heart-Shaped Watch" >> EmeraldCity/TinMan`
`% echo "Badge of Courage" >> EmeraldCity/CowardlyLion`
`% echo "Kansas" >> Oz/Dorothy`
`% echo "Yummy Monkey Chow" >> Oz/FlyingMonkeys`

*: to give gifts, you can redirect the ouput of the echo command:

$ echo "a diploma" >> Oz/Scarecrow

"I hereby confer upon you the honorary degree of TH.D."

**Comment by RobertAKARobin** [comment]
✅
