### ISSUE TITLE
"To Oz" HW1 D.Adams

### ISSUE THREAD

**Issue by BlvckYuppie** [ga-wdi-exercises/to_oz#77]
Comfort : 3.5-ish - 5
Completion: 4.7 - 5

"I wanted to stay true to the instructions and retain the case sensitivity of the file names / folders as they were provided, so i figured out how to add spaces in the file and folder names when using 'touch' and 'mkdir'. Seemed like good practice at the time, and I learned something new. BUT, it has bitten me in the ass. When attempting to get the echo command to work, I just can't seem to get the syntax right.... yet. What's the proper way to write this?" (I hate explicitly asking for answers, but i've searched, and i'm stumped)
## Example of echo problem

"Denzels-MacBook-Pro:Emerald City Corduroy$ echo "a heart shaped watch" >> Emerald\City/Tin\Man/ 
-bash: EmeralddCity/Tin\Man/ : No such file or directory
Denzels-MacBook-Pro:Emerald City Corduroy$ echo "a heart shaped watch" >> Emerald\City/"TinMan" 
-bash: EmeralddCity/TinMan: No such file or directory
Denzels-MacBook-Pro:Emerald City Corduroy$"
## Start HW Here ( each step is its own paragraph )

Denzels-MacBook-Pro:wdi Corduroy$ cd sandbox
Denzels-MacBook-Pro:sandbox Corduroy$ mkdir homework1
Denzels-MacBook-Pro:sandbox Corduroy$ cd homework1
Denzels-MacBook-Pro:homework1 Corduroy$ pwd
/Users/Corduroy/wdi/sandbox/homework1

Denzels-MacBook-Pro:homework1 Corduroy$ mkdir House
Denzels-MacBook-Pro:homework1 Corduroy$ cd house
Denzels-MacBook-Pro:house Corduroy$ touch Dorothy Toto
Denzels-MacBook-Pro:house Corduroy$ ls
Dorothy Toto

Denzels-MacBook-Pro:house Corduroy$ cd ..
Denzels-MacBook-Pro:homework1 Corduroy$ mkdir Oz
Denzels-MacBook-Pro:homework1 Corduroy$ ls
House   Oz

Denzels-MacBook-Pro:homework1 Corduroy$ cd oz
Denzels-MacBook-Pro:oz Corduroy$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West" 
Denzels-MacBook-Pro:oz Corduroy$ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South     Wicked Witch of the West

Denzels-MacBook-Pro:oz Corduroy$ rm "Wicked Witch of the East"
Denzels-MacBook-Pro:oz Corduroy$ ls
Good Witch of the North     Good Witch of the South     Wicked Witch of the West

Denzels-MacBook-Pro:homework1 Corduroy$ cd House
Denzels-MacBook-Pro:House Corduroy$ mv Dorothy ../oz
Denzels-MacBook-Pro:House Corduroy$ ls 
Toto

Denzels-MacBook-Pro:Oz Corduroy$ touch  "Scarecrow" "Tin Man" "Cowardly Lion" 
Denzels-MacBook-Pro:Oz Corduroy$ ls
Cowardly Lion           Good Witch of the South     Wicked Witch of the West
Dorothy             Scarecrow
Good Witch of the North     Tin Man

Denzels-MacBook-Pro:Oz Corduroy$ mv "Cowardly Lion" Emerald\ City/
Denzels-MacBook-Pro:Oz Corduroy$ mv "Tin Man" Emerald\ City/
Denzels-MacBook-Pro:Oz Corduroy$ mv "Scarecrow" Emerald\ City/
Denzels-MacBook-Pro:Oz Corduroy$ mv "Dorothy" Emerald\ City/
Denzels-MacBook-Pro:Oz Corduroy$ ls
Emerald City            Good Witch of the South
Good Witch of the North     Wicked Witch of the West

Denzels-MacBook-Pro:Oz Corduroy$ cd Emerald\ City/
Denzels-MacBook-Pro:Emerald City Corduroy$ ls
Cowardly Lion   Dorothy     Scarecrow   Tin Man

Denzels-MacBook-Pro:Emerald City Corduroy$ cd ..
Denzels-MacBook-Pro:Oz Corduroy$ ls
Emerald City            Good Witch of the South
Good Witch of the North     Wicked Witch of the West
Denzels-MacBook-Pro:Oz Corduroy$ touch "Flying Monkeys"
Denzels-MacBook-Pro:Oz Corduroy$ ls
Emerald City            Good Witch of the North     Wicked Witch of the West
Flying Monkeys          Good Witch of the South 

Denzels-MacBook-Pro:Oz Corduroy$ rm Wicked\ Witch\ of\ the\ West 
Denzels-MacBook-Pro:Oz Corduroy$ ls
Emerald City        Flying Monkeys      Good Witch of the North  
Good Witch of the South

**Comment by BlvckYuppie** [comment]
Just realized i swore on github...

We're all adults here, right? lol

**Comment by RobertAKARobin** [comment]
You have to put a space after the backslash. So `Emerald\City` is incorrect, but `Emerald\ City` is correct.

✅
