### ISSUE TITLE
To OZ HW1

### ISSUE THREAD

**Issue by AT89** [ga-wdi-exercises/to_oz#78]
Comments: Tried to put the witches in quotes, didnt work..
Just found out after I did this that I can touch and create multiple files ie (touch dorothy toto)
Completeness 5/5
Comfort level 5/5

Anhs-MacBook-Pro:exercises anhtice$ mkdir Oz_exercise
Anhs-MacBook-Pro:exercises anhtice$ cd Oz_exercise/
Anhs-MacBook-Pro:Oz_exercise anhtice$ mkdir House
Anhs-MacBook-Pro:Oz_exercise anhtice$ cd House
Anhs-MacBook-Pro:House anhtice$ touch Dorothy
Anhs-MacBook-Pro:House anhtice$ touch Toto
Anhs-MacBook-Pro:House anhtice$ cd ..
Anhs-MacBook-Pro:Oz_exercise anhtice$ mkdir Oz
Anhs-MacBook-Pro:Oz_exercise anhtice$ cd Oz
Anhs-MacBook-Pro:Oz anhtice$ touch Good_Witch_of_the_North
Anhs-MacBook-Pro:Oz anhtice$ touch Wicked_Witch_of_the_East
Anhs-MacBook-Pro:Oz anhtice$ touch Good_Witch_of_the_South
Anhs-MacBook-Pro:Oz anhtice$ touch Wicked_Witch_of_the_West
Anhs-MacBook-Pro:Oz anhtice$ rm Wicked_Witch_of_the_East
Anhs-MacBook-Pro:Oz anhtice$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
Anhs-MacBook-Pro:Oz anhtice$ cd ..
Anhs-MacBook-Pro:Oz_exercise anhtice$ mv House/Dorothy Oz/
Anhs-MacBook-Pro:Oz_exercise anhtice$ cd Oz
Anhs-MacBook-Pro:Oz anhtice$ ls
Dorothy             Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Anhs-MacBook-Pro:Oz anhtice$ touch Scarecrow
Anhs-MacBook-Pro:Oz anhtice$ touch Tin_Man
Anhs-MacBook-Pro:Oz anhtice$ touch Cowardly_Lion
Anhs-MacBook-Pro:Oz anhtice$ mkdir Emerald_City
Anhs-MacBook-Pro:Oz anhtice$ mv Scarecrow Emerald_City/
Anhs-MacBook-Pro:Oz anhtice$ mv Tin_man Emerald_City/
Anhs-MacBook-Pro:Oz anhtice$ mv Cowardly_Lion Emerald_City/
Anhs-MacBook-Pro:Oz anhtice$ mv Dorothy Emerald_City/
Anhs-MacBook-Pro:Oz anhtice$ ls
Emerald_City            Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Anhs-MacBook-Pro:Oz anhtice$ touch Flying_Monkeys
Anhs-MacBook-Pro:Oz anhtice$ rm Wicked_Witch_of_the_West 
Anhs-MacBook-Pro:Oz anhtice$ ls
Emerald_City        Good_Witch_of_the_North
Flying_Monkeys      Good_Witch_of_the_South
Anhs-MacBook-Pro:Oz anhtice$ cd Emerald_City/
Anhs-MacBook-Pro:Emerald_City anhtice$ echo "a diploma" >> Scarecrow
Anhs-MacBook-Pro:Emerald_City anhtice$ echo "heart shaped watch" >> Tin_Man
Anhs-MacBook-Pro:Emerald_City anhtice$ echo "medal" >> Cowardly_Lion
Anhs-MacBook-Pro:Emerald_City anhtice$ ls
Cowardly_Lion   Dorothy     Scarecrow   Tin_man
Anhs-MacBook-Pro:Emerald_City anhtice$

**Comment by RobertAKARobin** [comment]
✅
