### ISSUE TITLE
Rebekah Milford's "to_oz" Homework

### ISSUE THREAD

**Issue by rmilford** [ga-wdi-exercises/to_oz#79]
comfort score: 4/5
completeness: 5/5

Rebekahs-MacBook-Pro:~ rebekahmilford$ pwd
/Users/rebekahmilford
Rebekahs-MacBook-Pro:~ rebekahmilford$ ls
Applications            World
Desktop             bin
Documents           foundations-challenge-1
Downloads           foundations-challenge-3
FullstackTestFirst      fundamentals
FullstackTestFirst-Part-1   funny_things
Library             git
Movies              haiku
Music               learnyounode
Pictures            my-first-repo
Public              wdi
TestFirstAssessmentPractice
Rebekahs-MacBook-Pro:~ rebekahmilford$ cd wdi
Rebekahs-MacBook-Pro:wdi rebekahmilford$ ls
Rakefile    installfest.yml projects
exercises   lessons     sandbox
Rebekahs-MacBook-Pro:wdi rebekahmilford$ cd exercises/
Rebekahs-MacBook-Pro:exercises rebekahmilford$ mkdir house
Rebekahs-MacBook-Pro:exercises rebekahmilford$ cd house
Rebekahs-MacBook-Pro:house rebekahmilford$ pwd
/Users/rebekahmilford/wdi/exercises/house
Rebekahs-MacBook-Pro:house rebekahmilford$ touch dorothy.txt toto.txt house.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ ls
dorothy.txt house.txt   toto.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ mkdir oz
Rebekahs-MacBook-Pro:house rebekahmilford$ cd oz
Rebekahs-MacBook-Pro:oz rebekahmilford$ touch good_witch_of_the_north.txt wicked_witch_of_the_east.txt good_witch_of_the_south.txt wicked_witch_of_the_west.txt
Rebekahs-MacBook-Pro:oz rebekahmilford$ ls
good_witch_of_the_north.txt wicked_witch_of_the_east.txt
good_witch_of_the_south.txt wicked_witch_of_the_west.txt
Rebekahs-MacBook-Pro:oz rebekahmilford$ rm wicked_witch_of_the_east.txt
Rebekahs-MacBook-Pro:oz rebekahmilford$ ls
good_witch_of_the_north.txt wicked_witch_of_the_west.txt
good_witch_of_the_south.txt
Rebekahs-MacBook-Pro:oz rebekahmilford$ cd ..
Rebekahs-MacBook-Pro:house rebekahmilford$ ls
dorothy.txt house.txt   oz      toto.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ mv dorothy.txt ~/house/oz
mv: rename dorothy.txt to /Users/rebekahmilford/house/oz: No such file or directory
Rebekahs-MacBook-Pro:house rebekahmilford$ pwd
/Users/rebekahmilford/wdi/exercises/house
Rebekahs-MacBook-Pro:house rebekahmilford$ mv dorothy.txt oz
Rebekahs-MacBook-Pro:house rebekahmilford$ pwd
/Users/rebekahmilford/wdi/exercises/house
Rebekahs-MacBook-Pro:house rebekahmilford$ ls oz
dorothy.txt         good_witch_of_the_south.txt
good_witch_of_the_north.txt wicked_witch_of_the_west.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ touch scarecrow.txt tinman.txt cowardly_lion.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ mkdir emerald_city
Rebekahs-MacBook-Pro:house rebekahmilford$ mv scarecrow.txt tinman.txt cowardly_lion.txt emerald_city
Rebekahs-MacBook-Pro:house rebekahmilford$ ls emerald city
ls: city: No such file or directory
ls: emerald: No such file or directory
Rebekahs-MacBook-Pro:house rebekahmilford$ ls emerald_city
cowardly_lion.txt   scarecrow.txt       tinman.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ touch mv dorothy.txt emerald_city
Rebekahs-MacBook-Pro:house rebekahmilford$ ls emerald_city
cowardly_lion.txt   scarecrow.txt       tinman.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ ls oz
dorothy.txt         good_witch_of_the_south.txt
good_witch_of_the_north.txt wicked_witch_of_the_west.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ pwd
/Users/rebekahmilford/wdi/exercises/house
Rebekahs-MacBook-Pro:house rebekahmilford$ mv dorothy.txt good_witch_of_the_north.txt good_witch_of_the_south.txt wicked_witch_of_the_west.txt emerarld_city
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Rebekahs-MacBook-Pro:house rebekahmilford$ mv dorothy.txt good_witch_of_the_north.txt good_witch_of_the_south.txt wicked_witch_of_the_west.txt emerarld_city
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Rebekahs-MacBook-Pro:house rebekahmilford$ pwd
/Users/rebekahmilford/wdi/exercises/house
Rebekahs-MacBook-Pro:house rebekahmilford$ ls
dorothy.txt house.txt   oz
emerald_city    mv      toto.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ ox
-bash: ox: command not found
Rebekahs-MacBook-Pro:house rebekahmilford$ oz
-bash: oz: command not found
Rebekahs-MacBook-Pro:house rebekahmilford$ ls oz
dorothy.txt         good_witch_of_the_south.txt
good_witch_of_the_north.txt wicked_witch_of_the_west.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ touch flying_monkeys.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ ls
dorothy.txt     house.txt       toto.txt
emerald_city        mv
flying_monkeys.txt  oz
Rebekahs-MacBook-Pro:house rebekahmilford$ mv flying_monkeys.txt oz
Rebekahs-MacBook-Pro:house rebekahmilford$ ls
dorothy.txt house.txt   oz
emerald_city    mv      toto.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ ls oz
dorothy.txt         good_witch_of_the_south.txt
flying_monkeys.txt      wicked_witch_of_the_west.txt
good_witch_of_the_north.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ ls oz
dorothy.txt         good_witch_of_the_south.txt
flying_monkeys.txt      wicked_witch_of_the_west.txt
good_witch_of_the_north.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ ls emerald_city
cowardly_lion.txt   scarecrow.txt       tinman.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ pwd
/Users/rebekahmilford/wdi/exercises/house
Rebekahs-MacBook-Pro:house rebekahmilford$ ls
dorothy.txt house.txt   oz
emerald_city    mv      toto.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ mv dorothy.txt oz
Rebekahs-MacBook-Pro:house rebekahmilford$ ls oz
dorothy.txt         good_witch_of_the_south.txt
flying_monkeys.txt      wicked_witch_of_the_west.txt
good_witch_of_the_north.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ ls emerald_city
cowardly_lion.txt   scarecrow.txt       tinman.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ mv flying_monkeys.txt oz
mv: flying_monkeys.txt: No such file or directory
Rebekahs-MacBook-Pro:house rebekahmilford$ rm wicked_witch_of_the_west.txt
rm: wicked_witch_of_the_west.txt: No such file or directory
Rebekahs-MacBook-Pro:house rebekahmilford$ pwd
/Users/rebekahmilford/wdi/exercises/house
Rebekahs-MacBook-Pro:house rebekahmilford$ cd oz
Rebekahs-MacBook-Pro:oz rebekahmilford$ rm wicked_witch_of_the_west.txt
Rebekahs-MacBook-Pro:oz rebekahmilford$ ls
dorothy.txt         good_witch_of_the_north.txt
flying_monkeys.txt      good_witch_of_the_south.txt
Rebekahs-MacBook-Pro:oz rebekahmilford$ pwd
/Users/rebekahmilford/wdi/exercises/house/oz
Rebekahs-MacBook-Pro:oz rebekahmilford$ cd ..
Rebekahs-MacBook-Pro:house rebekahmilford$ pwd
/Users/rebekahmilford/wdi/exercises/house
Rebekahs-MacBook-Pro:house rebekahmilford$ ls
emerald_city    house.txt   mv      oz      toto.txt
Rebekahs-MacBook-Pro:house rebekahmilford$ tree
.
├── emerald_city
│   ├── cowardly_lion.txt
│   ├── scarecrow.txt
│   └── tinman.txt
├── house.txt
├── mv
├── oz
│   ├── dorothy.txt
│   ├── flying_monkeys.txt
│   ├── good_witch_of_the_north.txt
│   └── good_witch_of_the_south.txt
└── toto.txt

2 directories, 10 files
Rebekahs-MacBook-Pro:house rebekahmilford$ cd emerald_city
Rebekahs-MacBook-Pro:emerald_city rebekahmilford$ echo "a diploma" >> scarecrow.txt
Rebekahs-MacBook-Pro:emerald_city rebekahmilford$ echo "a heart shaped watch" >> tinman.txt
Rebekahs-MacBook-Pro:emerald_city rebekahmilford$ echo "a medal" >> cowardly_lion.txt
Rebekahs-MacBook-Pro:emerald_city rebekahmilford$

**Comment by RobertAKARobin** [comment]
✅
