### ISSUE TITLE
To Oz

### ISSUE THREAD

**Issue by gardner589** [ga-wdi-exercises/to_oz#80]
??Did I do this wrong?

~/To_Oz (master *) 
$ ls
House
~/To_Oz (master *) 
$ touch Dorothy.txt Toto.txt /House
touch: /House: Permission denied
~/To_Oz (master *) 
$ rm House
rm: House: is a directory
~/To_Oz (master *) 
$ rm -d House
~/To_Oz (master *) 
$ ls
Dorothy.txt Toto.txt
~/To_Oz (master *) 
$ rm Dorothy.txt Toto.txt
~/To_Oz (master *) 
$ ks
-bash: ks: command not found
~/To_Oz (master *) 
$ ls
~/To_Oz (master *) 
$ cd ..
~ 
$ ls
Applications        Movies          VirtualBox VMs
Desktop         Music           funny_things
Documents       Pictures        index.html
Downloads       Public          wdi
Library         To_Oz           wdi-fundamentals
~ 
$ cd To_Oz
~/To_Oz (master *) 
$ ls
~/To_Oz (master *) 
$ mkdir House
~/To_Oz (master *) 
$ cd House
~/To_Oz/House (master *) 
$ touch Dorothy.txt Toto.txt
~/To_Oz/House (master *) 
$ ls
Dorothy.txt Toto.txt
~/To_Oz/House (master *) 
$ cd ..
~/To_Oz (master *) 
$ ls
House
~/To_Oz (master *) 
$ mkdir Oz
~/To_Oz (master *) 
$ cd Oz
~/To_Oz/Oz (master *) 
$ touch WWOT-East.txt WWOT-West.txt GWOT-North.txt GWOT-South.txt
~/To_Oz/Oz (master *) 
$ pwd
/Users/LORDSHIRC/To_Oz/Oz
~/To_Oz/Oz (master *) 
$ mv ../House/Dorothy.txt ../Oz
~/To_Oz/Oz (master *) 
$ ls
Dorothy.txt GWOT-North.txt  GWOT-South.txt  WWOT-East.txt   WWOT-West.txt
~/To_Oz/Oz (master *) 
$ rm WWOT-East.txt
~/To_Oz/Oz (master *) 
$ touch Scarecrow.txt Tin-Man.txt Cowardly-Lion.txt
~/To_Oz/Oz (master *) 
$ ls
Cowardly-Lion.txt   GWOT-South.txt      WWOT-West.txt
Dorothy.txt     Scarecrow.txt
GWOT-North.txt      Tin-Man.txt
~/To_Oz/Oz (master *) 
$ pwd
/Users/LORDSHIRC/To_Oz/Oz
~/To_Oz/Oz (master *) 
$ cd ../
~/To_Oz (master *) 
$ mkdir Emerald-City
~/To_Oz (master *) 
$ mv Emerald-City -r OZ
mv: rename -r to OZ/-r: No such file or directory
~/To_Oz (master *) 
$ mv Emerald-City -r Oz
mv: Emerald-City: No such file or directory
mv: rename -r to Oz/-r: No such file or directory
~/To_Oz (master *) 
$ Mv Emerald-City Oz
Mv: Emerald-City: No such file or directory
~/To_Oz (master *) 
$ pwd
/Users/LORDSHIRC/To_Oz
~/To_Oz (master *) 
$ ls
House   Oz
~/To_Oz (master *) 
$ cd Oz
~/To_Oz/Oz (master *) 
$ ls
Cowardly-Lion.txt   GWOT-North.txt      Tin-Man.txt
Dorothy.txt     GWOT-South.txt      WWOT-West.txt
Emerald-City        Scarecrow.txt
~/To_Oz/Oz (master *) 
$ mv Cowardly-Lion.txt Scarecrow.txt Tin-Man.txt Dorothy.txt Emerald-City
~/To_Oz/Oz (master *) 
$ ls
Emerald-City    GWOT-North.txt  GWOT-South.txt  WWOT-West.txt
~/To_Oz/Oz (master *) 
$ touch Flying-Monkies.txt
~/To_Oz/Oz (master *) 
$ rm WWOT-West.txt
~/To_Oz/Oz (master *) 
$ cd Emerald-City
~/To_Oz/Oz/Emerald-City (master *) 
$ ls
Cowardly-Lion.txt   Scarecrow.txt
Dorothy.txt     Tin-Man.txt
~/To_Oz/Oz/Emerald-City (master *) 
$ echo "Heart shaped wacth for you!" >> Cowardly-Lion.txt 
-bash: !": event not found
~/To_Oz/Oz/Emerald-City (master *) 
$ cat Cowardly-Lion.txt 
~/To_Oz/Oz/Emerald-City (master *) 
$ echo "

> echo "Heart watch" >> Cowardly-Lion.txt 
> cat Cowardly-Lion.txt 
> "

echo Heart watch >> Cowardly-Lion.txt 
cat Cowardly-Lion.txt 

~/To_Oz/Oz/Emerald-City (master *) 
$ cat Cowardly-Lion.txt 
~/To_Oz/Oz/Emerald-City (master *) 
$ echo "Heart watch" >> Cowardly-Lion.txt 
~/To_Oz/Oz/Emerald-City (master *) 
$ cat Cowardly-Lion.txt 
Heart watch
~/To_Oz/Oz/Emerald-City (master *) 
$ 
~/To_Oz/Oz/Emerald-City (master *) 
$ echo "heart watch" >> Tin-Man.txt 
~/To_Oz/Oz/Emerald-City (master *) 
$ echo "Diploma" >> Scarecrow.txt 
~/To_Oz/Oz/Emerald-City (master *) 
$ cat Scarecrow.txt 
Diploma
~/To_Oz/Oz/Emerald-City (master *) 
$

**Comment by RobertAKARobin** [comment]
Hard to say! Does it work?

✅
