### ISSUE TITLE
CLI Homework (Julia Najafi)

### ISSUE THREAD

**Issue by JuliaNajafi** [ga-wdi-exercises/to_oz#81]
Completeness: 5/5
Comfort: 4.5/5

$ ls
Applications        Library         exercises
Creative Cloud Files    Movies          fundamentals
Desktop         Music           nano.save
Documents       Pictures        wdi
Downloads       Public
~ 
$ cd exercises
~/exercises 
$ ls
~/exercises 
$ mkdir House
~/exercises 
$ cd House
~/exercises/House 
$ touch Dorothy
~/exercises/House 
$ touch Toto
~/exercises/House 
$ ls
Dorothy Toto
~/exercises/House 
$ cd ..
~/exercises 
$ mkdir Oz
~/exercises 
$ cd Oz
~/exercises/Oz 
$ touch goodWitchOfTheNorth
~/exercises/Oz 
$ touch wickedWitchOfTheEast
~/exercises/Oz 
$ touch goodWitchOfTheSouth
~/exercises/Oz 
$ touch wickedWitchOfTheWest
~/exercises/Oz 
$ ls
goodWitchOfTheNorth wickedWitchOfTheEast
goodWitchOfTheSouth wickedWitchOfTheWest
~/exercises/Oz 
$ rm wickedWitchOfTheEast
~/exercises/Oz 
$ ls
goodWitchOfTheNorth goodWitchOfTheSouth wickedWitchOfTheWest
~/exercises/Oz 
$ cd ..
~/exercises 
$ ls
House   Oz
~/exercises 
$ mv Dorothy Oz
mv: rename Dorothy to Oz/Dorothy: No such file or directory
~/exercises 
$ man mv
~/exercises 
$ mv -h
mv: illegal option -- h
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/exercises 
$ mv Dorothy ... Oz
mv: rename Dorothy to Oz/Dorothy: No such file or directory
mv: rename ... to Oz/...: No such file or directory
~/exercises 
$ ls
House   Oz
~/exercises 
$ cd oz
~/exercises/oz 
$ ls
goodWitchOfTheNorth goodWitchOfTheSouth wickedWitchOfTheWest
~/exercises/oz 
$ cd ..
~/exercises 
$ cd House
~/exercises/House 
$ ls
Dorothy Toto
~/exercises/House 
$ mv Dorothy exercises/Oz
mv: rename Dorothy to exercises/Oz: No such file or directory
~/exercises/House 
$ ls
Dorothy Toto
~/exercises/House 
$ cd ..
~/exercises 
$ ls
House   Oz
~/exercises 
$ cd oz
~/exercises/oz 
$ pwd
/Users/JuliaNajafi/exercises/oz
~/exercises/oz 
$ cd House
-bash: cd: House: No such file or directory
~/exercises/oz 
$ ls
goodWitchOfTheNorth goodWitchOfTheSouth wickedWitchOfTheWest
~/exercises/oz 
$ cd ..
~/exercises 
$ ls
House   Oz
~/exercises 
$ cd Oz
~/exercises/Oz 
$ ls
goodWitchOfTheNorth goodWitchOfTheSouth wickedWitchOfTheWest
~/exercises/Oz 
$ cd ..
~/exercises 
$ ls
House   Oz
~/exercises 
$ cd House
~/exercises/House 
$ ls
Dorothy Toto
~/exercises/House 
$ mv Dorothy ~/exercises/oz
~/exercises/House 
$ ls
Toto
~/exercises/House 
$ cd ..
~/exercises 
$ ls
House   Oz
~/exercises 
$ cd Oz
~/exercises/Oz 
$ ls
Dorothy         goodWitchOfTheSouth
goodWitchOfTheNorth wickedWitchOfTheWest
~/exercises/Oz 
$ cd ..
~/exercises 
$ ls
House   Oz
~/exercises 
$ touch Scarecrow
~/exercises 
$ touch TinMan
~/exercises 
$ touch CowardlyLion
~/exercises 
$ mkdir EmeraldCity
~/exercises 
$ ls
CowardlyLion    House       Scarecrow
EmeraldCity Oz      TinMan
~/exercises 
$ mv Scarecrow ~/exercises/EmeraldCity
~/exercises 
$ mv TinMan ~/exercises/EmeraldCity
~/exercises 
$ mv CowardlyLion ~/exercises/EmeraldCity
~/exercises 
$ cd EmeraldCity
~/exercises/EmeraldCity 
$ ls
CowardlyLion    Scarecrow   TinMan
~/exercises/EmeraldCity 
$ cd ..
~/exercises 
$ ls
EmeraldCity House       Oz
~/exercises 
$ cd Oz
~/exercises/Oz 
$ touch FlyingMonkeys
~/exercises/Oz 
$ l
-bash: l: command not found
~/exercises/Oz 
$ ls
Dorothy         goodWitchOfTheNorth wickedWitchOfTheWest
FlyingMonkeys       goodWitchOfTheSouth
~/exercises/Oz 
$ rm wickedWitchOfTheWest 
~/exercises/Oz 
$ cd ..
~/exercises 
$ ls
EmeraldCity House       Oz
~/exercises 
$ tree
.
├── EmeraldCity
│   ├── CowardlyLion
│   ├── Scarecrow
│   └── TinMan
├── House
│   └── Toto
└── Oz
    ├── Dorothy
    ├── FlyingMonkeys
    ├── goodWitchOfTheNorth
    └── goodWitchOfTheSouth

3 directories, 8 files
~/exercises 
$ echo "a diploma" >> ~/exercises/EmeraldCity/Scarecrow 
~/exercises 
$ echo "a heart shaped watch" >> ~/exercises/EmeraldCity/TinMan 
~/exercises 
$ echo "a medal" >> ~/exercises/EmeraldCity/CowardlyLion 
~/exercises 
$

**Comment by RobertAKARobin** [comment]
✅
