### ISSUE TITLE
CLI HW Courtney Seitz

### ISSUE THREAD

**Issue by Courtney-Seitz** [ga-wdi-exercises/to_oz#82]
Completeness - 5/5
Comfort Level - 3/5

Courtneys-MacBook-Pro:wdi courtneyseitz$ mkdir House
Courtneys-MacBook-Pro:wdi courtneyseitz$ ls
House           installfest.yml     projects
Rakefile        kitchen_organizer   sandbox
exercises       lessons
Courtneys-MacBook-Pro:wdi courtneyseitz$ cd House/
Courtneys-MacBook-Pro:House courtneyseitz$ touch Dorothy Toto
Courtneys-MacBook-Pro:House courtneyseitz$ ls
Dorothy Toto
Courtneys-MacBook-Pro:House courtneyseitz$ cd ..
Courtneys-MacBook-Pro:wdi courtneyseitz$ ls
House           installfest.yml     projects
Rakefile        kitchen_organizer   sandbox
exercises       lessons
Courtneys-MacBook-Pro:wdi courtneyseitz$ mkdir Oz
Courtneys-MacBook-Pro:wdi courtneyseitz$ ls
House           exercises       lessons
Oz          installfest.yml     projects
Rakefile        kitchen_organizer   sandbox
Courtneys-MacBook-Pro:wdi courtneyseitz$ cd Oz/
Courtneys-MacBook-Pro:Oz courtneyseitz$ touch Good_Witch_of_the_North Wicked_Witch_of_the_East Good_Witch_of_the_South Wicked_Witch_of_the_West
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_East
Good_Witch_of_the_South     Wicked_Witch_of_the_West
Courtneys-MacBook-Pro:Oz courtneyseitz$ rm Wicked_Witch_of_the_East
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
Courtneys-MacBook-Pro:Oz courtneyseitz$ mv ../House/Dorothy .
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Dorothy             Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Courtneys-MacBook-Pro:Oz courtneyseitz$ touch Scarecrow Tin_Man Cowardly_Lion 
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Cowardly_Lion           Scarecrow
Dorothy             Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
Courtneys-MacBook-Pro:Oz courtneyseitz$ mkdir Emerald_City
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Cowardly_Lion           Good_Witch_of_the_South
Dorothy             Scarecrow
Emerald_City            Tin_Man
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Courtneys-MacBook-Pro:Oz courtneyseitz$ mv Scarecrow ./Emerald_City/
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Cowardly_Lion           Good_Witch_of_the_South
Dorothy             Tin_Man
Emerald_City            Wicked_Witch_of_the_West
Good_Witch_of_the_North
Courtneys-MacBook-Pro:Oz courtneyseitz$ mv Dorothy Toto Tin_Man Cowardly_Lion ./Emerald_City/
mv: rename Toto to ./Emerald_City/Toto: No such file or directory
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Emerald_City            Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Courtneys-MacBook-Pro:Oz courtneyseitz$ touch Toto
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Emerald_City            Toto
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Good_Witch_of_the_South
Courtneys-MacBook-Pro:Oz courtneyseitz$ mv Toto ./Emerald_City/
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Emerald_City            Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Courtneys-MacBook-Pro:Oz courtneyseitz$ cd Emerald_City/
Courtneys-MacBook-Pro:Emerald_City courtneyseitz$ ls
Cowardly_Lion   Dorothy     Scarecrow   Tin_Man     Toto
Courtneys-MacBook-Pro:Emerald_City courtneyseitz$ cd ..
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Emerald_City            Good_Witch_of_the_South
Good_Witch_of_the_North     Wicked_Witch_of_the_West
Courtneys-MacBook-Pro:Oz courtneyseitz$ touch Flying_Monkeys
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Emerald_City            Good_Witch_of_the_South
Flying_Monkeys          Wicked_Witch_of_the_West
Good_Witch_of_the_North
Courtneys-MacBook-Pro:Oz courtneyseitz$ rm Wicked_Witch_of_the_West 
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Emerald_City        Good_Witch_of_the_North
Flying_Monkeys      Good_Witch_of_the_South
Courtneys-MacBook-Pro:Oz courtneyseitz$ echo "a diploma" >> ./Emerald_City/Scarecrow 
Courtneys-MacBook-Pro:Oz courtneyseitz$ ls
Emerald_City        Good_Witch_of_the_North
Flying_Monkeys      Good_Witch_of_the_South
Courtneys-MacBook-Pro:Oz courtneyseitz$ echo "a heart shaped watch" >> ./Emerald_City/Tin_Man 
Courtneys-MacBook-Pro:Oz courtneyseitz$ echo "a medal" >> ./Emerald_City/Cowardly_Lion

**Comment by RobertAKARobin** [comment]
✅
