### ISSUE TITLE
Tyler Rosenberg's HW

### ISSUE THREAD

**Issue by TyRyanR** [ga-wdi-exercises/to_oz#87]
Comfort: 3.5
Completeness: 5

This HW was a good challenge. Didn't have too much trouble with it but it took me a few minutes on each step. ***I would like to know how to touch a file into a directory from a different folder. Each time I wanted to add a new file I had to 'CD'  into the directory then touch from there. I'd like to know how to be working in a parent folder for instance, and touch files into that parent directory's child folder.

---

Tylers-MacBook:Oz Tyler$ cd .. ..
Tylers-MacBook:wdi Tyler$ ls
House       Oz      Rakefile    exercises   installfest.yml lessons     projects    sandbox     test
Tylers-MacBook:wdi Tyler$ rm -r House
Tylers-MacBook:wdi Tyler$ rm -r Oz
Tylers-MacBook:wdi Tyler$ ls
Rakefile    exercises   installfest.yml lessons     projects    sandbox     test
Tylers-MacBook:wdi Tyler$ mkdir House
Tylers-MacBook:wdi Tyler$ cd House
Tylers-MacBook:House Tyler$ touch Dorothy.txt Toto.txt
Tylers-MacBook:House Tyler$ pwd
/Users/Tyler/wdi/House
Tylers-MacBook:House Tyler$ cd ..
Tylers-MacBook:wdi Tyler$ mkdir Oz
Tylers-MacBook:wdi Tyler$ cd Oz
Tylers-MacBook:Oz Tyler$ touch 'Good Witch Of The North' 'Wicked Witch Of The East' 'Good Witch Of The South' 'Wicked Witch Of The West'
Tylers-MacBook:Oz Tyler$ ls
Good Witch Of The North     Good Witch Of The South     Wicked Witch Of The East    Wicked Witch Of The West
Tylers-MacBook:Oz Tyler$ rm Wicked\ Witch\ Of\ The\ East\

> q
> rm: Wicked Witch Of The Eastq: No such file or directory
> Tylers-MacBook:Oz Tyler$ rm 'Wicked Witch Of The East'
> Tylers-MacBook:Oz Tyler$ ls
> Good Witch Of The North     Good Witch Of The South     Wicked Witch Of The West
> Tylers-MacBook:Oz Tyler$ cd ..
> Tylers-MacBook:wdi Tyler$ cd House
> Tylers-MacBook:House Tyler$ ls
> Dorothy.txt Toto.txt
> Tylers-MacBook:House Tyler$ mv Dorothy.txt ../Oz/
> Tylers-MacBook:House Tyler$ cd ..
> Tylers-MacBook:wdi Tyler$ ls
> House       Oz      Rakefile    exercises   installfest.yml lessons     projects    sandbox     test
> Tylers-MacBook:wdi Tyler$ cd Oz
> Tylers-MacBook:Oz Tyler$ ls
> Dorothy.txt         Good Witch Of The North     Good Witch Of The South     Wicked Witch Of The West
> Tylers-MacBook:Oz Tyler$ touch Scarecrow Tinman 'Cowardly Lion'
> Tylers-MacBook:Oz Tyler$ ls
> Cowardly Lion           Good Witch Of The North     Scarecrow           Wicked Witch Of The West
> Dorothy.txt         Good Witch Of The South     Tinman
> Tylers-MacBook:Oz Tyler$ mkdir 'Emerald City'
> Tylers-MacBook:Oz Tyler$ ls
> Cowardly Lion           Emerald City            Good Witch Of The South     Tinman
> Dorothy.txt         Good Witch Of The North     Scarecrow           Wicked Witch Of The West
> Tylers-MacBook:Oz Tyler$ mv 'Scarecrow' 'Tinman' 'Cowardly Lion' 'Dorothy.txt' 'Emerald City'/
> Tylers-MacBook:Oz Tyler$ touch 'Flying Monkeys'
> Tylers-MacBook:Oz Tyler$ ls
> Emerald City            Flying Monkeys          Good Witch Of The North     Good Witch Of The South     Wicked Witch Of The West
> Tylers-MacBook:Oz Tyler$ rm 'Wicked Witch Of The West' 
> Tylers-MacBook:Oz Tyler$ ls
> Emerald City        Flying Monkeys      Good Witch Of The North Good Witch Of The South
> Tylers-MacBook:Oz Tyler$ cd Emerald\ City/
> Tylers-MacBook:Emerald City Tyler$ ls
> Cowardly Lion   Dorothy.txt Scarecrow   Tinman
> Tylers-MacBook:Emerald City Tyler$ echo "a diploma" >> Scarecrow
> Tylers-MacBook:Emerald City Tyler$ echo "heart shaped watch" >> Tinman
> Tylers-MacBook:Emerald City Tyler$ echo "medal" >> 'Cowardly Lion' 
> Tylers-MacBook:Emerald City Tyler$ open Cowardly\ Lion 
> Tylers-MacBook:Emerald City Tyler$

**Comment by nayana487** [comment]
👍 

You can do this from the parent directory: touch child_directory/index.html
If you wanted to make a file in the parent directory from the child, you can do this: touch ../index.html
