### ISSUE TITLE
Rasheeda's HW

### ISSUE THREAD

**Issue by RasheedaAlexander** [ga-wdi-exercises/to_oz#88]
Comfort: 5
Completeness: 5

Comments: I'm going home to take a nap :)

$ mkdir House
-bash: __git_ps1: command not found
  Mon Jun 27 17:12:12 ~/wdi/homework
$ ls
House
-bash: __git_ps1: command not found
  Mon Jun 27 17:12:14 ~/wdi/homework
$ cd ..
-bash: __git_ps1: command not found
  Mon Jun 27 17:12:22 ~/wdi
$ pwd
/Users/SheedaBeeda/wdi
-bash: __git_ps1: command not found
  Mon Jun 27 17:12:24 ~/wdi
$ cd homework
-bash: __git_ps1: command not found
  Mon Jun 27 17:12:30 ~/wdi/homework
$ ls
House
-bash: __git_ps1: command not found
  Mon Jun 27 17:12:31 ~/wdi/homework
$ cd House
-bash: __git_ps1: command not found
  Mon Jun 27 17:12:36 ~/wdi/homework/House
$ pwd
/Users/SheedaBeeda/wdi/homework/House
-bash: __git_ps1: command not found
  Mon Jun 27 17:12:38 ~/wdi/homework/House
$ touch Dorothy Toto
-bash: __git_ps1: command not found
  Mon Jun 27 17:12:56 ~/wdi/homework/House
$ ls
Dorothy Toto
-bash: __git_ps1: command not found
  Mon Jun 27 17:13:00 ~/wdi/homework/House
$ cd ..
-bash: __git_ps1: command not found
  Mon Jun 27 17:13:08 ~/wdi/homework
$ pwd
/Users/SheedaBeeda/wdi/homework
-bash: __git_ps1: command not found
  Mon Jun 27 17:13:09 ~/wdi/homework
$ mkdir Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:13:14 ~/wdi/homework
$ ls
House   Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:13:15 ~/wdi/homework
$ cd Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:13:22 ~/wdi/homework/Oz
$ ls
-bash: __git_ps1: command not found
  Mon Jun 27 17:13:23 ~/wdi/homework/Oz
$ pwd
/Users/SheedaBeeda/wdi/homework/Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:13:24 ~/wdi/homework/Oz
$ touch "Good Witch of the North"
-bash: __git_ps1: command not found
  Mon Jun 27 17:14:52 ~/wdi/homework/Oz
$ ls
Good Witch of the North
-bash: __git_ps1: command not found
  Mon Jun 27 17:14:53 ~/wdi/homework/Oz
$ pwd
/Users/SheedaBeeda/wdi/homework/Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:14:56 ~/wdi/homework/Oz
$ touch "Wicked Witch of the East"
-bash: __git_ps1: command not found
  Mon Jun 27 17:15:13 ~/wdi/homework/Oz
$ ls
Good Witch of the North     Wicked Witch of the East
-bash: __git_ps1: command not found
  Mon Jun 27 17:15:15 ~/wdi/homework/Oz
$ touch "Good Witch of the South"
-bash: __git_ps1: command not found
  Mon Jun 27 17:15:35 ~/wdi/homework/Oz
$ ls
Good Witch of the North     Good Witch of the South     Wicked Witch of the East
-bash: __git_ps1: command not found
  Mon Jun 27 17:15:37 ~/wdi/homework/Oz
$ touch "Wicked Witch of the West"
-bash: __git_ps1: command not found
  Mon Jun 27 17:15:51 ~/wdi/homework/Oz
$ ls
Good Witch of the North     Wicked Witch of the East
Good Witch of the South     Wicked Witch of the West
-bash: __git_ps1: command not found
  Mon Jun 27 17:15:52 ~/wdi/homework/Oz
$ rm "Wicked Witch of the East"
-bash: __git_ps1: command not found
  Mon Jun 27 17:16:08 ~/wdi/homework/Oz
$ ls
Good Witch of the North     Good Witch of the South     Wicked Witch of the West
-bash: __git_ps1: command not found
  Mon Jun 27 17:16:09 ~/wdi/homework/Oz
$ pwd
/Users/SheedaBeeda/wdi/homework/Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:16:42 ~/wdi/homework/Oz
$ cd ..
-bash: __git_ps1: command not found
  Mon Jun 27 17:16:47 ~/wdi/homework
$ ls
House   Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:16:48 ~/wdi/homework
$ cd House
-bash: __git_ps1: command not found
  Mon Jun 27 17:16:55 ~/wdi/homework/House
$ ls
Dorothy Toto
-bash: __git_ps1: command not found
  Mon Jun 27 17:16:56 ~/wdi/homework/House
$ mv Dorothy ~/Oz/
mv: rename Dorothy to /Users/SheedaBeeda/Oz/: No such file or directory
-bash: __git_ps1: command not found
  Mon Jun 27 17:18:11 ~/wdi/homework/House
$ mv Dorothy ../Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:19:12 ~/wdi/homework/House
$ ls
Toto
-bash: __git_ps1: command not found
  Mon Jun 27 17:19:15 ~/wdi/homework/House
$ cd ..
-bash: __git_ps1: command not found
  Mon Jun 27 17:19:19 ~/wdi/homework
$ ls
House   Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:19:20 ~/wdi/homework
$ cd Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:19:26 ~/wdi/homework/Oz
$ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the West
-bash: __git_ps1: command not found
  Mon Jun 27 17:19:27 ~/wdi/homework/Oz
$ pwd
/Users/SheedaBeeda/wdi/homework/Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:19:37 ~/wdi/homework/Oz
$ touch Scarecrow
-bash: __git_ps1: command not found
  Mon Jun 27 17:20:30 ~/wdi/homework/Oz
$ touch "Tin Man"
-bash: __git_ps1: command not found
  Mon Jun 27 17:20:36 ~/wdi/homework/Oz
$ touch "Cowardly Lion"
-bash: __git_ps1: command not found
  Mon Jun 27 17:20:43 ~/wdi/homework/Oz
$ ls
Cowardly Lion           Good Witch of the South     Wicked Witch of the West
Dorothy             Scarecrow
Good Witch of the North     Tin Man
-bash: __git_ps1: command not found
  Mon Jun 27 17:21:28 ~/wdi/homework/Oz
$ mkdir Emerald City
-bash: __git_ps1: command not found
  Mon Jun 27 17:21:45 ~/wdi/homework/Oz
$ ls
City                Emerald             Scarecrow
Cowardly Lion           Good Witch of the North     Tin Man
Dorothy             Good Witch of the South     Wicked Witch of the West
-bash: __git_ps1: command not found
  Mon Jun 27 17:21:47 ~/wdi/homework/Oz
$ rm Emerald City
rm: Emerald: is a directory
rm: City: is a directory
-bash: __git_ps1: command not found
  Mon Jun 27 17:21:58 ~/wdi/homework/Oz
$ ls
City                Emerald             Scarecrow
Cowardly Lion           Good Witch of the North     Tin Man
Dorothy             Good Witch of the South     Wicked Witch of the West
-bash: __git_ps1: command not found
  Mon Jun 27 17:22:03 ~/wdi/homework/Oz
$ rm Emerald
rm: Emerald: is a directory
-bash: __git_ps1: command not found
  Mon Jun 27 17:22:07 ~/wdi/homework/Oz
$ rmdir Emerald
-bash: __git_ps1: command not found
  Mon Jun 27 17:22:26 ~/wdi/homework/Oz
$ rmdir City
-bash: __git_ps1: command not found
  Mon Jun 27 17:22:31 ~/wdi/homework/Oz
$ ls
Cowardly Lion           Good Witch of the South     Wicked Witch of the West
Dorothy             Scarecrow
Good Witch of the North     Tin Man
-bash: __git_ps1: command not found
  Mon Jun 27 17:22:32 ~/wdi/homework/Oz
$ mkdir "Emerald City"
-bash: __git_ps1: command not found
  Mon Jun 27 17:22:46 ~/wdi/homework/Oz
$ ls
Cowardly Lion           Good Witch of the North     Tin Man
Dorothy             Good Witch of the South     Wicked Witch of the West
Emerald City            Scarecrow
-bash: __git_ps1: command not found
  Mon Jun 27 17:22:47 ~/wdi/homework/Oz
$ mv "Scarecrow" "Tin Man" "Cowardly Lion" "Emerald City"
-bash: __git_ps1: command not found
  Mon Jun 27 17:25:05 ~/wdi/homework/Oz
$ ls
Dorothy             Good Witch of the North     Wicked Witch of the West
Emerald City            Good Witch of the South
-bash: __git_ps1: command not found
  Mon Jun 27 17:25:07 ~/wdi/homework/Oz
$ cd "Emerald City"
-bash: __git_ps1: command not found
  Mon Jun 27 17:25:14 ~/wdi/homework/Oz/Emerald City
$ ls
Cowardly Lion   Scarecrow   Tin Man
-bash: __git_ps1: command not found
  Mon Jun 27 17:25:18 ~/wdi/homework/Oz/Emerald City
$ cd ..
-bash: __git_ps1: command not found
  Mon Jun 27 17:25:29 ~/wdi/homework/Oz
$ ls
Dorothy             Good Witch of the North     Wicked Witch of the West
Emerald City            Good Witch of the South
-bash: __git_ps1: command not found
  Mon Jun 27 17:25:30 ~/wdi/homework/Oz
$ pwd
/Users/SheedaBeeda/wdi/homework/Oz
-bash: __git_ps1: command not found
  Mon Jun 27 17:25:56 ~/wdi/homework/Oz
$ touch "Flying Monkeys"
-bash: __git_ps1: command not found
  Mon Jun 27 17:26:08 ~/wdi/homework/Oz
$ ls
Dorothy             Flying Monkeys          Good Witch of the South
Emerald City            Good Witch of the North     Wicked Witch of the West
-bash: __git_ps1: command not found
  Mon Jun 27 17:26:10 ~/wdi/homework/Oz
$ rm "Wicked Witch of the West"
-bash: __git_ps1: command not found
  Mon Jun 27 17:26:26 ~/wdi/homework/Oz
$ ls
Dorothy         Flying Monkeys      Good Witch of the South
Emerald City        Good Witch of the North
-bash: __git_ps1: command not found
  Mon Jun 27 17:26:27 ~/wdi/homework/Oz
$ echo "a diploma" >> Oz/Scarecrow
-bash: Oz/Scarecrow: No such file or directory
-bash: __git_ps1: command not found
  Mon Jun 27 17:26:58 ~/wdi/homework/Oz
$ cd "Emerald City"
-bash: __git_ps1: command not found
  Mon Jun 27 17:27:25 ~/wdi/homework/Oz/Emerald City
$ ls
Cowardly Lion   Scarecrow   Tin Man
-bash: __git_ps1: command not found
  Mon Jun 27 17:27:26 ~/wdi/homework/Oz/Emerald City
$ echo "a diploma" >> Emerald City/Scarecrow
-bash: __git_ps1: command not found
  Mon Jun 27 17:27:51 ~/wdi/homework/Oz/Emerald City
$ ls
Cowardly Lion   Emerald     Scarecrow   Tin Man
-bash: __git_ps1: command not found
  Mon Jun 27 17:27:53 ~/wdi/homework/Oz/Emerald City
$ pwd
/Users/SheedaBeeda/wdi/homework/Oz/Emerald City
-bash: __git_ps1: command not found
  Mon Jun 27 17:28:00 ~/wdi/homework/Oz/Emerald City
$ rm Emerald
-bash: __git_ps1: command not found
  Mon Jun 27 17:28:22 ~/wdi/homework/Oz/Emerald City
$ ls
Cowardly Lion   Scarecrow   Tin Man
-bash: __git_ps1: command not found
  Mon Jun 27 17:28:24 ~/wdi/homework/Oz/Emerald City
$ echo "a diploma" >> Scarecrow
-bash: __git_ps1: command not found
  Mon Jun 27 17:28:58 ~/wdi/homework/Oz/Emerald City
$ ls
Cowardly Lion   Scarecrow   Tin Man
-bash: __git_ps1: command not found
  Mon Jun 27 17:28:59 ~/wdi/homework/Oz/Emerald City
$ cd Scarecrow
-bash: cd: Scarecrow: Not a directory
-bash: __git_ps1: command not found
  Mon Jun 27 17:29:05 ~/wdi/homework/Oz/Emerald City
$ ls
Cowardly Lion   Scarecrow   Tin Man
-bash: __git_ps1: command not found
  Mon Jun 27 17:29:07 ~/wdi/homework/Oz/Emerald City
$ echo "a heart shaped watch" >> "Tin Man"
-bash: __git_ps1: command not found
  Mon Jun 27 17:29:43 ~/wdi/homework/Oz/Emerald City
$ cat
"Tin Man"
"Tin Man"
^Z
[1]+  Stopped                 cat
-bash: __git_ps1: command not found
  Mon Jun 27 17:30:12 ~/wdi/homework/Oz/Emerald City
$ cat "Tin Man"
a heart shaped watch
-bash: __git_ps1: command not found
  Mon Jun 27 17:30:18 ~/wdi/homework/Oz/Emerald City
$ ls
Cowardly Lion   Scarecrow   Tin Man
-bash: __git_ps1: command not found
  Mon Jun 27 17:30:27 ~/wdi/homework/Oz/Emerald City
$ echo "a medal" >> "Cowardly Lion"
-bash: __git_ps1: command not found
  Mon Jun 27 17:30:44 ~/wdi/homework/Oz/Emerald City
$ cat "Cowardly Lion"
a medal
-bash: __git_ps1: command not found
  Mon Jun 27 17:30:50 ~/wdi/homework/Oz/Emerald City
$ cat "Scarecrow"
a diploma
-bash: __git_ps1: command not found
  Mon Jun 27 17:30:57 ~/wdi/homework/Oz/Emerald City

**Comment by andrewsunglaekim** [comment]
hope you enjoyed your nap!

👍
