### ISSUE TITLE
Megan's HW

### ISSUE THREAD

**Issue by megancoyle** [ga-wdi-exercises/to_oz#89]
Comfort: 5
Completeness: 5

$ mkdir House
$ touch House/Dorothy House/Toto
$ mkdir Oz
$ cd ./Oz
$ touch "Good Witch of the North" "Wicked Witch of the East" "Good Witch of the South" "Wicked Witch of the West”
$ rm "Wicked Witch of the East”
$ cd ../
$ mv House/Dorothy Oz/
$ touch "Scarecrow" "Tin Man" "Cowardly Lion”
$ mkdir "Emerald City”
$ mv "Scarecrow" "Emerald City”
$ mv "Tin Man" "Emerald City”
$ mv "Cowardly Lion" "Emerald City”
$ touch Oz/"Flying Monkeys”
$ rm Oz/"Wicked Witch of the West”
$ echo "a diploma" >> “Emerald City"/Scarecrow
$ echo "a heart shaped watch" >> “Emerald City"
/"Tin Man”
$ echo "a medal" >> “Emerald City"
/"Cowardly Lion”

**Comment by andrewsunglaekim** [comment]
👍
