### ISSUE TITLE
Sarah'S Day 1 Homework

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/to_oz#9]
Last login: Mon Feb  8 17:30:02 on ttys000
~ 
$ pwd
/Users/sarahivey
~ 
$ ls
Desktop     Library     Pictures    funny_things    world
Documents   Movies      Public      git
Downloads   Music       fundamentals    wdi
~ 
$ cd wdi
~/wdi 
$ ls
Rakefile    installfest.yml projects
exercises   lessons     sandbox
~/wdi 
$ cd exercises
~/wdi/exercises 
$ ls
House   Oz
~/wdi/exercises 
$ ls Oz
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
~/wdi/exercises 
$ Touch "Wicked Witch of the West"
~/wdi/exercises 
$ ls
House               Wicked Witch of the West
Oz
~/wdi/exercises 
$ rm "Wicked Witch of the West"
~/wdi/exercises 
$ cd Oz
~/wdi/exercises/Oz 
$ ls
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
~/wdi/exercises/Oz 
$ Touch "Wicked Witch of the West"
~/wdi/exercises/Oz 
$ ls
Good Witch of the North     Wicked Witch of the West
Good Witch of the South
~/wdi/exercises/Oz 
$ Touch "wicked Witch of the East"
~/wdi/exercises/Oz 
$ ls
Good Witch of the North     Wicked Witch of the West
Good Witch of the South     wicked Witch of the East
~/wdi/exercises/Oz 
$ rm "wicked Witch of the East"
~/wdi/exercises/Oz 
$ mv ../House/Dorothy
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/exercises/Oz 
$ cd ..
~/wdi/exercises 
$ ls
House   Oz
~/wdi/exercises 
$ cd House
~/wdi/exercises/House 
$ mv Dorothy Oz
mv: Dorothy: No such file or directory
~/wdi/exercises/House 
$ ls
House       Oz      Toto        exercises
~/wdi/exercises/House 
$ rm exercises
rm: exercises: is a directory
~/wdi/exercises/House 
$ touch Dorothy
~/wdi/exercises/House 
$ cd ..
~/wdi/exercises 
$ mv House/Dorothy Oz
~/wdi/exercises 
$ cd Oz
~/wdi/exercises/Oz 
$ ls
Dorothy             Good Witch of the South
Good Witch of the North     Wicked Witch of the West
~/wdi/exercises/Oz 
$ touch Scarecrow
~/wdi/exercises/Oz 
$ touch "Tin Man"
~/wdi/exercises/Oz 
$ touch "Cowardly Lion"
~/wdi/exercises/Oz 
$ mkdir "Emerald City"
~/wdi/exercises/Oz 
$ mv "Scarecrow" "Emerald City"
~/wdi/exercises/Oz 
$ mv "Tin Man" "Emerald City"
~/wdi/exercises/Oz 
$ mv "Cowardly Lion" "Emerald City"
~/wdi/exercises/Oz 
$ mv "Dorothy" "Emerald City"
~/wdi/exercises/Oz 
$ touch "Flying Monkeys"
~/wdi/exercises/Oz 
$ rm "Wicked Witch of the West"
~/wdi/exercises/Oz 
$ echo "a diploma" >> Oz/Scarecrow
-bash: Oz/Scarecrow: No such file or directory
~/wdi/exercises/Oz 
$ cd "Emerald City"
~/wdi/exercises/Oz/Emerald City 
$ echo "a diploma" >> Oz/Scarecrow
-bash: Oz/Scarecrow: No such file or directory
~/wdi/exercises/Oz/Emerald City 
$ echo "a diploma" >> Scarecrow
~/wdi/exercises/Oz/Emerald City 
$ echo "a heart shaped watch" >>"Tin Man"
~/wdi/exercises/Oz/Emerald City 
$ echo "medal" >> Lion
~/wdi/exercises/Oz/Emerald City 
$

**Comment by RobertAKARobin** [comment]
Nice!
