### ISSUE TITLE
Marc's HW

### ISSUE THREAD

**Issue by mfournier91** [ga-wdi-exercises/to_oz#90]
Comfort: 5
Completeness: 5

No more movie spoilers, please. Just kidding.
'''
$ mkdir House
$ touch House/Dorothy.txt House/Toto.txt
$ mkdir Oz
$ touch Oz/Good_Witch_of_the_North.txt Oz/Wicked_Witch_of_the_East.txt Oz/Good_Witch_of_the_South.txt Oz/Wicked_Witch_of_the_West.txt
$ rm Oz/Wicked_Witch_of_the_East.txt
$ mv House/Dorothy.txt Oz
$ touch Scarecrow.txt Tin_Man.txt Cowardly_Lion.txt
$ mkdir Emerald_City
$ mv *.txt Emerald_City
$ mv Oz/Dorothy.txt Emerald_City
$ touch Oz/Flying_Monkeys.txt
$ rm Oz/Wicked_Witch_of_the_West.txt
$ echo "a diploma" >> Emerald_City/Scarecrow.txt
$ echo "a heart-shaped watch" >> Emerald_City/Tin_Man.txt
$ echo "a medal" >> Emerald_City/Cowardly_Lion.txt
'''

**Comment by andrewsunglaekim** [comment]
👍  well try our best!
