### ISSUE TITLE
Alex Holland

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/to_oz#97]
comfort: 4

completeness: 5- I did not see any bonus challenges?!

Comments:  When we did typed in   [  echo "...." >> oz/.....   ]  was it suppose to stick to the file or just echo back to us?

'''
mkdir House
cd House
touch Dorothy
touch Toto

mkdir oZ
cd oZ
touch goodWitchOfTheNorth WickedWitchOfTheEast GoodWitchOfTheSouth WickedWitchOfTheWest

rm -f wickedWitchOfTheEast

cd ..

mv house/dorothy oz

touch scareCrow tinMan cowardlyLion

mv scareCrow emeraldCity
mv tinMan emeraldCity
mv cowardlyLion emeraldCity

cd ..

cd oZ

touch flyingMonkeys

rm -f wickedWitchOfTheWest

echo "a diploma" >> Oz/Scarecrow

echo "a heart shapped watch" >> oz/tinman

echo “a medal” >> oz/cowardlyLion
'''

**Comment by superbuggy** [comment]
nice work alex! nailed it dude. 👍
